<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');

$contexts = $contextSwitch->getActionContexts($action);


$dom 	  = new DomDocument("1.0", "UTF-8");
$constituencies  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$constituencies->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('totalItems',$this->data->getTotalItemCount()));
$meta->appendChild( $dom->createElement('currentPage',$this->data->getCurrentPageNumber()));
$meta->appendChild( $dom->createElement('totalPages',ceil($this->data->getTotalItemCount()/$this->data->getItemCountPerPage())));
$meta->appendChild( $dom->createElement('itemsReturned',$this->data->getItemCountPerPage()));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$constituenciesElem = $dom->createElement('constituencies');
$constituencies->appendChild($constituenciesElem);
foreach($this->data as $r => $v) {
     $constituencyElem = $dom->createElement('constituency');
   foreach($v as $k => $a){
      
       $constituencyElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
   $constituenciesElem->appendChild($constituencyElem);
}
$dom->appendChild( $constituencies );

$xmlData  = $dom->saveXML();
echo $xmlData;
