<?php
$this->headTitle('All finds recorded in the Parliamentary constituency of ' . $this->constituency);
$this->metaBase()
    ->setDescription('This page lists all objects recorded by the Scheme in the Parliamentary constituency of ' . $this->constituency)
    ->setSubject('archaeology')
    ->setKeywords('finds,found in,constituency,archaeology,portable antiquities,' . $this->constituency)
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

    <div class="row-fluid">
        <div class="span9">
            <?php if ($this->finds): ?>
                <div class="stripeMe">
                    <?php echo $this->partialLoop('partials/database/structural/findRecordList.phtml', $this->finds); ?>
                </div>
            <?php else: ?>
                <p>No records are available.</p>
            <?php endif; ?>
        </div>
        <div class="span3">
            <?php echo $this->facetCreator()->setFacets($this->facets); ?>
        </div>
    </div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>