<?php
$this->headTitle('All finds recorded in the Parliamentary constituency of '.$this->constituency);
$this->MetaBase('This page lists all objects recorded by the Scheme in the Parliamentary constituency of '.$this->constituency,'archaeology','finds,found in,constituency,archaeology,portable antiquities,' . $this->constituency);
?>
<h2>Finds within constituency of <?php echo $this->escape($this->constituency);?></h2>
<div class="row-fluid">
<div class="span9">
<?php if ($this->finds): ?>
    <div class="stripeMe">
        <?php echo $this->partialLoop('partials/database/findRecordList.phtml',$this->finds);?>
    </div>
<?php else:?>
    <p>No records are available.</p>
<?php endif; ?>
</div>
<div class="span3">
        <?php
echo $this->facetCreator($this->facets);
?>
</div>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>

