<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getActionContexts($action);
$dom = new DomDocument("1.0", "UTF-8");
$artefact  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$artefact->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');

$meta->appendChild($formats);	
foreach ($contexts as $k ){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

$statistics = $dom->createElement('statistics');
$statistics->appendChild( $dom->createElement('totalResults', $this->paginator->getTotalItemCount()));
$statistics->appendChild( $dom->createElement('currentPage', $this->paginator->getCurrentPageNumber()));
$statistics->appendChild( $dom->createElement('resultsPerPage', $this->paginator->getItemCountPerPage()));
$meta->appendChild($statistics);


$artefactsElem = $dom->createElement('results');
foreach($this->finds as $r){
	if(array_key_exists('knownas', $r)){
		unset($r['fourFigure']);
	}
	if(!array_key_exists('thumbnail', $r)){
		unset($r['imagedir']);
		unset($r['filename']);
	}
	$artefactElem = $dom->createElement('result');
   foreach($r as $k => $a){
      
       $artefactElem->appendChild( $dom->createElement($k, htmlspecialchars(strip_tags($a)))); 
   }


$artefactsElem->appendChild( $artefactElem );
}
$artefact->appendChild($artefactsElem);
$dom->appendChild( $artefact );

$xmlData  = $dom->saveXML();
echo $xmlData;