<?php
$feedArray = array(
    'title' => 'Latest finds from the Scheme',
    'link' => $this->CurUrl(),
    'charset' => 'utf-8',
    'description' => 'Latest rss feed of finds recorded by the Portable Antiquities Scheme',
    'author' => 'The Portable Antiquities Scheme',
    'image' => $this->serverUrl() . '/assets/logos/pas.jpg',
    'email' => 'info@finds.org.uk',
    'copyright' => 'Creative Commons Licenced',
    'generator' => 'The Scheme database powered by Zend Framework and Dan\'s magic',
    'language' => 'en',
    'entries' => array()
    );
foreach ($this->finds as $find) {
    $feedArray['entries'][] = array(
        'title' => $find['old_findID'].' '.$find['objecttype'].' '.$find['broadperiod'],
        'link' => $this->serverUrl() . '/database/artefacts/record/id/' . $find['id'],
        'guid' => $this->serverUrl() . '/database/artefacts/record/id/' . $find['id'],
        'description' => $this->ellipsisString(strip_tags($find['description'])),
        'lastUpdate' => strtotime($find['updated']),
        'content' => $this->ellipsisstring(strip_tags($find['description'])),
        );
    }

    $feed = Zend_Feed::importArray($feedArray,'atom');
    $feed->send();