<li><?= $this->fullname; ?> [<a href="<?php echo $this->url(array(
        'module' => 'database',
        'controller' => 'search',
        'action' => 'results',
        'rallyID' => $this->rallyID,
        'createdBy' => $this->id),
        null, true) ?>" title="Find all records recorded at this rally by <?php echo $this->fullname; ?>">Find all
        records created</a>]

        Attended: <?php echo $this->niceShortDate()->setDate($this->datefrom) . ' - ' . $this->niceShortDate()->setDate($this->dateto);?>

    <?php
    echo $this->href(array('module' => 'database', 'controller' => 'rallies', 'action' => 'deleteflo', 'checkAcl' => true,
        'acl' => 'Zend_Acl', 'params' => array('rallyID' => $this->rallyID, 'staffID' => $this->id), 'content' => 'Delete',
        'attribs' => array('title' => 'Delete flo details from this rally')));
    ?> </li>

