<?php 
$this->headTitle('Delete coin reference');
if ($this->coin) :?>
<h2>Delete coin reference</h2>
<p>Are you sure that you want to delete this coin reference. Remember, it is final!</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'coins','action'=>'deletecoinref'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->coin->id; ?>" />
<input type="hidden" name="returnID" value="<?php echo $this->returnID; ?>" />

<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>