<?php
$this->headTitle();
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p><a class="btn btn-success btn-small"
          href="<?php echo $this->url(
              array(
                  'module' => 'database',
                  'controller' => 'artefacts',
                  'action' => 'record',
                  'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('returnID')
              ), null, true); ?>" title="return to the record">Return to record</a></p>

<?php
$this->editCheck()
    ->setInstitution($this->coin[0]['institution'])
    ->setCreatedBy($this->coin[0]['createdBy'])
    ->canThey();
?>
<?php
$this->form->setLegend('Edit data');
echo $this->form;
?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jQueryLinkedSelect.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/coinslinkedselect.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');

?>

<?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function() {
    // focus on the first text input field in the first field on the page
    $("input[type='select']:first", document.forms[0]).focus();
    $('form').areYouSure();
    });
<?php $this->jQuery()->javascriptCaptureEnd(); ?>