<h2>Scheme attended Festival of British Archaeology Events</h2>
<p>The Scheme is organising (or helping with) a variety of events to coincide with the <a href="http://festival.britarch.ac.uk/" >Festival 
of British Archaeology</a>, that is run by the Council for British Archaeology.</p>
<img src="/images/logos/title.png" alt="The festival logo" height="68" width="558" />
<?php
echo $this->partialLoop('partials/events/fobaDetails.phtml',$this->events);
