<li>
    <?php echo $this->referenceName; ?> : <?php echo $this->vol_no; ?> <?php echo $this->reference; ?>
    <?php $auth = Zend_Registry::get('auth'); ?>
    <?php if ($auth->hasIdentity()): ?>
        <?php $user = $auth->getIdentity(); ?>
        <?php $allowed = array('fa', 'admin', 'flos', 'hoard'); ?>
        <?php if (in_array($user->role, $allowed)): ?>
            <div class="btn-group">
                <a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'coins', 'action' => 'editcoinref', 'id' => $this->id, 'returnID' => $this->returnID), null, true); ?>"
                   title="Edit this coin reference" class="btn btn-mini">Edit</a>
                <a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'coins', 'action' => 'deletecoinref', 'id' => $this->id, 'returnID' => $this->returnID), null, true); ?>"
                   title="Delete this reference" class="btn btn-mini">Delete</a>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</li>