<?php
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$url = array('module' => $module, 'controller' => $controller, 'action' => 'denomination', 'id' => $this->id);
?>

<li>
    <a href="<?php echo $this->url($url, null, true); ?>" title="View details for this
    <?php echo $this->denomination; ?>"><?php echo ucfirst($this->denomination); ?></a> -
    <a href="<?php echo $this->url($url, null, true); ?>"
       title="Search database for all examples of <?php echo $this->denomination; ?>"><i class="icon-search"></i></a>
</li>