<h2>Website administration centre</h2>
<?php
$this->headTitle('Portable Antiquities Scheme: The British Museum');
$welcome = array('Welcome','Welkom','Namaste','Ayubowan','Marhaban','F&agrave;ilte','Witam','Haere mai','Khosh aamadid');
$randomWelcome = $welcome[array_rand($welcome)];
?>

<div class="well lead text-success"><h1><?php echo $randomWelcome;?>!</h1></div>
<?php 
echo $this->WhatYouWantToDoAdmin();
?>