<?php
$this->headTitle('Portable Antiquities Scheme: The British Museum');
$welcome = array('Welcome', 'Welkom', 'Namaste', 'Ayubowan', 'Marhaban', 'F&agrave;ilte', 'Witam', 'Haere mai', 'Khosh aamadid');
$randomWelcome = $welcome[array_rand($welcome)];
?>
<h2 class="lead">Website administration centre</h2>
<div class="well text-success">
    <h1 class="lead"><?php echo $randomWelcome; ?>!</h1>
</div>
<?php echo $this->whatYouWantToDoAdmin(); ?>