<?php
$this->metaBase()->setSubject('Early Medieval numismatics')
    ->setKeywords('numismatics,early medieval,coins,categories,Vikings,invaders')
    ->setDescription('This page provides a list of coin denominations issued in the Early Medieval period')
    ->generate();
$this->headTitle('Early Medieval Denominations issued');
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->denominations)): ?>
    <p>The following coins were issued during the Early Medieval period.</p>

    <ul>
        <?php echo $this->partialLoop('partials/numismatics/denominations.phtml', $this->denominations); ?>
    </ul>
<?php else: ?>
    <p>No denominations listed at present.</p>
<?php endif; ?>
