<tr class="valid-<?php echo $this->publishState;?>">
<td><?php echo $this->title;?></td>
<td><?php echo $this->sectionTitle($this->section);?></td>
<td><?php echo $this->nameThem()->setName($this->fullname);?></td>
<td><?php echo $this->timeAgoInWords($this->created);?></td>
<td><?php echo $this->nameThem()->setName($this->fn);?></td>
<td><?php echo $this->timeAgoInWords($this->updated);?></td>
<td><?php echo $this->publish()->setState($this->publishState);?></td>
<td>
<?php
$edit = $this->Href(array(
    'module' => 'admin',
    'controller' => 'help',
    'action' => 'edit',
    'checkAcl' => true,
    'acl'=>'Zend_Acl',
    'attribs' => array('title' => 'Edit ' . $this->title),
    'params' => array('id'=>$this->id),
    'content'=> 'Edit')
    );
$delete = $this->Href(array(
    'module' => 'admin',
    'controller' =>'help',
    'action' =>'delete',
    'checkAcl' => true,
    'acl' => 'Zend_Acl',
    'attribs' => array('title' => 'Delete ' . $this->title),
    'params' => array('id'=>$this->id),
    'content' => 'Delete')
    );

echo implode(' | ', array($edit, $delete));
?>
</td>
</tr>