<?php
$this->headTitle('Profile for ' . $this->firstname . ' ' . $this->lastname);
$this->metaBase()->setDescription($this->title())->generate();
?>

<div id="person" class="hresume">
    <div class="contact vcard">
        <h2 class="fn n">
            <span class="given-name"><?= $this->firstname ?></span>
            <span class="family-name"><?= $this->lastname ?></span>
        </h2>

        <div class="btn-group">
            <a class="btn btn-default" href="<?= $this->url(
                array(
                    'module' => 'admin',
                    'controller' => 'contacts',
                    'action' => 'edit',
                    'id' => $this->number
                ), 'default', true) ?>">Edit</a>
            <a class="btn btn-danger" href="<?= $this->url(
                array(
                    'module' => 'admin',
                    'controller' => 'contacts',
                    'action' => 'delete',
                    'id' => $this->number
                ), 'default', true) ?>">Delete</a>
        </div>

        <div id="image-<?= $this->number ?>" class="pull-right">
            <?php if (!is_null($this->image)): ?>
                <?php if (file_exists(ASSETS_PATH . '/staffphotos/thumbnails/' . $this->image)): ?>
                    <img class="img-circle" width="140" height="140"
                         src="<?php echo $this->baseUrl() . '/assets/staffphotos/thumbnails/' . $this->image; ?>"/>
                    <p>
			<a class="btn-danger btn" href="<?= $this->url(
		            array(
                                'module' => 'admin', 
				'controller' => 'contacts', 
				'action' => 'deleteavatar',
				'id' => $this->number), 'default', true);?>">Delete this image
			</a>
		    </p>
                <?php else: ?>
                    <img src="<?= $this->baseUrl() ?>/assets/gravatar.png" width="80" height="80"
                         class="img-circle"/>
                    <p>Image unavailable<br/>Error: 404</p>
                <?php endif; ?>
            <?php else: ?>
                <p>
                    <a class="btn btn-success" href="<?= $this->url(
                        array(
                            'module' => 'admin',
                            'controller' => 'contacts',
                            'action' => 'avatar',
			    'id' => $this->number
                        ), null, true) ?>"
                       title="Add a new image">Add a photo</a>
                </p>
            <?php endif; ?>
        </div>
        <p><strong>Role</strong>: <span class="title"><?= $this->staffroles ?></span> <br/>
            <strong>Database records prefix</strong>: <?= $this->identifier ?></p>
        <?php if (isset($this->host)): ?>
            <h3 class="lead"><strong>Host logo</strong></h3>
            <?php if (file_exists(ASSETS_PATH . '/logos/' . $this->host)): ?>
                <img src="<?= $this->baseUrl() ?>/assets/logos/resized/<?= $this->escape($this->host) ?>"
                     alt="<?= $this->escape($this->description) ?>'s logo"/>
            <?php else: ?>
                <img src="<?= $this->serverUrl() ?>/assets/gravatar.png" width="80" height="80"
                     class="img-circle"/>
                <p>Image unavailable<br/>Error: 404</p>
            <?php endif; ?>
        <?php endif; ?>

	<address>
	    <strong>Address</strong>:<br/>
	    <span class="postal-code"><?= $this->escape($this->address_1) ?></span><br/>
	    <span class="org organization-name"><?= $this->escape($this->description) ?></span><br/>
            <span class="street-address"><?= $this->escape($this->address_2) ?></span><br/>
            <span class="locality"><?= $this->escape($this->town) ?></span><br/>
            <span class="region"><?= $this->escape($this->county) ?></span><br/>
            <span class="postal-code"><?= $this->escape($this->postcode) ?></span>
	</address>

        <div class="geo"><p><strong>Geo</strong>:
                <span class="latitude"><?= $this->latitude ?></span>,
                <span class="longitude"><?= $this->longitude ?></span></p>
        </div>

        <p><strong>Short profile</strong>:</p>
        <?php if (!is_null($this->profile)): ?>
            <span class="summary"><?= $this->profile ?></span>
        <?php else: ?>
            <p>No profile added.</p>
        <?php endif; ?>
	<p> </p>

        <?php if (!is_null($this->telephone)): ?>
	    <p><strong>Phone (<span class="type">work</span>)</strong>: <span class="value"><?= $this->escape($this->telephone) ?></span>
        <?php endif; ?>

        <?php if (!is_null($this->fax)): ?>
	    <p><strong>Phone (<span class="type">fax</span>)</strong>: <span class="value"><?= $this->escape($this->fax) ?></span>
        <?php endif; ?>

        <?php if (!is_null($this->email_one)): ?>
            <p><strong>Email address:</strong> <a href="mailto:<?= $this->escape($this->email_one) ?>"
                                 class="email"><?= $this->escape($this->email_one) ?></a></p>
        <?php endif; ?>

    </div>
</div>
