<tr class="valid-<?php echo $this->publishState;?>">
<td><?php echo $this->title;?></td>
<td><?php echo $this->sectionTitle()->setTitle($this->section);?></td>
<td><?php echo $this->timeAgoInWords($this->created);?></td>
<td><?php echo $this->createdBy;?></td>
<td><?php echo $this->timeAgoInWords($this->updated);?></td>
<td><?php echo $this->updatedBy;?></td>
<td>
<?php
$edit = $this->url(array(
    'module' => 'admin',
    'controller' => 'content',
    'action' => 'edit',
    'id' => $this->id),
        'default', true);
$delete = $this->url(array(
    'module' => 'admin',
    'controller' => 'content',
    'action' => 'delete',
    'id' => $this->id),
        'default', true);

?>
    <div class="btn-group"><a href="<?php echo $edit;?>" class="btn-small btn-info">Edit</a>
    <a href="<?php echo $delete;?>" class="btn-small btn-danger">Delete</a></div>
</td>
</tr>