<tr class="valid-<?php echo $this->publishState; ?>">
    <td><?php echo $this->title; ?></td>
    <td><?php echo $this->sectionTitle($this->section); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->created); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td><?php echo $this->publish()->setState($this->publishState); ?></td>
    <td>
        <?php
        $edit = $this->url(array(
            'module' => 'admin',
            'controller' => 'help',
            'action' => 'edit',
            'id' => $this->id),
            'default', true);
        $delete = $this->url(array(
            'module' => 'admin',
            'controller' => 'help',
            'action' => 'delete',
            'id' => $this->id),
            'default', true);

        ?>
        <div class="btn-group"><a href="<?php echo $edit; ?>" class="btn-mini btn btn-info">Edit</a>
            <a href="<?php echo $delete; ?>" class="btn-mini btn btn-danger">Delete</a></div>
    </td>
</tr>