<?php
$this->headTitle('Profile for ' . $this->firstname . ' ' . $this->lastname);
$this->metaBase()->setDescription($this->title())->generate();
?>

<div id="person" class="hresume">
    <div class="contact vcard">
        <h2 class="fn n">
            <span class="given-name"><?php echo $this->firstname; ?></span>
            <span class="family-name"><?php echo $this->lastname; ?></span>
        </h2>

        <div class="btn-group">
            <a class="btn btn-default" href="<?php echo $this->url(
                array(
                    'module' => 'admin',
                    'controller' => 'contacts',
                    'action' => 'edit',
                    'id' => $this->number
                ), 'default', true); ?>">Edit</a>
            <a class="btn btn-danger" href="<?php echo $this->url(
                array(
                    'module' => 'admin',
                    'controller' => 'contacts',
                    'action' => 'delete',
                    'id' => $this->number
                ), 'default', true); ?>">Delete</a>
        </div>

        <div id="image-<?php echo $this->number; ?>" class="pull-right">
            <?php if (!is_null($this->image)): ?>
                <?php if (file_exists(ASSETS_PATH . '/staffphotos/thumbnails/' . $this->image)): ?>
                    <img class="img-circle"
                         src="<?php echo $this->baseUrl() . '/assets/staffphotos/thumbnails/' . $this->image; ?>"/>
                    <p><a href="#" class="deleteimage btn-danger btn">Delete this image</a></p>
                <?php else: ?>
                    <img src="<?php echo $this->baseUrl(); ?>/assets/gravatar.png" width="80" height="80"
                         class="img-circle"/>
                    <p>Image unavailable<br/>Error: 404</p>
                <?php endif; ?>
            <?php else: ?>
                <p>
                    <a class="btn btn-success" href="<?php echo $this->url(
                        array(
                            'module' => 'admin',
                            'controller' => 'contacts',
                            'action' => 'addpicture',
                            'id' => $this->number
                        ), 'default', true); ?>"
                       title="Add a new image">Add a photo
                        for <?php echo $this->firstname; ?> <?php echo $this->lastname; ?></a>
                </p>
            <?php endif; ?>
        </div>
        <p>Role: <span class="title"><?php echo $this->staffroles; ?></span> <br/>
            Database records prefix: <strong><?php echo $this->identifier; ?></strong></p>
        <?php if (isset($this->host)): ?>
            <h3 class="lead">Host logo</h3>
            <?php if (file_exists(ASSETS_PATH . '/logos/' . $this->host)): ?>
                <img src="<?php echo $this->baseUrl(); ?>/asset/logos/<?php echo $this->escape($this->host); ?>"
                     alt="<?php echo $this->escape($this->description); ?>'s logo"/>
            <?php else: ?>
                <img src="<?php echo $this->baseUrl(); ?>/assets/gravatar.png" width="80" height="80"
                     class="img-circle"/>
                <p>Image unavailable<br/>Error: 404</p>
            <?php endif; ?>
        <?php endif; ?>

        <p class="adr work">Address: <?php echo $this->escape($this->address_1); ?><br/>
            <span class="org organization-name"><?php echo $this->escape($this->description); ?></span>
            <span class="street-address"><?php echo $this->escape($this->address_2); ?></span>
            <span class="locality"><?php echo $this->escape($this->town); ?></span>
            <span class="region"><?php echo $this->escape($this->county); ?></span>
            <span class="postal-code"><?php echo $this->escape($this->postcode); ?></span>
        </p>

        <div class="geo"><p>Geo:
                <span class="latitude"><?php echo $this->latitude; ?></span>,
                <span class="longitude"><?php echo $this->longitude; ?></span></p>
        </div>

        <p>Short profile:</p>
        <?php if (!is_null($this->profile)): ?>
            <span class="summary"><?php echo $this->profile; ?></span>
        <?php else: ?>
            <p>No profile added.</p>
        <?php endif; ?>

        <?php if (!is_null($this->telephone)): ?>
            <div class="tel">
                <dl>
                    <dt>Phone (<span class="type">work</span>)</dt>
                    <dd><span class="value"><?php echo $this->escape($this->telephone); ?></span></dd>
                </dl>
            </div>
        <?php endif; ?>

        <?php if (!is_null($this->fax)): ?>
            <div class="tel">
                <dl>
                    <dt>Phone (<span class="type">fax</span>)</dt>
                    <dd><span class="value"><?php echo $this->escape($this->fax); ?></span></dd>
                </dl>
            </div>
        <?php endif; ?>

        <?php if (!is_null($this->email_one)): ?>
            <p>Email address: <a href="mailto:<?php echo $this->escape($this->email_one); ?>"
                                 class="email"><?php echo $this->escape($this->email_one); ?></a></p>
        <?php endif; ?>

    </div>
</div>

<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function(){
$('a.deleteimage').click(function(e) {
e.preventDefault();
var parent = $(this).parents("div:first");
$.ajax({
type: 'get',
url: '<?php echo $this->url(array('module' => 'default', 'controller' => 'ajax', 'action' => 'deleteprofileimage'), null, true); ?>',
data: 'id=' + parent.attr('id').replace('image-',''),
beforeSend: function() {
parent.animate({'backgroundColor':'#fb6c6c'},300);
},
success: function() {
parent.slideUp(300,function() {
parent.remove();
});
}
});
});
});

<?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function(){

$('a[class^=delete]').confirm({
dialogShow:'fadeIn',
dialogSpeed:'slow',
buttons: {
wrapper:'
<button></button>', separator:'  '
}
});
});


<?php $this->jQuery()->javascriptCaptureEnd(); ?>
