<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->dynasty);?></td>
<td><?php echo $this->adbc($this->escape($this->date_from));?></td>
<td><?php echo $this->adbc($this->escape($this->date_to));?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td>
<?php
$edit = $this->Href(array(
    'module' => 'admin',
    'controller' => 'numismatics',
    'action' => 'editdynasty',
    'checkAcl' => true,
    'acl'=>'Zend_Acl',
    'attribs' => array('title' => 'Edit a dynasty'),
    'params' => array('id' => $this->id),
    'content'=> 'Edit')
    );
$delete = $this->Href(array(
    'module' => 'admin',
    'controller' =>'numismatics',
    'action' =>'deletedynasty',
    'checkAcl' => true,
    'acl' => 'Zend_Acl',
    'attribs' => array('title' => 'Delete a dynasty'),
    'params' => array('id' => $this->id),
    'content' => 'Delete')
    );

echo implode(' | ', array($edit, $delete));
?>
</td>
</tr>