<tr class="valid-<?php echo $this->valid; ?>">
    <td><?php echo $this->escape($this->dynasty); ?></td>
    <td><?php echo $this->adBc()->setDate($this->date_from); ?></td>
    <td><?php echo $this->adBc()->setDate($this->date_to); ?></td>
    <td><?php echo $this->timeAgoInWords($this->created); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'editdynasty',
                'id' => $this->id), 'default', true); ?>" class="btn btn-mini btn-inverse">Edit</a>
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'deletedynasty',
                'id' => $this->id), 'default', true); ?>" class="btn btn-mini btn-danger">Delete</a>
        </div>
    </td>
</tr>