<tr>
    <td><?php echo $this->name; ?></td>
    <td><?php echo $this->niceShortDate()->setDate($this->created); ?></td>
    <td><?php echo $this->fullname; ?></td>
    <td><?php if (!is_null($this->updated)) {
            echo $this->niceShortDate()->setDate($this->updated);
        } ?></td>
    <td><?php echo $this->fn; ?></td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'editemperor',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-inverse">Edit</a>
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'deleteemperor',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-danger">Delete</a>
        </div>
    </td>
</tr>