<tr>
<td><?php echo $this->name;?></td>
<td><?php echo $this->niceshortdate($this->created);?></td>
<td><?php echo $this->fullname;?></td>
<td><?php if(!is_null($this->updated)) {echo $this->niceshortdate($this->updated);}?></td>
<td><?php echo $this->fn;?></td>
<td>
<?php
$edit = $this->Href(array(
    'module' => 'admin',
    'controller' => 'numismatics',
    'action' => 'editemperor',
    'checkAcl' => true,
    'acl'=>'Zend_Acl',
    'attribs' => array('title' => 'Edit an emperor'),
    'params' => array('id' => $this->id),
    'content'=> 'Edit')
    );
$delete = $this->Href(array(
    'module' => 'admin',
    'controller' =>'numismatics',
    'action' =>'deleteemperor',
    'checkAcl' => true,
    'acl' => 'Zend_Acl',
    'attribs' => array('title' => 'Delete an emperor'),
    'params' => array('id' => $this->id),
    'content' => 'Delete')
    );

echo implode(' | ', array($edit, $delete));
?>
</td>
</tr>