<tr>
    <td width="10%"><?php echo $this->eventTitle; ?><br/>
        <?php echo $this->description; ?></td>
    <td><?php echo strftime("%A %d %B %Y", strtotime($this->eventStartDate)); ?></td>
    <td width="10%"><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->created); ?></td>
    <td width="10%"><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'events', 'action' => 'edit', 'id' => $this->id), null, true); ?>"
               class="btn btn-mini btn-success" title="Edit details for <?php echo $this->eventTitle; ?>">Edit</a>
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'events', 'action' => 'delete', 'id' => $this->id), null, true); ?>"
               class="btn btn-mini btn-danger" title="Delete details for <?php echo $this->eventTitle; ?>">Delete</a>
        </div>
    </td>
</tr>