<tr>
<td><?php echo $this->eventTitle;?><br />
<?php echo $this->description;?></td>
<td><?php echo strftime("%A %d %B %Y", strtotime($this->eventStartDate));?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'events','action' => 'edit','id' => $this->id),null,true);?>" title="Edit details for <?php echo $this->eventTitle;?>">Edit</a> | <a href="<?php echo $this->url(array('module' => 'admin','controller' => 'events','action' =>'delete','id' => $this->id),null,true);?>" title="Delete details for <?php echo $this->eventTitle;?>">Delete</a></td>
</tr>