<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->term);?></td>
<td><?php echo $this->timeAgoInWords($this->created);?></td>
<td><?php echo $this->nameThem()->setName($this->fullname);?></td>
<td><?php echo $this->timeAgoInWords($this->updated);?></td>
<td><?php echo $this->nameThem()->setName($this->fn);?></td>
<td>
<?php
$edit = $this->Href(array(
    'module' => 'admin',
    'controller' => 'terminology',
    'action' => 'editmaterial',
    'checkAcl' => true,
    'acl'=>'Zend_Acl',
    'attribs' => array('title' => 'Edit a material type'),
    'params' => array('id' => $this->id),
    'content'=> 'Edit')
    );
$delete = $this->Href(array(
    'module' => 'admin',
    'controller' =>'terminology',
    'action' =>'deletematerial',
    'checkAcl' => true,
    'acl' => 'Zend_Acl',
    'attribs' => array('title' => 'Delete a material type'),
    'params' => array('id' => $this->id),
    'content' => 'Delete')
    );

echo implode(' | ', array($edit, $delete));
?>
</td>
</tr>