<tr class="valid-<?php echo $this->valid; ?>">
    <td width="20%"><?php echo $this->mint_name . '<br /> ' . $this->t; ?></td>
    <td><?php echo $this->created; ?></td>
    <td width="10%"><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td width="10%"><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td><?php echo $this->validity()->setValid($this->valid); ?></td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'editmint',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-inverse">Edit</a>
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'deletemint',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-danger">Delete</a>
        </div>
    </td>
</tr>
