<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 08/06/15
 * Time: 16:31
 */
?>
<tr>
    <td><?php echo $this->name; ?></td>
    <td><?php echo $this->date_1; ?></td>
    <td><?php echo $this->date_2; ?></td>
    <td><?php echo $this->validity()->setValid($this->valid); ?></td>
    <td>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => 'editmoneyer', 'id' => $this->id), 'default', true); ?>"
           class="btn-mini btn btn-success">Edit</a>
    </td>
</tr>