<tr>
<td><?php echo $this->escape($this->title);?></td>
<td><?php echo $this->niceshortdate($this->created);?></td>
<td><?php echo $this->createdBy;?></td>
<td><?php echo $this->updated;?></td>
<td><?php echo $this->updatedBy;?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'news', 'action' => 'edit', 'id' => $this->id),null,true);?>" title="Edit this story">Edit</a> | <a href="<?php echo $this->url(array('module' => 'admin','controller' => 'news', 'action' => 'delete', 'id' => $this->id),null,true);?>" title="Delete this story">Delete</a></td>
</tr>