<tr>
<td><?php echo $this->ellipsisstring($this->quote,60);?></td>
<td><?php echo ucfirst($this->type);?></td>
<td><?php echo $this->NiceShortDate()->setDate($this->expire);?></td>
<td><?php echo $this->timeAgoInWords($this->created);?></td>
<td><?php echo $this->nameThem()->setName($this->fullname);?></td>
<td><?php echo $this->timeAgoInWords($this->updated);?></td>
<td><?php echo $this->nameThem()->setName($this->fn);?></td>
<td>
    <?php
$edit = $this->Href(array(
    'module' => 'admin',
    'controller' => 'quotes',
    'action' => 'edit',
    'checkAcl' => true,
    'acl'=>'Zend_Acl',
    'attribs' => array('title' => 'Edit a quote'),
    'params' => array('id' => $this->id),
    'content'=> 'Edit')
    );
$delete = $this->Href(array(
    'module' => 'admin',
    'controller' =>'quotes',
    'action' =>'delete',
    'checkAcl' => true,
    'acl' => 'Zend_Acl',
    'attribs' => array('title' => 'Delete a quote'),
    'params' => array('id' => $this->id),
    'content' => 'Delete')
    );

echo implode(' | ', array($edit, $delete));
?>
</td>
</tr>