<tr>
    <td><?php echo $this->ellipsisString()->setString($this->quote)->setMax(60); ?></td>
    <td><?php echo ucfirst($this->type); ?></td>
    <td><?php echo $this->niceShortDate()->setDate($this->expire); ?></td>
    <td><?php echo $this->timeAgoInWords($this->created); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'quotes',
                'action' => 'edit',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-inverse">Edit</a>
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'quotes',
                'action' => 'delete',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-danger">Delete</a>
        </div>
    </td>
</tr>