<tr id="project-<?php echo $this->id; ?>">
    <td width="20%"><a
            href="<?php echo $this->url(array('module' => 'research', 'controller' => 'projects', 'action' => 'project', 'id' => $this->id), null, true); ?>"
            title="View this project's full details"><?php echo $this->title; ?></a></td>
    <td><?php echo $this->investigator; ?></td>
    <td><?php echo $this->type; ?></td>
    <td>
        <?php if (!is_null($this->start)):?>
            <?php echo $this->start;?>
        <?php  else:?>
            N/A
        <?php endif;?>
    </td>
    <td>
        <?php if (!is_null($this->finish)):?>
            <?php echo $this->finish;?>
        <?php  else:?>
            N/A
        <?php endif;?>
    </td>
    <td>
        <div class="btn-group"><a class="btn btn-mini btn-default"
                                  href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'research', 'action' => 'edit', 'id' => $this->id), null, true); ?>"
                                  title="Edit details for <?php echo $this->title; ?>">Edit</a><a
                class="btn btn-mini btn-warning" href="#" title="Delete this project" class="delete">Delete</a>
    </td>
    </div>
</tr>