<?php $this->headTitle('Details for the role of '.$this->role);?>
<h2>Details for the role of <?php echo $this->role;?></h2>
<p><a class="btn btn-large btn-warning" href="<?php echo $this->url(array('module' => 'admin','controller' => 'roles','action' => 'edit','id' => $this->id),null,true);?>" title="Edit the role of <?php echo $this->role;?>">Edit</a></p>
<?php echo $this->description;?>
<h3>Audit data</h3>
<ul id="related">
<?php if(isset($this->created)):?>
<li>Created: <?php echo $this->timeagoinwords($this->created);?></li>
<?php endif;?>
<li>Created by: <?php echo $this->namethem($this->fullname);?></li>
<li>Updated: <?php echo $this->timeagoinwords($this->updated);?></li>
<li>Updated by: <?php echo $this->namethem($this->fn);?></li>
</ul>