<?php
switch ($this->term) {
    case 'IRON AGE':
        $action = 'ironageruler';
        break;
    case 'ROMAN':
        $action = 'romanruler';
        break;
    case 'EARLY MEDIEVAL';
        $action = 'medruler';
        break;
    case 'MEDIEVAL';
        $action = 'medruler';
        break;
    case 'POST MEDIEVAL';
        $action = 'medruler';
        break;
    case 'GREEK AND ROMAN PROVINCIAL';
        $action = 'greekruler';
        break;
    case 'BYZANTINE';
        $action = 'byzruler';
        break;
}
?>

<tr class="valid-<?php echo $this->valid; ?>">
    <td>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => $action, 'id' => $this->id), null, true); ?>"
           title="View details"><?php echo $this->issuer; ?></a> <br/><?php echo $this->term; ?></td>
    <td><?php echo $this->timeAgoInWords($this->created); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td><?php echo $this->validity()->setValid($this->valid); ?></td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'editruler',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-inverse">Edit</a>
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'deleteruler',
                'id' => $this->id), 'default', true);?>" class="btn btn-mini btn-danger">Delete</a>
        </div>
    </td>
</tr>