<?php
switch($this->term) {
case 'IRON AGE':
$action = 'ironageruler';
break;
case 'ROMAN':
$action = 'romanruler';
break;
case 'EARLY MEDIEVAL';
$action = 'medruler';
break;
case 'MEDIEVAL';
$action = 'medruler';
break;
case 'POST MEDIEVAL';
$action = 'medruler';
break;
case 'GREEK AND ROMAN PROVINCIAL';
$action = 'greekruler';
break;
case 'BYZANTINE';
$action = 'byzruler';
break;
}
?>

<tr class="valid-<?php echo $this->valid;?>">
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => $action,'id' => $this->id),null,true);?>" title="View details"><?php echo $this->issuer;?></a> <br/><?php echo $this->term;?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td>
<?php
$edit = $this->Href(array(
    'module' => 'admin',
    'controller'=>'numismatics',
    'action'=>'editruler',
    'checkAcl'=>true,
    'acl'=>'Zend_Acl',
    'params' =>array('id'=>$this->id),
    'content'=>'Edit')
    );
$delete = $this->Href(array(
    'module' => 'admin',
    'controller'=>'numismatics',
    'action'=>'deleteruler',
    'checkAcl'=>true,
    'acl'=>'Zend_Acl',
    'params' =>array('id'=>$this->id),
    'content'=>'Delete')
    );

echo implode(' | ', array($edit,$delete));
?>
</td>
</tr>