<tr class="valid-<?php echo $this->valid; ?>">
    <td width="15%">
        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'roles', 'action' => 'role', 'id' => $this->id), null, true) ?>"
           title="View all members assigned to <?= $this->role ?>">
		<?= $this->role ?>
	</a>
    </td>
    <td><?= $this->timeAgoInWords($this->created) ?></td>
    <td><?= $this->nameThem()->setName($this->fullname) ?></td>
    <td><?= $this->timeAgoInWords($this->updated) ?></td>
    <td><?= $this->nameThem()->setName($this->fn) ?></td>
    <td><?= $this->validity()->setValid($this->valid) ?></td>
    <td>
        <div class="btn-group">
            <a class="btn btn-mini btn-success" href="<?= $this->url(array(
                'module' => 'admin',
                'controller' => 'roles',
                'action' => 'edit',
                'id' => $this->id),
                'default', true) ?>">Edit</a>

            <a class="btn btn-mini btn-danger" href="<?= $this->url(array(
                'module' => 'admin',
                'controller' => 'roles',
                'action' => 'delete',
                'id' => $this->id),
                'default', true) ?>">Delete</a>
        </div>
    </td>
</tr>
