<tr class="valid-<?php echo $this->valid; ?>">
    <td width="15%">
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'roles', 'action' => 'role', 'id' => $this->id), null, true); ?>"
           title="View all members assigned to <?php echo $this->role; ?>"><?php echo $this->role; ?></a></td>
    <td><?php echo $this->timeAgoInWords($this->created); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td><?php echo $this->validity()->setValid($this->valid); ?></td>
    <td>
        <div class="btn-group">
        <a class="btn btn-mini btn-success" href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'roles',
                    'action' => 'edit',
                    'id' => $this->id),
                'default', true);?>">edit</a>

        <a class="btn btn-mini btn-danger" href="<?php echo $this->url(array(
                    'module' => 'admin',
                    'controller' => 'roles',
                    'action' => 'delete',
                    'id' => $this->id),
                'default', true);?>">delete</a>
        </div>
    </td>
</tr>