<tr class="valid-<?php echo $this->valid;?>">
<td><a href="<?php echo $this->url(array('module' =>'admin','controller' => 'roles','action' => 'role','id' => $this->id),null,true);?>" title="View all members assigned to <?php echo $this->role;?>"><?php echo $this->role;?></a></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td>
<?php
$edit = '<a href="' . $this->url(array(
    'module' 	=> 'admin',
    'controller'=>'roles',
    'action'	=>'edit',
    'id' 		=> $this->id),
    'default', true) . '">edit</a>';
    
$delete = '<a href="' . $this->url(array(
    'module' 	=> 'admin',
    'controller'=>'roles',
    'action'	=>'delete',
    'id' 		=> $this->id),
    'default', true) . '">delete</a>';

echo implode(' | ', array($edit,$delete));
?>
</td>
</tr>