<tr>
    <td width="15%"><?php echo $this->escape($this->title); ?></td>
    <td>
        <?php if ($this->temporal): ?>
            <?php echo $this->temporal; ?>
        <?php else: ?>
            N/A
        <?php endif; ?>
    </td>
    <td width="10%"><?php echo $this->type; ?></td>
    <td><?php echo $this->created; ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td>
        <?php if (!is_null($this->updated)): ?>
            <?php echo $this->updated; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
    <td width="10%"><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td>
        <div class="btn-group">
            <a class="btn btn-mini btn-success"
               href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'research', 'action' => 'editsuggested', 'id' => $this->id), 'default', true); ?>"
               title="Edit this topic">Edit</a><a
                href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'research', 'action' => 'deletesuggested', 'id' => $this->id), 'default', true); ?>"
                title="Delete this topic" class="btn-mini btn btn-danger">Delete</a>
        </div>
    </td>
</tr>