<tr>
<td><?php echo $this->escape($this->title);?></td>
<td>
    <?php if($this->temporal):?>
    <?php echo $this->temporal;?>
    <?php else:?>
        N/A
    <?php endif;?>
</td>
<td><?php echo $this->type;?></td>
<td><?php echo $this->niceShortDate()->setDate($this->created);?></td>
<td><?php echo $this->nameThem()->setName($this->fullname);?></td>
<td><?php echo $this->niceShortDate()->setDate($this->updated);?></td>
<td><?php echo $this->nameThem()->setName($this->fn);?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'research','action' => 'editsuggested','id' => $this->id),'default',true);?>" title="Edit this topic">Edit</a> | <a href="<?php echo $this->url(array('module' => 'admin','controller' => 'research','action' => 'deletesuggested','id' => $this->id),'default',true);?>" title="Delete this topic">Delete</a></td>
</tr>