<tr>
    <td>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'system', 'action' => 'role', 'id' => $this->id), null, true); ?>"
           title="View <?php echo $this->role; ?> role's details"><?php echo $this->role; ?></a></td>
    <td><?php echo $this->count; ?></td>
    <td><?php echo $this->timeAgoInWords($this->created); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->updated); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td>
        <a class="btn btn-mini" href="<?php echo $this->url(array('module' => 'admin', 
        'controller' => 'system', 'action' => 'editrole', 'id' => $this->id), null, true); ?>"
           title="Edit role">Edit</a></td>
</tr>
