<tr>
    <td><?php echo $this->type; ?><br/>Category: <em><?php echo $this->c; ?></em></td>
    <td><?php echo $this->timeAgoInWords($this->escape($this->created)); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fullname); ?></td>
    <td><?php echo $this->timeAgoInWords($this->escape($this->updated)); ?></td>
    <td><?php echo $this->nameThem()->setName($this->fn); ?></td>
    <td>
        <div class="btn-group">
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'edittype',
                'id' => $this->id), 'default', true); ?>" class="btn btn-mini btn-inverse">Edit</a>
            <a href="<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'numismatics',
                'action' => 'deletetype',
                'id' => $this->id), 'default', true); ?>" class="btn btn-mini btn-danger">Delete</a>
        </div>
    </td>
</tr>
