<tr class="valid-<?php echo $this->expiredorlive($this->expire);?>">
<td><?php echo $this->escape($this->title);?><br />
Region: <?php echo $this->escape($this->staffregions);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->escape($this->fullname));?></td>
<td><?php echo $this->escape($this->updated);?></td>
<td><?php echo $this->namethem($this->escape($this->fn));?></td>
<td><?php echo $this->niceshortdate($this->escape($this->expire));?></td>
<td><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'vacancies','action' => 'edit','id' => $this->id),null,true);?>" title="Edit details for <?php echo $this->escape($this->title);?>">Edit</a> | <a href="<?php echo $this->url(array('module' => 'admin','controller' => 'vacancies','action' => 'delete','id' => $this->id),null,true);?>" title="Delete details for vacancy">Delete</a></td>
</tr>