<?php
$this->headTitle('A list of Early Medieval coin types ');
$this->metaBase()->setDescription('The Early Medieval period for numismatics is broken down into a series of coin typologies. These
types are closely aligned to the Fitzwilliam\'s Early Medieval coin corpus')
    ->setKeywords('types,early medieval,coins,numsimatics,corpus,index')
    ->setSubject('Early Medieval Numismatics')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->types)): ?>
    <table class="table table-striped" summary="<?php echo $this->title(); ?>">
        <caption><?php echo $this->title(); ?></caption>
        <thead>
        <tr>
            <th>Coin type</th>
            <th>Issuing ruler</th>
            <th>Issue date</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/numismatics/medievalTypes.phtml', $this->types); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->types, 'Elastic', 'structure/pagination.phtml'); ?>

<?php else: ?>
    <p>There are no coin types available.</p>
<?php endif; ?>