<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$dynasties  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$dynasties->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

foreach($this->dynasties as $d){
$d = (object)$d;
$dynElem = $dom->createElement('dynasty');
$dynElem->appendChild( $dom->createElement('id', $d->id));
$dynElem->appendChild( $dom->createElement('name', $d->dynasty));
$dynElem->appendChild( $dom->createElement('description', $d->description));
$dynElem->appendChild( $dom->createElement('created', $d->created));
$dynElem->appendChild( $dom->createElement('updated', $d->updated));

$emperorsElem = $dom->createElement('emperors');
$dynElem->appendChild($emperorsElem);
foreach($this->emperors as $e){
$e = (object)$e;
$empElem = $dom->createElement('emperors');
$empElem->appendChild( $dom->createElement('id', $e->id));
$empElem->appendChild( $dom->createElement('name', $e->issuer));
$empElem->appendChild( $dom->createElement('dateFrom', $e->date_from));
$empElem->appendChild( $dom->createElement('dateTo', $e->date_to));
$emperorsElem->appendChild($empElem);	
}
//$imageElem = $dom->createElement('recentRecords');	
//$denominationElem->appendChild($imageElem);
//
//foreach($this->images as $i){
//$i = (object)$i;
//$recordElem = $dom->createElement('record');
//$imageElem->appendChild( $recordElem);
//$recordElem->appendChild( $dom->createElement('findID', $i->old_findID));
//$recordElem->appendChild( $dom->createElement('label', $i->label));
//$recordElem->appendChild( $dom->createElement('objectType', $i->objecttype));
//$recordElem->appendChild( $dom->createElement('broadPeriod', $i->broadperiod));
//$recordElem->appendChild( $dom->createElement('url', $site . '/database/artefacts/record/id/' . $i->id));
//$recordElem->appendChild( $dom->createElement('thumbnail', $site . ' /images/' . $i->id . '.jpg'));
//}
$dynasties->appendChild( $dynElem );
}

$dom->appendChild( $dynasties );

$xmlData  = $dom->saveXML();
echo $xmlData;
