<?php
$this->headTitle('Dynastic groupings of the Roman Empire');
$this->metaBase()->setDescription('A list of Roman dynasties from the Roman Empire')
    ->setKeywords('roman,coins,dynasties,numismatics')
    ->setSubject('Roman Numismatics')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/roman/dynasties.phtml', $this->dynasties); ?>
</ul>