<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();
$dom 	  = new DomDocument("1.0", "UTF-8");

$dynasties  = $dom->createElement('response');
$meta = $dom->createElement('meta');

$dynasties->appendChild($meta);

$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->dynasties)));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

//1st item
$dynsElem = $dom->createElement('dynasties');
$dynasties->appendChild($dynsElem);
// set it's attribute
foreach($this->dynasties as $d){
$d = (object)$d;
$dynElem = $dom->createElement('dynasty');
$dynElem ->appendChild( $dom->createElement('id', $d->id));
$dynElem ->appendChild( $dom->createElement('name', $d->dynasty));
$dynElem ->appendChild( $dom->createElement('url',$site . $this->url(array('module' => $module,
'controller' => $controller,'action' => 'dynasty','id' => $d->id),NULL,true) ));
$dynElem->appendChild( $dom->createElement('dateFrom',$d->date_from));
$dynElem->appendChild( $dom->createElement('dateTo',$d->date_to));
$dynElem->appendChild( $dom->createElement('description',$d->description));
$dynElem->appendChild( $dom->createElement('created',$d->created));
$dynElem->appendChild( $dom->createElement('updated',$d->updated));
$dynsElem->appendChild( $dynElem  );
}

$dom->appendChild( $dynasties );

$xmlData  = $dom->saveXML();
echo $xmlData;
