<?php
$this->headTitle('Details for ' . $this->term . ' decorative method');
$this->metaBase()->setDescription($this->title())
    ->setSubject('terminology')
    ->setKeywords('terminology,vocabulary,decorative,methods')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!is_null($this->terdesc)): ?>
    <?php echo $this->termdesc; ?>
<?php else: ?>
    <p>No scope note has been provided.</p>
<?php endif; ?>
<p>
    View <a
        href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'decoration' => $this->id), null, true); ?>"
        title="Search database for all attributed records">all records</a> assigned to this method on our database.
</p>
