<?php
$this->headTitle('Die Axis term: ' . $this->die_axis_name);
$this->metaBase()->setDescription($this->title())
    ->setSubject('terminology')
    ->setKeywords('archaeology,numismatics,die axed')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!is_null($this->termdesc)): ?>
    <?php echo $this->termdesc; ?>
<?php else: ?>
    <p>No scope note entered.</p>
<?php endif; ?>

<?php echo $this->searchLink()->setId($this->id)->setField('axis'); ?>
<?php echo $this->latestRecords()->setQuery('axis:' . $this->id); ?>