<?php
$this->headTitle('Landuse type: ' . $this->term);
$this->metaBase()->setDescription('Details for ' . $this->title())
    ->setKeywords('terminology')
    ->setSubject('terminology')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!is_null($this->termdesc)): ?>
    <?php echo $this->termdesc; ?>
<?php else: ?>
    <p>No scope note has been provided.</p>
<?php endif; ?>
