<tr>
    <td>
        <a href="<?php echo $this->url(
            array(
                'module' => 'datalabs',
                'controller' => 'terminology',
                'action' => 'material',
                'id' => $this->id),
            'default', true); ?>"
           title="View <?php echo $this->term; ?>'s details"><?php echo $this->term; ?></a>
    </td>
    <td><?php echo $this->bmID; ?></td>
    <td><?php echo $this->ehID; ?></td>
</tr>