<?php $this->headTitle('Discovery method ' . lcfirst($this->method)); ?>
<?php
$this->metaBase()->setDescription('Details for discovery method ' . $this->method)
    ->setKeywords('discovery,method')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title() ; ?></h2>
<?php if (!is_null($this->termdesc)): ?>
    <?php echo $this->termdesc; ?>
<?php else: ?>
    <p>No term description is available at present.</p>
<?php endif; ?>
<?php echo $this->latestRecords()->setQuery('discovery:' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>