<?php
$this->headTitle('Find of note reason: ' . $this->term);
$this->metaBase()->setDescription($this->title())
    ->setSubject('terminology')
    ->setKeywords('reasoning,terminology,archaeology')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!is_null($this->termdesc)): ?>
    <?php echo $this->termdesc; ?>
<?php else: ?>
    <p>No scope note entered.</p>
<?php endif; ?>
<?php echo $this->searchLink()->setField('reason')->setId($this->id); ?>
<?php echo $this->latestRecords()->setQuery('reason:' . $this->id); ?>