<?php
$this->headTitle('Find of note reason: ' . $this->term);
$this->metaBase()->setDescription($this->title())
    ->setSubject('terminology')
    ->setKeywords('reasoning,terminology,archaeology')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php echo $this->termdesc; ?>
    <p>View <a href="<?php echo $this->url(
            array(
                'module' => 'database',
                'controller' => 'search',
                'action' => 'results',
                'note' => 1,
                'reason' => $this->id),
            'default', true);?>"
               title="View all records that have been denoted as <?php echo $this->term; ?>">all records</a>
        assigned to this reason.</p>
<?php echo $this->latestRecords()->setQuery('reason:' . $this->id); ?>