<?php
$this->headTitle('Details for the ' . $this->term . ' period');
$this->metaBase()->setDescription($this->title())
    ->setSubject('Terminology')
    ->setKeywords('time,zone,period')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>Date range: <?php echo $this->adBc()->setDate($this->fromdate); ?>
        to <?php echo $this->adBc()->setDate($this->todate); ?></p>
    <p>Notes: </p> <?php echo $this->notes; ?>

    <h3 class="lead">Linked data</h3>
    <ul>
        <?php if (!is_null($this->ehTerm)): ?>
            <li>SENESCHAL URI: <a
                    href="http://purl.org/heritagedata/schemes/eh_period/concepts/<?php echo $this->ehTerm; ?>">http://purl.org/heritagedata/schemes/eh_period/concepts/<?php echo $this->ehTerm; ?></a>
            </li>
        <?php endif; ?>
        <?php if (!is_null($this->bmID)): ?>
            <li>British Museum URI: <a
                    href="http://collection.britishmuseum.org/id/thesauri/x<?php echo $this->bmID; ?>">http://collection.britishmuseum.org/id/thesauri/x<?php echo $this->bmID; ?></a>
            </li>
        <?php endif; ?>
    </ul>
<?php echo $this->searchLink()->setField('periodFrom')->setId($this->id); ?>
<?php echo $this->latestRecords()->setQuery('broadperiod:"' . $this->term . '"'); ?>