<?php
$this->headTitle('Details for SMR entitled ' . $this->monumentName);
$this->metaBase()->setSubject('Scheduled monument')
->setKeywords('scheduled,monument')
->setDescription('Details of the intersection between the reporting of finds and scheduled monuments')
->generate();
?>

<h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>
        <strong>Record number:</strong> <?php echo $this->monumentNumber; ?><br/>
        <?php if ($this->dateScheduled != 0000 - 00 - 00): ?>
            <strong>Date scheduled:</strong> <?php echo $this->timeAgoInWords($this->dateScheduled); ?><br/>
        <?php endif; ?>
        <strong>County:</strong> <?php echo $this->county; ?><br/>
        <strong>District:</strong> <?php echo $this->district; ?><br/>
        <strong>Parish:</strong> <?php echo $this->parish; ?><br/>
        <strong>Grid reference:</strong> <?php echo $this->gridref; ?><br/>
        <strong>Four Figure NGR:</strong> <?php echo $this->fourFigure; ?><br/>
        <strong>Easting:</strong> <?php echo $this->easting; ?><br/>
        <strong>Northing:</strong> <?php echo $this->northing; ?><br/>
        <strong>Map 25k:</strong> <?php echo $this->map25k; ?><br/>
        <strong>Map 10k:</strong> <?php echo $this->map10k; ?><br/>
        <strong>Latitude:</strong> <?php echo $this->lat; ?> <strong>Longitude:</strong> <?php echo $this->lon; ?><br/>
        <strong>WOEID:</strong> <?php echo $this->woeid; ?><br/>
        <strong>Elevation:</strong> <?php echo $this->elevation; ?> metres
    </p>
<?php echo $this->yahooGeoAdjacentSmr()->setWoeid($this->woeid); ?>

<div id="map">
    <noscript><img
            src="https://maps.google.com/maps/api/staticmap?center=<?php echo $this->lat; ?>,<?php echo $this->lon; ?>&zoom=14&size=640x300&maptype=terrain&markers=color:green|label:G|<?php echo $this->lat; ?>,<?php echo $this->lon; ?>&sensor=false"/>
    </noscript>
</div>