<?php $this->headTitle('Details for workflow stage ' . $this->workflowstage); ?>
<?php $this->metaBase()->setDescription($this->title())
    ->setKeywords('workflow,management,records')
    ->setSubject('terminology')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!is_null($this->termdesc)): ?>
    <?php echo $this->termdesc; ?>
<?php else: ?>
    <p>No scope note has been entered.</p>
<?php endif; ?>
    <p>View <a href="<?php echo $this->url(array(
            'module' => 'database',
            'controller' => 'search',
            'action' => 'results',
            'workflow' => $this->id), null, true);?>"
               title="Search the database for this workflow stage">all records</a> assigned to this workflow stage.</p>
<?php echo $this->latestRecords()->setQuery('workflow:' . $this->id); ?>