<?php
$this->headTitle('A list of all cases of Treasure in reverse chronologvical order');
$this->MetaBase('The Scheme keeps an archive of Treasure cases, which can be queried via this page',
'treasure finds',
'treasure,archaeology,counties,T numbers');
?>
<h2>Treasure cases reported</h2>
<?php 
$page = Zend_Controller_Front::getInstance()->getRequest()->getParam('page');
if(is_null($page)){
?>
<p>This list is not yet complete, and we're working to improve this situation by enriching past records. Once it is, 
you will be able to find our details of the find, valuations and further information such as acquiring body.</p>
<?php 
}
?>

<?php if($this->treasurecases):?>
<ul id="yearrange">
<?php echo $this->partialLoop('partials/treasure/archiveYearsStats.phtml',$this->years);?>
</ul>
<table class="table table-striped">
<caption>All Treasure cases reported</caption>
<thead>
<tr>
	<th>Treasure number</th>
	<th>PAS ID</th>
	<th>County</th>
	<th>Last updated</th>
	
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/treasure/treasureTable.phtml',$this->treasurecases);?>
</tbody>
</table>
<?php echo $this->paginationControl($this->treasurecases, 'Sliding', 'structure/pagination.phtml'); ?>


<?php else:?>
<p>No Treasure cases are available for you to view.</p>
<?php endif;?>