<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 12/12/14
 * Time: 10:40
 */
?>
<iframe width="<?php echo $this->width; ?>" height="<?php echo $this->height; ?>"
        src="https://sketchfab.com/models/<?php echo $this->modelID; ?>/embed" frameborder="0" allowfullscreen
        mozallowfullscreen="true" webkitallowfullscreen="true" onmousewheel="" class="pull-right"></iframe>
<div>
<p>Created via the crowd for the MicroPasts project. For the people, by the people.</p>
<img src="https://farm3.staticflickr.com/2813/12070982995_f38aa033bc_s.jpg" height="75" width="75"
     alt="Created via MicroPasts" />
</div>