<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 12/12/14
 * Time: 10:40
 */

?>
<div class="cookieconsent-optout-statistics"
     style="background:black; width:<?= $this->width; ?>; height: <?= $this->height; ?>; display:block; padding-top: 28.12%; padding-bottom: 28.12%; margin-bottom: 40px">
    <div style="color:white; font-family: Arial, sans-serif; text-align:center">
        Please <a href="javascript:Cookiebot.renew()"
                  style="color:white !important; text-decoration:underline;">accept
            statistics-cookies</a> to see this 3d scan
    </div>
</div>

<div class="cookieconsent-optin-statistics">
    <iframe width="<?= $this->width; ?>" height="<?= $this->height; ?>"
            src="<?= $this->baseurl; ?><?= $this->modelID; ?>/embed" frameborder="0" allowfullscreen
            data-src="<?= $this->baseurl; ?><?= $this->modelID; ?>/embed"
            data-cookieconsent="statistics"
            frameborder="0" allowfullscreen
            mozallowfullscreen="true" webkitallowfullscreen="true" onmousewheel="" class="pull-right">
    </iframe>
</div>