<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 12/12/14
 * Time: 10:40
 */

?>
<div class="embed-container" style="--aspect-ratio:4/3">
    <div class="cookieconsent-optout-statistics cookie-placeholder dark ">
        <div style="color:white; font-family: Arial, sans-serif;">
            Please <a href="javascript:Cookiebot.renew()"
                      style="color:white !important; text-decoration:underline;">accept
                statistics-cookies</a> to see this 3d scan
        </div>
    </div>
    <iframe frameborder="0" allowfullscreen
            data-src="<?= $this->baseurl; ?><?= $this->modelID; ?>/embed"
            data-cookieconsent="statistics"
            frameborder="0" allowfullscreen
            mozallowfullscreen="true" webkitallowfullscreen="true" onmousewheel="">
    </iframe>
</div>
