<?php $this->headTitle('Details for: ' . $this->escape($this->fullname)); ?>
<h2 class="lead">Details for: <?php echo $this->fullname; ?></h2>

<div class="btn-group"><a href="<?php echo $this->url(array(
        'module' => 'database',
        'controller' => 'people',
        'action' => 'edit',
        'id' => $this->id), null, true); ?>" title="Edit this person's details"
                          class="btn btn-warning btn-small">Edit</a>
    <?php if (!$this->finds) : ?> <a href="<?php echo $this->url(array(
        'module' => 'database',
        'controller' => 'people',
        'action' => 'delete',
        'id' => $this->id), null, true); ?>" title="Delete this person's details" class="btn btn-danger btn-small">
            Delete</a><?php endif; ?></div>
<div class="vcard">
    <p>
<span class="fn n">
<?php if (!empty($this->title) && ($this->title != 'Other')) { echo $this->escape($this->title); } ?> <span class="given-name"><?php echo $this->escape($this->forename); ?></span>
<span class="family-name"><?php echo $this->escape($this->surname); ?></span><br/>
</span>
<span class="adr">
<?php if (!is_null($this->address)): ?>
    Address: <span class="street-address"><?php echo $this->escape($this->address); ?></span><br/>
<?php endif; ?>
    <?php if (!is_null($this->town)): ?>
        Town: <span class="locality"><?php echo $this->escape($this->town_city); ?></span><br/>
    <?php endif; ?>
    <?php if (!is_null($this->county)): ?>
        County: <?php echo $this->escape($this->county); ?><br/>
    <?php endif; ?>
    <?php if (!is_null($this->postcode)): ?>
        Postcode: <span class="postal-code"><?php echo $this->escape($this->postcode); ?></span><br/>
    <?php endif; ?>
    <?php if (!is_null($this->abode)): ?>
        Country: <span class="country-name"><?php echo $this->escape($this->abode); ?></span><br/>
    <?php endif; ?>
</span>
        <?php if (!is_null($this->hometel)): ?>
            <span class="tel"><span class="type">Home</span> T: <span
                    class="value"><?php echo $this->escape($this->hometel); ?></span></span><br/>
        <?php endif; ?>
        <?php if (!is_null($this->worktel)): ?>
            <span class="tel"><span class="type">Work</span> T: <span
                    class="value"><?php echo $this->escape($this->worktel); ?></span></span><br/>
        <?php endif; ?>
        <?php if (!is_null($this->fax)): ?>
            <span class="tel"><span class="type">Fax</span>: <span
                    class="value"><?php echo $this->escape($this->fax); ?></span></span><br/>
        <?php endif; ?>
        <?php if (!is_null($this->org)): ?>
            Member of the: <span class="org"><a
                    href="<?php echo $this->url(array('module' => 'database', 'controller' => 'organisations', 'action' => 'organisation', 'id' => $this->escape($this->i)), null, true); ?>"
                    title="View details for <?php $this->escape($this->org); ?>"><?php echo $this->escape($this->org); ?></a></span>
            <br/>
        <?php endif; ?>
        <?php if (!is_null($this->email)): ?>
            Email: <a href="mailto:<?php echo $this->email; ?>" title="Send an email to this person"
                      class="email"><?php echo $this->email; ?></a><br/>
        <?php endif; ?>
        <?php if (!is_null($this->role)): ?>
            Primary activity engaged in: <?php echo $this->escape($this->role); ?><br/>
        <?php endif; ?>
        <?php
        if (isset($this->lat)):?>
            <?php if (!is_null($this->woeid)): ?>
                WOEID: <?php echo $this->woeid; ?><br/>
            <?php endif; ?>
            Latitude: <?php echo $this->lat; ?><br/> Longitude: <?php echo $this->lon; ?> <br/>
            <?php echo $this->gridRef($this->lat, $this->lon); ?>
        <?php endif; ?>
    </p>
    <?php if (!empty($this->comments)): ?>
        <h3 class="lead">Comments on person</h3>
        <?php echo $this->comments; ?>
    <?php endif; ?>
    <div class="btn-group">
        <a class="btn btn-small"
           href="<?php echo $this->url(array('module' => 'database', 'controller' => 'people', 'action' => 'person', 'id' => $this->id, 'format' => 'vcf'), 'default', true); ?>"
           title="Download vcard">Download vcard</a>
        <a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'finderID' => $this->secuid), 'default', true);?>" class="btn btn-small">Find all records</a>
    </div>

</div>
