<?php
   $this->headTitle('Delete Profile Image');
   $this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!$this->contacts['image']) : ?>
    <h2 class="lead">Delete your profile image</h2>
    <p>Are you sure that you want to delete the image</p>
    <form action="<?= $this->url(array('module' => 'users', 'controller' => 'profile', 'action' => 'deleteprofileimage'), null, true) ?>" method="post">
        <div class="btn-toolbar">
            <input type="hidden" name="id" value="<?= $this->contacts['image'] ?>"/>
            <input type="submit" class="btn btn-danger" name="confirmDelete" value="Yes"/>
            <input type="submit" class="btn btn-default" name="confirmDelete" value="No"/>
        </div>
    </form>
<?php else: ?>
    <p>Cannot find the item requested.</p>
<?php endif; ?>
