<h2 class="lead">Edit a contact</h2>
<?php 
$this->headTitle('Edit your staff profile');
$this->googleDynamicMap();
echo $this->form;?>

<?php $this->inlineScript()->captureStart() ?>
var markerLocation;
var latLngArray;
var ukMapCentre;

function placeMarker(latLng, map) {
if (markerLocation) {
markerLocation.setPosition(latLng)
} else {
markerLocation = new google.maps.Marker({
position: latLng,
map: map,
});
}
}

function initMap() {
var myOptions = {
zoom: 6,
center: ukMapCentre,
streetViewControl: false,
fullscreenControl: false,
};

return new google.maps.Map(document.getElementById("map"), myOptions);
}

function initInfoWindow() {
return new google.maps.InfoWindow({
content: "Click window to set your public position on contact map",
position: ukMapCentre,
pixelOffset: new google.maps.Size(0, -25),
});
}

function createInfoWindow(latLng) {
return new google.maps.InfoWindow({
position: latLng,
pixelOffset: new google.maps.Size(0, -25),
maxWidth: 100,
});
}

function setMarkerLocationFromForm(map) {
let lat = document.getElementById('latitude').value;
let lng = document.getElementById('longitude').value;
let latlng = { lat: parseFloat(lat), lng: parseFloat(lng) }

if (lat && lng) {
placeMarker(latlng, map)
map.panTo(latlng);
ukMapCentre = latlng;
}
}

$(document).ready(function () {
ukMapCentre = new google.maps.LatLng(54.70235509327093, -3.2080078125);
// Create the map
var map = initMap();
setMarkerLocationFromForm(map)

// Create the initial InfoWindow.
var infoWindow = initInfoWindow();
infoWindow.open(map);


// Get Lat/Long input boxes
var inputLat = document.getElementById('latitude');
var inputLong = document.getElementById('longitude');

// Configure the click listener.
map.addListener("click", (mapsMouseEvent) => {
// Close the current InfoWindow.
infoWindow.close();

// Create a new InfoWindow.
infoWindow = createInfoWindow(mapsMouseEvent.latLng);

infoWindow.setContent(
"Lat: " + mapsMouseEvent.latLng.toJSON().lat.toFixed(4) + "<br>" +
"Lng: " + mapsMouseEvent.latLng.toJSON().lng.toFixed(4) + "<br>"
);
latLngArray = mapsMouseEvent.latLng;

placeMarker(mapsMouseEvent.latLng, map);

inputLat.value = mapsMouseEvent.latLng.toJSON().lat.toFixed(4);
inputLong.value = mapsMouseEvent.latLng.toJSON().lng.toFixed(4);

infoWindow.open(map);
map.panTo(mapsMouseEvent.latLng);
});


inputLat.addEventListener("blur", function () {
setMarkerLocationFromForm(map)
});

inputLong.addEventListener("blur", function () {
setMarkerLocationFromForm(map)
});

});
<?php $this->inlineScript()->captureEnd() ?>

