<?php 
   $this->headTitle('Contact Profile Image');
?>
<h2 class="lead">Contact Profile Image</h2>
<div id="image-<?php echo $this->contacts['id'];?>">
   <?php if (!empty($this->contacts['image'])): ?>
      <h3 class="lead">Your current image:</h3>
      <p>
         <img property="foaf:img google:photo" src="<?= $this->baseUrl() ?>/assets/staffphotos/thumbnails/<?= $this->contacts['image'] ?>" 
            title="Image of <?= $this->escape($this->contacts['firstname']) ?> <?= $this->escape($this->contacts['lastname']) ?>"> <br />
            <a href="<?= $this->url(array('module' => 'users','controller' => 'profile','action' => 'deleteprofileimage'),null,true) ?>" class="deleteimage" title="Delete this image">
               Delete this image
            </a>
      </p> 
   <?php endif; ?>
</div>       
<?php echo $this->form;?>
