<li>
<strong><a href="<?php echo $this->url(array(
'module' => 'contacts', 
'controller' => 'alumni',
'action' => 'profile', 
'id' => $this->id)
);?>" 
title="Read <?php echo $this->escape($this->firstname);?> <?php echo $this->escape($this->lastname);?>'s profile">
<?php echo $this->escape($this->firstname);?> 
<?php echo $this->escape($this->lastname);?></a></strong> 
- Worked for the Scheme as a <?php echo $this->escape($this->staffroles);?> 
covering <?php echo $this->escape($this->staffregions);?>. 
</li>
