<?php
EasyRdf_Namespace::set('con', 'http://www.w3.org/2000/10/swap/pim/contact#');
EasyRdf_Namespace::set('geo', 'http://www.w3.org/2003/01/geo/wgs84_pos#');
$graph = new EasyRdf_Graph();

$me = $graph->resource($this->serverUrl() . '/contacts/staff/profile/id/' . $this->number, 'foaf:Person');
$me->set('foaf:name', $this->firstname . ' ' . $this->lastname);
$me->set('foaf:givenName', $this->firstname);
$me->set('foaf:familyName', $this->lastname);
$email = $graph->resource("mailto:" . $this->email_one);
$me->add('foaf:mbox', $email);
$me->add('foaf:mbox_sha1sum', sha1($this->email_one))   ;
$home = $graph->resource($this->serverUrl());
$me->add('foaf:homepage', $home);
$phone = $graph->resource($this->telephone);
$me->add('foaf:phone', $phone);
$me->add('foaf:workplaceHomepage',$home);
$info = $graph->resource($this->serverUrl() . '/contacts/staff/profile/id/' . $this->number);
$me->add('foaf:workInfoHomepage', $info);
$depiction = $graph->resource($this->serverUrl() . '/assets/staffphotos/thumbnails/' . $this->image);
$me->add('foaf:depiction', $depiction);
echo $graph->serialise('rdfxml');