<?php
$this->googleDynamicMap(null, null, true);
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>

    <h3 class="lead">Spatial data</h3>
<?php
echo $this->findSpotEditDeleteLink()->setController($controller)
    ->setCreatedBy($this->createdBy)
    ->setInstitution($this->institution)
    ->setRecordID($this->findSpotID); ?>

<?php if (!is_null($this->lon) && !is_null($this->lat)) : ?>

    <div id="map">
        <noscript><img src="https://maps.google.com/maps/api/staticmap?center=<?php echo $this->lat; ?>,
	<?php echo $this->lon; ?>&zoom=14&size=640x300&maptype=terrain&markers=color:green|label:G|
	<?php echo $this->lat; ?>,<?php echo $this->lon; ?>&sensor=false"/>
        </noscript>
    </div>
    <?php
    $allowed = array(
        'hero', 'flos', 'admin',
        'treasure', 'research', 'fa',
        'hoard'
    );
    $auth = Zend_registry::get('auth');
    $identity = $auth->getIdentity();
    $role = $identity->role;
    if (in_array($role, $allowed)):
        ?>
        <div id="radius">
            <?php $distance = array(1, 2, 3, 4, 5, 10, 20); ?>
            <p>
                Find objects within:
            </p>

            <div class="btn-group">
                <?php foreach ($distance as $range): ?>
                    <a class="btn btn-mini btn-success" href="<?php echo $this->url(array(
                        'module' => 'database', 'controller' => 'search', 'action' => 'results',
                        'lat' => $this->lat, 'lon' => $this->lon, 'd' => $range
                    ), null, true); ?>"
                       title="Use the Haversine formula to find adjacent objects"> <?php echo $range; ?> km
                        radius </a>
                <?php endforeach; ?>
            </div>


        </div>
    <?php endif; ?>
    <?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function() {
    <?php
    $user = new Pas_User_Details();
    $person = $user->getPerson();
    if ($person) {
        $role = $person->role;
    } else {
        $role = NULL;
    }
    $allowed = array(
        'admin', 'fa', 'flos',
        'research', 'treasure', 'hero',
        'hoard'
    );
    if (in_array($role, $allowed)) {
        $maxzoom = 18;
        $minzoom = 1;
    } else {
        $maxzoom = 11;
        $minzoom = 1;
    }
    ?>

    var max = <?php echo $maxzoom; ?>;
    var min = <?php echo $minzoom; ?>;

    var imperium = new google.maps.ImageMapType({
    getTileUrl: function (coord, zoom) {
    return "<?php echo $this->serverUrl(); ?>/imperium/" +
    zoom + "/" + coord.x + "/" + coord.y + ".png";

    },
    tileSize: new google.maps.Size(256, 256),
    isPng: true,
    alt: "Imperium layer",
    name: "Imperium",
    maxZoom: 11,
    minZoom:3
    });

    var osmMapType = new google.maps.ImageMapType({
    getTileUrl: function (coord, zoom) {
    return "https://b.tile.openstreetmap.org/" +
    zoom + "/" + coord.x + "/" + coord.y + ".png";

    },
    tileSize: new google.maps.Size(256, 256),
    isPng: true,
    alt: "OpenStreetMap layer",
    name: "OSM",
    maxZoom: max
    });


    var myOptions = {
    center: new google.maps.LatLng(<?php echo $this->lat; ?>, <?php echo $this->lon; ?>),
    zoom: 12,
    mapTypeControlOptions: {
    mapTypeIds: [
    google.maps.MapTypeId.ROADMAP,
    google.maps.MapTypeId.HYBRID,
    google.maps.MapTypeId.TERRAIN,
    google.maps.MapTypeId.SATELLITE,
    'OSM',
    'Imperium',
    ]
    },
    mapTypeControl: true,
    style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
    scaleControl: true,
    zoomControl: true,
    mapTypeId: 'OSM',
    scrollwheel: false,
    };
    var map = new google.maps.Map(document.getElementById("map"),
    myOptions);
    map.mapTypes.set('OSM',osmMapType);
    map.mapTypes.set('Imperium',imperium);
    map.setTilt(45);
    var marker = new google.maps.Marker({
    position: new google.maps.LatLng(<?php echo $this->lat; ?>, <?php echo $this->lon; ?>),
    map: map,
    animation: google.maps.Animation.DROP,
    title:"Findspot location",
    icon: "<?php echo $this->serverUrl() . $this->baseUrl(); ?>/assets/mapIcons/museumArcheological.png"
    });

    var myTitle = document.createElement('h1');
    myTitle.style.color = '#444444';
    myTitle.style.font = "10px sans-serif";


    var myTextDiv = document.createElement('div');
    myTextDiv.appendChild(myTitle);

    map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(myTextDiv);

    map.data.loadGeoJson('<?php echo $this->serverUrl(); ?>/geojson/<?php echo $this->regionID; ?>.geojson');
    map.data.loadGeoJson('<?php echo $this->serverUrl(); ?>/geojson/<?php echo $this->districtID; ?>.geojson');
    map.data.loadGeoJson('<?php echo $this->serverUrl(); ?>/geojson/<?php echo $this->parishID; ?>.geojson');

    <?php
    $bbox = new Pas_Geo_BoundBox();
    $d = 5;  // distance
    $path_top_right = $bbox->createPoint($this->lat, $this->lon, 45, $d);
    $path_bottom_right = $bbox->createPoint($this->lat, $this->lon, 135, $d);
    $path_bottom_left = $bbox->createPoint($this->lat, $this->lon, 225, $d);
    $path_top_left = $bbox->createPoint($this->lat, $this->lon, 315, $d);
    ?>

    var latLngBounds = new google.maps.LatLngBounds(
    new google.maps.LatLng(<?php echo $path_bottom_left; ?>),
    new google.maps.LatLng(<?php echo $path_top_right; ?>)
    );
    map.fitBounds(latLngBounds);
    google.maps.event.addListener(marker, 'click', toggleBounce);

    function toggleBounce() {
    if (marker.getAnimation() != null) {
    marker.setAnimation(null);
    } else {
    marker.setAnimation(google.maps.Animation.BOUNCE);
    }
    }
    });
    <?php $this->inlineScript()->captureEnd(); ?>
<?php endif; ?>
    <div class="row-fluid">

    <div class="span4">
        <h3 class="lead">Spatial metadata</h3>

        <p>
            <?php if (!is_null($this->region)) : ?>
                Region: <a
                    href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->regionID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->region; ?></a>
                <i class="icon-external-link"></i>

                <?php if (!is_null($this->regionType)): ?>
                    (<?php echo $this->regionType; ?>)
                <?php endif; ?>
                <br/>
            <?php endif; ?>
            <?php if (!is_null($this->county)) : ?>
                County or Unitary authority: <a
                    href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->countyID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->county; ?></a>
                <i class="icon-external-link"></i>
                <?php if (!is_null($this->countyType)): ?>
                    (<?php echo $this->countyType; ?>)
                <?php endif; ?><br/>
            <?php endif; ?>
            <?php if (!is_null($this->district)) : ?>
                District: <a
                    href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->districtID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->district; ?></a>
                <i class="icon-external-link"></i>
                <?php if (!is_null($this->districtType)): ?>
                    (<?php echo $this->districtType; ?>)
                <?php endif; ?>

            <?php endif; ?>
            <?php if (!is_null($this->parish)) : ?>
                <br/>
                Parish or ward: <a
                    href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->parishID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->parish; ?></a>
                <i class="icon-external-link"></i>
                <?php if (!is_null($this->parishType)): ?>
                    (<?php echo $this->parishType; ?>)
                <?php endif; ?>
            <?php endif; ?>
            <?php if (!is_null($this->knownas)) : ?>
                <br/><span class="knownas">To be known as: <?php echo $this->escape($this->knownas); ?></span>
            <?php endif; ?>
            <?php if ($this->centreLat): ?>
                <br/>
                Centre of parish as LatLon pair: <?php echo $this->centreLat; ?>,<?php echo $this->centreLon; ?>
                <br/>
                Centre of parish <?php echo $this->gridRef($this->centreLat, $this->centreLon); ?>
            <?php endif; ?>
        </p>

    </div>

    <div class="span4">
<?php if (!is_null($this->gridref)): ?>
    <h3 class="lead">Spatial coordinates</h3>

    <p>
        Grid reference: <?php echo $this->stripGrid()->setGrid($this->gridref); ?><br/>
        <span class="fourfigure">4 Figure: <?php echo $this->fourFigure; ?></span><br/>
        <?php if (!is_null($this->source)): ?>
            Grid reference source: <?php echo $this->escape($this->source); ?><br/>
        <?php endif; ?>
        Grid reference accurate to a <?php echo $this->getAccuracy()->setGridRef($this->gridref); ?> metre
        square.<br/>
        Grid reference length: <?php echo $this->gridlen; ?><br/>
        Easting: <?php echo $this->easting; ?> Northing: <?php echo $this->northing; ?><br/>
        Latitude: <?php echo $this->lat; ?> Longitude: <?php echo $this->lon; ?><br/>
        Four figure Latitude: <?php echo $this->fourFigureLat; ?><br/> Four figure
        longitude: <?php echo $this->fourFigureLon; ?><br/>
        1:25K map: <?php echo $this->map25k; ?><br/>
        1:10K map: <?php echo $this->map10k; ?><br/>
        <?php if ((!is_null($this->woeid)) && is_null($this->knownas)): ?>
            WOEID: <a href="http://woe.spum.org/id/<?php echo $this->woeid; ?>"><?php echo $this->woeid; ?></a><br/>
        <?php endif; ?>
        <?php if (!is_null($this->elevation)): ?>
            Elevation: <?php echo $this->elevation; ?> metres<br/>
        <?php endif; ?>
    </p>

    </div>

    <div class="span4 noprint">
        <?php echo $this->domesdayNear()->setLat($this->lat)->setLon($this->lon)->setRadius(2); ?>
    </div>

    </div>

    <div class="row-fluid">
        <?php //echo $this->findsNearSmr()->setLat($this->lat)->setLon($this->lon)->setDistance(0.25); ?>
    </div>

    <div class="row-fluid">

        <div class="span4 noprint">
            <?php echo $this->findspotGeo()->setWoeID($this->woeid)->setLat($this->lat)->setLon($this->lon); ?>
        </div>

        <div class="span4 noprint">
            <?php echo $this->yahooGeoAdjacent()->setWoeid($this->woeid); ?>
        </div>
        <?php
        $discovery = array($this->method, $this->disccircum, $this->curr_loc, $this->landvalue, $this->landuse);
        if (array_filter($discovery)):
            ?>
            <div class="span4">
                <h3 class="lead">Discovery metadata</h3>

                <p>
                    <?php if (!is_null($this->discoveryMethod)) : ?>
                        Method of discovery: <?php echo $this->escape($this->discmethod); ?>
                        <a href="<?php echo $this->url(array(
                            'module' => 'datalabs',
                            'controller' => 'terminology',
                            'action' => 'method',
                            'id' => $this->discoveryMethod), null, true); ?>"
                           title="Read scope note for <?php echo $this->discmethod; ?>"><i class="icon-search"></i></a>
                        <br/>
                    <?php endif; ?>

                    <?php if (!is_null($this->disccircum)) : ?>
                        Discovery circumstances:  <?php echo $this->escape($this->disccircum); ?> <br/>
                    <?php endif; ?>

                    <?php if (!is_null($this->curr_loc)) : ?>
                        Current location: <?php echo $this->escape($this->curr_loc); ?> <br/>
                    <?php endif; ?>

                    <?php if (!is_null($this->landvalue)) : ?>
                        General land use: <?php echo $this->landvalue; ?>
                        <a href="<?php echo $this->url(array(
                                'module' => 'datalabs',
                                'controller' => 'terminology',
                                'action' => 'landuse',
                                'id' => $this->landusevalue)
                            , NULL, true); ?>" title="View scope notes for <?php echo $this->landvalue; ?>"><i
                                class="icon-search"></i></a>
                        <br/>
                    <?php endif; ?>

                    <?php if (!is_null($this->landuse)) : ?>
                        Specific landuse: <?php echo $this->escape($this->landuse); ?>
                        <a href="<?php echo $this->url(array(
                            'module' => 'datalabs',
                            'controller' => 'terminology',
                            'action' => 'landuse',
                            'id' => $this->landusecode), null, true); ?>"
                           title="Read scope note for <?php echo $this->landuse; ?>"><i class="icon-search"></i></a>
                    <?php endif; ?>
                </p>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>

    <!-- </div> -->
<?php
$details = array(
    $this->findspotDescription, $this->comments, $this->landOwnerName,
    $this->address, $this->postcode, $this->landOwnerID
);
?>
<?php if (array_filter($details)): ?>
    <div class="row-fluid">
        <p>
            <?php if (!is_null($this->findspotDescription)): ?>
                Find spot description: <?php echo strip_tags($this->findspotDescription); ?>
            <?php endif; ?>

            <?php if (!is_null($this->comments)): ?>
                <br/>
                Find spot comments: <?php echo strip_tags($this->comments); ?>
            <?php endif; ?>

            <?php if (!is_null($this->landOwnerName)): ?>
                <br/>
                Land owned by: <a
                    href="<?php echo $this->url(array('module' => 'database', 'controller' => 'people', 'action' => 'person', 'id' => $this->landOwnerID), 'default', true); ?>"><?php echo $this->landOwnerName; ?></a>
            <?php endif; ?>

            <?php if (!is_null($this->address)): ?>
                <br/>
                Address: <?php echo $this->escape($this->address); ?>
            <?php endif; ?>

            <?php if (!is_null($this->postcode)): ?>
                <br/>
                Postcode: <?php echo $this->escape($this->postcode); ?>
            <?php endif; ?>

        </p>
    </div>
<?php endif; ?>