<?php if (!is_null($this->gridref) && is_null($this->knownas)) : ?>
    <?php
    $this->googleDynamicMap(null, null, true);
    ?>
    <?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function() {
    <?php
    $user = new Pas_User_Details();
    $person = $user->getPerson();
    if ($person) {
        $role = $person->role;
    } else {
        $role = NULL;
    }
    $allowed = array('admin', 'fa', 'flos', 'research', 'treasure');
    if (in_array($role, $allowed)) {
        $maxzoom = 18;
        $minzoom = 1;
    } else {
        $maxzoom = 11;
        $minzoom = 1;
    }
    ?>

    var max = <?php echo $maxzoom; ?>;
    var min = <?php echo $minzoom; ?>;

    var imperium = new google.maps.ImageMapType({
    getTileUrl: function (coord, zoom) {
    return "<?php echo $this->serverUrl();?>/imperium/" +
    zoom + "/" + coord.x + "/" + coord.y + ".png";

    },
    tileSize: new google.maps.Size(256, 256),
    isPng: true,
    alt: "Imperium layer",
    name: "Imperium",
    maxZoom: 10,
    minZoom:3
    });

    var osmMapType = new google.maps.ImageMapType({
    getTileUrl: function (coord, zoom) {
    return "https://a.tile.openstreetmap.org/" +
    zoom + "/" + coord.x + "/" + coord.y + ".png";

    },
    tileSize: new google.maps.Size(256, 256),
    isPng: true,
    alt: "OpenStreetMap layer",
    name: "OSM",
    maxZoom: max
    });


    var myOptions = {
    center: new google.maps.LatLng(<?php echo $this->fourFigureLat; ?>, <?php echo $this->fourFigureLon; ?>),
    zoom: 12,
    mapTypeControlOptions: {
    mapTypeIds: [
    google.maps.MapTypeId.ROADMAP,
    google.maps.MapTypeId.HYBRID,
    google.maps.MapTypeId.TERRAIN,
    google.maps.MapTypeId.SATELLITE,
    'OSM',
    'Imperium',
    ]
    },
    mapTypeControl: true,
    style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
    scaleControl: true,
    zoomControl: true,
    mapTypeId: 'OSM',
    scrollwheel: false,
    maxZoom: max,
    minZoom: min
    };
    var map = new google.maps.Map(document.getElementById("map"),
    myOptions);
    map.mapTypes.set('OSM',osmMapType);
    map.mapTypes.set('Imperium',imperium);
    map.setTilt(45);

    var myTitle = document.createElement('h1');
    myTitle.style.color = '#444444';
    myTitle.style.font = "10px sans-serif";
    myTitle.innerHTML = 'Imperium layer from the <a href="http://pelagios-project.blogspot.co.uk/2012/09/a-digital-map-of-roman-empire.html">Pelagios project</a> <a href="http://creativecommons.org/licenses/by/3.0/">CC-BY</a> | Historical maps from <a href="http://geo.nls.uk/maps/api/">NLS Maps API</a> | OSM &copy; <a href="http://www.openstreetmap.org/">OpenStreetMap</a> contributors,<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>';
    var myTextDiv = document.createElement('div');
    myTextDiv.appendChild(myTitle);

    map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(myTextDiv);

    <?php if(!is_null($this->regionID)):?>
        map.data.loadGeoJson('<?php echo $this->serverUrl(); ?>/geojson/<?php echo $this->regionID; ?>.geojson');
    <?php endif;?>

    <?php if(!is_null($this->countyID)):?>
        map.data.loadGeoJson('<?php echo $this->serverUrl(); ?>/geojson/<?php echo $this->countyID; ?>.geojson');
    <?php endif;?>

    <?php if(!is_null($this->districtID)):?>
        map.data.loadGeoJson('<?php echo $this->serverUrl(); ?>/geojson/<?php echo $this->districtID; ?>.geojson');
    <?php endif;?>

    <?php if(!is_null($this->parishID)):?>
        map.data.loadGeoJson('<?php echo $this->serverUrl(); ?>/geojson/<?php echo $this->parishID; ?>.geojson');
    <?php endif;?>

    map.data.setStyle({
    fillColor: 'white',
    fillOpacity: 0.0,
    strokeColor: 'black',
    strokeWeight: 0.9
    });

    <?php
    $bbox = new Pas_Geo_BoundBox();
    $d = 5;  // distance
    $path_top_right = $bbox->createPoint($this->lat, $this->lon, 45, $d);
    $path_bottom_right = $bbox->createPoint($this->lat, $this->lon, 135, $d);
    $path_bottom_left = $bbox->createPoint($this->lat, $this->lon, 225, $d);
    $path_top_left = $bbox->createPoint($this->lat, $this->lon, 315, $d);
    ?>

    var latLngBounds = new google.maps.LatLngBounds(
    new google.maps.LatLng(<?php echo $path_bottom_left; ?>),
    new google.maps.LatLng(<?php echo $path_top_right; ?>)
    );
    map.fitBounds(latLngBounds);
    });
    <?php $this->inlineScript()->captureEnd(); ?>

    <!-- the map container -->
    <div id="map">
        <!-- If no script render a static map -->
        <noscript>
            <img
                src="https://maps.google.com/maps/api/staticmap?center=<?php echo $this->fourFigureLat; ?>,<?php echo $this->fourFigureLon; ?>&amp;zoom=6&amp;size=640x300&amp;maptype=terrain&amp;markers=color:green|label:G|<?php echo $this->fourFigureLat; ?>,<?php echo $this->fourFigureLon; ?>&amp;sensor=false"
                alt="Findspot map generated via google static maps"/>
        </noscript>
        <!-- render static map finish -->
    </div>
    <!-- End of map container -->
<?php endif; ?>

<!-- Main div -->
<div class="row-fluid">

    <!-- the spatial metadata column -->
    <div class="span4">
        <h3 class="lead">Spatial metadata</h3>

        <?php if (!is_null($this->region)) : ?>
            Region: <a
                href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->regionID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->region; ?></a>

            <?php if (!is_null($this->regionType)): ?>
                (<?php echo $this->regionType; ?>)
            <?php endif; ?>
        <?php endif; ?>
        <?php if (!is_null($this->county)) : ?>
            <br/>
            County or Unitary authority: <a
                href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->countyID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->county; ?></a> <?php if (!is_null($this->countyType)): ?>
                (<?php echo $this->countyType; ?>)
            <?php endif; ?>
        <?php endif; ?>
        <?php if (!is_null($this->district)) : ?>
            <br/>
            District: <a
                href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->districtID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->district; ?></a>
            <?php if (!is_null($this->districtType)): ?>
                (<?php echo $this->districtType; ?>)
            <?php endif; ?>

        <?php endif; ?>

            <?php if (!is_null($this->parish) && is_null($this->knownas))  : ?>
                <br/>
                Parish or ward: <a
                    href="http://data.ordnancesurvey.co.uk/doc/7000000000<?php echo str_pad($this->parishID, 6, '0', STR_PAD_LEFT); ?>"><?php echo $this->parish; ?></a> <?php if (!is_null($this->parishType)): ?>
                    (<?php echo $this->parishType; ?>)<?php endif;?>
                <?php endif; ?>

            <?php if (!is_null($this->knownas)) : ?>
                <br/>
                <span class="knownas">To be known as: <?php echo $this->escape($this->knownas); ?></span>
            <?php endif; ?>
        </p>

    </div>
    <!-- End of spatial metadata column -->

    <!-- Start of the coordinates column -->
    <div class="span4">
        <?php if (!is_null($this->gridref)): ?>
        <h3 class="lead">Spatial coordinates</h3>

        <p>
            <?php if (!is_null($this->gridref) && is_null($this->knownas)): ?>
                <span class="fourfigure">4 Figure: <?php echo $this->fourFigure; ?></span>
                <br/>
                Four figure Latitude: <?php echo $this->fourFigureLat; ?>
                <br />
                Four figure longitude: <?php echo $this->fourFigureLon; ?>
                <?php if (!is_null($this->map25k)): ?>
                    <br/>
                    1:25K map: <?php echo $this->map25k; ?>
                <?php endif; ?>

                <?php if(!is_null($this->map10k)):?>
                <br/>
                1:10K map: <?php echo $this->map10k; ?>
                <?php endif;?>

                <?php if ((!is_null($this->woeid)) && is_null($this->knownas)): ?>
                    <br/>
                    WOEID: <a href="http://woe.spum.org/id/<?php echo $this->woeid; ?>"><?php echo $this->woeid; ?></a>
                <?php endif; ?>
                <?php if(!is_null($this->what3words)):?>
                    <br />
                    <a href="https://what3words.com"> What3Words</a>: <a href="https://map.what3words.com/<?php echo $this->what3words;?>"><?php echo $this->what3words;?></a> <i class="icon-external-link"></i>
                <?php endif;?>
            <?php endif; ?>

            <?php if ($this->source): ?>
                <br/>
                Grid reference source: <?php echo $this->escape($this->source); ?>
            <?php endif; ?>

            <?php if (!is_null($this->gridref)): ?>
                <br/>
                Unmasked grid reference accurate to a <?php echo $this->getAccuracy()->setGridRef($this->gridref); ?> metre square.
            <?php endif; ?>


        </p>

    </div>
    <!-- End of spatial coordinates column -->


    <!-- Start of the discovery column -->
    <?php
    $discovery = array($this->method, $this->disccircum, $this->curr_loc, $this->landvalue, $this->landuse);
    if(array_filter($discovery)):
        ?>
    <div class="span4">
        <h3 class="lead">Discovery metadata</h3>

        <p>
            <?php if (!is_null($this->discmethod)) : ?>
                Method of discovery: <?php echo $this->escape($this->discmethod); ?>
                <a href="<?php echo $this->url(array(
                    'module' => 'datalabs',
                    'controller' => 'terminology',
                    'action' => 'method',
                    'id' => $this->discoveryMethod), null, true); ?>"
                   title="Read scope note for <?php echo $this->discmethod; ?>"><i class="icon-search"></i></a>
                <br/>
            <?php endif; ?>

            <?php if (!is_null($this->disccircum)) : ?>
                Discovery circumstances:  <?php echo $this->escape($this->disccircum); ?> <br/>
            <?php endif; ?>

            <?php if (!is_null($this->curr_loc)) : ?>
                Current location: <?php echo $this->escape($this->curr_loc); ?> <br/>
            <?php endif; ?>

            <?php if (!is_null($this->landvalue)) : ?>
                General landuse: <?php echo $this->landvalue; ?>
                <a href="<?php echo $this->url(array(
                            'module' => 'datalabs',
                            'controller' => 'terminology',
                            'action' => 'landuse',
                            'id' => $this->landusevalue)
                        , NULL, true);?>" title="View scope notes for <?php echo $this->landvalue; ?>"><i class="icon-info-sign"></i></a>
                <br/>
            <?php endif; ?>

            <?php if (!is_null($this->landuse)) : ?>
                Specific landuse: <?php echo $this->escape($this->landuse); ?>
                <a href="<?php echo $this->url(array(
                        'module' => 'datalabs',
                        'controller' => 'terminology',
                        'action' => 'landuse',
                        'id' => $this->landusecode), null, true);?>"
                                        title="Read scope note for <?php echo $this->landuse; ?>"><i class="icon-info-sign"></i></a>
                <br/>
            <?php endif; ?>
        </p>
    </div>
    <!-- end of discovery column -->
        <?php endif;?>

<?php endif; ?>

</div>

<?php if (!is_null($this->gridref) && is_null($this->knownas)): ?>
    <div class="row-fluid">
        <div class="span4">
            <?php //echo $this->domesdayNear()->setLat($this->fourFigureLat)->setLon($this->fourFigureLon)->setRadius(2); ?>
        </div>
    </div>
<?php endif; ?>
