<?php
$this->headTitle('Contact the Scheme');
$this->headMeta('Contact the Portable Antiquities Scheme','description');
?>
<h2>Contact the Portable Antiquities Scheme</h2>
<p>The British Museum cannot provide valuations for any objects; if this is what you require we suggest that you contact a reputable auction house or a numismatic dealer.
</p>
<?php echo $this->form;?>
<p>If your query is related to getting objects found within the boundaries of England and Wales recorded 
with the Scheme then go to our <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'contacts'),null,true);?>">
contacts page</a>. </p>
<p>If your object is from outside England and Wales, then the following might be of more use to you:</p>
<ul> 
<li>Ancient Egypt and the Sudan: egyptian@britishmuseum.org +44 (0) 207 323 8311</li>
<li>Coins and Medals: coins@britishmuseum.org +44 (0) 207 323 8607</li>
<li>Middle East: ancientneareast@britishmuseum.org +44 (0) 207 323 8308</li>
<li>Greek and Roman: greekandroman@britishmuseum.org +44 (0) 207 323 8321</li>
<li>Asia: asia@britishmuseum.org +44 (0) 207 323 8416</li>
<li>Africa,Oceania and Americas:  aoa@britishmuseum.org +44 (0) 207 323 8041</li>
<li>Prehistory and Europe: prehistoryandeurope@britishmuseum.org +44 (0) 207 323 8629</li>
<li>Prints and drawings: prints@britishmuseum.org +44 (0) 207 323 8408</li>
<li>Ancient Near East: anicentneareast@britishmuseum.org +44 (0) 207 323 8308</li>
</ul>
<p>If you are enquiring about tickets please contact our box office.</p>
<p>If you are making a Freedom of Information request, we suggest you contact us directly on +44 (0) 207 323 8611, we'll probably just tell you..</p>
 