<?php
$this->headTitle('Issuing mints of the Byzantine Empire');
$this->metaBase()->setDescription('A list of all Byzantine or Latin Empire issuing mints that the Scheme
uses on its database. The background information have been enhanced from dbpedia')
    ->setKeywords('issuing,mints,byzantium,holy roman empire,numsimatics')
    ->setSubject('numismatics and archaeology of Byzantium')
    ->generate();
?>

<h2 class="lead"><?php echo $this->title(); ?></h2>

<ul>
    <?php echo $this->partialLoop(('partials/numismatics/mints.phtml'), $this->mints); ?>
</ul>