<?php $this->headTitle('Visits to the site by hour ' . $this->timeSpanParameter());?>
<h2><?php echo $this->title();?></h2>
<?php echo $this->timeSpansGa();?>

<div id="chart"></div>

<table class="table table-striped">
	<caption><?php echo $this->title();?></caption>
	<thead>
		<tr>
			<th>Hour of the day</th>
			<th>Number of visits</th>
			<th>Number of visitors</th>
			<th>Time on site</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->results as $row):?>
		<tr>
			<td><?php echo date("H:i", STRTOTIME($row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_HOUR)->value . ':00'));?></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITS)->value;?></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value;?></td>
			<td><?php echo $this->secondsToMinutes()->setSeconds($row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_AVG_TIME_ON_SITE)->value);?></td>
		</tr>
<?php endforeach;?>	
	</tbody>
</table>
<?php 
$this->inlineScript()->appendFile('https://www.google.com/jsapi',$type = 'text/javascript');
$this->inlineScript()->captureStart();?>
google.load('visualization', '1', {packages: ['corechart']});
 function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
          ['Hour',   'Visitors'],
          <?php foreach($this->results as $row):?>
          ['<?php echo date("H:i", STRTOTIME($row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_HOUR)->value . ':00'));?>' , <?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value;?> ],
          <?php endforeach;?>
        ]);
      
        // Create and draw the visualization.
        var ac = new google.visualization.AreaChart(document.getElementById('chart'));
        ac.draw(data, {
          title : 'Hourly visits',
          isStacked: true,
          width: 900,
          height: 400,
          vAxis: {title: "Visitors"},
          hAxis: {title: "Hour"}
        });
      }
      

      google.setOnLoadCallback(drawVisualization);
<?php $this->inlineScript()->captureEnd();?>   