<?php
$this->headTitle('Visitors analytical data provided via Google Analytics ' . $this->timeSpanParameter());
?>
<h2><?php echo $this->title();?></h2>
<?php echo $this->timeSpansGa();?>
<?php echo $this->form;?>

<?php 
$this->inlineScript()->appendFile('https://www.google.com/jsapi',$type = 'text/javascript');
$this->inlineScript()->captureStart();?>
google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Date', 'Visitors', 'Visits'],
      <?php 
      $data = array();
      foreach($this->results as $row){
      	$data[] =array(
      	'date' => $row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_DATE)->value,
      	'visitors' => $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value,
      	'visits' =>  $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITS)->value
      	);
      }
      ?>
      <?php 
      foreach($data as $d){
      	?>
      	['<?php echo $d['date'];?>', <?php echo $d['visitors'];?>, <?php echo $d['visits'];?>],
      	<?php       }
      ?>
        
        ]);

        var options = {
        title: 'Vistors vs visits'
        };

        var chart = new google.visualization.LineChart(document.getElementById('chart'));
        chart.draw(data, options);
    };
<?php $this->inlineScript()->captureEnd();?>   
<div id="chart" style="width: 900px; height: 500px;"></div>

<table class="table table-striped">
	<caption><?php echo $this->title();?> </caption>
		<thead>
		<tr>
			<th>Date</th>
			<th>Visitors</th>
			<th>Visits</th>
			<th>Bounces</th>
			<th>Time on site</th>
		</tr>
		</thead>
		<tbody>
			<?php foreach($this->results as $row):
			?>
			
			<tr>
				<td><?php echo $this->niceshortdate(strtotime($row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_DATE)->value));?></td>
				<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value;?></td>
				<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITS)->value;?></td>
				<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_BOUNCES)->value;?></td>
				<td><?php echo $this->secondsToMinutes()->setSeconds($row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_AVG_TIME_ON_SITE));?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
</table>
