<?php 
$this->inlineScript()->captureStart();?>
$(document).ready(function() {


    var nlsmap = new google.maps.ImageMapType({
	   getTileUrl: function(tile, zoom) { 
	   return NLSTileUrlOS(tile.x, tile.y, zoom); 
	   },
	   tileSize: new google.maps.Size(256, 256),
	   isPng: false,
	   maxZoom: <?php echo $this->maxZoom;?>,
	   minZoom: <?php echo $this->minZoom;?>,
	   name: 'Historic',
	   alt: "NLS Historic Map"
	});
});

<?php $this->inlineScript()->captureEnd();?>


