<?php
$this->headTitle('Your account is ready!');
$this->metaBase()->setSubject('Error reports')
    ->setDescription('A page that is displayed when an account is not set up completely')
    ->generate();
?>
<h1 class="lead">Welcome!</h1>

<p>Thank you for registering with the PAS. You are now able to explore the database and see all the finds you have recorded.</p>
<p>What would you like to do next?</p>

<ul>
    <li><a href="<?php echo ($this->baseUrl().'/database'); ?>">Search the database</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/contacts'); ?>">Find your local FLO</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/treasure'); ?>">Read about the Treasure Act 1996</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/guides'); ?>">Read our guides</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/publications'); ?>">Read our Annual Reports</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/news'); ?>">Find out our latest news</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/counties'); ?>">Visit your local County Page</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/users/account'); ?>">Change your password</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/users/account'); ?>">Edit your account</a></li>
    <li><a href="<?php echo ($this->baseUrl().'/users/account'); ?>">Request an account upgrade</a></li>
</ul>

<div class="row-fluid">
    <img src="http://farm7.staticflickr.com/6051/6432122477_e0b9b17530_b.jpg" alt="Gladiator" width="250px"/>
</div>
<p>The image above is a CC licenced image by <a href="http://www.flickr.com/photos/54459164@N00/">Johnson Cameraface</a>.
</p>
