<?php

$this->headTitle("You don't have permission to do that");
$this->metaBase()->setSubject('Error reports')
    ->setDescription('A page that is displayed when an account is not set up completely')
    ->generate();
?>

<div class="container">
    <div class="row">
        <div class="span12">
            <br />&nbsp;
        </div>
    </div>
    <div class="row">
        <div class="span2"></div>
        <div class="span8">
            <div class="row">
                <div class="span8">
                    <h1 class="lead">Sorry! You don't have permission to do that.</h1>
                    <p>But please take a look at the links below, and explore the database.</p>
                    <p>What would you like to do next?</p>
                </div>
            </div>

            <div class="row">
                <div class="span3">
                    <ul>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/database'); ?>">Search the database<br></a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/contacts'); ?>">Find your local FLO</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/treasure'); ?>">Read about the Treasure Act 1996</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/guides'); ?>">Read our guides</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/publications'); ?>">Read our Annual Reports</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/news'); ?>">Find out our latest news</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/counties'); ?>">Visit your local County Page</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/users/account/changepassword'); ?>">Change your password</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/users/account/edit'); ?>">Edit your account</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/users/account/upgrade'); ?>">Request an account upgrade</a></li>
                        <li><a href="<?php
                            echo($this->baseUrl() . '/users/account'); ?>">Visit your account</a></li>
                    </ul>
                </div>

                <div class="span5">
                    <figure style="width: 250px; margin: 0px;">
                        <img src="https://farm7.staticflickr.com/6051/6432122477_e0b9b17530_b.jpg" alt="Gladiator"
                             width="250px"/>
                        <figcaption style="text-align:center">The image above is a CC licenced image by <a
                                    href="https://farm7.staticflickr.com/6051/6432122477_e0b9b17530_b.jpg/">Johnson
                                Cameraface</a>.
                        </figcaption>
                    </figure>
                </div>
            </div>

        </div>
        <div class="span2"></div>
    </div>
</div>

<hr class="featurette-divider">
