<?php $this->headTitle('Your account needs some work!');?>
<h1>Your account is not connected to your finds yet.</h1> 

<p>When you registered for access to the database, it was the first step to getting access to your records. 
To finish this process we need you to do the following:</p>
<ul>
<li>Contact your local <a href="<?php echo $this->url(array('module' => 'contacts'),null,true);?>" title="Contact your flo">Finds Liaison Officer</a></li>
<li>Ask them to link your username to your personal data</li>
</ul>
<div style="margin-left:90px; margin-right:20px">
<img src="http://farm4.static.flickr.com/3407/3478660349_f8ed50f4d7.jpg" alt="The trip home" width="500" height="322" />
</div>
<p>The image above is a CC licenced image by <a href="http://www.flickr.com/photos/kwl/" >Kennymatic</a>.</p>