<?php $this->headTitle('Your account needs some work!');?>
<h1>Your account isn't ready for recording yet.</h1> 

<p>When you registered for access to the database, this was the first step on your route to recording glory. 
To finish this process we need you to do the following:</p>
<ul>
<li>Contact your local <a href="<?php echo $this->url(array('module' => 'contacts'),null,true);?>" title="Contact your flo">Finds Liaison Officer</a></li>
<li>If you haven't recorded with us before give them the personal details they ask for</li>
<li>Ask them to link your username to your personal data</li>
<li>Record in style!</li>
</ul>
<div class="row-fluid">
<img src="http://farm7.staticflickr.com/6051/6432122477_e0b9b17530_b.jpg" alt="Gladiator"  />
</div>
<p>The image above is a CC licenced image by <a href="http://www.flickr.com/photos/54459164@N00/" >Johnson Cameraface</a>.</p>