<?php $this->headTitle('Our database is having a glitch');?>
<h1>Unfortunately we have a problem</h1> 

<p>We've logged this and will look into it right away</p>
<div style="margin-left:90px; margin-right:20px">
<img src="http://farm4.static.flickr.com/3407/3478660349_f8ed50f4d7.jpg" alt="The trip home" width="500" height="322" />
</div>
<p>The image above is a CC licenced image by <a href="http://www.flickr.com/photos/kwl/" >Kennymatic</a>.</p>