<?php
$this->headTitle('Iron Age denominations');
$this->metaBase()->setSubject('Iron Age numismatics')
    ->setDescription('Iron Age denominations in use on the PAS database')
    ->setKeywords('iron age, celtic, numismatics')
    ->generate();?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/iadenoms.phtml', $this->denoms) ?>
</ul>
