<?php echo $this->partialLoop('partials/numismatics/category.phtml', $this->categories); ?>

<div class="row-fluid">
    <!--  Navigation for tabs  -->
    <ul id="tab" class="nav nav-tabs">
        <li class="active"><a href="#rulers" data-toggle="tab">Issuing rulers</a></li>
        <li><a href="#types" data-toggle="tab">Types</a></li>
        <li><a href="#map" data-toggle="tab">Map</a></li>
    </ul>
    <!--  End of Tabs navigation -->

    <!-- Start of tabbed content div -->
    <div id="myTabContent" class="tab-content">

        <div class="tab-pane fade in active" id="rulers">
            <h3 class="lead">Associated rulers</h3>
            <?php if (!empty($this->denominations)): ?>
                <ul>
                    <?php echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->rulers) ?>
                </ul>
            <?php else: ?>
                <p>No rulers available.</p>
            <?php endif; ?>
        </div>

        <div class="tab-pane fade" id="types">
            <h3 class="lead">Types of coin associated with this category</h3>
            <?php if (!empty($this->types)): ?>
                <ul>
                    <?php echo $this->partialLoop('partials/numismatics/types.phtml', $this->types) ?>
                </ul>
            <?php else: ?>
                <p>No types available.</p>
            <?php endif; ?>
        </div>

        <div class="tab-pane fade" id="map">

        </div>
    </div>
    <!--  End of tabbed content div -->

</div>