<?php
$this->headTitle('Medieval coin categories');
$this->metaBase()->setSubject('Medieval numismatics')
    ->setDescription('A list of medieval coin categories')
    ->setKeywords('medieval,numismatics,coin,categories')
    ->generate();
?>

<h2 class="lead"><?php echo $this->title(); ?></h2>

<ul>
    <?php echo $this->partialLoop('partials/numismatics/medieval/categories.phtml', $this->categories); ?>
</ul>