<li>
    <a href="<?= $this->url(array('module' => 'romancoins', 'controller' => 'emperors', 'action' => 'emperor', 'id' => $this->id), null, true) ?>">
       <?= $this->issuer ?>
    </a>

    <?php
        $printableYearFrom = $this->adBc()->setDate($this->date_from)->html();
        $printableYearTo = $this->adBc()->setDate($this->date_to)->html();
    ?>
    <?php if (empty($printableYearTo)) : ?>
        [<?= $printableYearFrom ?>]
    <?php else: ?>
        [<?= $printableYearFrom ?> - <?= $printableYearTo ?>]
    <?php endif; ?>

    <a href="<?= $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'ruler' => $this->dbaseID,), null, true) ?>" title="View all records on the database">
	<i class="icon-search"></i>
    </a>
</li>
