<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 06/08/15
 * Time: 15:55
 */
?>
<?php if (!empty($this->startDate)): ?>
    <li>
        <a href="<?= $this->type ?>">
            <?= $this->label ?>
            <i class="fa fa-external-link"></i>
        </a>
        Issued: 
        <?= implode(' - ', array(
                    $this->adBc()->setDate($this->startDate->__toString())->__toString(),
                    $this->adBc()->setDate($this->endDate->__toString())->__toString()
                )
            ) 
        ?>
    </li>   
<?php else: ?>
    <li>
        <a href="<?= $this->type ?>">
            <?= $this->label ?>
            <i class="fa fa-external-link"></i>
        </a>
    </li>
<?php endif; ?>
