<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$cats  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$cats->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

foreach($this->categories as $r){
$r = (object)$r;
$mintElem = $dom->createElement('category');
$mintElem->appendChild( $dom->createElement('id', $r->id));
$mintElem->appendChild( $dom->createElement('name', $r->term));
$empsElem = $dom->createElement('issuers');	
$mintElem->appendChild($empsElem);
$typesElem = $dom->createElement('types');
$mintElem->appendChild($typesElem);

foreach($this->rulers as $r => $v) {
     $issuerElem = $dom->createElement('issuer');
   foreach($v as $k => $a){
      
       $issuerElem->appendChild( $dom->createElement($k, $a)); 
   }
   $empsElem->appendChild($issuerElem);
}
foreach($this->types as $r => $v) {
     $typeElem = $dom->createElement('type');
   foreach($v as $k => $a){
      
       $typeElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
   $empsElem->appendChild($typeElem);
}
$cats->appendChild( $mintElem );
}

$dom->appendChild( $cats );

$xmlData  = $dom->saveXML();
echo $xmlData;
