<?php echo $this->partialLoop('partials/numismatics/medieval/category.phtml', $this->categories); ?>
<div class="row-fluid">
    <!--  Navigation for tabs  -->
    <ul id="tab" class="nav nav-tabs">
        <li class="active"><a href="#rulers" data-toggle="tab">Issuing rulers</a></li>
        <li><a href="#types" data-toggle="tab">Types</a></li>
        <li><a href="#map" data-toggle="tab">Map</a></li>
    </ul>
    <!--  End of Tabs navigation -->

    <!-- Start of tabbed content div -->
    <div id="myTabContent" class="tab-content">

        <div class="tab-pane fade in active" id="rulers">

            <h3 class="lead">Associated rulers</h3>
            <?php if (!empty($this->rulers)): ?>
                <ul>
                    <?php echo $this->partialLoop('partials/numismatics/shared/rulers.phtml', $this->rulers) ?>
                </ul>
                <?php else:?>
                <p>No rulers available at the moment.</p>
            <?php endif; ?>
        </div>

        <div class="tab-pane fade" id="types">
            <h3 class="lead">Types of coin associated with this category</h3>
            <?php if(!empty($this->types)):?>
            <ul>
                <?php echo $this->partialLoop('partials/numismatics/medieval/types.phtml', $this->types) ?>
            </ul>
            <?php else:?>
                <p>No coin types associated with this category.</p>
            <?php endif;?>
        </div>

        <div class="tab-pane fade" id="map">

        </div>
    </div>
    <!--  End of tabbed content div -->

</div>