<?php
$this->headTitle('Early Medieval Categories of coin produced');
$this->metaBase()->setDescription('A list of the categories of coin we document for the Early Medieval period')
    ->setSubject('Early Medieval numismatics')
    ->setKeywords('early medieval,numismatics,categories,category')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/categories.phtml', $this->categories); ?>
</ul>