<div class="modal-header">
    <a class="close" data-dismiss="modal">x</a>

    <h2 class="lead">
        Audit of find spot changes
    </h2>

    <div class="modal-body">
        <ul>
            <li>
                Audit changes made <?php echo $this->timeAgoInWords($this->audit[0]['created']); ?>
            </li>
            <li>
                All changes made by <?php echo $this->audit[0]['fullname']; ?>
            </li>
        </ul>

        <table class="table table-striped" summary="A list of changes" style="width:100%;">
            <thead>
            <tr>
                <th>
                    Field name
                </th>
                <th>
                    Before change
                </th>
                <th>
                    After change
                </th>
            </tr>
            </thead>
            <?php foreach ($this->audit as $audit): ?>
                <tr>
                    <td>
                        <?php echo $this->fieldNamesDb()->setField($audit['fieldName']); ?>
                    </td>
                    <td>
                        <?php echo $audit['beforeValue']; ?>
                    </td>
                    <td>
                        <?php echo $audit['afterValue']; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <div class="modal-footer">
        <a href="#" data-dismiss="modal" class="btn">Close</a>
    </div>