  <div class="modal-header">
    <a class="close" data-dismiss="modal">x</a>
    <h2>Audit of findspot changes</h2>
      <div class="modal-body">
<h2>Audit changes made <?php echo $this->timeagoinwords($this->audit['0']['created']);?></h2>
<p>All changes made by <?php echo $this->audit['0']['fullname'];?></p>
<table class="table table-striped" summary="A list of changes" style="width:100%;">
<thead>
<tr>
<th>Field name</th>
<th>Before change</th>
<th>After change</th>
</tr>
</thead>
<?php foreach($this->audit as $a):?>
<tr>
<td><?php echo ucfirst($a['fieldName']);?></td>
<td><?php echo $a['beforeValue'];?></td>
<td><?php echo $a['afterValue'];?></td>
</tr>
<?php endforeach;?>
</table>
</div>
<div class="modal-footer">
    <a href="#" data-dismiss="modal" class="btn">Close</a>
  </div>