<?php
$dom 	  = new DomDocument("1.0", "UTF-8");
$dom->createElement('kml');
$nameSpace = $dom->createElementNS('http://www.opengis.net/kml/2.2',
'kml');

$dom->appendChild($nameSpace);

$documentNode = $dom->createElement('Document');
$nameSpace->appendChild($documentNode);
$nameSpace->setAttributeNS('http://www.w3.org/2000/xmlns/' ,'xmlns:gx', 'http://www.google.com/kml/ext/2.2');
$documentName = $dom->createElement('name','search.kml');
$documentNode->appendChild($documentName);

foreach($this->results as $result){
    if(!is_null($result['longitude'])){

          if(isset($result['thumbnail'])){
            $url = '/images/thumbnails/';
        $description = '<img src="' . $this->serverUrl() . $url . $result['thumbnail'] . '.jpg" style="float:right;"/>';
        }
        $description .= htmlspecialchars($result['description']);

        $description .= '<p>Record Url: <a href="' . $this->serverUrl() . '/database/artefacts/record/id/' . $result['id'] . '">';
        $description .= $this->serverUrl() . '/database/artefacts/record/id/' . $result['id'] . '</a></p>';
	$place = $dom->createElement('Placemark');
	$place->appendChild( $dom->createElement('name', $result['old_findID']));
	$place->appendChild( $dom->createElement('description', $description));
	$point = $dom->createElement('Point');
	$point->appendChild( $dom->createElement('coordinates', $result['longitude'] . ',' . $result['latitude']));
	$place->appendChild( $point );
	$documentNode->appendChild( $place );
    }
}



$xmlData  = $dom->saveXML();
echo $xmlData;