<?php
$dom = new DomDocument("1.0", "UTF-8");
$dom->createElement('markers');

$documentNode = $dom->createElement('markers');
$dom->appendChild($documentNode);

foreach ($this->results as $result) {
    if (array_key_exists('longitude', $result)) {
        $description = '';
        if (isset($result['thumbnail'])) {
            $url = '/images/thumbnails/';
            $description = '<img src="' . $this->serverUrl() . $url . $result['thumbnail'] . '.jpg" style="float:right;"/>';
        }
        $description .= '<h3 class="lead">';
        $description .= $result['old_findID'];
        $description .= '</h3>';
        if (array_key_exists('description', $result)) {
            $description .= $this->ellipsisString()->setString($this->purify($result['description']));
        }

        switch(substr($result['findIdentifier'], 0, 6)){
            case 'hoards' :
                $type = 'hoards';
                break;
            default:
                $type = 'artefacts';
                break;
        }

        $description .= '<p>Record Url: <a href="' . $this->serverUrl() . '/database/' . $type . '/record/id/' . $result['id'] . '">';
        $description .= $this->serverUrl() . '/database/' . $type . '/record/id/' . $result['id'] . '</a></p>';
        $marker = $dom->createElement('marker');
        $marker->setAttribute('lat', $result['latitude']);
        $marker->setAttribute('lng', $result['longitude']);
        $marker->setAttribute('content', $description);
        $marker->setAttribute('title', $result['old_findID']);
        $documentNode->appendChild($marker);
    }
}
$xmlData = $dom->saveXML();
echo $xmlData;
