<table border="1" cellpadding="2" cellspacing="0" nobr="true" >
<thead>
<tr>
<th width="10%">Find ID</th>
<th width="10%">Broad period</th>
<th width="10%">Finder</th>
<th width="10%">Object type</th>
<th width="40%">Description</th>
<th width="15%">Findspot</th>
<th width="5%">Smr ref</th>
</tr>
</thead>
<tbody>
<?php foreach($data as $d):?>
   <tr nobr="true">
   <td width="10%"><?php echo $d['old_findID'];?></td>
   <td width="10%"><?php echo $d['broadperiod'];?></td>
   <td width="10%"><?php echo $d['finder'];?></td>
   <td width="10%"><?php echo $d['objecttype'];?></td>
   <td width="40%"><?php echo $d['description'];?></td>
   <td width="15%">County: ' . $pdf->lowerCaseIt($d['county']) . '<br />';
   District: ' . $pdf->lowerCaseIt($d['district']) . '<br />';
   Parish: ' . $pdf->lowerCaseIt($d['parish']) . '<br />';
    if(!is_null($d['knownas'])){
   Known as: ' . $d['knownas'] . '<br />';
    }
    $tbl .=  'NGR: ' . $d['gridref'] . '<br />';
   Four figure: ' . $d['fourFigure'] . '</td>';
   <td width="5%">' . $d['smrRef'] . '</td>';
   </tr>';
<?php endforeach;?>
</tbody></table>