<div style="width:800px;height:500px;overflow:auto;margin-left:10px;margin-right:10px;">
<?php
echo $this->partial('partials/database/recordh2section.phtml',$this->finds['0']);
?>
<div id="imagepane">
<?php if (count($this->thumbs) > 0) : ?>
<?php echo $this->partialLoop('partials/database/thumbs.phtml', $this->thumbs) ;
?>
<?php else: ?>
<ul>
<li>There are currently no images available.</li>
</ul>
<?php endif;?>
</div>


<?php
echo $this->partialLoop('partials/database/recorddescriptive.phtml',$this->finds);
echo $this->partial('partials/database/treasurefinddetails.phtml', $this->finds['0']);
echo $this->partial('partials/database/temporal.phtml', $this->temporals['0']);
?>


<?php
$objectarray = array('coin','COIN','Coin');
if ((count($this->coins)) && in_Array($this->finds['0']['objecttype'],$objectarray)) { ?>
<?php if (($this->finds['0']['broadperiod']) == 'Iron Age' ) : ?>
<?php echo $this->partial('partials/database/ironagedata.phtml', $this->coins['0']) ?>
<?php endif; ?>
<?php if (($this->finds['0']['broadperiod']) == 'Byzantine' ) : ?>
<?php echo $this->partial('partials/database/byzantinedata.phtml', $this->coins['0']) ?>
<?php endif; ?>
<?php if (($this->finds['0']['broadperiod']) == 'Roman') : ?>
<?php echo $this->partial('partials/database/romandata.phtml', $this->coins['0']) ?>
<?php endif; ?>
<?php if (($this->finds['0']['broadperiod']) == 'Medieval' ) : ?>
<?php echo $this->partial('partials/database/meddata.phtml', $this->coins['0']) ?>
<?php endif; ?>
<?php if (($this->finds['0']['broadperiod']) == 'Early Medieval') : ?>
<?php echo $this->partial('partials/database/earlymeddata.phtml', $this->coins['0']) ?>
<?php endif; ?>
<?php if (($this->finds['0']['broadperiod']) == 'Post Medieval') : ?>
<?php echo $this->partial('partials/database/postmeddata.phtml', $this->coins['0']) ?>
<?php endif; ?>
<?php if (($this->finds['0']['broadperiod']) == 'Greek and Roman Provincial') : ?>
<?php echo $this->partial('partials/database/greekdata.phtml', $this->coins['0']) ?>
<?php endif; ?>
<?php }?>

<?php
$objectarray = array('coin','COIN','Coin');
if((!count($this->coins)) && in_Array($this->finds['0']['objecttype'],$objectarray)) { ?>
<h3>Numismatic data</h3>
<p>No numismatic data has been recorded for this coin yet.</p>
<?php $this->allowedtest('<p>You have not added <a href="'.$this->url(array('module' => 'database','controller' => 'coins','action' => 'add', 'broadperiod' => $this->finds['0']['broadperiod'],'findID' => $this->finds['0']['secuid'],'returnID' => $this->finds['0']['id']),null,true).'" class="btn btn-small"  title="Add '.$this->finds['0']['broadperiod'].' coin data">coin data</a>.</p>');?>
<?php }?>


<?php echo $this->partial('partials/database/datefound.phtml',$this->finds['0']);?>


<?php if (count($this->rallyfind) > 0) : ?>
<?php echo $this->partialLoop('partials/database/rallyfind.phtml', $this->rallyfind) ?>
<?php endif;?>


<?php if (count($this->findsdata) > 0) : ?>
<?php echo $this->partialLoop('partials/database/dimensions.phtml', $this->findsdata) ?>
<?php endif;?>

<?php if (count($this->findsmaterial)) : ?>
<?php echo $this->partialLoop('partials/database/materials.phtml', $this->findsmaterial) ?>
<?php endif;?>


<?php if (count($this->peoples) > 0) : ?>
<h3>Personal details</h3>

<?php echo $this->partialLoop('partials/database/personal.phtml', $this->peoples) ?>
<?php endif;?>

<?php if (count($this->findsotherefs) > 0) : ?>
<?php echo $this->partialLoop('partials/database/otherrefs.phtml', $this->findotherrefs) ;?>
<?php endif;?>


<h3>References cited</h3>
<div id="references">
<?php
if (count($this->refs) > 0) : ?>
<ul id="related">
<?php echo $this->partialLoop('partials/database/harvardbook.phtml', $this->refs);?>
</ul>
<?php else:?>
<p class="norefs">No references cited so far.</p>
<?php endif;?>
</div>

<?php echo $this->partial('partials/database/recordaudit.phtml',$this->finds['0']);?>
</div>