<?php
$dom = new DomDocument("1.0", "UTF-8");
$dom->createElement('markers');

$documentNode = $dom->createElement('markers');
$dom->appendChild($documentNode);
foreach($this->results as $result){
	
	$url = $this->serverUrl() .  '/database/smr/record/id/';
    if(!is_null($result['longitude'])){
        $title = $result['name'];
		$content = '<a href="' . $url . $result['id'] . '">' . $title . '</a>';
		
		$marker = $dom->createElement('marker');
		$marker->setAttribute('lat', $result['latitude']);
        $marker->setAttribute('lng', $result['longitude']);
        $marker->setAttribute('title', $title);
        $marker->setAttribute('id',$result['id']);
        $marker->setAttribute('content', $content);
		$documentNode->appendChild( $marker );
    }
}
$xmlData  = $dom->saveXML();
echo $xmlData;