<div class="modal-header">
    <a class="close" data-dismiss="modal">x</a>

    <h3 class="lead">
        Cite this record
    </h3>
</div>

<div class="modal-body">
    <h3 class="lead">
        Publication citation
    </h3>
    <?php if (!empty($this->finds)): ?>
        <p>
            This record can be cited in the Harvard bibliographic style using the text below:
        </p>
        <?php if ($this->type == 'artefacts'): ?>
            <?php echo $this->partial('partials/database/citations/webCiteData.phtml', $this->finds[0]); ?>
        <?php else: ?>
            <?php echo $this->partial('partials/database/citations/webCiteHoard.phtml', $this->finds[0]); ?>
        <?php endif; ?>

        <h3 class="lead">
            Wikipedia citation
        </h3>
        <?php if ($this->type == 'artefacts'): ?>
            <?php echo $this->partial('partials/database/citations/wikiCite.phtml', $this->finds[0]); ?>
        <?php else: ?>
            <?php echo $this->partial('partials/database/citations/wikiCiteHoard.phtml', $this->finds[0]); ?>
        <?php endif; ?>
    <?php else: ?>
        <p>An error has occurred, no data retrieved.</p>
    <?php endif; ?>
</div>

<div class="modal-footer">
    <a href="#" data-dismiss="modal" class="btn">Close</a>
</div>