<?php
	//Create the kml document
	$dom = new DomDocument("1.0", "UTF-8");
	// Creates the root KML element and appends it to the root document.
	$node = $dom->createElementNS('http://earth.google.com/kml/2.1', 'kml');
	$parNode = $dom->appendChild($node);
	// Creates a KML Document element and append it to the KML element.
	$dnode = $dom->createElement('Document');
	$docNode = $parNode->appendChild($dnode);
	foreach($this->finds as $result){
	if(array_key_exists('knownas', $result)) {
		unset($result['fourFigureLat']);
		unset($result['fourFigureLon']);
		unset($result['parish']);
	}	
	
	if(!array_key_exists('thumbnail', $result)){
		unset($result['imagedir']);
		unset($result['filename']);
	}
	// Creates a Placemark and append it to the Document.
	$node = $dom->createElement('Placemark');
	$placeNode = $docNode->appendChild($node);

	// Creates an id attribute and assign it the value of id column.
	$placeNode->setAttribute('id', 'placemark-' . $result['id']);

	
	if(!is_null($result['description'])){
	$html = '';
	if(!is_null($result['thumbnail'])){
	$html .= '<img src="' . $this->serverUrl() . '/images/thumbnails/' . $result['thumbnail'] . '.jpg" style="float:right" />';
	}
	$html .= '<p>';
	$html .= $result['description'];
	$html .= '</p>';  
	}
	$url = $this->serverUrl() . '/database/artefacts/record/id/' . $result['id'];
	$html .= 'Stable URI: <a href="' . $url . '">' . $url . '</a><br />';
	$name = $result['old_findID'] . ': ' .  $result['objecttype'];
	// Create name, and description elements and assigns them the values of the name and address columns from the results.
	$nameNode = $dom->createElement('name',htmlentities($name));
	$placeNode->appendChild($nameNode);
	$descriptionNode = $dom->createElement('description',htmlspecialchars($html, ENT_QUOTES, 'UTF-8'));
	$placeNode->appendChild($descriptionNode);
	// Creates a Point element.
	$pointNode = $dom->createElement('Point');
	$placeNode->appendChild($pointNode);

	// Creates a coordinates element and gives it the value of the lng and lat columns from the results.
	$coorStr = $result['fourFigureLon'] . ','  . $result['fourFigureLat'];
	$coorNode = $dom->createElement('coordinates', $coorStr);
	$pointNode->appendChild($coorNode);
	}
	$kmlOutput = $dom->saveXML();
	$filename = 'KMLExport_' . Zend_Date::now()->toString('yyyyMMddHHmmss') . '.kml';
	$response = Zend_Controller_Front::getInstance()->getResponse();
	$response->setHeader('Content-type', 'application/vnd.google-earth.kml+xml');
	$response->setHeader('Content-Disposition', 'attachment; filename=' . $filename);
	echo $kmlOutput;
