<?php
$this->headTitle('Edit details for a person');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title();?></h2>
<?php echo $this->form ;?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {
$('form').areYouSure();
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>