<?php
$this->headTitle('People registered with the Scheme');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/JQuery/autocompleteinitpeople1.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/autocomplete.css')
?>
<h2>People registered with the Scheme</h2>
<div class="row-fluid">
<?php echo $this->peopleToolbox();?>

<?php echo $this->form;?>

<?php if ($this->results): ?>

<div >

	<table class="table table-striped span8" summary="All people registered on our database">
	<thead>
	    <tr>
	        <th>Name</th>
	        <th>County</th>
	        <th>Organisation</th>
	        <th>Primary activity</th>
	        <th>Actions</th>
	    </tr>
	</thead>
	
	<tbody>
	<?php 
	echo $this->partialLoop('partials/database/peopleTableList.phtml', $this->results);?>
	</tbody>
	</table>
	
</div>

		<div class="span2">
        <?php echo $this->facetCreatorPeople($this->facets); ?>
        
        </div>
<?php else :?>
<p>There are no people registered or available to you.</p>
<?php endif; ?>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
<?php 
$this->inlineScript()->appendFile('/js/bootstrap-modal.js', $type='text/javascript');
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
	$('#print').click(function() {
	window.print();
	return false;
	});

    $('.overlay').click(function(e) {
    e.preventDefault();
    var href = $(e.target).attr('href');
    if (href.indexOf('#') == 0) {
        $(href).modal('open');
    } else {
        $.get(href, function(data) {
            $('<div class="modal fade" >' + data + '</div>').modal();
        });
    }
});

	}); 
<?php $this->inlineScript()->captureEnd();?>
