<?php
$vc = new Pas_VCard();
$data = array();
foreach ($this->peoples as $person) {
    $data['display_name'] = $person['forename'] . ' ' . $person['surname'];
    $data['first_name'] = $person['forename'];
    $data['last_name'] = $person['surname'];
    $data['name_prefix'] = $person['title'];
    $data['company'] = $person['org'];
    $data['work_address'] = $person['address'];
    $data['work_city'] = $person['town_city'];
    $data['work_state'] = $person['county'];
    $data['work_postal_code'] = $person['postcode'];
    $data['work_country'] = $person['abode'];
    $data['home_tel'] = $person['hometel'];
    $data['office_tel'] = $person['worktel'];
    $data['email1'] = $person['email'];
}
$data['timezone'] = "00:00";
}
$vc->setData($data);
$vc->setClass('PUBLIC');;
echo $vc->createCard();