<h2>
    Research agenda: <?php echo $this->title;?>
</h2>
<p>
    <?php
    $editurl = array('controller' => 'users','action' => 'editagenda','id' => $this->id);
    $deleteurl = array('controller' => 'users','action' => 'deleteagenda','id' => $this->id);
    ?>
<div class="btn-group">
    <a href="<?php echo $this->url($editurl,null,true);?>" title="Edit this agenda" class="btn btn-mini">Edit</a> |
    <a href="<?php echo $this->url($deleteurl,null,true);?>" title="Delete this agenda from your catalogue"
       class="btn btn-mini">Delete</a>
</div>
</p>
<?php echo $this->description;?>
<p>
    Created <?php echo $this->timeAgoInWords($this->created);?>
    <br />
    <?php if(($this->updated) == (NULL || '0000-00-00 00:00:00')) { ?>
        Updated <?php echo $this->timeAgoInWords($this->updated);?>
    <?php } ?>
</p>