<tr id="signup-<?php echo $this->id; ?>">
    <td>
        <?php if (!is_null($this->name)): ?>
            <?php echo $this->name; ?>
        <?php else: ?>
            HER name missing
        <?php endif; ?>
    </td>
    <td>
        <?php if (!is_null($this->contact_name)): ?>
            <?php echo $this->contact_name; ?>
        <?php else: ?>
            No primary contact
        <?php endif; ?>
    </td>
</tr>