<?php
$this->headTitle('Details for suggested topic: ' . $this->title);
$this->metaBase()->setSubject('Research')
    ->setDescription($this->title())
    ->generate();

?>
<h2 class="lead"><?php echo $this->title; ?></h2>

<?php if (!is_null($this->temporal)): ?>
    <p>Suggested period: <?php echo $this->temporal; ?></p>
<?php endif; ?>

<?php if (!is_null($this->description)): ?>
    <?php echo $this->description; ?>
<?php endif; ?>


<h3 class="lead">Audit data</h3>
<p>
    <?php if (!is_null($this->created)): ?>
        Created by:  <?php echo $this->fullname; ?>
        <br />
        Created: <?php echo $this->timeAgoInWords($this->created); ?>
    <?php endif; ?>
    <?php if (!is_null($this->updated)): ?>
        <br />
        Updated by: <?php echo $this->fn;?>
        <br />
        Updated: <?php echo $this->timeAgoInWords($this->updated); ?>
    <?php endif; ?>
</p>
