<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 10/12/14
 * Time: 16:59
 */
?>
<li>
    <?php echo $this->authors; ?>, <?php echo $this->publication_year; ?>. <em><a
            href="<?php echo $this->url(array('module' => 'database', 'controller' => 'publications', 'action' => 'publication', 'id' => $this->id), null, true); ?>"
            title="View reference work's details">
            <?php echo $this->title; ?></a></em> <?php if(!is_null($this->publication_place)) { echo $this->publication_place;} ?>
    : <?php if(!is_null($this->publisher)){echo $this->publisher;} ?> <?php if(!is_null($this->vol_no)){echo $this->vol_no;} ?> <?php if(!is_null($this->pp)){echo $this->pp;} ?>
    <?php echo $this->referencesEditDeleteLink()
        ->setRecordID($this->i)
        ->setFindID($this->fID)
        ->setCreatedBy($this->createdBy)
        ->setInstitution($this->institution);
    ?>
</li>