<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 10/12/14
 * Time: 16:54
 */
?>
<li>
    <?php echo $this->authors; ?>, <?php echo $this->publication_year; ?><em>
        <a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'publications', 'action' => 'publication', 'id' => $this->id), null, true); ?>"
           title="View reference work\'s details">'
            <?php echo $this->title; ?></a></em><?php echo $this->vol_no; ?>,<?php echo $this->pp; ?>, <?php echo $this->ref; ?>. <?php echo $this->referencesEditDeleteLink()->setRecordID($this->i)->setFindID($this->fID)->setCreatedBy($this->createdBy);?>
</li>