<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 10/12/14
 * Time: 16:55
 */
?>
<li>
    <?php echo $this->authors; ?>, <?php echo $this->publication_year; ?> <em><a href="<?php echo $this->url(array(
                'controller' => 'database',
                'action' => 'publication',
                'id' => $this->id)
            , null, true);?>" title="View this reference work's details">
            <?php echo $this->title; ?></a></em>, <?php echo $this->vol_no; ?>, <?php echo $this->pp; ?>
</li>