<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 10/12/14
 * Time: 16:55
 */
?>
<li>
    <?php echo $this->authors; ?>, <?php echo $this->publication_year; ?> <em><?php echo $this->title; ?></em> [<?php echo $this->medium; ?>] Available at: <a href="<?php echo $this->url; ?>" title="View webpage referenced"><?php echo $this->url; ?></a> [Accessed <?php echo $this->accessedDate; ?>].
</li>