<?php
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controller = strtolower(Zend_Controller_Front::getInstance()->getRequest()->getControllerName());
?>
<li>
    <?php echo
        '<a href="' .
        $this->url(array('module' => $module, 'controller' => $controller, 'action' => 'category', 'id' => $this->id), null, true)
        . '" title="View details for '
        . $this->term
        . '">'
        . $this->term .
        '</a>'; ?> - <a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search',
        'action' => 'results', 'category' => $this->id), null, true); ?>" title="Search for all examples of
            <?php echo $this->term; ?> on the database"><i class="icon-search"></i></a>
</li>