<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$denominations  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$denominations->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('totalItems',$this->denominations->getTotalItemCount()));
$meta->appendChild( $dom->createElement('currentPage',$this->denominations->getCurrentPageNumber()));
$meta->appendChild( $dom->createElement('totalPages',ceil($this->denominations->getTotalItemCount()/$this->denominations->getItemCountPerPage())));

$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$denominationsElem = $dom->createElement('denominations');
$denominations->appendChild($denominationsElem);
// set it's attribute
foreach($this->denominations as $d){
$d = (object)$d;
$denominationElem = $dom->createElement('denomination');
$denominationElem->appendChild( $dom->createElement('id', $d->id));
$denominationElem->appendChild( $dom->createElement('name', $d->denomination));
$denominationElem->appendChild( $dom->createElement('description',$d->description));
$denominationElem->appendChild( $dom->createElement('material',$d->old_material));
$denominationElem->appendChild( $dom->createElement('url',$site . $this->url(array('module' => $module,
'controller' => $controller,'action' => 'denomination','id' => $d->id),NULL,true) ));
$denominationsElem->appendChild( $denominationElem );
}

$dom->appendChild( $denominations );

$xmlData  = $dom->saveXML();
echo $xmlData;
