<?php
$this->headTitle('Routing configuration');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<table class="table table-striped" width="95%">
    <caption><?php echo $this->title(); ?></caption>
    <thead>
    <tr>
        <th>System keys</th>
        <th>Properties</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->routing as $k => $v): ?>
        <tr>
            <th colspan="3"><?php echo $k; ?></th>
        </tr>
        <?php foreach ($v as $a => $b) : ?>
            <tr>
                <td><?php echo $a; ?></td>
                <td width="60%" style="WORD-BREAK:BREAK-ALL;"><?php
                    if (is_array($b)) {
                        foreach ($b as $c => $d) {
                            if (is_array($d)) {
                                foreach ($d as $e => $f) {
                                    echo $c . ' | ' . $e . ' ' . $f . '<br />';
                                }

                            } else {
                                echo $c . ' | ' . $d . '<br />';
                            }
                        }
                    } else {
                        echo $b;
                    } ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>