<?php
$this->headTitle('Configuration keys for web services');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if($this->webservice):?>
<table class="table table-striped" width="95%">
    <caption><?php echo $this->title(); ?></caption>
    <thead>
    <tr>
        <th>Web service api keys</th>
        <th>Properties</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->webservice as $k => $v) : ?>
        <tr>
            <th colspan="3"><?php echo $k; ?></th>
        </tr>
        <?php foreach ($v as $a => $b) : ?>
            <tr>
                <td><?php echo $a; ?></td>
                <td width="60%" style="WORD-BREAK:BREAK-ALL;"><?php echo $b; ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else:?>
<p>The web services list is unavailable.</p>
<?php endif;?>