<?php
$this->headTitle('Configuration keys for webservices');
?>
<h2>Webservices configuration entries</h2>
<table class="table table-striped" width="95%">
<caption>All webservice config data</caption>
<thead><tr><th>Webservice api keys</th><th>Properties</th></tr></thead>
<tbody>
<?php
foreach($this->webservice as $k => $v){
?>
<tr><th colspan="3"><?php echo $k;?></th></tr>
<?php  foreach($v as $a => $b){ ?>
<tr><td><?php echo $a;?></td><td width="60%" style="WORD-BREAK:BREAK-ALL;"><?php echo $b; ?></td></tr>
<?php }?>
<?php
}
?>
</tbody>
</table>