<?php $this->headTitle('All images added by me');?>
<h2>All images added by me</h2>
<?php echo $this->form;?>

<?php if ($this->results): ?>
<div class="row-fluid ">
    <div class="span9">
    <ul class="thumbnails">
<?php echo $this->partialLoop('partials/database/myimagesList.phtml',
        $this->results);?>
    </ul>
    </div>
    <div class="span3">        
    	<?php echo $this->resultsQuantityChooser($this->paginator);?>
        <?php echo $this->thumbnailToggler();?>
        <?php echo $this->resultsSorter($this->paginator);?>
		<?php echo $this->facetCreatorMyImages($this->facets); ?>
	</div>
</div>

<?php echo $this->paginationControl($this->paginator, 'Elastic',
        'structure/pagination.phtml'); ?>

<?php else:?>
<p>You have added no images to our database.</p>
<?php endif; ?>

<?php 
$this->inlineScript()->appendFile('/js/bootstrap-modal.js', $type='text/javascript');
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
	$('#print').click(function() {
	window.print();
	return false;
	});

    $('.overlay').click(function(e) {
    e.preventDefault();
    var href = $(e.target).attr('href');
    if (href.indexOf('#') == 0) {
        $(href).modal('open');
    } else {
        $.get(href, function(data) {
            $('<div class="modal fade" >' + data + '</div>').modal();
        });
    }
});

	}); 
<?php $this->inlineScript()->captureEnd();?>
