<?php
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/autocompleteinit.js',$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->headTitle('All finds created by my institution');
?>
<?php $this->headTitle('All finds created by ' . $this->Institution($this->inst)); ?>
<h2>All finds and coins recorded by institution: <?php echo $this->Institution($this->inst);?></h2>
<?php echo $this->loggedinlinks();?>
<?php if($this->params):?>
<?php echo $this->SearchParams($this->params);?>
<?php endif;?>
<?php echo $this->form;?>
<div class="row-fluid">
		
    	<?php if ($this->results): ?>
		<div class="span9">
        <?php echo $this->partialLoop('partials/database/findRecordList.phtml',$this->results);?>
        </div>
        <div class="span3">
		<p><a class="btn btn-small" href="<?php echo $this->url(array('action' => 'institutionmap'),null,false);?>" title="Map these records">Map these finds <i class="icon-map-marker"></i></a></p>
      <?php echo $this->resultsQuantityChooser($this->paginator);?>
        <?php echo $this->thumbnailToggler();?>
        <?php echo $this->resultsSorter($this->paginator);?>
        <p>Total results available: <?php echo number_format($this->paginator->getTotalItemCount());?></p>
        <?php echo $this->paginationControl($this->paginator,'elastic','structure/paginationSolr.phtml'); ?>
		<?php echo $this->statGenerator($this->stats);?>
        <?php echo $this->facetCreatorMyInstitution($this->facets); ?>
		</div>
        <?php else:?>
    
    	<p>No records are available.

        <?php endif; ?>
        
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
<?php 
$this->inlineScript()->appendFile('/js/bootstrap-modal.js', $type='text/javascript');
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
	$('#print').click(function() {
	window.print();
	return false;
	});

    $('.overlay').click(function(e) {
    e.preventDefault();
    var href = $(e.target).attr('href');
    if (href.indexOf('#') == 0) {
        $(href).modal('open');
    } else {
        $.get(href, function(data) {
            $('<div class="modal fade" >' + data + '</div>').modal();
        });
    }
});

	}); 
<?php $this->inlineScript()->captureEnd();?>


