<?php $this->headTitle('Reply to comment');?>
<?php
echo $this->metaBase()
        ->setDescription('Reply to a comment entered on the database')
        ->setSubject('Commentary')
        ->setKeywords('reply,comment')
        ->generate();
?>
<h2 class="lead"><?php echo $this->title();?></h2>
<?php
$auth = Zend_Registry::get('auth');
if ($auth->hasIdentity()) {
    $user = $auth->getIdentity();
    $this->form->comment_author->setValue($user->fullname);
    $this->form->comment_author_email->setValue($user->email);
}
echo $this->form;
?>
