<?php
$this->headTitle('Medieval issuing mints');
$this->metaBase()->setDescription('A list of all issuing mintd for the medieval period')
    ->setKeywords('medieval,period,numismatics,archaeology,coins,mints')
    ->setSubject('Medieval Numismatics')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<table class="table table-striped" summary="A list of all Medieval mints in use">
    <caption>A list of all Medieval mints in England and Wales</caption>
    <thead>
    <tr>
        <th>Mint name</th>
        <th>Geo location</th>
    </tr>
    </thead>
    <tbody>
    <?php echo $this->partialLoop('partials/numismatics/medieval/medievalMints.phtml', $this->mints); ?>
    </tbody>
</table>