<?php $this->headTitle('All ips used for access');?>
<h2>IP address history</h2>
<?php if($this->logins):?>

<table class="table table-striped" summary="A list of my login history">
<caption>Tabulated list of your logins</caption>
<thead>
<tr>
<th>IP Address</th>
<th>Reverse lookup</th>
<th>Number of users</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/users/ipaddresses.phtml',$this->logins);?>
</tbody>
</table>
<?php echo $this->paginationControl($this->logins, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>There is no login history available for you. Which is an error!</p>
<?php endif;?>