<?php
$this->headTitle('Issuing mints of the Greek and Roman Provincial period');
$this->metaBase()->setDescription('A list of all issuing mints of the Greek and Roman provincial period.
This comes from the SNG.')
    ->setKeywords('greek,roman,provincial,mints,issued,')
    ->setSubject('Greek numismatics')
    ->generate();
?>

<h2 class="lead"><?php echo $this->title(); ?></h2>

<ul>
    <?php echo $this->partialLoop(('partials/numismatics/shared/mints.phtml'), $this->greeks); ?>
</ul>
