<?php
$this->headTitle('Edit a publication\'s details');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead">Edit publication's details</h2>
<?php $url = array(
    'module' => 'database',
    'controller' => 'publications',
    'action' => 'publication',
    'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('id'));
?>
    <a href="<?php echo $this->url($url, 'default', true); ?>" class="btn btn-small btn-success"
       title="Return to record">Return to record</a>
<?php echo $this->form; ?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function() {
        $('form').areYouSure();
        $("form").submit(function() {
            $(":submit", this).attr("disabled", "disabled");
        });
    });
<?php $this->jQuery()->javascriptCaptureEnd(); ?>