<?php
$paginator = $this->paginator;
$results = array();
foreach($this->results as $result){
	$results[] = $result;
}

$meta = array(
    'currentPage' => $paginator->getCurrentPageNumber(),
    'totalResults' => $paginator->getTotalItemCount(),
    'resultsPerPage' => $paginator->getItemCountPerPage(),
    'totalPages' => ceil($paginator->getTotalItemCount()/$paginator->getItemCountPerPage()));

echo Zend_Json::prettyPrint(Zend_Json::encode( ( array('meta' => $meta, 'publications' => $results, 'facets' => $this->facets ) ) ) );