<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getActionContexts($action);
$dom = new DomDocument("1.0", "UTF-8");
$publications  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$publications->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k ){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$publicationsElem = $dom->createElement('publication');
foreach($this->publications as $r){
$publicationElem = $dom->createElement('publication');
   foreach($r as $k => $a){
      
       $publicationElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
$publicationsElem->appendChild( $publicationElem );
$findsElem = $dom->createElement('recentRecords');	
$publicationElem->appendChild($findsElem);

foreach($this->finds as $i){
$findElem = $dom->createElement('record');
 foreach($i as $k => $a){
       $findsElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
}
$publications->appendChild( $publicationElem );
}

$dom->appendChild( $publications );

$xmlData  = $dom->saveXML();
echo $xmlData;
