<?php
$this->headTitle('Delete an acronym from the system');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!is_null($this->acronym)) :?>
    <h2 class="lead">Delete: <?php echo $this->escape($this->acronym->expanded); ?> </h2>
    <p>Are you sure that you want to delete
        '<?php echo $this->escape($this->acro->expanded); ?>'
    </p>
    <form
        action="<?php echo $this->url(
            array(
                'module' => 'admin',
                'controller' => 'acronyms',
                'action' => 'delete'),
            'default', true); ?>"
        method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->acronym->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <p>Cannot find the item requested.</p>
<?php endif; ?>