<?php 
$this->headTitle('Delete an acronym from the system');
if ($this->acro) :?>
<h2>Delete: <?php echo $this->escape($this->acro->expanded); ?> </h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->acro->expanded); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'acronyms','action'=>'delete'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->acro->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>
