<?php
$this->headTitle('Edit acronym');
$this->metaBase()->setSubject('Acronyms')->setDescription('Edit acronyms in use on the database')->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'acronyms'), 'default', true); ?>"
   class="btn btn-small btn-success">Return to acronyms list</a>
    <?php echo $this->form; ?>
