<?php 
$this->headTitle('Add a new reference for a find');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jQueryLinkedSelect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/findSpotLinkedSelect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/publicationLinkedQuery.js',$type='text/javascript');
?>

<h2 class="lead">Add a new reference</h2>
<?php $params = Zend_Controller_Front::getInstance()->getRequest()->getParams();?>
<a href="<?php echo $this->url(array('module' => 'database', 'controller' => $params['recordtype'], 'action' => 'record', 'id' => $params['findID']), 'default', true); ?>"
   class="btn btn-small btn-success">Return to record</a>
<?php echo $this->form;?>
