<?php if ($this->bib) :?>
    <?php $params = Zend_Controller_Front::getInstance()->getRequest()->getParams();?>
    <a href="<?= $this->url(array('module' => 'database', 'controller' => $params['recordtype'], 'action' => 'record', 'id' => $params['findID']), 'default', true) ?>"
            class="btn btn-small btn-success">Return to record
    </a>

    <h2 class="lead">Delete reference</h2>
    <?php $this->headTitle('Delete reference: '.$this->escape($this->bib['0']['publicationtitle']));?>
    <p>
	Are you sure that you want to delete '<strong><?= $this->escape($this->bib['0']['publicationtitle']) ?></strong>'
    </p>
    <form action="<?= $this->url(array('module' => 'database', 'controller' => 'references', 'action'=>'delete', 'id'  => $this->bib['0']['id']),null,true) ?>" method="post">
	<div class="btn-toolbar" id="reference">
	    <input type="hidden" name="id" value="<?= $this->id ?>" />
	    <input type="hidden" name="findID" value="<?= $this->bib['0']['id'] ?>" />
	    <input type="hidden" name="controller" value="<?= $this->bib['0']['controller'] ?>"/>
	    <input type="submit" class="btn btn-danger" name="confirmDelete" value="Yes"/>
	    <input type="submit"  class="btn btn-default" name="confirmDelete" value="No"/>
	</div>
    </form>
<?php else: ?>
    <?php $this->headTitle('Error deleting reference');?>
    <h2 class="lead">There has been an error</h2>
    <p>Cannot find the publication that you requested.</p>
<?php endif;?>
