<?php if ($this->bib) :?>
<?php $this->headTitle('Delete reference: '.$this->escape($this->bib['0']['publicationtitle']));?>
<h2>Delete reference to find</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->bib['0']['publicationtitle']); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'references','action'=>'delete','id'  =>$this->bib['0']['id']),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->id; ?>" />
<input type="hidden" name="findID" value="<?php echo $this->bib['0']['id']; ?>" />
<input type="submit" name="del" value="Yes" class="large"/>
<input type="submit" name="del" value="No" class="large"/>
</div>
</form>
<?php else: ?>
<?php $this->headTitle('Error deleting reference');?>
<h2>There has been an error</h2>
<p>Cannot find the publication that you requested.</p>
<?php endif;?>