<?php
$this->headTitle('Biographical details for ' . $this->issuer);
$this->metaBase()->setDescription('A page documenting the biography for Byzantine issuer ' . $this->issuer)
    ->setSubject('Byzantine numismatics')
    ->setKeywords('byzantine,numismatics,issuers')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

<?php if (!is_null($this->filename)) { ?>
    <a href="<?php echo $this->url(array(
        'controller' => 'romancoins',
        'action' => 'zoomifyoverlay',
        'id' => $this->id), null, true);?>" title="View a high resolution image of <?php echo $this->issuer; ?>"><img
            src="<?php echo $this->serverUrl() . $this->baseUrl(); ?>/assets/rulers/resized/<?php echo $this->escape($this->filename); ?>"
            class="portrait" alt="Obverse image of a coin of <?php echo $this->issuer; ?>"></a>
<?php } ?>
    <p>Coins for this issuer were issued
        from <?php if (isset($this->date1)): ?><?php echo $this->adBc()->setDate($this->date1); ?> <?php if (isset($this->date2)): ?>until <?php echo $this->adBc()->setDate($this->date2); ?><?php endif; ?>
        <?php endif; ?>
        .</p>
<?php if (!is_null($this->biography)): ?>
    <?php echo $this->biography; ?>
<?php endif; ?>
    <p>Created: <?php echo $this->timeAgoInWords($this->created); ?></p>
<?php echo $this->searchLink()->setField('ruler')->setId($this->id); ?>
<?php echo $this->latestRecords()->setQuery('ruler:' . $this->id) ?>