<?php
$this->headTitle('Full details for numismatic category: ' . $this->term);
$this->metaBase()->setSubject('Early Medieval numismatics')
    ->setKeywords('numismatics,early medieval,coins,categories')
    ->setDescription('The Early Medieval numismatic period is broken down into a series of categories that
can be used to categorise the coinage issued. This pages describes ' . $this->term)
    ->generate();

?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php echo $this->searchLink()->setField('category')->setId($this->id); ?>
<?php echo $this->latestRecords()->setQuery('category:' . $this->id); ?>