<?php
$this->headTitle('Details of ' . $this->name . ' personified');
$this->headMeta($this->curUrl(), 'dc.identifier')
    ->headMeta('Daniel Pett', 'dc.creator')
    ->headMeta('The Portable Antiquities Scheme', 'dc.publisher')
    ->headMeta('CC BY-SA', 'dc.rights');
?>
<div about="personifcation-<?php echo $this->name; ?>">
    <h2 class="lead">
        <?php echo $this->title(); ?>
    </h2>
    <?php if (isset($this->image) && file_exists(IMAGE_PATH . '/images/coins/reverses/' . $this->image)): ?>
        <img src="<?php echo IMAGE_PATH;?>/coins/reverses/<?php echo $this->image; ?>"
             alt="Thumbnail image of a reverse depicting <?php echo $this->name; ?>" property="foaf:depiction"
             class="flow"/>
    <?php endif; ?>
    <p>
        <?php echo $this->description; ?>
    </p>
    <?php if (!is_null($this->attrib1)): ?>
        <h4 class="lead">
            Attributes
        </h4>
        <ul>
            <li>
                <?php echo $this->attrib1; ?>
            </li>

            <?php if (!is_null($this->attrib2)): ?>
                <li>
                    <?php echo $this->attrib2; ?>
                </li>
            <?php endif; ?>

            <?php if (isset($this->attrib3)): ?>
                <li>
                    <?php echo $this->attrib3; ?>
                </li>
            <?php endif; ?>
        </ul>
    <?php endif; ?>

    <?php if (isset($this->greek)): ?>
        <h4 class="lead">
            Greek counterpart
        </h4>
        <p>
            <?php echo $this->name; ?> can be identified with the Greek deity <?php echo $this->greek; ?>
        </p>
    <?php endif; ?>
</div>