<?php 
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>

<li><a href="<?php echo $this->url(array('module' => $module,'controller' => $controller,'action' => 'denomination','id' => $this->id),null,true);?>"   title="View details for this <?php echo $this->denomination;?>"><?php echo ucfirst($this->denomination);?></a> - <span class="scope">[<a href="<?php echo $this->url(array('module' =>'database','controller' => 'search','action' => 'results','denomination' => $this->id),null,true);?>" title="Search database for all examples of <?php echo $this->denomination;?>">view attributed examples</a>]</span></li>