<?php
$this->headTitle($this->dynasty);
$this->metaBase()->setDescription('Details for ' . lcfirst($this->title))
    ->setKeywords('dyanasty,roman,empire,' . $this->dynasty)
    ->generate();
?>

<h2 class="lead"><?php echo $this->title(); ?></h2>
<p>Date in power from: <?php echo $this->adBc()->setDate($this->date_from); ?><br/>
    Date in power until: <?php echo $this->adBc()->setDate($this->date_to); ?> </p>
