<?php $this->headTitle('Details for Roman mint at '.$this->mint_name);?>
<h2>The mint at <?php echo $this->escape($this->mint_name);?></h2>

<p>Mint: <?php echo $this->escape($this->mint_name);?> <br />
Geo location: <?php echo $this->escape($this->latitude);?> <?php echo $this->escape($this->longitude);?><br />
Abbreviation: <?php echo $this->abbrev;?><br />
<?php echo $this->description;?></p>
<p>View <a href="<?php echo $this->url(array('module'=>'database','controller' => 'search','action'=>'results', 'mint'=>$this->pasID),null,true);?>" title="View all records">all coins recorded</a>, which are attributed to <?php echo $this->escape($this->name);?>.</p>
