<?php $this->headTitle('Details for the '.$this->term.' mint at '.$this->mint_name);
$this->headMeta('Details for the '.$this->escape($this->mint_name),'description');
$this->headMeta('numismatics','dc.subject');
$this->headLink()->appendAlternate($this->baseUrl().'/database/search/results/mint/'.$this->id.'/format/atom/', 
	 			'application/rss+xml', 'Latest recorded finds feed for '.$this->escape($this->mint_name));?>
<h2>The <?php echo $this->escape($this->mint_name);?> mint</h2>

<p>Mint: <?php echo $this->escape($this->mint_name);?> <br />
<?php if(!is_null($this->latitude)):?>
Geo location: <?php echo $this->escape($this->latitude);?> <?php echo $this->escape($this->longitude);?><br />
<?php endif;?>
<?php if(!is_null($this->abbrev)):?>
Abbreviation: <?php echo $this->abbrev;?><br />
<?php endif;?>
</p>
<?php echo $this->description;?>

<p>View <a href="<?php echo $this->url(array('module'=>'database','controller' => 'search','action'=>'results', 'mint'=>$this->id),null,true);?>" title="View all records">all coins recorded</a>, which are attributed to <?php echo $this->escape($this->mint_name);?>.</p>
