<?php $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();?>

<tr>
<td><a href="<?php echo $this->url(array('module' => $module,'controller' => 'types','action' => 'type','id' => $this->id),null,true);?>" title="View details for <?php echo $this->type;?>"><?php echo $this->type;?></a></td>
<td><a href="<?php echo $this->url(array('module' => $module,'controller' => 'rulers','action' => 'ruler','id' => $this->i),null,true);?>" title="View details for <?php echo $this->ruler;?>"><?php echo $this->ruler;?></a></td>
<td><?php echo $this->adbc($this->datefrom); if(isset($this->dateto)) { echo ' - '.$this->adbc($this->dateto);}?></td>
</tr>