<?php
$this->headTitle('Details for ' . $this->period_name);
$this->metaBase()->setDescription('Full description for the Roman coin classification series: ' . $this->period_name)
    ->setKeywords('coins,coin,roman,reece,periods,' . $this->period_name)
    ->setSubject('numismatics')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

<?php if (!is_null($this->date_range)): ?>
    <p>Date range: <?php echo $this->escape($this->date_range); ?></p>
<?php endif; ?>

<?php if (!is_null($this->description)): ?>
    <p>Description: <?php echo $this->escape($this->description); ?></p>
    <?php echo $this->searchLink()->setField('reeceID')->setId($this->id); ?>
<?php endif; ?>