<?php
$this->headTitle('Details for reverse type: ' . $this->type);
$this->metaBase()->setDescription($this->title())
    ->setKeywords('reverse,fourth,century.roman,type' . $this->type)
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<p>
    <?php if (!is_null($this->translation)): ?>
        Translation: <?php echo $this->translation; ?><br/>
    <?php endif; ?>
    <?php if (!is_null($this->description)): ?>
        Description: <?php echo $this->description; ?><br/>
    <?php endif; ?>
    <?php if (!is_null($this->period_name)): ?>
        Reece period: <a href="<?php echo $this->url(array(
            'module' => 'romancoins',
            'controller' => 'reeceperiods',
            'action' => 'period',
            'id' => $this->i), null, true);?>"><?php echo $this->period_name; ?></a> [
        <?php echo $this->date_range; ?>]<br/>
    <?php endif; ?>
    <?php if (!is_null($this->gendate)): ?>
        General date: <?php echo $this->gendate; ?>
    <?php endif; ?>
</p>

<?php echo $this->searchLink()->setField('reverse')->setId($this->id); ?>
<?php echo $this->latestRecords()->setQuery('reverse:' . $this->id); ?>