<?php $this->headTitle('Details for denomination: ' . $this->denomination);
$this->headMeta($this->curUrl(), 'dc.identifier')
    ->headMeta('CC NC-SA-BY', 'dc.rights')
    ->headMeta('Daniel Pett', 'dc.creator')
    ->headMeta('The Portable Antiquities Scheme', 'dc.publisher');
$this->headMeta('This page outlines detail for the denomination of '
    . $this->denomination . ' as used on the Scheme\'s database.
            When possible, this has been enhanced with dbpedia.', 'description');
$this->headLink()->appendAlternate($this->baseUrl()
    . '/database/search/results/denomination/' . $this->id . '/format/atom/',
    'application/rss+xml', 'Latest recorded finds feed for '
    . $this->escape($this->denomination));?>
<h2 class="lead">The <?php echo $this->denomination; ?></h2>
<?php echo $this->description; ?>
<?php if (!is_null($this->rarity)): ?>
    <p><?php echo $this->rarity; ?></p>
<?php endif; ?>

<p>

    <?php if (!is_null($this->weight)): ?>
        Weight: <?php echo $this->weight; ?> g<br/>
    <?php endif; ?>

    <?php if (!is_null($this->thickness)): ?>
        Thickness: <?php echo $this->thickness; ?> mm<br/>
    <?php endif; ?>

    <?php if (!is_null($this->diameter)): ?>
        Diameter: <?php echo $this->diameter; ?> mm<br/>
    <?php endif; ?>

    <?php if (!is_null($this->term)): ?>
        Metal: <?php echo $this->term; ?>
    <?php endif; ?>
</p>