<?php
$this->headTitle('Details for ' . $this->issuer . ' ' . $this->adBc($this->date1) . ' - ' . $this->adBc($this->date2));
$this->metaBase()->setSubject('numismatics')
    ->setDescription($this->title())
    ->setKeywords('ruler,profile,' . $this->issuer)
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

<?php if (!is_null($this->date1)): ?>
    <?php $dates = array($this->adBc()->setDate($this->date1), $this->adBc()->setDate($this->date2)); ?>
    <p>Date of reign:  <?php echo implode('-', $dates); ?></p>
<?php endif; ?>

<?php if (!is_null($this->styled)): ?>
    <p>Styled as: <?php echo $this->styled; ?></p>
<?php endif; ?>

<?php if (!is_null($this->alias)): ?>
    <p>Alias: <?php echo $this->alias; ?></p>
<?php endif; ?>

<?php if (isset($this->born)): ?>
    <p>Born: <?php echo $this->adBc()->setDate($this->born); ?>
        Died: <?php echo $this->adBc()->setDate($this->died); ?></p>
<?php endif; ?>

<?php if (!is_null($this->biography)): ?>
    <?php echo $this->biography; ?>
<?php endif; ?>

<?php echo $this->searchLink()->setField('ruler')->setId($this->id); ?>
<?php echo $this->latestRecords()->setQuery('ruler:' . $this->id); ?>