<?php
$this->headTitle('Access denied');
$this->metaBase()->setSubject('Error report')->setDescription('Access denied page')->generate();

?>


<h2 class="lead">Do You Want to Access the Statistics Pages?</h2>
<p><?php echo $this->message; ?></p>

<p>If you would like to see the statistics for the PAS website, and you already have an account for the site, please log in <a href="<?= $this->baseUrl() . '/users'?>">here</a> and come back to this page.</p>

<p>If you haven’t registered with the site, why don’t you consider it? You can set up an account <a href="<?= $this->baseUrl() . '/users/account/register' ?>">here</a> and it will allow you to do more with all of the wonderful data we have for objects found in the UK.</p>


<p>What would you like to do next?</p>

<ul>
    <?php if ("member" === $this->role): ?>
        <li>
            <a href="<?php
            echo($this->baseUrl() . '/users/account/upgrade'); ?>">Request an account upgrade</a>
        </li>
    <?php endif; ?>
    <?php if ("public" === $this->role): ?>
        <li>
            <a href="<?php
            echo($this->baseUrl() . '/users/account/register'); ?>">Register with the Scheme</a>
        </li>
    <?php endif; ?>
    <li><a href="<?php
        echo($this->baseUrl() . '/database'); ?>">Search the database<br></a></li>
    <li><a href="<?php
        echo($this->baseUrl() . '/contacts'); ?>">Find your local FLO</a></li>
    <li><a href="<?php
        echo($this->baseUrl() . '/treasure'); ?>">Read about the Treasure Act 1996</a></li>
    <li><a href="<?php
        echo($this->baseUrl() . '/guides'); ?>">Read our guides</a></li>
    <li><a href="<?php
        echo($this->baseUrl() . '/publications'); ?>">Read our Annual Reports</a></li>
    <li><a href="<?php
        echo($this->baseUrl() . '/news'); ?>">Find out our latest news</a></li>
    <li><a href="<?php
        echo($this->baseUrl() . '/counties'); ?>">Visit your local County Page</a></li>
</ul>
