<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$mints  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$mints->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$mintsElem = $dom->createElement('mints');
$mints->appendChild($mintsElem);
// set it's attribute
foreach($this->mints as $m){
$m = (object)$m;
$mintElem = $dom->createElement('mint');
$mintElem->appendChild( $dom->createElement('id', $m->i));
$mintElem->appendChild( $dom->createElement('name', $m->mint_name));
$mintElem->appendChild( $dom->createElement('created', $m->created));
$mintElem->appendChild( $dom->createElement('updated', $m->updated));
$mintElem->appendChild( $dom->createElement('period', $m->p));
$mintElem->appendChild( $dom->createElement('url',$site . $this->url(array('module' => $module,
'controller' => $controller,'action' => 'mints','id' => $m->i),NULL,true) ));
//$infoElem->appendChild( $dom->createCDATASection('Sun Certified Java Programmer book') );
$mintsElem->appendChild( $mintElem );
}

$dom->appendChild( $mints );

$xmlData  = $dom->saveXML();
echo $xmlData;
