<?php
$this->headTitle('Issuing mints of the Iron Age');
$this->metaBase()->setSubject('Iron Age numismatics')
    ->setKeywords('coins,numismatics,iron age')
    ->setDescription('This page lists the 3 known British Iron Age mints in operation.')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->mints)): ?>
    <ul>
        <?php echo $this->partialLoop('partials/numismatics/shared/mints.phtml', $this->mints) ?></ul>
<?php else: ?>
    <p>There are no mints available for this period.</p>
<?php endif; ?>