<tr id="project-<?php echo $this->id;?>">
<td><a href="<?php echo $this->url(array('module' => 'research','controller' => 'projects','action' => 'project','id' => $this->id),null,true);?>" title="View this project's full details"><?php echo $this->title;?></a></td>
<td><?php echo $this->investigator;?></td>
<td><?php echo $this->type;?></td>
<td><?php if($this->start != '0000'){echo $this->start;}else{echo 'N/A';}?></td>
<td><?php if($this->finish != '0000'){echo $this->finish;}else{echo 'N/A';}?></td>
<?php echo $this->allowedtest('<td><a href="'
.$this->url(array('module' => 'admin','controller' => 'research','action' => 'edit','id' => $this->id),null,true)
.'" title="Edit details for '
.$this->title
.'">Edit</a><br ><a href="#" title="Delete this project" class="delete">Delete</a></td>');?>
</tr>