<?php
$this->headTitle('Research project: ' . $this->title);
$this->metaBase()->setDescription($this->title())
    ->setSubject('Research')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title; ?></h2>

    <p>This research project is being directed principally by: <?php echo $this->fullname; ?><br/>
        Level of research: <?php echo $this->type; ?></p>
<?php if (!is_null($this->description)): ?>
    <?php echo $this->description; ?>
<?php else: ?>
    <p>No description entered.</p>
<?php endif; ?>
<?php if (!is_null($this->startDate)): ?>
    <?php echo $this->startDate; ?>
<?php endif; ?>