<?php
$this->headTitle('An introduction to our photos');
$this->MetaBase('The Scheme curates a large number of images on it\'s flickr profile feed.
They are all produced under a Creative Commons licence, feel free to use them - except for commercial use',
'Photos',
'flickr,photos,archaeology,numismatics,coins,museums');
$this->jQuery()->addJavascriptFile('/js/bootstrap-carousel.js',$type='text/javascript');
?>

<h2>The Scheme on Flickr</h2>
<?php
$flickr = $this->getInvokeArg('bootstrap')->config->webservice->flickr;
?>
<div class="row-fluid">
<?php
echo $this->flickrFront()->setLimit(12)->setFlickrConfig($flickr);
?>
<div class="row-fluid span10">
<?php
echo $this->flickrContactsList()->setFlickr($flickr);
?>
</div>
<div class="row-fluid span10">
<?php echo $this->flickrTags()->setApi($flickr);?>
</div>
<div class="row-fluid span10">
<?php
echo $this->flickrTotalViews()->setApi($flickr);
?>
</div>

</div>