<?php
$this->headTitle('A test for heatmapping');
$this->jQuery()->addJavascriptFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=visualization', $type = 'text/javascript');
?>
<h2 class="lead"><?php echo $this->title();?></h2>
<?php $this->jQuery()->javascriptCaptureStart();?>
// Adding 500 Data Points
<?php 
$html = '';
foreach($this->results as $result) {
if(!empty($result['fourFigureLat'])){
  $html .= 'new google.maps.LatLng(' . $result['fourFigureLat'] . ',' .$result['fourFigureLon']. '),';
}
}
$html = substr($html,0,-1);
?> 
var map, pointarray, heatmap;
var Data = [
<?php echo $html;?>
];

<?php 
$config = Zend_Controller_Front::getInstance()->getParam('bootstrap');
$allowed = $config->getOption('higherLevel');
	$user = new Pas_User_Details();
	$person = $user->getPerson();
	if($person){
		$role = $person->role;
	} else {
		$role = NULL;
	}
	if(in_array($role, $allowed)) {
		$maxzoom = 18;
		$minzoom = 1;
	} else {
		$maxzoom = 11;
		$minzoom = 1;
	}
?>

	var max = <?php echo $maxzoom;?>;
	var min = <?php echo $minzoom;?>;
function initialize() {
  var mapOptions = {
    zoom: 6,
    scrollwheel: false,
          maxZoom: max,
          minZoom: min,
    center: new google.maps.LatLng(54, -2),
    mapTypeId: google.maps.MapTypeId.SATELLITE
  };

  map = new google.maps.Map(document.getElementById('map'),
      mapOptions);

  var pointArray = new google.maps.MVCArray(Data);

  heatmap = new google.maps.visualization.HeatmapLayer({
    data: pointArray
  });

  heatmap.setMap(map);
}

function toggleHeatmap() {
  heatmap.setMap(heatmap.getMap() ? null : map);
}

function changeGradient() {
  var gradient = [
    'rgba(0, 255, 255, 0)',
    'rgba(0, 255, 255, 1)',
    'rgba(0, 191, 255, 1)',
    'rgba(0, 127, 255, 1)',
    'rgba(0, 63, 255, 1)',
    'rgba(0, 0, 255, 1)',
    'rgba(0, 0, 223, 1)',
    'rgba(0, 0, 191, 1)',
    'rgba(0, 0, 159, 1)',
    'rgba(0, 0, 127, 1)',
    'rgba(63, 0, 91, 1)',
    'rgba(127, 0, 63, 1)',
    'rgba(191, 0, 31, 1)',
    'rgba(255, 0, 0, 1)'
  ]
  heatmap.setOptions({
    gradient: heatmap.get('gradient') ? null : gradient
  });
}

function changeRadius() {
  heatmap.setOptions({radius: heatmap.get('radius') ? null : 20});
}

function changeOpacity() {
  heatmap.setOptions({opacity: heatmap.get('opacity') ? null : 0.2});
}

google.maps.event.addDomListener(window, 'load', initialize);
<?php $this->jQuery()->javascriptCaptureEnd();?>
<div id="panel">
      <button onclick="toggleHeatmap()">Toggle Heatmap</button>
      <button onclick="changeGradient()">Change gradient</button>
      <button onclick="changeRadius()">Change radius</button>
      <button onclick="changeOpacity()">Change opacity</button>
    </div>
    <div id="map"></div>