<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$moneyers  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$moneyers->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

foreach($this->moneyer as $moneyer){
$moneyerElem = $dom->createElement('moneyer');
	foreach($moneyer as $k => $v){
	$moneyerElem->appendChild( $dom->createElement($k, $v));
	}
$moneyers->appendChild( $moneyerElem );
}

$dom->appendChild( $moneyers  );

$xmlData  = $dom->saveXML();
echo $xmlData;
