<?php
$this->headTitle('Denominations issued during the Medieval period');
$this->metaBase()->setDescription('A list of all issued denominations for the Medieval period in England and Wales.')
    ->setKeywords('medieval,coins,numismatics,archaeology,medieval,england,wales')
    ->setSubject('Medieval numismatics')
    ->generate();
?>
<h2 class="lead">Medieval denominations</h2>
<p>The following coins were issued during the Medieval period.</p>
<?php if (!empty($this->denominations)): ?>
    <ul>
        <?php echo $this->partialLoop('partials/numismatics/denominations.phtml', $this->denominations); ?>
    </ul>
    <?php echo $this->paginationControl($this->denominations, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>There are no denominations available to you.</p>
<?php endif; ?>
