<?php
$this->headTitle('Add a rally');
$this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {

    var datePickerSettings = {
        format: 'yyyy-mm-dd',
        endDate: (new Date((new Date()).getFullYear() + 1, 12, 0)),
    };

    $("#date_from").datepicker(datePickerSettings);
    $("#date_to").datepicker(datePickerSettings);

});
<?php $this->jQuery()->javascriptCaptureEnd();

$this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/bootstrap-datepicker.js', $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/JQuery/jQueryLinkedSelect.js', $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/JQuery/findSpotLinkedSelect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/JQuery/findSpotLinkedQuery.js',$type='text/javascript');

$this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/bootstrap-typeahead.js', $type='text/javascript');

$this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/typeaheads/organiser.js', $type='text/javascript');

$this->headLink()->appendStylesheet('/css/bootstrap-datepicker.css');
?>

<h2 class="lead"><?php echo $this->title();?></h2>
<?php echo $this->form; ?>