<?php 
	$this->headTitle('Delete a rally');
if ($this->rally) :?>
<h2>Delete: <?php echo $this->escape($this->rally->rally_name); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->rally->rally_name); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'rallies','action'=>'delete'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->rally->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>