<?php 
	$this->headTitle('Delete a linked finds liaison officer to a rally');
if ($this->rally) :?>
<h2>Delete attending person</h2>
<p>Are you sure that you want to delete this attending person from rally
</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'rallies','action'=>'deleteflo'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="rallyID" value="<?php echo $this->rally->rallyID; ?>" />
<input type="hidden" name="staffID" value="<?php echo $this->rally->staffID; ?>" />

<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>