<?php $this->headTitle('Edit rally details');?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function() {
        $("#date_from").datepicker({ maxDate: '+1y'});
        $("#date_to").datepicker({ maxDate: '+1y'});
    });
<?php $this->jQuery()->javascriptCaptureEnd();?>
<?php

    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/bootstrap-datepicker.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/jQueryLinkedSelect.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/findSpotLinkedSelect.js',$type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/findSpotLinkedQuery.js',$type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
        . '/js/bootstrap-typeahead.js', $type='text/javascript');

    $this->jQuery()->addJavascriptFile($this->baseUrl()
        .'/js/JQuery/typeaheads/organiser.js', $type='text/javascript');
?>
<h2><?php echo $this->title();?></h2>

    <?php echo $this->form ;?>