<?php
$this->metaBase()->setDescription('All known metal detecting rallies that the Scheme has tried to attend. These present the Scheme
with a resource management issue')
    ->setKeywords('archaeology,rally,rallies,england,wales')
    ->setSubject('Metal detecting rallies');
$this->headTitle('Rallies known to the Scheme');
?>

<h2 class="lead">Metal Detecting Rallies</h2>
<?php
echo $this->Href(array('module' => 'database', 'controller' => 'rallies', 'action' => 'add', 'checkAcl' => true,
    'acl' => 'Zend_Acl', 'wrapper' => array('tag' => 'div', 'id' => 'action'), 'content' => 'Add a rally', 'attribs' => array('title' => 'Add an organisation', 'class' => 'btn btn-small btn-primary',)));
?>


<?php if (count($this->rallies)): ?>
    <ul id="yearrange">
        <?php echo $this->partialLoop('partials/database/archiveYearsRallies.phtml', $this->yearList()->setStartYear(1998)->generateArray()); ?>
    </ul>
    <a class="btn btn-small btn-info"
       href="<?php echo $this->url(array('module' => 'database', 'controller' => 'rallies', 'action' => 'map'), NULL, true); ?>"
       title="View rally locations">View rally locations on a map <i class="icon-map-marker"></i></a>
    <table class="table table-striped" summary="A list of all rallies we have attended">
        <caption>Rallies that the Scheme has attended</caption>
        <thead>
        <tr>
            <th>Rally Name</th>
            <th>Date from</th>
            <th>Date to</th>
            <?php
            $auth = Zend_Auth::getInstance();
            if ($auth->hasIdentity()) {
                $user = $auth->getIdentity();
                {
                    $allowedAccess = array('flos', 'fa', 'admin');
                    if (in_array($user->role, $allowedAccess)) {
                        ?>

                        <th>Actions</th>
                    <?php
                    }
                }
            }
            ?>


        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/database/rallies.phtml', $this->rallies) ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->rallies, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <ul id="yearrange">
        <?php echo $this->partialLoop('partials/database/archiveYearsRallies.phtml', $this->years); ?>
    </ul>
    <p>There are no rallies in that date range.</p>
<?php endif; ?>