<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$rallies  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$rallies->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->rallies)));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$ralliesElem = $dom->createElement('rallies');
$rallies->appendChild($ralliesElem);
// set it's attribute
foreach($this->rallies as $rally){
$rallyElem = $dom->createElement('rallyDetails');
foreach($rally as $k => $v){
$rallyElem->appendChild( $dom->createElement($k, htmlentities($v)));
}
$ralliesElem->appendChild( $rallyElem );
}

$dom->appendChild( $rallies );

$xmlData  = $dom->saveXML();
echo $xmlData;