<?php
$this->headTitle('Details for rally: ');
echo $this->partial('partials/database/rallies/rally.phtml', $this->rallies['0']) ?>
<h4 class="lead">Attending Scheme staff</h4>
<?php if ($this->atts): ?>
    <ul>
        <?php echo $this->partialLoop('partials/database/rallies/attendingFlos.phtml', $this->atts); ?>
    </ul>
<?php else: ?>
    <p>No FLOs have been listed as attending so far.</p>
<?php endif; ?>
<?php
echo $this->href(array('module' => 'database', 'controller' => 'rallies', 'action' => 'addflo', 'checkAcl' => true,
    'acl' => 'Zend_Acl', 'params' => array('id' => $this->rallies['0']['id']), 'content' => 'Add an attending finds liaison officer', 'attribs' => array('title' => 'Add a new attending flo'),
    'attribs' => array('class' => 'btn btn-small')));
?>
<?php echo $this->latestRecords()->setQuery('rallyID:' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>
