<?php
echo $this->headTitle('Database settings');
?>
<h2><?php echo $this->title();?></h2>
<div class="row-fluid">
	<p>View and change your database settings.</p>
<div class="row span8">
	<h3>Copy last record options</h3>
	<h4>Finds</h4>
	<blockquote >
	<?php
	$findFields = array();
	foreach($this->findFields as $findField){
            $clean = $this->fieldNamesDb()->setField($findField)->parseField();
            $findFields[] = $clean;
	}
	?>
	<p><?php echo implode(', ', $findFields);?></p>
	</blockquote>
	<p><a class="btn" href="<?php echo $this->url(array('module' => 'users', 'controller' => 'configuration', 'action' => 'find'),'default',true);?>">Change finds form</a></p>
</div>
<div class="row span8">
	<h4>Findspots</h4>
	<blockquote >
	<?php
	$findSpotFields = array();
	foreach($this->findSpotFields as $findSpotField){
            $findSpotFields[] = $this->fieldNamesDb()
                    ->setField($findSpotField)
                    ->parseField();
	}
	?>
	<p><?php echo implode(', ', $findSpotFields);?></p>
	</blockquote>
	<p><a class="btn" href="<?php echo $this->url(array('module' => 'users', 'controller' => 'configuration', 'action' => 'findspot'),'default',true);?>">Change findspot form</a></p>
</div>
<div class="row span8">
	<h4>Coins</h4>
	<blockquote >
	<?php
	$coinFields = array();
	foreach($this->coinFields as $coinField){
            $coinFields[] = $this->fieldNamesDb()
                    ->setField($coinField)
                    ->parseField();
	}
	?>
	<p><?php echo implode(', ', $coinFields);?></p>
	</blockquote>
	<p><a class="btn" href="<?php echo $this->url(array('module' => 'users', 'controller' => 'configuration', 'action' => 'coin'),'default',true);?>">Change coins form</a></p>
</div>
<div class="row span8">
	<h3>Page after logging in</h3>
	<blockquote >
        <?php

	foreach( $this->redirectUri as $k => $v) {?>
            <a href="<?php echo $k;?>"><?php echo $v;?></a>
        <?php }
	?>


	</blockquote>
	<p><a class="btn" href="<?php echo $this->url(array('module' => 'users', 'controller' => 'configuration', 'action' => 'redirect'),'default',true);?>">Change page</a></p>
</div>

    <div class="row span8">
        <h3>Coin hoard</h3>
        <blockquote >
            <?php
            $hoardFields = array();
            foreach($this->hoards as $hoardField){
                $hoardFields[] = $this->fieldNamesDb()
                    ->setField($hoardField)
                    ->parseField();
            }
            ?>
            <p><?php echo implode(', ', $hoardFields);?></p>
        </blockquote>
        <p><a class="btn" href="<?php echo $this->url(array('module' => 'users', 'controller' => 'configuration', 'action' => 'hoard'),'default',true);?>">Change hoard</a></p>
    </div>
</div>