<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$rulers  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$rulers->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->rulers)));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$rulersElem = $dom->createElement('rulers');
$rulers->appendChild($rulersElem);
// set it's attribute
foreach($this->rulers as $r){
$r = (object)$r;
$rulerElem = $dom->createElement('mint');
$rulerElem->appendChild( $dom->createElement('id', $r->id));
$rulerElem->appendChild( $dom->createElement('name', $r->issuer));
//$mintElem->appendChild( $dom->createElement('created', $r->created));
//$mintElem->appendChild( $dom->createElement('updated', $r->updated));
$rulerElem->appendChild( $dom->createElement('region', $r->region));
$rulerElem->appendChild( $dom->createElement('url',$site . $this->url(array('module' => $module,
'controller' => $controller,'action' => 'ruler','id' => $r->id),NULL,true) ));
//$infoElem->appendChild( $dom->createCDATASection('Sun Certified Java Programmer book') );
$rulersElem->appendChild( $rulerElem );
}

$dom->appendChild( $rulers );

$xmlData  = $dom->saveXML();
echo $xmlData;
