<?php if (!empty($this->rulers)): ?>
<?php echo $this->partialLoop('partials/numismatics/ironAge/ironAgeRuler.phtml', $this->rulers) ?>
<?php else: ?>
    <p class="error">There are no entries for this ruler ID.</p>
<?php endif; ?>
<?php if (!empty($this->regions)): ?>
<h3 class="lead">Region(s)</h3>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/ironAge/ironAgeGeography.phtml', $this->regions) ?>
</ul>
<?php else: ?>
    <p>There are no specified regions for this ruler.</p>
<?php endif; ?>