<?php 
$this->headTitle('Issuing rulers of the Post Medieval period');
?>
<h2 class="lead">Issuing rulers of the Post Medieval period</h2>

<?php echo $this->partial('partials/numismatics/medieval/categoryTitle.phtml', $this->rulers['0']) ; ?>
<p>This period had <?php echo count($this->rulers);?> issuers.</p>
<ul><?php echo $this->partialLoop('partials/numismatics/shared/rulers.phtml', $this->rulers) ?></ul>

