<?php
$this->headTitle('A timeline of post medieval issuers');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/compiled/js/storyjs-embed.js',$type = 'text/javascript');
$this->metaBase()
        ->setDescription('A timeline of Post Medieval issuers')
        ->setKeywords('post medieval,issuers,timeline,king')
        ->generate();
?>
<h2>
    <?php echo $this->title();?>
</h2>
<div id="timeline">
</div>
<?php $this->jQuery()->javascriptCaptureStart() ?>

$(document).ready(function() {
    createStoryJS({
        type: 'timeline',
        width: '100%',
        height: '600',
        source: 'http://finds.org.uk/postmedievalcoins/rulers/data/format/json',
        embed_id: 'timeline',
        hash_bookmark: true,                           
        });
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>