<?php
$this->metaBase('A timeline of Post Medieval issuers',null,'post medieval,issuers,timeline,king');
$this->headTitle('A timeline of Roman issuers');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/compiled/js/storyjs-embed.js',$type = 'text/javascript');
?>
<h2>A timeline of Post Medieval issuers</h2>
<div id="timeline"></div>
<?php $this->jQuery()->javascriptCaptureStart() ?>

	$(document).ready(function() {
		createStoryJS({
					type:			'timeline',
					width:			'100%',
					height:			'600',
					source:			'http://finds.org.uk/postmedievalcoins/rulers/data/format/json',
					embed_id:		'timeline',
					hash_bookmark:  true,                           
				});
	});
<?php $this->jQuery()->javascriptCaptureEnd() ?>