<?php
$this->headTitle('Manage contact details for alumni');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->contacts)): ?>
    <table class="table table-striped" summary="List of all valid contacts associated with the Scheme">
        <thead>
        <tr>
            <th>Fullname</th>
            <th>Role</th>
            <th>Area covered</th>
            <th>Employment Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/contactListTable.phtml', $this->contacts); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->contacts, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else: ?>
    <p>There are no organisations available to you.</p>
<?php endif; ?>