<?php
$this->headTitle('Add an image to a contact profile');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->errors)): ?>
    <ul>
        <?php foreach ($this->errors as $key => $value): ?>
            <li><?php echo $value; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif;?>
<?php echo $this->form; ?>
