<?php
$this->headTitle('Delete an image');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if ($this->contact["image"]) : ?>
    <h2 class="lead">
        Delete an image 
    </h2>
    <p>Are you sure that you want to
        delete an image for <strong><?= $this->contact->firstname ?> <?= $this->contact->lastname ?></strong>
    </p>
    <form action="<?= $this->url(array(
            'module' => 'admin', 'controller' => 'contacts', 'action' => 'deleteavatar'
        ), 'default', true) ?>" method="post">
        <div class="btn-toolbar">
            <input type="hidden" name="id" value="<?= $this->contact->id ?>"/>
            <input type="submit" class="btn btn-danger" name="confirmDelete" value="Yes"/>
            <input type="submit" class="btn btn-default" name="confirmDelete" value="No"/>
        </div>
    </form>
<?php else: ?>
    <p>Cannot find the item requested.</p>
<?php endif; ?>
