<?php 
$this->headTitle('Delete contact');
if ($this->contact) :?>
<h2>Delete: <?php echo $this->escape($this->contact->firstname); ?> <?php echo $this->escape($this->contact->lastname); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->contact->firstname); ?> <?php echo $this->escape($this->contact->lastname); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'contacts','action'=>'deletecontact'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->contact->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>
