<?php
$this->headTitle('Manage contact details for staff');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<p><a href="<?php echo $this->url(
        array(
            'module' => 'admin', 'controller' => 'contacts', 'action' => 'add'
        ), null, true);?>" class="btn btn-small btn-warning"
      title="Add a new staff member to the system">Add a new staff member</a></p>
<?php if (!empty($this->contacts)): ?>
    <table class="table table-striped" summary="List of all valid contacts associated with the Scheme">
        <thead>
        <tr>
            <th>Fullname</th>
            <th>Role</th>
            <th>Area covered</th>
            <th>Employment Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/contactListTable.phtml', $this->contacts); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->contacts, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>There are no organisations available to you.</p>
<?php endif; ?>