<?php 
$this->headTitle('Archaeological images on flickr');
$this->metaBase()
        ->setDescription('Archaeological images that we\'ve seen on flickr. This should only
show The Trustees of the British Museum: CC-BY images.')
        ->setSubject('photos')
        ->setKeywords('photos,archaeology,favourites,portable antiquities,flickr')
        ->generate();
?>

<h2 class="lead">
    <?php echo $this->title();?>
</h2>
<div class="row-fluid">
<?php
if($this->photos->photo):
?>
<?php 
$photos = array();
foreach($this->photos->photo as $photo){
	$photos[] = (array)$photo;
}
echo $this->partialLoop('partials/flickr/favourite.phtml',$photos);
?> 

<div class="row span16">
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
</div>
<?php else:?>
<p>There are no favourites available at the moment</p>
<?php endif;?>
</div>