<?php
$this->headTitle('All pictures tagged with '.$this->tagtitle);
$this->MetaBase('A list of photos retrieved from the flickr api using creative commons searches on the tag '
. $this->tagtitle,
'photos',
'photos,flickr,api,tagged,' . $this->tagtitle);
?>
<?php if($this->tagtitle):?>
<h2>All photos tagged with <?php echo $this->tagtitle;?></h2>
<?php else:?>
<h2>All our tagged photos</h2>
<?php endif;?>
<div class="row-fluid">
<?php
$photos = array();
if(!is_null($this->pictures)) {
if(is_array($this->pictures->photo)){
foreach($this->pictures->photo as $photo){
	$photos[] = (array)$photo;
}
} else {
	$photos[] = (array)$this->pictures->photo;
}

if($photos):
?>
<?php echo $this->partialLoop('partials/flickr/set.phtml',$photos);?>
<?php
if(!is_null($this->pictures->photo)):?>
<div class="row span16">
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
</div>
<?php endif;?>
<?php else:?>
<p>There are no photos available with that tag.</p>
<?php endif;?>
</div>
<?php } else {?>
<p>There are no photos available with that tag.</p>
<?php }?>