<?php
$feedArray = array(
    'title' => 'Latest research projects being conducted on Scheme data',
    'link' => $this->curUrl(),
    'charset' => 'utf-8',
    'description' => 'Latest feeds of research projects on Scheme data',
    'author' => 'The Portable Antiquities Scheme',
    'image' => $this->serverUrl() . '/assets/logos/pas.jpg',
    'email' => 'info@finds.org.uk',
    'copyright' => 'Creative Commons Licenced',
    'generator' => 'The Scheme database powered by Zend Framework and Dan\'s magic',
    'language' => 'en',
    'entries' => array()
);
foreach ($this->projects as $project) {
    $feedArray['entries'][] = array(
        'title' => $project['title'],
        'link' => $this->serverUrl() . '/research/projects/project/id/' . $project['id'],
        'guid' => $this->serverUrl() . '/research/projects/project/id/' . $project['id'],
        'description' => strip_tags(substr(str_replace('£', '&pound;', $project['description']), 0, 300)),
        'lastUpdate' => strtotime($project['updated']),
        'content' => strip_tags(str_replace('£', '&pound;', $project['description']), ''),
    );
}
$feed = Zend_Feed::importArray($feedArray, 'rss');
$feed->send();