<?php
$this->headTitle('All research projects listed on our system');
$this->metaBase()
    ->setDescription('A list of all research projects that the Scheme knows about using PAS data')
    ->setSubject('research')
    ->setKeywords('archaeology,romans,saxons,phd,undergraduate,museum,danelaw')
    ->generate();
?>
<h2 class="lead">
    <?php if (!is_null($this->name)): ?>
        <?php echo $this->name; ?>
    <?php endif; ?> Research in progress using our data
</h2>
<?php if (!empty($this->projects)): ?>
    <p>There are <?php echo $this->paginationControl($this->projects, 'Sliding', 'structure/queryCounts.phtml'); ?>
        projects in progress that you can read about. If you're not listed here, then please do let us know and we'll
        add you.</p>

    <table class="table table-striped">
        <caption>Research projects in progress or completed</caption>
        <thead>
        <tr>
            <th>Primary investigator</th>
            <th>Title</th>
            <th>Level</th>
            <th>End date</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/research/projects.phtml', $this->projects); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->projects, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>There are no projects available to you.</p>
<?php endif; ?>
