<?php
$feedArray = array(
    'title' => 'Latest research projects being conducted on Scheme data',
    'link' => $this->curUrl(),
    'charset' => 'utf-8',
    'description' => 'Latest feeds of research projects on Scheme data',
    'author' => 'The Portable Antiquities Scheme',
    'image' => $this->serverUrl() . '/assets/logos/pas.jpg',
    'email' => 'info@finds.org.uk',
    'copyright' => 'Creative Commons Licenced',
    'generator' => 'The Scheme database powered by Zend Framework and Dan\'s magic',
    'language' => 'en',
    'entries' => array()
    );
    foreach ($this->projects as $proj) {
        $feedArray['entries'][] = array(
            'title' => $proj['title'],
            'link' => $this->serverUrl() . '/research/projects/project/id/' . $proj['id'],
            'guid' => $this->serverUrl() . '/research/projects/project/id/' . $proj['id'],
            'description' => strip_tags(substr(str_replace('£','&pound;',$proj['description']),0,300)),
            'lastUpdate' => strtotime($proj['updated']),
            'content' => strip_tags(str_replace('£','&pound;',$proj['description']),''),
            );
        }
        $feed = Zend_Feed::importArray($feedArray,'rss');
        $feed->send();