<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$faqs  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$faqs->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$faqsElem = $dom->createElement('researchProjects');
$faqs->appendChild($faqsElem);

foreach($this->projects as $f){
$faqElem = $dom->createElement('project');
foreach($f as $k => $v){
	$faqElem->appendChild( $dom->createElement($k, htmlspecialchars($v))); 
}
$faqsElem->appendChild( $faqElem );
}

$dom->appendChild( $faqs );

$xmlData  = $dom->saveXML();
echo $xmlData;