<?php

$paginator = $this->suggested;
$meta = array(
    'currentPage' => $paginator->getCurrentPageNumber(),
    'totalResults' => $paginator->getTotalItemCount(),
    'resultsPerPage' => $paginator->getItemCountPerPage(),
    'totalPages' => $paginator->getPageRange()
        );
$projects = array();
foreach($this->suggested as $project){
    $projects[] = $project;
}
echo Zend_Json::prettyPrint(Zend_Json::encode(( array('meta' => $meta, 'projects' => $projects))));