<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$suggested  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$suggested->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('totalItems',$this->suggested->getTotalItemCount()));
$meta->appendChild( $dom->createElement('currentPage',$this->suggested->getCurrentPageNumber()));
$meta->appendChild( $dom->createElement('itemsPerPage', $this->suggested->getItemCountPerPage()));
$meta->appendChild( $dom->createElement('totalPages',ceil($this->suggested->getTotalItemCount()/$this->suggested->getItemCountPerPage())));

$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$suggestedElem = $dom->createElement('suggestedResearch');
$suggested->appendChild($suggestedElem);
// set it's attribute

foreach($this->suggested as $r){
$projectElem = $dom->createElement('project');
   foreach($r as $k => $a){
       $projectElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
$suggestedElem->appendChild( $projectElem );
}

$dom->appendChild( $suggested );

$xmlData  = $dom->saveXML();
echo $xmlData;
