<?php
$this->headTitle("Coroners of England and Wales contact details");
$this->metaBase()
    ->setDescription('A list of all coroners known to the Portable Antiquities Scheme')
    ->setSubject('Coroners list')
    ->setKeywords('coroners,scheme,head office,archaeology')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>

<p>The contact information for specific coroners’ offices can be found on the Courts and Tribunals Judiciary
    website,
    <a href="https://www.judiciary.uk/courts-and-tribunals/coroners-courts/coroners-appointments-contacts-and-areas/the-appointment-of-senior-coroners/"
       target="_blank" title="Coroners: appointments and how to contact their offices - Courts and Tribunals Judiciary">here</a>.
</p>
