<?php
$paginator = $this->rulers;
$results = array();
foreach($this->rulers as $result){
	$results[] = $result;
}
$meta = array(
    'currentPage' => $paginator->getCurrentPageNumber(),
    'totalResults' => $paginator->getTotalItemCount(),
    'resultsPerPage' => $paginator->getItemCountPerPage(),
    'totalPages' => ceil($paginator->getTotalItemCount()/$paginator->getItemCountPerPage()));
echo Zend_Json::prettyPrint(Zend_Json::encode( ( array('meta' => $meta, 'rulers' => $results) ) ) ) ;