<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$mints  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$mints->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', $this->rulers->getTotalItemCount()));
$meta->appendChild( $dom->createElement('page', $this->rulers->getCurrentPageNumber()));
$meta->appendChild( $dom->createElement('totalPages', $this->rulers->totalPages));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action, 'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action, ),NULL,true)  ));
//1st item
$mintsElem = $dom->createElement('rulers');
$mints->appendChild($mintsElem);
// set it's attribute

foreach($this->rulers as $ruler){

$mintElem = $dom->createElement('ruler');
	foreach($ruler as $k => $v){
	$mintElem->appendChild( $dom->createElement($k, $v));
	}
$mintsElem->appendChild( $mintElem );
}

$dom->appendChild( $mints );

$xmlData  = $dom->saveXML();
echo $xmlData;
