<li><?php echo $this->fullname;?> [<a href="<?php echo $this->url(array(
	'module' => 'database',
	'controller' => 'search',
	'action' => 'results',
	'rallyID' => $this->rallyID, 
	'createdBy' => $this->id),
	null,true);?>" title="Find all records recorded at this rally by <?php echo $this->fullname;?>">Find all records created</a>
]
<?php if(isset($this->datefrom)):
    $dates = array($this->niceshortdate($this->datefrom), $this->niceshortdate($this->dateto));
    ?>

 Attended: <?php echo implode( ' - ', $dates);?>
 <?php endif;?>
   <?php
echo $this->Href(array('module' => 'database','controller'=>'rallies', 'action'=>'deleteflo', 'checkAcl'=>true,
'acl'=>'Zend_Acl',  'params' =>array('rallyID'=>$this->rallyID,'staffID' => $this->id), 'content'=>'Delete',
    'attribs' => array('title' => 'Delete flo details from this rally')));
?> </li>

