<h2 class="lead">Delete a findspot</h2>
<p>Are you sure that you want to delete '<?php echo $this->escape($this->old_findspotid); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'findspots','action'=>'delete'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->id; ?>" />
<input type="hidden" name="recordID" value="<?php echo $this->recordID;?>"/>
    <input type="hidden" name="controller" value="<?php echo $this->controller;?>"/>
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
