<tr>
<td><a href="<?php echo $this->url(array('module' => $this->denomController($this->temporal), 'controller' => 'denominations','action' => 'denomination' , 'id' => $this->id),null,true);?>" title="View details for denomination <?php echo ucfirst($this->denomination);?>"><?php echo ucfirst($this->denomination);?></a></td>
<td><?php echo $this->escape($this->mat);?></td>
<td><?php echo $this->escape($this->temporal);?></td>
</tr>
