<tr>
    <td>
        <?php
        $url = array(
            'module' => $this->denomController()->setPeriod($this->temporal),
            'controller' => 'denominations',
            'action' => 'denomination',
            'id' => $this->id
        );?>
        <a href="<?php echo $this->url($url, 'default', true); ?>"
           title="View details for denomination <?php echo ucfirst($this->denomination); ?>"><?php echo ucfirst($this->denomination); ?></a>
    </td>
    <td><?php echo $this->mat; ?></td>
    <td><?php echo $this->temporal; ?></td>
</tr>
