<?php
/** A partial for delivering details on measurements and weights
 * @author Daniel Pett <dpett at britishmuseum.org>
 * @license http://www.gnu.org/licenses/agpl-3.0.txt GNU Affero GPL v3.0
 * @version 1
 */
?>
<h4>
    Dimensions and weight
</h4>
<div id="dimensions">
    <p>
    <?php if(!is_null($this->length)): ?>
    Length: <span property="pas:length" datatype="units:mm"><?php echo $this->escape($this->length);?></span> mm
    <br />
    <?php endif;?>

    <?php if(!is_null($this->height)) : ?>
    Height: <span property="pas:height" datatype="units:mm"><?php echo $this->escape($this->height);?></span> mm
    <br />
    <?php endif;?>

    <?php if(!is_null($this->width)) : ?>
    Width:  <span property="pas:width" datatype="units:mm"><?php echo $this->escape($this->width);?></span> mm
    <br />
    <?php endif;?>

    <?php if(!is_null($this->thickness)) : ?>
    Thickness: <span property="pas:thickness" datatype="units:mm"><?php echo $this->escape($this->thickness);?></span> mm
    <br />
    <?php endif;?>

    <?php if(!is_null($this->weight)) : ?> 
    Weight: <span property="pas:weight" datatype="units:g"><?php echo $this->escape($this->weight);?></span> g
    <br />
    <?php endif;?>

    <?php if(!is_null($this->diameter)) :?>
    Diameter:  <span property="pas:diameter" datatype="units:mm"><?php echo $this->escape($this->diameter);?></span> mm
    <br />
    <?php endif;?>
    
    Quantity: <span property="pas:quantity" datatype="xsd:decimal"><?php echo $this->escape($this->quantity);?></span>
    </p>
</div>