<?php
/** A partial for displaying early medieval data
 * @author Daniel Pett <dpett at britishmuseum.org>
 * @copyright  Copyright (c) 2014 dpett @ britishmuseum.org
 * @license http://www.gnu.org/licenses/agpl-3.0.txt GNU Affero GPL v3.0
 * @version 1
 */
?>
<h3>
    Coin data (numismatics)
</h3>
<?php echo $this->CoinEditDeleteLink()
        ->setFindID($this->id)
        ->setBroadperiod($this->broadperiod)
        ->setSecuID($this->secuid)
        ->setInstitution($this->institution)
        ->setCreatedBy($this->createdBy)
        ->setRecordID($this->coinID);
?>
<p>
    <!-- Start of denomination span -->
    <?php if(!is_null($this->denominationID)) : ?>
    Denomination: <?php echo $this->escape($this->denomination);?>
    <span class="scope">
        [<a href="<?php echo $this->url(array(
        'module' => 'earlymedievalcoins',
        'controller'=>'denominations',
        'action'=>'denomination',
        'id' => $this->denominationID),null,true);?>" title="Read scope note for <?php echo
        $this->d;?>">scope notes</a> | <a href="<?php echo $this->url(array(
            'module' => 'database',
            'controller'=>'search',
            'action'=>'results',
            'denomination' => $this->denomination),null,true);?>"
            title="view all records assigned to denomination:
        <?php echo $this->denomination;?>">view all attributed records</a>]
    </span>
    <br />
    Denomination certainty: <?php echo $this->certainty()->setCertainty($this->denominationQualifier);?>
    <br />
    <?php endif;?>
    <!-- End of denomination span -->
    
    <!-- Start of ruler span -->
    <?php if(!is_null($this->primaryRuler)) : ?>
    Ruler/issuer: <?php echo $this->escape($this->ruler1);?>
    <span class="scope">
        [<a href="<?php echo $this->url(array(
        'module' => 'earlymedievalcoins',
        'controller'=>'rulers',
        'action'=>'ruler',
        'id' => $this->primaryRuler),null,true);?>" title="Read scope note for
    <?php echo $this->period_name;?>">scope notes</a> | <a href="<?php echo
    $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'ruler' => $this->primaryRuler),null,true);?>"
        title="view all records assigned to <?php echo $this->ruler1;?>">
        view all attributed records</a>]
    </span>
    <br />
    <?php endif;?>
    <?php if(!is_null($this->rulerQualifier)):?>
    Ruler certainty: <?php echo $this->certainty()->setCertainty($this->rulerQualifier);?>
    <br />
    <?php endif;?>       
    <!-- End of ruler span --> 

    <!-- Start of mint span --> 
    <?php if(!is_null($this->mintName)) : ?>
    Mint or issue place: <?php echo $this->escape($this->mintName);?>
    <span class="scope">[<a href="<?php echo $this->url(array(
        'module' => 'earlymedievalcoins',
        'controller'=>'mints',
        'action'=>'mint',
        'id' => $this->mintID),null,true);?>" title="Read scope note for
    <?php echo $this->mintName;?>">scope notes</a> | <a href="
    <?php echo $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'mint' => $this->mintID),null,true);?>" title="view all records assigned to
    <?php echo $this->mintName;?>">view all attributed records</a>]</span><br />
    <?php endif;?>
    <!-- End of mint span --> 
    
    <!-- Start of category span -->
    <?php if(!is_null($this->category)) : ?>
    Category: <?php echo $this->escape($this->category);?> 
    <span class="scope">[
        <a href="<?php echo $this->url(array(
            'module' => 'earlymedievalcoins',
            'controller'=>'categories',
            'action'=>'category',
            'id' => $this->categoryID),null,true);?>" title="Read scope note for
        <?php echo $this->category;?>">scope notes</a> | <a href="<?php echo
        $this->url(array(
            'module' => 'database',
            'controller'=>'search',
            'action'=>'results',
            'category' => $this->categoryID),null,true);?>"
            title="view all records assigned to <?php echo $this->category;?>">
            view all attributed records</a>]</span><br />
    <?php endif;?>
    <!-- End of category span -->

    <!-- Start of type span --> 
    <?php if(!is_null($this->type)) : ?>
    Type: <?php echo $this->escape($this->type);?> <span class="scope">[<a href="
    <?php echo $this->url(array(
        'module' => 'earlymedievalcoins',
        'controller'=>'types',
        'action'=>'type',
        'id' => $this->typeID),null,true);?>" title="Read scope note for <?php echo
        $this->type;?>">scope notes</a> | <a href="<?php echo $this->url(array(
            'module' => 'database',
            'controller'=>'search',
            'action'=>'results',
            'typeID' => $this->typeID),null,true);?>" title="view all records
            assigned to <?php echo $this->type;?>">view all attributed records</a>]
    </span>
    <br />
    <?php endif;?>
    <!-- End of type span --> 

    <!-- Start of obverse --> 
    <?php if(!is_null($this->obverseDescription)) : ?>
    Obverse description: <?php echo $this->obverse_description;?>
    <br />
    <?php endif;?>

    <?php if(!is_null($this->obverseInscription)) : ?>
    Obverse inscription: <?php echo $this->obverse_inscription;?>
    <br />
    <?php endif;?>
    <!-- End of obverse --> 
    
    <!-- Start of reverse --> 
    <?php if(!is_null($this->reverseDescription)) : ?>
    Reverse description: <?php echo $this->reverseDescription;?><br />
    <?php endif;?>

    <?php if(!is_null($this->reverse_inscription)) : ?>
    Reverse inscription: <?php echo $this->reverse_inscription;?><br />
    <?php endif;?>
    <!-- End of reverse --> 

    <!-- Start of reverse mintmark -->
    <?php if(!is_null($this->reverse_mintmark)) :?>
    Reverse mintmark: <?php echo $this->escape($this->reverse_mintmark);?><br />
    <?php endif;?>
    <!-- End of reverse mintmark --> 

    <!-- Start of initial mark --> 
    <?php if(!is_null($this->initial_mark)) :?>
    Initial mark: <?php echo $this->escape($this->initial_mark);?><br />
    <?php endif;?>
    <!-- End of initial mark --> 

    <!-- Start of die axis --> 
    <?php if(!is_null($this->dieAxisName)) : ?>
    Die axis measurement: <?php echo $this->escape($this->die_axis_name);?>
    <span class="scope">[<a href="<?php echo $this->url(array(
        'module' => 'database',
        'controller'=>'terminology',
        'action'=>'dieaxis',
        'id' => $this->die),null,true);?>" title="Read scope note for
    <?php echo $this->die_axis_name;?>">scope notes</a> | <a href="<?php echo
    $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'axis' => $this->die),null,true);?>" title="view all records assigned to
    <?php echo $this->die_axis_name;?>">view all attributed records</a>]</span><br/>
    <?php endif;?>
    <!-- End of die axis --> 
    
    <!-- Start of wear span -->
    <?php if(!is_null($this->wear)) : ?>
    Degree of wear: <?php echo $this->escape($this->wear);?>
    <span class="scope">[<a href="<?php echo $this->url(array(
        'module' => 'database',
        'controller'=>'terminology',
        'action'=>'weartype',
        'id' => $this->wearID),null,true);?>" title="Read scope note for
    <?php echo $this->wear;?>">scope notes</a> | <a href="<?php echo
    $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'wear' => $this->wearID),null,true);?>" title="view all records assigned to
    <?php echo $this->wear;?>">view all attributed records</a>]</span>
    <?php endif;?>
    <!-- End of wear span --> 
</p>