<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 09/12/14
 * Time: 10:46
 */
?>
<?php
$editUrl = $this->url(
    array(
        'module' => 'database',
        'controller' => $this->controller,
        'action' => 'edit',
        'id' => $this->id
    ), null, true);
?>
<?php
$deleteUrl = $this->url(
    array(
        'module' => 'database',
        'controller' => $this->controller,
        'action' => 'delete',
        'id' => $this->id
    ), null, true);
?>
<a class="btn btn-small btn-warning" href="<?php echo $editUrl; ?>" title="Edit details for <?php $this->recordID; ?>"
   accesskey="e">Edit <i class="icon-white icon-edit"></i></a> <a class="btn btn-small btn-danger"
                                                                  href="<?php echo $deleteUrl; ?>"
                                                                  title="Delete record <?php echo $this->recordID; ?>"
                                                                  accesskey="d">Delete <i
        class="icon-white icon-trash"></i></a>