<h2>Large image view and metadata</h2>

<?php
$file = $this->filename;
$path = $this->imagedir;
//Zend_Debug::dump($path);
$location = './'.$this->baseUrl().$path.$file;
$name = substr($file, 0, strrpos($file, '.'));
$ext = '.jpg';
$smalldir = './'.$path.'small/';
$mediumdir = './'.$path.'medium/';
$create_mode = 0777;
if (!is_dir($smalldir) ) {
	mkdir($smalldir, $create_mode, true);
	}
if (!is_dir($mediumdir) ) {
	mkdir($mediumdir, $create_mode, true);
	}
$tempfile = './'.$path.'medium/'.$name.$ext;

$tempfilesmall = './'.$path.'small/'.$name.$ext;

//Zend_Debug::dump($tempfile);
?>

<div id="image">
<?php

if(file_exists($location)) {
?>
<?php
if(file_exists($tempfile)) {
list($w, $h, $type, $attr) = getimagesize('./'.$this->baseUrl().'/'.$path.'medium/'.$name.$ext);
echo '<img src="'.$this->baseUrl().'/'.$path.'medium/'.$name.$ext.'" height="'.$h.'" width="'.$w.'" alt="A resized image of '.$this->label.'" />';
} else {
$phMagick = new phMagick($location, $tempfile);
$phMagick->resize(500,500);
$phMagick->convert();
echo '<img src="'.$this->baseUrl().'/'.$path.'medium/'.$name.$ext.'" alt="A resized image of '.$this->label.'">';
}
$this->metaBaseImage($this->label, $subject = 'archaeology', implode(',',array(
$this->broadperiod,$this->county, $this->objecttype)), $this->serverUrl().'/'.$path.'medium/'.rawurlencode($name).$ext, $w, $h);

?>
<p><a class="btn" href="<?php echo $this->url(array('module' => 'database','controller' => 'ajax','action' => 'download','id' => $this->id),null,true);?>" title="Download image">Download original</a>
<a class="btn" href="<?php echo $this->url(array('module' => 'database','controller' => 'images','action' => 'zoom','id' => $this->id),null,true);?>" title="Zoom this image">Zoom image</a>
<?php echo $this->imagetoolbox()->setID($this->id)->setCreatedBy($this->createdBy)->setInstitution($this->institution);?></p>
</div>


<div class="row-fluid">
	<!--  Navigation for tabs  -->
	<ul id="tab" class="nav nav-tabs">
        <li><a class="active" href="#meta" data-toggle="tab">Metadata</a></li>
        <li><a href="#exif" data-toggle="tab">Exif data</a></li>
        <li><a href="#others" data-toggle="tab">Other sizes</a></li>
	</ul>
	<!--  End of Tabs navigation -->

	<!-- Start of tabbed content div -->
	<div id="myTabContent" class="tab-content">

		<div class="tab-pane fade in active" id="meta">
		<h3>Image meta data</h3>
		<ul>
		<li>Label: <?php echo $this->label;?></li>
		<li>Broadperiod: <?php echo $this->broadperiod;?></li>
		<li>County: <?php echo $this->county;?></li>
		<li>Filesize: <?php echo $this->humanfilesize($this->filesize);?></li>
		<li>Copyright: <?php echo $this->imagerights;?></li>
		<li>License: <?php echo $this->license;?></li>
		</ul>
		</div>

		<div class="tab-pane fade " id="others">
		<h4>Other sizes</h4>
		<?php
		$thumb = './images/thumbnails/'.$this->id.'.jpg';
		if(file_exists($thumb)) { ?>
		<img src="<?php echo $this->baseUrl();?>/images/thumbnails/<?php echo $this->id;?>.jpg" alt="A resized image of <?php echo $this->label;?>"/>
		<?php } else {
		$phMagick = new phMagick($location, $thumb);
		$phMagick->resize(100,0);
		$phMagick->convert();
		//Zend_Debug::dump($phMagick);
		?>
		<img src="<?php echo $this->baseUrl();?>/images/thumbnails/<?php echo $this->id;?>.jpg" alt="A resized image of <?php echo $this->label;?>"/>
		<?php

		}
		?>
		<?php
		if(file_exists($tempfilesmall)) {
		echo '<img src="'.$this->baseUrl().'/'.$path.'small/'.$name.$ext.'" alt="A resized image of '.$this->label.'" />';
		} else {
		$phMagick = new phMagick($location, $tempfilesmall);
		$phMagick->resize(40,0);
		$phMagick->convert();
		//Zend_Debug::dump($phMagick);
		echo '<img src="'.$this->baseUrl().'/'.$path.'small/'.$name.$ext.'" alt="A resized image of '.$this->label.'" />';
		}
		?>
		</div>

        <div class="tab-pane fade" id="exif">
        <h3>Extracted data</h3>
		<ul id="related">
		<?php  $img = getimagesize($location);
		//Zend_Debug::dump($img);
		echo '<li>Width: '.$img['0'] .' pixels </li>';
		echo '<li>Height: '.$img['1'] .' pixels </li>';
		if(isset($img['channels'])){
		echo '<li>Channels: '.$img['channels'] .'</li>';
		}
		if(isset($img['bits'])){
		echo '<li>Bits: '.$img['bits'] .'</li>';
		}
		echo '<li>Mime type: '.$img['mime'] .'</li>';
		if (isset($img["APP13"])) {
		$iptc = iptcparse($img["APP13"]);
		 //   Zend_Debug::dump($iptc);
		}
		if($img['mime'] == 'image/jpeg') {

		$data = new Pas_Exif_Reader($location);
		//Zend_Debug::dump($data->getImageInfo());
		//Zend_Debug::dump($data->getThumbnail());
		if($data->ThumbnailSize > 0) {
			echo "<br /><img src='".$data->getThumbnail()."'>";
		 }
		$exif = exif_read_data($location, 0, true);
		if(isset($exif['FILE'])){
		echo $this->partial('partials/database/exifData.phtml',$exif['FILE']);
		}
		if(isset($exif['COMPUTED'])){
		echo $this->partial('partials/database/exifDataComputed.phtml',$exif['COMPUTED']);
		}
		if(isset($exif['IFD0'])){

		echo $this->partial('partials/database/exifDataIFD0.phtml',$exif['IFD0']);
		}
		if(isset($exif['EXIF'])) {
		$extended = $exif['EXIF'];
		unset($extended['MakerNote']);
		unset($extended['UserComment']);
		foreach($extended as $k => $v) {
		echo '<li>'.$k. ' : '.$v.'</li>';
		}
		}
		}

		 ?>

		</ul>
		</div>



	</div>
	<!--  End of tabbed content div -->

</div>



<?php
} else {?>
<img src="http://farm4.static.flickr.com/3407/3478660349_f8ed50f4d7.jpg" alt="The trip home" class="img img-circle" width="500" height="322" />
<p>Image unavailable just now: <?php echo $this->filename;?></p>
<p>The image above is a CC licenced image by <a href="http://www.flickr.com/photos/kwl/" >Kennymatic</a>.</p>

<?php
}
?>

</div>