<div class="thumbnail well span2" about="thumbnail-<?php echo $this->id;?>">

<?php
	$name = substr($this->filename, 0, strrpos($this->filename, '.'));
	$ext = '.jpg';
	$file = $name . $ext;
?>
<?php 
$thumbnail = './images/thumbnails/' . $this->thumbnail . '.jpg';
if(file_exists($thumbnail)){
list($w, $h, $type, $attr) = getimagesize( $thumbnail );
?>

<a href="/<?php echo $this->imagedir;?>medium/<?php echo $file;?>" rel="lightbox" title="<?php echo $this->label;?>">
<img class="img-polaroid stelae" src="<?php echo $this->baseUrl().'/images/thumbnails/' . $this->thumbnail;?>.jpg"  width="<?php echo $w; ?>"
height="<?php echo $h;?>" alt="PAS record number: <?php echo $this->old_findID;?>" /></a>
          

<?php } else {?>
<img src="/assets/gravatar.png" width="80" height="80" class="img-circle" />
            <p>Image unavailable<br />Error: 404</p>
<?php }?>
<div class="caption">
<p>
Record: <a href="<?php echo $this->url(array('module' => 'database','controller' => 'artefacts',
'action'=>'record','id' => $this->id),null,true);?>" title="PAS record number: <?php echo $this->old_findID;?>"><?php echo $this->old_findID;?></a><br />
Object type: <?php echo $this->objecttype;?><br />
Broadperiod: <?php echo $this->broadperiod;?><br />
Description: <?php echo $this->ellipsisstring($this->description,150);?><br />
Workflow: <?php echo $this->workflowStatus($this->workflow);?><?php echo $this->workflow($this->workflow);?>
</p>
          </div>
</div>