<?php
$materials = array(
        $this->material1, $this->material2, $this->manufacture,
        $this->decoration, $this->style, $this->completeness,
        $this->surface
    );
?>
<?php if(array_filter($materials)):?>
<h4 class="lead">Materials and construction</h4>

<p>
    <?php if (!is_null($this->material1)) : ?>
        Primary material: <span property="pas:primaryMaterial"><?php echo $this->primaryMaterial; ?></span> <span class="scope">[<a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'material', 'id' => $this->material1), NULL, true); ?>"
                title="View scope notes for <?php echo $this->escape($this->mat1); ?>">scope notes</a> | <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'material' => $this->material1), NULL, true); ?>"
                title="Find all records assigned to  <?php echo $this->mat1; ?>">view all attributed records</a>]</span>
        <br/>
    <?php endif; ?>
    <?php if (!is_null($this->material2)) : ?>
        Secondary material: <span property="pas:secondaryMaterial"><?php echo $this->secondaryMaterial; ?></span> <span
            class="scope">[<a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'material', 'id' => $this->material2), NULL, true); ?>"
                title="View scope notes for <?php echo $this->escape($this->mat2); ?>">scope notes</a>| <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'material' => $this->material2), NULL, true); ?>"
                title="Find all records assigned to  <?php echo $this->mat2; ?>">view all attributed records</a>]</span>
        <br/>
    <?php endif; ?>
    <?php if (!is_null($this->manufacture)) : ?>
        Manufacture method: <span property="pas:manufactureMethod"><?php echo $this->manufacture; ?></span> <span
            class="scope">[<a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'manufacture', 'id' => $this->manmethod), NULL, true); ?>"
                title="View scope notes for <?php echo $this->escape($this->manufacture); ?>">scope notes</a> | <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'manufacture' => $this->manmethod), NULL, true); ?>"
                title="Find all records assigned to  <?php echo $this->manufacture; ?>">view all attributed records]</a></span>
        <br/>
    <?php endif; ?>
    <?php if (!is_null($this->decoration)) : ?>
        Decoration method: <span property="pas:decoration"><?php echo $this->decoration; ?></span> <span class="scope">[<a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'decorationmethod', 'id' => $this->decmethod), NULL, true); ?>"
                title="View scope notes for <?php echo $this->escape($this->decoration); ?>">scope notes</a> | <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'decoration' => $this->decoration), NULL, true); ?>"
                title="Find all records assigned to  <?php echo $this->manufacture; ?>">view all attributed records]</a></span>
        <br/>
    <?php endif; ?>
    <?php if (!is_null($this->style)) : ?>
        Decoration style: <span property="pas:decorationStyle"><?php echo $this->style; ?></span> <span
            class="scope">[<a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'decorationstyle', 'id' => $this->decstyle), NULL, true); ?>"
                title="View scope notes for <?php echo $this->escape($this->decoration); ?>">scope notes</a> | <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'decstyle' => $this->decstyle), NULL, true); ?>"
                title="Find all records assigned to  <?php echo $this->style; ?>">view all attributed
                records]</a></span><br/>
    <?php endif; ?>
    <?php if (!is_null($this->completeness)) : ?>
        Completeness: <span
            property="pas:completeness"><?php echo $this->completeness()->setInt($this->complete); ?></span> <span
            class="scope">[<a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'completeness', 'id' => $this->complete), NULL, true); ?>"
                title="View scope notes for <?php echo $this->completeness()->setInt($this->completeness); ?>">scope
                notes</a> | <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'complete' => $this->complete), NULL, true); ?>"
                title="Find all records assigned to  <?php echo $this->completeness()->setInt($this->completeness); ?>">view
                all attributed records]</a></span><br/>
    <?php endif; ?>
    <?php if (!is_null($this->surface)) : ?>
        Surface Treatment: <span property="pas:surfaceTreatment"><?php echo $this->surface; ?></span> <span
            class="scope">[<a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'surface', 'id' => $this->surftreat), NULL, true); ?>"
                title="View scope notes for <?php echo $this->escape($this->surface); ?>">scope notes</a> | <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'surface' => $this->surftreat), NULL, true); ?>"
                title="Find all records assigned to  <?php echo $this->surface; ?>">view all attributed
                records]</a></span>
    <?php endif; ?>
</p>
<?php endif;?>