<?php
$ctrllr = $this->rulerperiod($this->t).'coins';
?>
<tr class="valid-<?php echo $this->valid;?>">
<td><?php echo $this->escape($this->mint_name).'<br /> ' .$this->escape($this->t);?></td>
<td><?php echo $this->timeagoinwords($this->created);?></td>
<td><?php echo $this->namethem($this->fullname);?></td>
<td><?php echo $this->timeagoinwords($this->updated);?></td>
<td><?php echo $this->namethem($this->fn);?></td>
<td><?php echo $this->validity($this->valid);?></td>
<td>
<?php
$edit = $this->Href(array(
    'module' => 'admin',
    'controller' => 'numismatics',
    'action' => 'editmint',
    'checkAcl' => true,
    'acl'=>'Zend_Acl',
    'attribs' => array('title' => 'Edit a mint'),
    'params' => array('id'=>$this->id),
    'content'=> 'Edit')
    );
$delete = $this->Href(array(
    'module' => 'admin',
    'controller' =>'numismatics',
    'action' =>'deletemint',
    'checkAcl' => true,
    'acl' => 'Zend_Acl',
    'attribs' => array('title' => 'Delete a mint'),
    'params' => array('id'=>$this->id),
    'content' => 'Delete')
    );

echo implode(' | ', array($edit, $delete));
?>
</td>
</tr>
