<?php $this->headScript()->captureStart() ?>
function load () {	
if (GBrowserIsCompatible()) {


        var map = new GMap2(document.getElementById("mapobjects"));
	
	    map.addControl(new GSmallMapControl());
		map.addControl(new GMenuMapTypeControl());
		//map.addControl (new GHierarchicalMapTypeControl());
		map.addMapType(G_PHYSICAL_MAP);
        map.setCenter(new GLatLng(52.6164, -1.0547), 5 , G_PHYSICAL_MAP);
		map.enableContinuousZoom();
		map.addControl(new GScaleControl());
      var n=0;

      var icon = new GIcon();
      icon.image = "http://labs.google.com/ridefinder/images/mm_20_red.png";
      icon.shadow = "http://labs.google.com/ridefinder/images/mm_20_shadow.png";
      icon.iconSize = new GSize(12, 20);
      icon.shadowSize = new GSize(22, 20);
      icon.iconAnchor = new GPoint(6, 20);
      icon.infoWindowAnchor = new GPoint(5, 1);      

      iconblue = new GIcon(icon,"http://labs.google.com/ridefinder/images/mm_20_blue.png"); 
      icongreen = new GIcon(icon,"http://labs.google.com/ridefinder/images/mm_20_green.png"); 
      iconyellow = new GIcon(icon,"http://labs.google.com/ridefinder/images/mm_20_yellow.png"); 


      function createMarker(point,name,html,icon) {
        var marker = new GMarker(point, {icon:icon});
        GEvent.addListener(marker, "click", function() {
          marker.openInfoWindowHtml(html);
        });
        return marker;
      }



      // read the markers from the XML
      GDownloadUrl("<?php echo $this->baseUrl();?>/ajax/mapdata/ruler/<?php echo $this->pasID;?>", function (doc) {
        var gmarkersA = [];      
        var gmarkersB = [];      
        var xmlDoc = GXml.parse(doc);
        var markers = xmlDoc.documentElement.getElementsByTagName("marker");

          
        for (var i = 0; i < markers.length; i++) {
          // obtain the attribues of each marker
          var lat = parseFloat(markers[i].getAttribute("lat"));
          var lng = parseFloat(markers[i].getAttribute("lng"));
          var point = new GLatLng(lat,lng);
          var objectname = markers[i].getAttribute("name");
          var type = markers[i].getAttribute("type");
          var broadperiod = markers[i].getAttribute("broadperiod");

          // split the markers into four arrays, with different GIcons
          if (type == 'coin') {
             var marker = createMarker(point,objectname,broadperiod+"Name: +objectname<br />Type: "+type,icon);
             gmarkersA.push(marker);
          }
          else  {
             var marker = createMarker(point,objectname,broadperiod+"Name: +objectname<br />Type: "+type,iconblue);
             gmarkersB.push(marker);
          }
        }

     
        var mm = new GMarkerManager(map, {borderPadding:1});

        mm.addMarkers(gmarkersA,0,17);
        mm.addMarkers(gmarkersB,10,17);
        mm.refresh();
		
      });
		
    }

    // display a warning if the browser was not compatible
    else {
      alert("Sorry, the Google Maps API is not compatible with this browser");
    }
    
    //</XMLCDATA>
	}

window.onload = load;
window.onunload = GUnload;

<?php $this->headScript()->captureEnd() ?>
<div id="mapobjects"></div>