<?php if(!is_null($this->smrRef) || !is_null($this->otherRef) || !is_null($this->musaccno)):?>
<h4>
    Other reference numbers
</h4>
<p>
    <?php if(!is_null($this->smr_ref)) :?>
    SMR reference number: <?php echo $this->smrRef;?><br />
    <?php endif;?>
    
    <?php if(!is_null($this->other_ref)):?>
    Other reference: <?php echo $this->otherRef;?><br />
    <?php endif;?>
    
    <?php if(!is_null($this->musaccno)):?>
    Museum accession number: <?php echo $this->musaccno;?>
    <?php endif;?>
</p>
<?php endif;?>