<?php if(!is_null($this->smr_ref) || !is_null($this->other_ref) 
|| !is_null($this->treasureID || !is_null($this->musaccno))):?>
<h4>Other reference numbers</h4>
<p>
<?php if(isset($this->smr_ref)|| ($this->smr_ref != '')):?>
SMR reference number: <?php echo $this->escape($this->smr_ref);?><br />
<?php endif;?>
<?php if(isset($this->other_ref)):?>
Other reference: <?php echo $this->escape($this->other_ref);?><br />
<?php endif;?>
<?php if(isset($this->treasureID)):?>
Treasure case number: <?php echo $this->escape($this->treasureID);?><br />
<?php endif;?>
<?php if(isset($this->musaccno)):?>
Museum accession number: <?php echo $this->escape($this->musaccno);?>
<?php endif;?>
</p>
<?php endif;?>