<?php
$numbers = array( $this->smrRef, $this->otherRef, $this->treasureID, $this->museumAccession);
if(array_filter($numbers)):?>
    <h4 class="lead">Other reference numbers</h4>
    <p>
        <?php if (!is_null($this->smrRef)): ?>
            SMR reference number: <?php echo $this->smrRef; ?><br/>
        <?php endif; ?>
        <?php if (!is_null($this->otherRef)): ?>
            Other reference: <?php echo $this->otherRef; ?><br/>
        <?php endif; ?>
        <?php if (!is_null($this->treasureID)): ?>
            Treasure case number: <?php echo $this->treasureID; ?><br/>
        <?php endif; ?>
        <?php if (!is_null($this->musaccno)): ?>
            Museum accession number: <?php echo $this->museumAccession; ?>
        <?php endif; ?>
    </p>
<?php endif;?>