<tr class="valid-<?php echo $this->valid;?>">
<td><a href="<?php echo $this->url(array(
'module' => 'database','controller'=>'terminology','action'=>'period', 'id'=>$this->id),null,true);?>" title="View details for the <?php echo $this->term;?> period"><?php echo $this->escape($this->term);?></a></td>
<td><?php echo $this->adbc($this->fromdate);?></td>
<td><?php echo $this->adbc($this->todate);?></td>
</tr>