<?php $this->headTitle('Details for the ' . $this->escape(ucfirst($this->term)) . ' period');?>
<h2><?php echo $this->title();?></h2>
<p>Date range: <?php echo $this->adbc($this->fromdate);?> to <?php echo $this->adbc($this->todate);?></p>
<p>Notes: </p> <?php echo $this->notes;?>

<h3>Linked data</h3>
<ul>
<?php if(!is_null($this->ehTerm)):?>
<li>SENESCHAL URI: <a href="http://purl.org/heritagedata/schemes/eh_period/concepts/<?php echo $this->ehTerm;?>">http://purl.org/heritagedata/schemes/eh_period/concepts/<?php echo $this->ehTerm;?></a></li>
<?php endif;?>
<?php if(!is_null($this->bmID)):?>
<li>British Museum URI: <a href="http://collection.britishmuseum.org/id/thesauri/x<?php echo $this->bmID;?>">http://collection.britishmuseum.org/id/thesauri/x<?php echo $this->bmID;?></a></li>
<?php endif;?>
</ul>
