<?php
$people = array($this->finder, $this->recorder, $this->identifier, $this->secondaryIdentifier);
if (array_filter($people)):?>
    <h4 class="lead">Personal details</h4>

    <p>
        <?php
        if (isset($this->finderID)) {
            $auth = Zend_Registry::get('auth');
            if ($auth->hasIdentity()) {
                $user = $auth->getIdentity();
                {
                    $allowed = array('fa', 'admin', 'flos', 'hero', 'treasure');
                    if (in_array($user->role, $allowed)) {
                        ?>
                        Found by: <span property="pas:finder foaf:name"
                                        instanceof="foaf:person"><?php echo $this->finder; ?></span> - <span
                            class="scope">[<a href="
<?php echo $this->url(array('module' => 'database', 'controller' => 'search',
                                'action' => 'results', 'finderID' => $this->finderID), null, true);?>"
                                              title="View other discoveries">view other discoveries by this finder</a>]</span>
                        <br/>
                    <?php
                    }
                }
            } else {
                ?>
                Found by: This information is restricted for your login. <br/>
            <?php
            }
        }
        ?>

        <?php if (!is_null($this->recorderID)) : ?>
            Recorded by: <span property="pas:recorder foaf:name" instanceof="foaf:person"><?php echo
                $this->recorder; ?></span>
            - <span class="scope">[
<a href="<?php echo $this->url(array(
    'module' => 'database',
    'controller' => 'search',
    'action' => 'results',
    'recorderID' => $this->recorderID), null, true);?>"
   title="Search database for all records recorded by <?php echo $this->recorderID; ?>">view all attributed records</a>]
</span><br/>
        <?php endif; ?>

        <?php if (!is_null($this->identifier1ID)) : ?>
            Identified by: <span property="pas:identifier foaf:name"
                                 instanceof="foaf:person"><?php echo $this->identifier; ?></span> - <span class="scope">[<a
                    href="
        <?php echo $this->url(array(
                        'module' => 'database',
                        'controller' => 'search',
                        'action' => 'results',
                        'identifierID' => $this->identifier1ID), null, true);?>" title="Search database for
    all records identified by <?php echo $this->identifier; ?>">view all attributed records</a>]</span><br/>
        <?php endif; ?>

        <?php if (!is_null($this->identifier2ID)) : ?>
            Secondary identifier: <span property="pas:identifierSecondary foaf:name"
                                        instanceof="foaf:person">
<?php echo $this->secondaryIdentifier; ?></span> - <span class="scope">[<a href="
 <?php echo $this->url(array(
                    'module' => 'database',
                    'controller' => 'search',
                    'action' => 'results',
                    'identifier2ID' => $this->identifier2ID), null, true);?>" title="Search database for
     all records identifed by <?php echo $this->secondaryIdentifier; ?>">view all attributed records</a>]</span><br/>
        <?php endif; ?>
    </p>
<?php endif; ?>