<?php
/** A partial for displaying post medieval data 
 * @author Daniel Pett <dpett at britishmuseum.org>
 * @copyright  Copyright (c) 2014 dpett @ britishmuseum.org
 * @version 1
 * @license http://www.gnu.org/licenses/agpl-3.0.txt GNU Affero GPL v3.0
 */
?>
<h4>
    Coin data (numismatics)
</h4>

    <?php 
        echo $this->CoinEditDeleteLink()
                ->setFindID($this->id)
                ->setBroadperiod($this->broadperiod)
                ->setSecuID($this->secuid)
                ->setInstitution($this->institution)
                ->setCreatedBy($this->createdBy);
    ?>

<p>
    <!-- Start of denomination span --> 
    <?php if(!is_null($this->d)) : ?>
    Denomination: <?php echo $this->escape($this->d);?> <span class="scope">[
    <a href="<?php echo $this->url(array(
        'module'=>'postmedievalcoins',
        'controller' => 'denominations',
        'action'=>'denomination',
        'id' => $this->denom),null,true);?>" title="Read scope note for <?php
        echo $this->d;?>">scope notes</a> |  <a href="<?php
        echo $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'denomination' => $this->denom),null,true);?>"
        title="view all records assigned to denomination:
        <?php echo $this->d;?>">view all attributed records</a>]</span><br />
    Denomination certainty: <?php echo $this->certainty()->setCertainty($this->denominationQualifier);?>
    <br />
    <?php endif;?>
    <!-- End of denomination span -->

    <!-- Start of ruler span --> 
    <?php if(!is_null($this->ruler1)) : ?>
    Ruler/issuer: <?php echo $this->escape($this->ruler1);?> <span class="scope">[
        <a href="<?php echo $this->url(array(
            'module'=>'postmedievalcoins',
            'controller' => 'rulers',
            'action'=>'ruler',
            'id' => $this->ruler_id),null,true);?>" title="Read scope note for
        <?php echo $this->ruler1;?>">scope notes</a> | <a href="<?php
        echo $this->url(array(
            'module' => 'database',
            'controller' => 'search',
            'action'=>'results',
            'ruler' => $this->ruler_id),null,true);?>"
            title="view all records assigned to <?php echo $this->ruler1;?>">
            view all attributed records</a>]</span><br />
    <?php endif;?>
    <?php if(!is_null($this->rulerQualifier)):?>
    Ruler certainty: <?php echo $this->certainty()->setCertainty($this->rulerQualifier);?>
    <br />
    <?php endif;?>
    <!-- End of ruler span --> 

    <!-- Start of mint span --> 
    <?php if(!is_null($this->mintName)) : ?>
    Mint or issue place: <?php echo $this->escape($this->mintName);?>
    <span class="scope">[<a href="<?php echo $this->url(array(
        'module'=>'postmedievalcoins',
        'controller' => 'mints',
        'action'=>'mint',
        'id' => $this->mintID),null,true);?>" title="Read scope note for
    <?php echo $this->mintName;?>">scope notes</a> | <a href="<?php echo
    $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'mint' => $this->mintID),null,true);?>" title="view all records assigned to
    <?php echo $this->mintName;?>">view all attributed records</a>]</span>
    <br />
    <?php endif;?>
    Mint certainty: <?php echo $this->certainty()->setCertainty($this->mintQualifier);?>
    <br />
    <!-- End of mint span --> 

    <!-- Start of category --> 
    <?php if(!is_null($this->category)) : ?>
    Category: <?php echo $this->escape($this->category);?> <span class="scope">[
        <a href="<?php echo $this->url(array(
        'module'=>'postmedievalcoins',
        'controller' => 'categories',
        'action'=>'category',
        'id' => $this->categoryID),null,true);?>"
    title="Read scope note for <?php echo $this->category;?>">scope notes</a> |
    <a href="<?php echo $this->url(array(
        'module'=>'database',
        'controller' => 'search',
        'action'=>'results',
        'category' => $this->categoryID),null,true);?>"
    title="view all records assigned to <?php echo $this->category;?>">
        view all attributed records</a>]</span><br />
    <?php endif;?>
    <!-- End of category --> 
    
    <!-- Start of type span --> 
    <?php if(!is_null($this->type)) : ?>
    Type: <?php echo $this->escape($this->type);?> <span class="scope">[<a href="
    <?php echo $this->url(array(
        'module'=>'postmedievalcoins',
        'controller' => 'types',
        'action'=>'type',
        'id' => $this->typeID),null,true);?>" title="Read scope note for
    <?php echo $this->type;?>">scope notes</a> | <a href="<?php
    echo $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'typeID' => $this->typeID),null,true);?>" title="view all records assigned to
    <?php echo $this->type;?>">view all attributed records</a>]</span><br />
    <?php endif;?>
    <!-- End of type span --> 

    <!-- Start of obverse --> 
    <?php if(!is_null($this->obverseDescription)) : ?>
    Obverse description: <?php echo $this->obverseDescription;?>
    <br />
    <?php endif;?>

    <?php if(!is_null($this->obverseInscription)) : ?>
    Obverse inscription: <?php echo $this->obverseInscription;?>
    <br />
    <?php endif;?>
    <!-- End of obverse -->
    
    <!-- Start of reverse --> 
    <?php if(!is_null($this->reverseDescription)) : ?>
    Reverse description: <?php echo $this->reverseDescription;?>
    <br />
    <?php endif;?>

    <?php if(!is_null($this->reverseInscription)) : ?>
    Reverse inscription: <?php echo $this->reverseInscription;?><br />
    <?php endif;?>
    <!-- End of reverse -->
    
    <!-- Start of reverse mintmark span --> 
    <?php if(!is_null($this->reverseMintmark)) :?>
    Reverse mintmark: <?php echo $this->escape($this->reverseMintmark);?><br />
    <?php endif;?>
    <!-- End of mint mark span -->
    
    <!-- Start of initial mark -->
    <?php if(!is_null($this->initialMark)) :?>
    Initial mark: <?php echo $this->escape($this->initialMark);?><br />
    <?php endif;?>
    <!-- End of initial mark -->

    <!-- Start of die axis name --> 
    <?php if(!is_null($this->dieAxisName)) : ?>
    Die axis measurement: <?php echo $this->escape($this->dieAxisName);?>
    <span class="scope">[<a href="<?php echo $this->url(array(
        'module' => 'database',
        'controller'=>'terminology',
        'action'=>'dieaxis',
        'id' => $this->dieAxis),null,true);?>" title="Read scope note for
    <?php echo $this->dieAxisName;?>">scope notes</a> | <a href="<?php
    echo $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'axis' => $this->dieAxis),null,true);?>" title="view all records assigned to
    <?php echo $this->dieAxisName;?>">view all attributed records</a>]</span>
    <br />
    Die certainty: <?php echo $this->certainty()->setCertainty($this->dieAxisCertainty);?>
    <br />
    <?php endif;?>
    <!-- End of axis --> 

    <!-- Start of wear -->
    <?php if(!is_null($this->wear)) : ?>
    Degree of wear: <?php echo $this->escape($this->wear);?> <span class="scope">[
        <a href="<?php echo $this->url(array(
        'module' => 'database',
        'controller'=>'terminology',
        'action'=>'weartype',
        'id' => $this->wearID),null,true);?>" title="Read scope note for
        <?php echo $this->wear;?>">scope notes</a> | <a href="<?php
        echo $this->url(array(
        'module' => 'database',
        'controller'=>'search',
        'action'=>'results',
        'wear' => $this->wearID),null,true);?>"
        title="view all records assigned to <?php echo $this->wear;?>">
            view all attributed records</a>]</span>
    <?php endif;?>
    <!-- End of wear --> 
</p>