<li class="previous"><a href="<?php echo $this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record','id' => $this->escape($this->id)),null,true);?>" title="View previous record">&larr; <?php echo $this->escape($this->old_findID). ' : ' .$this->escape(ucfirst(strtolower($this->broadperiod))).' '.$this->escape(strtolower($this->objecttype)) ; ?></a></li>
<?php 
$this->headLink(array(
            'rel' => 'prev',
            'href' => $this->serverUrl() . $this->url(array('module' => 'database','controller' => 'artefacts','action' => 'record','id' => $this->escape($this->id)),null,true),
            'APPEND')
);?>