<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 13/11/14
 * Time: 10:42
 */
$url = array('module' => 'datalabs', 'controller' => 'smr', 'action' => 'record', 'id' => $this->id);
?>
<li>
    This object was found within 250 metres of <a href="<?php echo $this->url($url, 'default', true); ?>"
       title="View details for <?php echo $this->monumentName; ?>"><?php echo $this->monumentName; ?></a>,
    from <?php echo $this->county; ?>
</li>