<tr>
    <td>
        <a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'rallies', 'action' => 'rally', 'id' => $this->escape($this->id)), null, true); ?>"
           title="View all details for <?php echo $this->escape($this->rally_name); ?>"><?php echo $this->escape($this->rally_name); ?></a>
    </td>
    <td>
        <?php echo $this->niceShortDate()->setDate($this->date_from); ?>
    </td>
    <td>
        <?php if(!is_null($this->date_to)):?>
        <?php echo $this->niceShortDate()->setDate($this->date_to); ?>
        <?php else:?>
            <?php echo $this->niceShortDate()->setDate($this->date_from); ?>

        <?php endif;?>
    </td>

</tr>