<?php
/** A partial for displaying who the relevant finds adviser is for a record
 * @author Daniel Pett <dpett at britishmuseum.org>
 * @copyright  Copyright (c) 2014 dpett @ britishmuseum.org
 * @license http://www.gnu.org/licenses/agpl-3.0.txt GNU Affero GPL v3.0
 * @version 1
 */
$this->headTitle('Submit an error report on ' . $this->old_findID);
$this->headMeta('Using the form on this page, an error report can be submitted
    for the record : ' . $this->old_findID,'description');
?>
<h2 class="lead">
    Report an error about record: <?php echo $this->old_findID;?>
</h2>
<p>
    Thank you for taking the time to report an error about this find. The error
    report will be sent to: <br />
    <?php echo $this->relevantAdviser()
            ->setObjectType($this->objecttype)
            ->setBroadperiod($this->broadperiod);
    ?>
</p>