<?php
/** A partial for displaying roman coin data
 * @author Daniel Pett <dpett at britishmuseum.org>
 * @copyright  Copyright (c) 2014 dpett @ britishmuseum.org
 * @license http://www.gnu.org/licenses/agpl-3.0.txt GNU Affero GPL v3.0
 * @version 1
 */
?>
<h4>
    Coin data (numismatics)
</h4>
<?php echo $this->CoinEditDeleteLink()
        ->setFindID($this->id)
        ->setBroadperiod($this->broadperiod)
        ->setSecuID($this->secuid)
        ->setInstitution($this->institution)
        ->setCreatedBy($this->createdBy);
?>
<div class="awld-scope">
    <p>

        <!-- Start of denomination span -->
        <?php if(!is_null($this->denomination)) : ?>
        Denomination: <span property="nm:denomination"><?php echo $this->denomination;?></span> 
        <span class="scope">[<a href="<?php echo $this->url(array(
            'module' => 'romancoins',
            'controller'=>'denominations',
            'action'=>'denomination',
            'id' => $this->denominationID),
                null,true);?>" title="Read scope note for 
                    <?php echo $this->denomination;?>">scope notes</a> | 
                    <a href="<?php echo $this->url(array(
                        'module' => 'database',
                        'controller' => 'search',
                        'action'=>'results',
                        'denomination' => $this->denominationID),
                            null,true);?>" title="view all records assigned to denomination: 
                                <?php echo $this->denomination;?>">view all attributed records</a>]</span>
        <br />
        Denomination certainty: <?php echo $this->certainty()->setCertainty($this->denominationQualifier);?>
        <br />
        <?php endif;?>
        <!-- end of denomination span -->

        <!-- Start of ruler span -->
        <?php if(!is_null($this->ruler1)) : ?>
        Ruler/issuer: <span property="nm:issuer" rel="owl:samesAs" resource="http://dbpedia.org/page/<?php echo $this->dbpedia;?>"><?php echo $this->escape($this->ruler1);?></span> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'romancoins','controller'=>'emperors','action'=>'emperor','id' => $this->empid),null,true);?>" title="Read scope note for <?php echo $this->period_name;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','ruler' => $this->ruler_id),null,true);?>" title="view all records assigned to <?php echo $this->ruler1;?>">view all attributed records</a>]</span><br />
        <?php endif;?>
        <?php if(!is_null($this->rulerQualifier)):?>
        Ruler certainty: <?php echo $this->certainty()->setCertainty($this->rulerQualifier);?><br />
        <?php endif;?>
        <!-- End of ruler span -->

        <!-- Start of reece period span -->
        <?php if(!is_null($this->periodName)) : ?>
        Reece period: <span property="pas:reecePeriod"><?php echo $this->escape($this->periodName);?></span> <?php echo '['. $this->escape($this->dateRange).']';?> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'romancoins','controller' => 'reeceperiods',
        'action'=>'period','id' => $this->reeceID),null,true);?>" title="Read scope note for <?php echo $this->periodName;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search',
        'action'=>'results','reeceID' => $this->reeceID),null,true);?>" title="view all records assigned to <?php echo $this->periodName;?>">view all attributed records</a>]</span><br />
        <?php endif;?>
        <!-- End of reece period span -->

        <!-- Start of mint span -->    
        <?php if(!is_null($this->mintName)) : ?>
        Mint or issue place: 
        <span property="skos:related" resource="http://pleiades.stoa.org/places/<?php echo $this->pleiadesID;?>"><?php echo $this->escape($this->mintName);?></span> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'romancoins','controller' => 'mints','action'=>'mint','id' => $this->mintID),null,true);?>" title="Read scope note for <?php echo $this->mintName;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','mint' => $this->mintID),null,true);?>" title="view all records assigned to <?php echo $this->mintName;?>">view all attributed records</a>]</span>
        <?php if(!is_null($this->pleiadesID)):?>
        <!-- The pelagios span -->
        <?php
        //$this->inlineScript()->appendFile('http://pelagios.github.com/pelagios-widgets/lib/require.js',$type = 'text/javascript');
        //$this->inlineScript()->appendFile('http://pelagios.github.com/pelagios-widgets/place.js',$type = 'text/javascript');
        ?>
        <span id="pelagios" data-pleiades_id="<?php echo $this->pleiadesID;?>" class="pelagios pelagios-place"></span>
        <?php endif;?>
        <!-- End of Pelagios --> 
        <br />
        Mint certainty: <?php echo $this->certainty()->setCertainty($this->mintQualifier);?>
        <br />
        <?php endif;?>
        <!-- End of mint span -->

        <!-- Start of obverse -->
        <div rel="obverse">
        <?php if(!is_null($this->obverseDescription)) : ?>
        Obverse description: <span property="description"><?php echo $this->obverseDescription;?></span>
        <br />
        <?php endif;?>
        <?php if(!is_null($this->obverseInscription)) : ?>
        Obverse inscription: <span property="legend"><?php echo $this->obverseInscription;?></span>
        <br />
        <?php endif;?>
        </div>
        <!-- End of obverse -->

        <!-- Start of reverse -->
        <div rel="reverse">
        <?php if(!is_null($this->reverseDescription)) : ?>
        Reverse description: <span property="description"><?php echo $this->reverseDescription;?></span>
        <br />
        <?php endif;?>
        <?php if(!is_null($this->reverseInscription)) : ?>
        Reverse inscription: <span property="legend"><?php echo $this->reverseInscription;?></span>
        <br />
        <?php endif;?>
        </div>
        <!-- End of reverse -->

        <!-- Die axis span --> 
        <?php if(!is_null($this->dieAxis)) : ?>
        Die axis measurement: <span property="nm:axis"><?php echo $this->escape($this->dieAxis);?></span> o'clock<span class="scope">[<a href="<?php echo $this->url(array('module' => 'database','controller'=>'terminology','action'=>'dieaxis','id' => $this->dieAxis),null,true);?>" title="Read scope note for <?php echo $this->dieAxis?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','axis' => $this->dieAxis),null,true);?>" title="view all records assigned to <?php echo $this->dieAxis;?>">view all attributed records</a>]</span>
        <br />
        Die certainty: <?php echo $this->certainty()->setCertainty($this->dieAxisCertainty);?>
        <br />
        <?php endif;?>
        <!-- End of die axis span --> 

        <!-- Start of wear --> 
        <?php if(!is_null($this->wear)) : ?>
        Degree of wear: <span property="pas:degreeOfWear"><?php echo $this->escape($this->wear);?></span> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'database','controller'=>'terminology','action'=>'weartype','id' => $this->wearID),null,true);?>" title="Read scope note for <?php echo $this->wear;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','wear' => $this->wearID),null,true);?>" title="view all records assigned to <?php echo $this->wear;?>">view all attributed records</a>]</span><br />
        <?php endif;?>
        <!-- End of wear --> 

        <!-- Moneyer name span --> 
        <?php if(!is_null($this->name)) : ?>
        Republican moneyer: <?php echo $this->escape($this->name);?> <span class="scope">[<a href="<?php echo $this->url(array('module'=>'romancoins','controller' => 'moneyers',
        'action'=>'called','by' => $this->moneyer),null,true);?>" title="Read scope note for <?php echo $this->name;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search',
        'action'=>'results','moneyer' => $this->moneyer),null,true);?>" title="view all records assigned to <?php echo $this->name;?>">view all attributed records</a>]</span><br />
        <?php endif;?>
        <!-- End of moneyer name span --> 

        <!-- Reverse type ID span --> 
        <?php if(!is_null($this->revtypeID) ) : ?>
        Fourth Century reverse type: <?php echo $this->escape($this->revname);?> <span class="scope">[<a href="<?php echo $this->url(array('module' => 'romancoins','controller'=>'reversetypes','action'=>'type','id' => $this->revtypeID),null,true);?>" title="Read scope note for <?php echo $this->name;?>">scope notes</a> | <a href="<?php echo $this->url(array('module' => 'database','controller'=>'search','action'=>'results','reverse' => $this->revtypeID),null,true);?>" title="view all records assigned to <?php echo $this->revname;?>">view all attributed records</a>]</span><br />
        <?php endif;?>
        <!-- End of reverse type ID --> 

        <!-- Reverse mintmark -->
        <?php if(!is_null($this->reverse_mintmark)):?>
        Reverse mintmark: <span property="pas:reverseMintMark"><?php echo $this->reverse_mintmark;?></span><br />
        <?php endif;?>
        <!-- End of reverse mint mark --> 

        <!-- Start of coin status span --> 
        <?php if(!is_null($this->status)):?>
        Status: <span property="pas:status"><?php echo $this->status;?></span> 
        <br />
        Status certainty: <?php echo $this->certainty()->setCertainty($this->statusQualifier);?>
        <br />
        <?php endif;?>
        <!-- End of status --> 
    </p>
</div>