<?php
$action = $this->term;
switch ($action) {
		case $action == strtoupper('Roman'):
			$actionset = 'emperor';
			$module = 'romancoins';
			break;
		case $action == strtoupper('Byzantine'):
			$module = 'byzantinecoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Greek and Roman Provincial');
			$module = 'greekromancoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Post Medieval'):
			$module = 'postmedievalcoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Early Medieval'):
			$module = 'earlymedievalcoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('Iron Age'):
			$module = 'ironagecoins';
			$actionset = 'ruler';
			break;
		case $action == strtoupper('medieval');
			$module = 'medievalcoins';
			$actionset = 'ruler';
			break;
			default:
			$actionset = 'ruler';
			$module = 'medievalcoins';
	}
	if($this->term == 'ROMAN'){
		$id = $this->pasID;
	} else {
		$id = $this->id;
	}
	?>
<tr>
<td><a href="<?php echo $this->url(array('module' => $module,'controller' => $actionset.'s' ,'action' => $actionset,'id' => $id),null,true);?>"><?php echo $this->issuer;?></a></td>
<td><a href="<?php echo $this->url(array('module' => 'database','controller' => 'terminology','action' => 'period','id' => $this->i),null,true);?>"><?php echo $this->term;?></a></td>
<td><?php echo $this->adbc($this->date1) . ' ' . $this->adbc($this->date2);?></td> 
</tr>
