<?php
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/typeaheads/objectType.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/typeaheads/treasureID.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/typeaheads/otherRef.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/typeaheads/finder.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/typeaheads/primaryID.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/typeaheads/recorder.js', $type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/typeaheads/secondaryID.js', $type='text/javascript');

    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/bootstrap-datepicker-v1.9.0.js',$type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/jQueryLinkedSelect.js',$type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/findSpotLinkedSelect.js',$type='text/javascript');
    $this->jQuery()->addJavascriptFile($this->baseUrl()
            . '/js/JQuery/findSpotLinkedQuery.js',$type='text/javascript');
    $this->headLink()->appendStylesheet('/css/bootstrap-datepicker.css');


    $this->headTitle('Advanced search the database');
    $this->metaBase()
            ->setDescription('A complex form generating highly targeted searches')
            ->setSubject('Search the PAS database')
            ->setKeywords('search,database,coin,artefact,form')
            ->generate();
?>

<!-- Instantiate datepicker -->
<?php $this->jQuery()->javascriptCaptureStart() ?>
    $(document).ready(function() {
        $datePickerSettings = {
            endDate: '0d',
            format: 'yyyy-mm-dd',
            assumeNearbyYear: true
        };
        $("#createdBefore").datepicker($datePickerSettings);
        $("#createdAfter").datepicker($datePickerSettings);
        $("#updatedBefore").datepicker($datePickerSettings);
        $("#updatedAfter").datepicker($datePickerSettings);
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<h2 class="lead">
    <?php echo $this->title();?>
</h2>

<p>
    This form allows you to perform some more advanced database searches. More 
    specific numismatic searching can be affected from period specific forms.
</p>

<div>
    <?php echo $this->form;?>
</div>