<?php 
$this->headMeta('You can email your last search result to another person 
    directly from our server','description');
$this->headTitle('Email your last search to another person');?>
<h2>Email your last search</h2>
<?php echo $this->SearchParams($this->params);?>

<p>Using the form below, you can email your last search that you performed to 
    another person. We cannot guarantee that the email will bypass individual 
    network administrative rules or your own spam filter.</p>
<?php echo $this->form;?>