<?php
$this->headTitle('Saved searches available');
$this->metaBase()->setDescription('A list of saved searches available to you.')
    ->setKeywords('searches, examples, saved, database')
    ->generate();
?>

<h2 class="lead">
    Saved searches
</h2>
<?php if ($this->data): ?>
        <?php echo $this->partialLoop('partials/users/searchDBList.phtml', $this->data) ?>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>No search history available to you at present.</p>
<?php endif; ?>