<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 29/10/14
 * Time: 11:58
 */
$this->headTitle('Search coin summaries from hoards');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/hoardPeriodLinkedSelect.js', $type='text/javascript');

$this->headLink()->appendStylesheet('//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css', 'screen');
$this->metaBase()->setDescription('A search form for interrogating coin summaries attached to hoard records')
    ->setKeywords('hoard,search,summaries')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php echo $this->form;?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {

$('#broadperiod').linkedSelect('/ajax/lastruler','#ruler',{firstOption: 'Please select a ruler'});
$('#broadperiod').linkedSelect('/ajax/getdenominations','#denomination',{firstOption: 'Please select a denomination'});
$('#broadperiod').linkedSelect('/ajax/getmints','#mint',{firstOption: 'Please select a mint'});
$('#broadperiod').linkedSelect('/database/ajax/getgeography','#geography',{firstOption: 'Please select a geography'});
var rulerPeriods = ['IRON AGE', 'EARLY MEDIEVAL', 'MEDIEVAL', 'POST MEDIEVAL', 'BYZANTINE',
'GREEK AND ROMAN PROVINCIAL'];

var IA = ['IRON AGE'];


$('select[name="broadperiod"]').on('change',function(){
$('#ruler_id').select2('val', 'All');
$('#mint_id').select2('val', 'All');
$('#denomination').select2('val', 'All');
$('#geographyID').select2('val', 'All');

var period = $(this).val();
if(jQuery.inArray(period, rulerPeriods) !== -1) {
console.log('In ruler array');

}
if (jQuery.inArray(period, IA) !== -1) {
$('#ruler_id').linkedSelect('/ajax/iageography','#geographyID',{firstOption: 'Please select a ruler'});
console.log('In IA array');
}
});
});

<?php $this->jQuery()->javascriptCaptureEnd(); ?>
