<tr>
<td>
<?php
if(!is_null($this->institution)) { 
echo '<a href="'.$this->url(array(
    'module' => 'database',
    'controller' => 'statistics',
    'action' => 'institution',
    'institution' => $this->institution),null,false) 
. '" title="View stats for this institution">' . $this->institution . '</a>';
} else {
echo 'No institition recorded';
}
?>
</td>
<td><?php echo $this->finds;?></td>
<td><?php echo $this->records;?></td>
</tr>