<tr>
    <td>
        <?php if (!is_null($this->institution)): ?>
            <?php
            $url = array(
                'module' => 'database', 'controller' => 'statistics', 'action' => 'institution',
                'institution' => $this->institution
            );
            ?>
            <a href="<?php echo $this->url($url, null, false); ?>"
               title="View stats for this institution"><?php echo $this->institution; ?></a>
        <?php else: ?>
            No institution recorded.
        <?php endif; ?>
    </td>
    <td><?php echo $this->finds; ?></td>
    <td><?php echo $this->records; ?></td>
</tr>