<tr>
    <td>
        <?php if (!is_null($this->county)): ?>
            <a href="<?php echo $this->url(array(
                'module' => 'database',
                'controller' => 'statistics',
                'action' => 'county',
                'institution' => $this->county
            ), null, false); ?>" title="View stats for <?php echo $this->county; ?>"><?php echo $this->county; ?></a>
        <?php else: ?>
            No institution recorded
        <?php endif; ?>
    </td>
    <td><?php echo $this->finds; ?></td>
    <td><?php echo $this->records; ?></td>
</tr>