<tr>
    <td>
        <?php if (!is_null($this->region)): ?>
            <a href="<?php echo $this->url(array(
                'module' => 'database',
                'controller' => 'statistics',
                'action' => 'regional',
                'region' => $this->id), null, false);
            ?>"
               title="View stats for this institution"><?php echo $this->region; ?></a>
        <?php else: ?>
            No region recorded
        <?php endif; ?>
    </td>
    <td><?php echo $this->finds; ?></td>
    <td><?php echo $this->records; ?></td>
</tr>