<?php
$this->headTitle('Details for issuer: ' . $this->issuer);
$this->metaBase()->setSubject('Iron Age Numismatics')
    ->setDescription('An entry for Iron Age ruler issuing coins')
    ->setKeywords('iron age,numismatics,coins')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php echo $this->searchLink()->setField('ruler')->setId($this->id); ?>
<?php echo $this->latestRecords()->setQuery('ruler:' . $this->id);