<?php
$this->headTitle('Add a degree of wear');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead">Add a new degree of wear term</h2>
<?php echo $this->form; ?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {
$('form').areYouSure();
$("form").submit(function() {
$(":submit", this).attr("disabled", "disabled");
});
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
