<?php
$this->headTitle('Manage degrees of wear');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!empty($this->degrees)): ?>
    <h2 class="lead">Degrees of wear (numismatics)</h2>
    <p><a class="btn btn-small btn-success"
          href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => 'adddegreeofwear'), null, true); ?>"
          title="Add a new degree of wear term">Add a new degree of wear term</a></p>
    <table class="table table-striped" summary="List of the degree of wear types that the Scheme uses">
        <caption>All degrees of wear used on database</caption>
        <thead>
        <tr>
            <th>Wear term</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/degreeOfWearTable.phtml', $this->degrees); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No wear types available.</p>
<?php endif; ?>