<?php
$this->headTitle('Manage degrees of wear');
if($this->degrees > 0):?>
<h2>Degrees of wear (numismatics)</h2>
<p><a class="btn btn-large btn-success" href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'adddegreeofwear'),null,true);?>" title="Add a new degree of wear term">Add a new degree of wear term</a></p>
<table class="table table-striped" summary="List of the degree of wear types that the Scheme uses">
<caption>All degrees of wear used on database</caption>
    <thead>
        <tr>
            <th>Wear term</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
    </thead>
<tbody>
    <?php echo $this->partialLoop('partials/admin/degreeofwearTable.phtml',$this->degrees);?>
</tbody>
</table>

<?php endif;?>