<?php
$this->headTitle('Delete a Reece period');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if ($this->reece) : ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>Are you sure that you want to delete <?php echo $this->reece->period_name; ?></p>
    <form
        action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => 'deletereeceperiod'), null, true); ?>"
        method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->reece->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>Cannot find the item requested.</p>
<?php endif; ?>
