<?php 
$this->headTitle('Delete a tribe\'s details');
if ($this->tribe) :?>
<h2>Delete a tribe</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->tribe->tribe); ?>'
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action'=>'deletetribe'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->tribe->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>
