<?php
$this->headTitle('Delete a mint from the system');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!is_null($this->mint)): ?>
    <h2 class="lead">Delete a mint</h2>
    <p>Are you sure that you want to delete <?php echo $this->mint->mint_name; ?></p>
    <form
        action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => 'deletemint'), null, true); ?>"
        method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->mint->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>Cannot find the item requested.</p>
<?php endif; ?>