<?php 
$this->headTitle("Delete a dieaxis from the system");
if ($this->dieaxis) :?>
<?php 
?>
<h2>Delete a Dynastic listing</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->dieaxis->term); ?>'
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action'=>'deletedieaxis'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->dieaxis->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<?php 
$this->headTitle("Error deleting die axis term");

?>

<h2>An error has occurred</h2>
<p>Cannot find the item requested.</p>
<?php endif;?>
