<?php
	$this->headTitle('Delete category'); 
if ($this->cats) :?>
<h2>Delete Medieval coin category: <?php echo $this->escape($this->cats->category); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->cats->category); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action'=>'deletecategory'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->cats->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>