<?php 
	$this->headTitle("Delete a medieval type from the system");
if ($this->medtype) :?>
<h2>Delete a Medieval type</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->medtype->type); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action'=>'deletetype'),null,true); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->medtype->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>