<?php if ($this->ruler) :
	$this->headTitle('Delete an active ruler from the system');?>
<h2>Delete <?php echo $this->escape($this->ruler->issuer); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->ruler->issuer); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action'=>'deleteruler'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->ruler->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>