<?php
$this->headTitle('Delete a dieaxis from the system');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!empty($this->dieaxis)) : ?>
    <h2 class="lead">Delete <?php echo $this->dieaxis->die_axis_name; ?></h2>
    <p>Are you sure that you want to delete <?php echo $this->dieaxis->die_axis_name; ?></p>
    <form
        action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => 'deletedieaxis'), null, true); ?>"
        method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->dieaxis->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>Cannot find the item requested.</p>
<?php endif; ?>
