<?php 
	$this->headTitle("Delete a reverse type from the system");
if ($this->reverse) :?>
<h2>Delete a reverse type</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->reverse->type); ?>'
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action'=>'deletereversetype'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->reverse->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>
