<h2><?php echo $this->adminperiod($this->period);?> denominations.</h2>
<?php echo $this->headTitle('Manage '. $this->adminPeriod($this->period).' denominations.');?>
<p><a class="btn btn-success btn-large" href="<?php echo $this->Url(array('module' => 'admin','controller' => 'numismatics','action' => 'adddenomination'),null,true);?>" title="Add a new denomination">Add new denomination</a></p>

<?php if (count($this->paginator)): ?>
<table class="table table-striped" summary="All denominations available for the <?php echo $this->period;?>">
    <thead>
        <tr>
            <th>Denomination</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php echo $this->partialLoop('partials/admin/denominationsTable.phtml',$this->paginator);?>
    </tbody>
</table>
<?php else: ?>
<p>No denominations available to you.</p>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>