<?php
$this->headTitle('Manage ' . $this->adminPeriod()->setPeriod($this->period) . ' denominations');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>

<p><a class="btn btn-success btn-small" href="<?php echo $this->url(
        array(
            'module' => 'admin',
            'controller' => 'numismatics',
            'action' => 'adddenomination'),
        null, true);?>" title="Add a new denomination">Add new denomination</a></p>

<?php if (!empty($this->paginator)): ?>
    <table class="table table-striped" summary="All denominations available for the
    <?php echo $this->adminPeriod()->setPeriod($this->period); ?>">
        <thead>
        <tr>
            <th>Denomination</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/denominationsTable.phtml', $this->paginator); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>No denominations available to you.</p>
<?php endif; ?>
