<?php
$this->headTitle('Edit a region\'s details');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead">Edit an Iron Age region</h2>
<?php echo $this->form; ?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {
$('form').areYouSure();
$("form").submit(function() {
$(":submit", this).attr("disabled", "disabled");
});
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>

