<?php 	$this->headTitle('Administer numismatic options');?>
<h2>Administer numismatics</h2>
<h3>General numismatics</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'dieaxes'),null,true);?>" title="Die axes listing">Die axes</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'degreesofwear'),null,true);?>" title="Manage degrees of wear terms">Degrees of wear</a></li>
</ul>

<h3>Roman</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'rulers', 'period' => '21'),null,true);?>" title="Administer rulers available">Emperors</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'mints', 'period' => '21'),null,true);?>" title="Administer mint available">Mints</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'reversetypes'),null,true);?>" title="Administer mint available">Reverse types</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'denominations', 'period' => '21'),null,true);?>" title="Manage Roman denominations">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'emperorbios'),null,true);?>" title="Manage Roman biographies">Issuer Biographies</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'reeceperiods'),null,true);?>" title="Manage Roman denominations">Reece periods</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'dynasties'),null,true);?>" title="Administer dynastic attributions">Dynasties</a></li>
</ul>

<h3>Iron Age</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'rulers', 'period' => '16'),null,true);?>" title="Administer rulers available">Issuers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'mints', 'period' => '16'),null,true);?>" title="Administer available mints">Mints</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'tribes'),null,true);?>" title="Administer available tribes">Tribes</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'regions'),null,true);?>" title="Administer available regions">Regions</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'denominations', 'period' => '16'),null,true);?>" title="Manage Iron Age denominations">Denominations</a></li>
</ul>

<h3>Byzantine</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'rulers', 'period' => '67'),null,true);?>" title="Administer rulers available">Issuers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'mints', 'period' => '67'),null,true);?>" title="Administer mint available">Mints</a></li><li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'denominations', 'period' => '67'),null,true);?>" title="Manage Byzantine denominations">Denominations</a></li>
</ul>

<h3>Greek and Roman Provincial</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'rulers', 'period' => '66'),null,true);?>" title="Administer rulers available">Issuers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'mints', 'period' => '66'),null,true);?>" title="Administer mint available">Mints</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'denominations', 'period' => '66'),null,true);?>" title="Manage Greek and Roman denominations">Denominations</a></li>
</ul>

<h3>Early Medieval</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'rulers', 'period' => '47'),null,true);?>" title="Administer rulers available">Issuers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'mints', 'period' => '47'),null,true);?>" title="Administer mint available">Mints</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'denominations', 'period' => '47'),null,true);?>" title="Manage Early Medieval denominations">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'categories', 'period' => '47'),null,true);?>" title="Manage Early Medieval categories">Categories</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'types', 'period' => '47'),null,true);?>" title="Manage Early Medieval types">Types</a></li>
</ul>

<h3>Medieval</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'rulers', 'period' => '29'),null,true);?>" title="Administer rulers available">Issuers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'mints', 'period' => '29'),null,true);?>" title="Administer mint available">Mints</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'denominations', 'period' => '29'),null,true);?>" title="Manage Medieval denominations">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'categories', 'period' => '29'),null,true);?>" title="Manage Early Medieval categories">Categories</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'types', 'period' => '29'),null,true);?>" title="Manage Medieval types">Types</a></li>
</ul>

<h3>Post Medieval</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'rulers', 'period' => '36'),null,true);?>" title="Administer rulers available">Issuers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'mints', 'period' => '36'),null,true);?>" title="Administer mint available">Mints</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'denominations', 'period' => '36'),null,true);?>" title="Manage Post Medieval denominations">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'categories', 'period' => '36'),null,true);?>" title="Manage Early Medieval categories">Categories</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics', 'action' => 'types', 'period' => '36'),null,true);?>" title="Manage Post Medieval types">Types</a></li>
</ul>