<?php
$this->MetaBasic();
$this->headTitle('Mints in use on the database');
?>
<h2>Mints in use on the database</h2>
<p><a class="btn-success btn btn-large" href="<?php echo $this->url(array('module' => 'admin','controller' => 'numismatics','action' => 'addmint'),null,true);?>" title="Add a new mint">Add a new mint</a></p>
<?php if (count($this->paginator)): ?>

<table class="table table-striped" summary="A list of all mints used by the database">
<caption>Mints in use on the system</caption>
    <thead>
        <tr>
            <th>Mint name</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
    </thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/mintsTableList.phtml',$this->paginator);?>
</tbody>
</table>
<?php endif;?>
<?echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
