<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 08/06/15
 * Time: 16:21
 */
?>
<h2 class="lead">A list of Republican Moneyers in use</h2>

<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => 'addmoneyer'), 'default', true); ?>"
   title="Add a new moneyer" class="btn btn-success">Add a moneyer</a>

<table class="table table-striped">
    <tr>
        <th>Name</th>
        <th>Date from</th>
        <th>Date to</th>
        <th>Valid?</th>
    </tr>
    <?php echo $this->partialLoop('partials/admin/moneyersListed.phtml', $this->moneyers); ?>
</table>