<?php
$this->headTitle('Reece Periods');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

    <p><a class="btn btn-small btn-success"
          href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'numismatics', 'action' => 'addreeceperiod'), null, true); ?>">Add
            a Reece Period</a></p>

<?php if (!empty($this->reeces)): ?>
    <table class="table table-striped" summary="A list of all Reece periods used on the database">
        <caption>Reece periods in use</caption>
        <thead>
        <tr>
            <th>Reece period</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/reeces.phtml', $this->reeces) ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No reece periods available.</p>
<?php endif; ?>