<?php
$this->headTitle('A Scheme event: '. $this->eventTitle);
$this->headMeta($this->CurUrl(),'dc.identifier');
$this->headMeta($this->title(),'dc.title');
$this->headMeta(strip_tags(substr($this->eventDescription,0,300)),'description');
$this->headMeta('The Portable Antiquities Scheme and the British Museum','dc.Publisher');
?>

<div class="vevent">
<h2 class="summary"><?php echo $this->eventTitle;?></h2>

<p>Add to my calendar: <a href="<?php echo $this->url(array(
    'module' => 'events',
    'controller' => 'info', 
    'action' => 'index', 
    'id' => $this->id,'format' => 'ics'), null, true);?>" 
    title="Download event details in ICS format">ics</a> | <a href="<?php echo 
    $this->url(array(
        'module' => 'events',
        'controller' => 'info', 
        'action' => 'index', 
        'id' => $this->id,'format' => 'rdf'), null, true);?>" 
        title="Download event details in RDF format">rdf</a> | <a href="
    <?php echo $this->url(array(
        'module' => 'events',
        'controller' => 'info', 
        'action' => 'index', 
        'id' => $this->id,
        'format' => 'xcs'),'info', true);?>" 
        title="Download event details in XCS format">xcs</a></p>

<p>Date(s): <abbr class="dtstart" title="<?php echo $this->toAtomDateStamp($this->eventStartDate);?><?php echo $this->eventStartTime;?>">
<?php echo ucwords(strftime("%A %d %B %Y", strtotime($this->eventStartDate)));?></abbr> 
<?php if((!is_null($this->eventEndDate)) || ($this->eventEndDate === $this->eventStartDate)) :?>
 -  <abbr class="dtend" title="<?php echo $this->toAtomDateStamp($this->eventEndDate);?><?php echo $this->eventEndTime;?>"><?php echo ucwords(strftime("%A %d %B %Y", strtotime($this->eventEndDate)));?></abbr>
 <?php endif;?>

<?php if(($this->eventStartTime) != '0000:00:00'):?> <br />
Timings: <?php echo $this->eventStartTime;?> - <?php echo $this->eventEndTime;?><br />
<?php endif;?>
<?php if(isset($this->eventLocation)):?>
Address: <?php echo $this->eventLocation;?>
<?php endif;?>
</p>
<?php if(isset($this->latitude) && isset($this->longitude)):?>

<?php 
$this->inlineScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false',$type='text/javascript');
$this->inlineScript()->captureStart();?>

$(document).ready(function() {
	var myLatlng = new google.maps.LatLng(<?php echo $this->latitude;?>,<?php echo $this->longitude;?>);
    var myOptions = {
      zoom: 14,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
	  scrollwheel:false
    }
    var map = new google.maps.Map(document.getElementById("eventmap"), myOptions);
    
    var marker = new google.maps.Marker({
        position: myLatlng, 
        map: map,
        title:"Event location"
    });   
});

<?php $this->inlineScript()->captureEnd();?>
<div id="eventmap" style="width:640px;height:300px;margin:auto;">
<noscript><img src="http://maps.google.com/maps/api/staticmap?center=<?php echo $this->latitude;?>,<?php echo $this->longitude;?>&zoom=14&size=640x300&maptype=terrain&markers=color:green|label:X|<?php echo $this->latitude;?>,<?php echo $this->longitude;?>&sensor=false" /></noscript>
</div>
<?php endif;?>
<span class="description"><?php echo $this->eventDescription;?></span>
<p>Event data created on:
<abbr class="dtstamp" title="<?php echo $this->toDateStamp($this->created);?>">
<?php echo ucwords(strftime("%A %d %B %Y", strtotime($this->created)));?></abbr></small></p>
</div>
<div class="vcard">
<p>Event data filed by: <span class="fn"><?php echo $this->fullname;?></span></p>
</div>
<?php if(($this->childrenAttend > 0 || $this->adultsAttend) != 0):?><div id="stats">
<h4>Attendance</h4>
<ul id="related">
<?php if($this->childrenAttend > 0) {
echo '<li>Attended by '.$this->childrenAttend.' children. </li>';
}
;?>
<?php if($this->adultsAttend > 0) {
echo '<li>Attended by '.$this->adultsAttend.' adults. </li>';
}
;?>

</ul></div>
<?php endif;?>
