<h3><a href="<?php echo $this->url;?>" title="Get this article on the Guardian's site"><?php echo $this->headline;?></a></h3>
<?php if(isset($this->image)) {?>
<img src="<?php echo $this->image;?>" alt="Trail image for this article" class="flow"/>
<?php }?>
<p class="byline"><?php echo date_format(date_create($this->pubDate),'Y/m/d');?> by <?php echo $this->byline;?><br />
Originally published in <?php echo $this->publication;?> <?php echo $this->sectionName;?></p>
<p><?php echo $this->ellipsisstring($this->content,1000);?></p>
<p>Read <a href="<?php echo $this->url(array('module' => 'news','controller' => 'guardian','action' => 'story','id' => urlencode($this->id)),NULL,true);?>" title="Read entire story here">entire story &raquo;</a></p>
<ul class="keywords">
<?php 
  foreach($this->tags as $t){
        if(!is_null($t->webUrl)){
          echo '<li><a href="'. $t->webUrl .'">'.$t->webTitle . '</a></li>';
         }
       }
	   ?>
</ul>
<p>Short url: <a href="<?php echo $this->shortUrl;?>" title="Guardian's short url"><?php echo $this->shortUrl;?></a></p>