<h3 class="lead"><a href="<?php echo $this->url; ?>"
                    title="Get this article on the Guardian's site"><?php echo $this->headline; ?></a></h3>
<?php if (isset($this->image)) { ?>
    <img class="img-circle pull-right" src="<?php echo $this->image; ?>" alt="Trail image for this article" class="flow"/>
<?php } ?>
<p class="byline"><?php echo date_format(date_create($this->pubDate), 'Y/m/d'); ?> by <?php echo $this->byline; ?><br/>
    Originally published in <?php echo $this->publication; ?> <?php echo $this->sectionName; ?></p>
<p><?php echo $this->ellipsisString()->setString($this->content)->setMax(1000); ?></p>
<p>Read <a
        href="<?php echo $this->shortUrl; ?>"
        title="Read entire story">entire story &raquo;</a></p>
<p><strong>Tags: </strong>
    <?php foreach ($this->tags as $t) { ?>
        <?php if (!is_null($t->webUrl)) { ?>
            <span class="label-info label" style="margin-right:10px;">
            <i class="icon-tag"></i><?php echo $t->webTitle; ?>
            </span>
        <?php } ?>
    <?php } ?>
</p>
