<?php
$apikey = Zend_Registry::get('config')->webservice->googlemaps->apikey;
$this->inlineScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.8&region=GB&key=' . $apikey, $type = 'text/javascript');
$this->inlineScript()->appendFile($this->serverUrl() . '/js/markerclusterer.js', $type = 'text/javascript');
?>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {

<?php
$user = new Pas_User_Details();
$person = $user->getPerson()->role;
$allowed = array('admin', 'fa', 'flos', 'research', 'treasure', 'hoard');
if (in_array($person, $allowed)) {
    $maxzoom = 18;
    $minzoom = 1;
} else {
    $maxzoom = 11;
    $minzoom = 1;
}
?>

var max = <?php echo $maxzoom; ?>;
var min = <?php echo $minzoom; ?>;

var osmMapType = new google.maps.ImageMapType({
getTileUrl: function (coord, zoom) {
return "https://a.tile.openstreetmap.org/" + 
zoom + "/" + coord.x + "/" + coord.y + ".png";

},
tileSize: new google.maps.Size(256, 256),
isPng: true,
alt: "OpenStreetMap layer",
name: "OSM",
maxZoom: max
});

var myOptions = {
center: new google.maps.LatLng( <?php echo $this->centre_lat; ?>, <?php echo $this->centre_lon; ?>),
zoom: 11,
mapTypeControlOptions: {
mapTypeIds: [
google.maps.MapTypeId.TERRAIN,
google.maps.MapTypeId.SATELLITE,
'OSM',
'SOIL',
'historic'
]
},
mapTypeControl: true,
style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
scaleControl: true,
zoomControl: true,
mapTypeId: 'OSM',
scrollwheel: false,
};

var map = new google.maps.Map(document.getElementById("map"),myOptions);
map.mapTypes.set('OSM',osmMapType);

<?php
$bbox = $this->min_lat . ',' . $this->min_lon . ',' . $this->max_lat . ',' . $this->max_lon;
$url = $this->serverUrl() . $this->url(array(
        'module' => 'database',
        'controller' => 'ajax',
        'action' => 'mapdata2',
        'bbox' => $bbox),
        'default', true);
?>

var markers = new Array();

var infowindow = new google.maps.InfoWindow();
jQuery.get("<?php echo $url; ?>", {}, function(data) {

jQuery(data).find("marker").each(function() {
var markerXML = jQuery(this);
var latlng = new google.maps.LatLng(
parseFloat(markerXML.attr("lat")),
parseFloat(markerXML.attr("lng"))
);
var marker = new google.maps.Marker({position: latlng, map: map});

// now that the marker is placed, assign event listener on the marker
// and create/assign infowindow to the event trigger.
markerInfoWindow(marker, markerXML.attr("content"));
markers.push(marker);
});
var markerCluster = new MarkerClusterer(map, markers);
});

function markerInfoWindow(marker, information){
google.maps.event.addListener(marker, 'click',
function() {
infowindow.close();
infowindow.setContent(information);
infowindow.setPosition(marker.getPosition());
infowindow.open(map, marker);
});
}
$('a[data-toggle="tab"]').on('shown', function (e) {
e.target // activated tab
e.relatedTarget // previous tab

google.maps.event.trigger(map, 'resize');
map.setZoom( map.getZoom() );
var latLngBounds = new google.maps.LatLngBounds(
new google.maps.LatLng(49.871159, -6.379880),
new google.maps.LatLng(55.811741, 1.768960)
);
map.fitBounds(latLngBounds);
})

});

<?php $this->inlineScript()->captureEnd(); ?>
<div id="map"></div>