
<p>
Party: <?php echo $this->party;?><br />
Constituency: <?php echo $this->constituency;?><br />
Entered house: <?php echo $this->timeagoinwords($this->entered_house);?>
<?php if($this->left_house != '9999-12-31') {?><br />
Left house: <?php echo$this->timeagoinwords($this->left_house);?><br />
Reason for leaving: <?php echo str_replace('_', ' ', $this->left_reason);?>
<?php
}?>
<?php if(isset($this->office)):?>
<?php foreach ($this->office as $o)
{
?>
Department: <?php echo $o->dept;?><br />
Position: <?php echo $o->position;?><br />
Took up office: <?php echo $this->niceshortdate($o->from_date);?><br />
<?php
}?></p>
<?php endif;?>