<?php
$this->headTitle('Details and finds for ' . $this->full_name . '\'s constituency', 'description');
$this->metaBase()->setDescription($this->title())
    ->generate();
?>
    <h2 class="lead">
        Details for objects found in <?php echo $this->full_name; ?>'s constituency
        of <?php echo $this->constituency; ?>
    </h2>


<?php if (!is_null($this->image)): ?>
    <img src="http://www.theyworkforyou.com<?php echo $this->image; ?>" height="<?php echo $this->image_height; ?>"
         width="<?php echo $this->image_width; ?>" alt="The latest portrait image of <?php echo $this->full_name; ?>"
         class="img-circle pull-right"/>
<?php endif; ?>