<?php
echo (string) '<Vevent>';
echo (string) '<uid>' . $this->id . '</uid>';
echo (string) '<summary>' . $this->eventTitle. '</summary>';
if (!is_null($this->eventDescription)) {
echo (string) '<description>' . $this->eventDescription . '</description>';
} // end if
echo (string) '<status/>';
echo (string) '<class resource="http://www.w3.org/2000/10/swap/pim/ical#private"/>';
echo (string) '<dtstart parseType="Resource">';
echo (string) '<value>' . $this->eventStartDate . '</value>';
echo (string) '</dtstart>';
echo (string) '<dtstamp>' . date('Ymd').'T'.date('His') . '</dtstamp>';
echo (string) '<due/>';
echo (string) '</Vevent>';
?>