<?php
$this->headTitle($this->title,'PREPEND');
$this->MetaBase(strip_tags($this->ellipsisstring($this->contents,150)),'archaeological news','');
?>
<h2><?php echo $this->title;?></h2>

<p><span class="updated dtstamp" title="<?php
$date = strtotime($this->golive);
echo date(DATE_ATOM,$date);?>">Published: <?php echo  $this->timeagoinwords($this->golive);?></span>
<span class="vcard">
Author: <span class="fn"><a rel="author" href="<?php echo $this->serverUrl();?>/contacts/staff/profile/id/<?php echo $this->personID;?>"><?php echo $this->escape($this->author);?></a></span> <a class="email" href="mailto:<?php echo $this->contactEmail;?>"><i class="icon-envelope"></i></a></span>
</p>
<?php echo $this->contents;?>
<p>Contact: <?php echo $this->contactName;?> <a href="mailto:<?php echo $this->contactEmail;?>"><i class="icon-envelope"></i></a> <?php echo $this->contactTel;?></p>
