<tr>
    <td>
        <?php echo $this->niceShortDate(strtotime($this->eventStartDate)); ?>
    </td>
    <td>
        <a href="<?php echo $this->url(array(
            'module' => 'news',
            'controller' => 'events',
            'action' => 'details',
            'id' => $this->id),
            'default', true); ?>" title="View this event's details"><?php echo $this->eventTitle; ?></a>
    </td>
    <td>
        <?php echo $this->location; ?>
    </td>
    <td>
        <?php echo $this->type; ?>
    </td>
    <td>
        <?php
        $types = array(
            'PAS' => 'Portable Antiquities Scheme',
            'BM' => 'British Museum',
            'MLA' => 'MLA',
            'HLF' => 'Heritage Lottery Fund',
            'IFA' => 'Institute of Archaeology',
            'CBA' => 'Council for British Archaeology',
            'ARCH' => 'Current Archaeology'
        );
        $search = array();
        $replace = array();
        foreach ($types as $t => $v) {
            $search[] = $t;
            $replace[] = $v;
        }
        echo str_replace($search, $replace, $this->organisation);
        ?>
    </td>
</tr>