<?php $this->headTitle('All errors submitted to the Scheme');?>
<h2><?php echo $this->title();?></h2>
<?php if(count($this->errors)):
?>

<table class="table table-striped">
<caption><?php echo $this->title();?></caption>
<thead>
	<tr>
		<th>Author</th>
		<th>Error report</th>
	</tr>
</thead>

<tbody>

<?php echo $this->partialLoop('partials/admin/allerrors.phtml', $this->errors) ?>

</tbody>

</table>
<?echo $this->paginationControl($this->errors, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>No errors are listed or available to you</p>
<?php endif;?>
