<?php     
$this->headTitle('Allen types listed');
?>
<h2>Allen types</h2>
<?php if($this->allens):?> 
<table summary="A list of all Allen types in use" class="table table-striped">
<caption>All Allen types</caption>
<thead>
<tr>
<th>Type name</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/numismatics/allen.phtml',$this->allens);?>
</tbody>
</table>
<?php echo  $this->paginationControl($this->allens, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else:?>
<p>No Allen types available</p>
<?php endif;?>