<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	= new DomDocument("1.0", "UTF-8");
$types  = $dom->createElement('response');
$meta 	= $dom->createElement('meta');
$types->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('totalItems',$this->allens->getTotalItemCount()));
$meta->appendChild( $dom->createElement('currentPage',$this->allens->getCurrentPageNumber()));
$meta->appendChild( $dom->createElement('totalPages',ceil($this->allens->getTotalItemCount()/$this->allens->getItemCountPerPage())));

$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$allensElem = $dom->createElement('allenTypes');
$types->appendChild($allensElem);
foreach($this->allens as $allen){
	$allenElem = $dom->createElement('type');
	foreach($allen as $k => $v ){
		$allenElem->appendChild( $dom->createElement($k, $v));
	}
	$allensElem->appendChild($allenElem);
}

$dom->appendChild( $types );

$xmlData  = $dom->saveXML();
echo $xmlData;
