<?php if ($this->type): ?>
    <?php
    $this->headTitle('Details for Allen Type: ' . $this->type->type);
    $this->metaBase()
        ->setDescription('The details for allen Type ' . $this->type->type)
        ->setSubject('Allen Type')
        ->setKeywords('Iron Age, coins, numismatics')
        ->generate();
    ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <?php echo $this->searchLink()->setField('allenType')->setId($this->type->type); ?>
    <?php echo $this->latestRecords()->setQuery('allenType:"' . $this->type->type . '"'); ?>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>No allen type has been found for that ID.</p>
<?php endif; ?>