<?php
$this->headTitle('Details for Allen Type:"' . $this->type->type);
$this->metaBase()
        ->setDescription('The details for allen Type ' . $this->type->type)
        ->setSubject('Allen Type')
        ->setKeywords('Iron Age, coins, numismatics')
        ->generate();
?>
<h2 class="lead">
    Details for <?php echo $this->title();?>
</h2>
<?php echo $this->latestRecords()->setQuery('allenType:"' .  Zend_Controller_Front::getInstance()->getRequest()->getParam('id') . '"');