<?php
$this->headTitle('Comments I made');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->comments)): ?>
    <ol id="timeline" class="statuses">
        <?php echo $this->partialLoop('partials/users/allComments.phtml', $this->comments) ?>
    </ol>
    <?php echo $this->paginationControl($this->comments, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>No comments are listed or available to you</p>
<?php endif; ?>
