<tr>
<td><a href="<?php echo $this->escape($this->schoolUrl);?>" title="Visit establishment homepage"><?php echo $this->escape($this->school);?></a></td>
<td><?php echo $this->type;?></td>
<td><?php echo $this->escape($this->subject);?></td>
<td><?php echo date('Y',strtotime($this->escape($this->dateFrom)));?></td>
<td><?php echo date('Y',strtotime($this->escape($this->dateTo)));?></td>
<td><a href="<?php echo $this->url(array('module' => 'users','controller' => 'education','action' => 'edit','id' => $this->id),null,true);?>" title="Edit this record">Edit</a> | <a href="<?php echo $this->url(array('module' => 'users','controller' => 'education','action' => 'delete','id' => $this->id),null,true);?>" title="Delete this record">Delete</a></td>
</tr>