<?php
$this->headTitle('User account details for ' . $this->fullname . ' - ' 
        . $this->visits . ' visits.');
?>

<h2><?php echo $this->title();?></h2>

<p>
<?php 
echo $this->gravatar($this->email,array(
	'imgSize' => 80, 
	'defaultImg' => 'http://finds.org.uk/assets/gravatar.png', 
	'secure' => true),
	array(
	'class' => 'avatar img-circle pull-left stelae', 
	'title' => $this->fullname . '\'s gravatar representation',
	'rating' => 'G',
	'width' => 80,
	'height' => 80)
	);
?>

<?php 
if(!is_null($this->institution)) {
echo 'Your recording institution is ' . $this->acronyms($this->institution) 
. ' and your username is set as ' . $this->username . '<br/>';
} else { 
echo 'Your username is currently '.$this->username;
} 
?>
You have logged in: <?php echo $this->visits;?> times.
<?php 
$more = $this->morevisitsthanme($this->visits);
if($more != 0) {
echo '<br />' . $more . ' people have visited the site more frequently than you!';
} else {
echo '<br />You are the most frequent visitor!';
}?>
<br />
Last visit registered at: <?php echo $this->escape($this->timeagoinwords($this->lastLogin));?><br />
Your specified role on the site is: <?php echo ucfirst($this->role);?><br />
Your account was last updated by <?php echo $this->updater;?>, <?php echo $this->escape($this->timeagoinwords($this->updated));?>.<br />Your account was created by: <?php echo $this->creator;?>.<br/ >
Your account was created: <?php echo $this->escape($this->timeagoinwords($this->created));?>.<br/ >
<?php 
if($this->canRecord === '1'):?>
<strong>Your account has permission to record objects</strong>
<?php else:?>
<span class="question">Your account does not have permission to record objects, if you want to do so, contact your local FLO.</span>
<?php endif;?>

<?php if(!is_null($this->peopleID)):?>
<br /><strong>Your account is attached to personal details on the database.</strong>
<?php if($this->institution === 'PUBLIC'):?>
<br />This url will take you to all publicly available finds you have recorded: <a href="<?php echo $this->serverUrl() . $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'finderID' => $this->peopleID),null,true);?>"><?php echo $this->serverUrl() . $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'finderID' => $this->peopleID),null,true);?></a>
<?php endif;?>
<br /><strong>Your unique identifier is: <?php echo $this->peopleID;?></strong>
<?php else:?>
<br /><span class="question">You have not been associated with personal details on our database. Contact your local flo to get this fixed.</span>
<?php endif;?>
</p>