<?php
$this->headTitle('User account details for ' . $this->fullname . ' - '
    . $this->visits . ' visits.');
?>

<h2 class="lead"><?= $this->title() ?></h2>

<p>
    <?php
    echo $this->gravatar($this->email, array(
        'imgSize' => 80,
        'defaultImg' => $this->serverUrl() . '/assets/gravatar.png',
        'secure' => true),
        array(
            'class' => 'avatar img-circle pull-left stelae',
            'title' => $this->fullname . '\'s gravatar representation',
            'rating' => 'G',
            'width' => 80,
            'height' => 80)
    );
    ?>

    <?php
    if (!is_null($this->institution)) {
        echo 'Your recording institution is <strong>' . $this->acronyms()->setString($this->institution)
            . '</strong> and your username is set as <strong>' . $this->username;
    } else {
        echo 'Your username is currently <strong>' . $this->username;
    }
    ?>
    </strong>.</br>
    You have logged in: <strong><?= $this->visits ?></strong> times.
    <?php
    $more = $this->moreVisitsThanMe()->setVisits($this->visits)->getData();
    if ((int)$more != 0) {
        echo '<br /><strong>' . $more . '</strong> people have visited the site more frequently than you.';
    } else {
        echo '<br />You are the most frequent visitor!';
    } ?>
    <br/>
    Last visit registered at: <strong><?= $this->escape($this->timeAgoInWords($this->lastLogin)) ?></strong>.<br/>
    Your specified role on the site is: <strong><?= ucfirst($this->role) ?></strong>.<br/>
    Your account was last updated by <strong><?= $this->updater ?></strong>, <strong><?= $this->escape($this->timeAgoInWords($this->updated)) ?></strong>.<br/>
    Your account was created by: <strong><?= empty($this->creator) ? "Unknown" : $this->creator ?></strong>.<br/>
    Your account was created: <strong><?= $this->escape($this->timeAgoInWords($this->created)) ?></strong>.<br/ >
    <?php
    if ($this->canRecord === '1'):?>
        <strong>Your account has permission to record objects.</strong>
    <?php else: ?>
        <span class="question">Your account does not have permission to record objects; if you want to do so, contact your local FLO.</span>
    <?php endif; ?>

    <?php if (!is_null($this->peopleID)): ?>
        <br/><strong>Your account is attached to personal details on the database.</strong>
        <?php if ($this->institution === 'PUBLIC'): ?>
            <br/>This url will take you to all publicly available finds you have recorded: 
		<a href="<?= $this->serverUrl() . $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'finderID' => $this->peopleID), null, true) ?>">
		    <?= $this->serverUrl() . $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'finderID' => $this->peopleID), null, true) ?></a>.
        <?php endif; ?>
        <br/>Your unique identifier is: <strong><?= $this->peopleID ?></strong>.
    <?php else: ?>
        <br/><span class="question">You have not been associated with personal details on our database. Contact your local FLO to get this fixed.</span>
    <?php endif; ?>
</p>
