<?php 
$string = unserialize($this->searchString);

$query = '';

foreach($string as $k => $v)
{
$query .= $k.'/'.$v.'/';
} 
$url = 'http://'.$_SERVER['SERVER_NAME'].'/database/search/results/'.$query;
?>
<li id="search-<?php echo $this->id;?>">

<span class="status-body">
You searched for: 
<?php echo $this->SearchParamsUsers($string);?>
<br />
Search performed: <span class="published timestamp" data="{time:'<?php echo date('W3C',$this->date);?>'}"><?php echo $this->timeagoinwords($this->date);?></span> 
<?php if(isset($this->C)):?>
Searched for <?php echo $this->C;?> times.
<?php endif;?>

<br />
<a href="<?php echo $url;?>" title="Permanent link">Permalink to search</a> <a href="<?php echo $url;?>format/rss/" title="RSS feed of these results">RSS</a> <a href="<?php echo $url;?>format/atom/" title="Atom feed of these results">ATOM</a> <a href="<?php echo $url;?>format/csv/" title="CSV spreadsheet of these results">CSV</a> <a href="<?php echo $url;?>format/json/" title="JSON feed of these results">JSON</a> <a href="<?php echo $url;?>format/xml/" title="XML feed of these results">XML</a> <a href="<?php echo $url;?>format/kml/" title="KML feed of these results">KML</a>
</span>

</span>
</li>
