<?php
$params = unserialize($this->searchString);

$query = array('module' => 'database', 'controller' => 'search', 'action' => 'results');
foreach($params as $key => $value){
    $query[$key] = $value;
}
$url = $this->url($query, 'default', true);
?>
<div class="row-fluid">
    <?= $this->gravatar($this->email, array(
        'imgSize' => 40,
        'defaultImg' => $this->serverUrl() . $this->baseUrl()
            . '/assets/gravatar.png',
        'secure' => true),
        array(
            'class' => 'avatar pull-left stelae img-circle',
            'title' => $this->username . '\'s gravatar representation',
            'rating' => 'G',
            'width' => 40,
            'height' => 40)
    );
    ?>    <a href="<?= $url; ?>"
             title="Permanent link"><?= strip_tags($this->title); ?></a>: <?= $this->searchDescription; ?>
    <br/>
    Search saved for
    reuse: <span class="published timestamp"
                 data="{time:'<?= date('W3C', strtotime($this->created)); ?>'}">
<?= $this->timeAgoInWords($this->created); ?></span>
</div>
