<tr>
    <td width="10%"><?php echo $this->escape($this->username); ?></td>
    <td width="10%"><?php echo $this->escape($this->fullname); ?></td>
    <td width="10%"><?php echo $this->role; ?></td>
    <td width="50%"><?php echo $this->timeAgoInWords($this->created);?><br /><?php echo strip_tags($this->researchOutline); ?></td>
    <td width="20%">
        <div class="btn-group">
            <a class="btn-mini btn" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'upgrade', 'id' => $this->id), NULL, true); ?>"
               title="Accept and upgrade this account">Accept</a>
            <a class="btn-mini btn" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'reject', 'id' => $this->id), NULL, true); ?>"
               title="Reject this application">Reject</a>
        </div>
    </td>
</tr>