<?php
$this->metaBase()->setSubject('Early Medieval numismatics')
    ->setKeywords('numismatics,early medieval,coins,categories,Vikings,invaders')
    ->setDescription('This page provides a list of mints that issued coins in the Early Medieval period', 'description')
    ->generate();
$this->headTitle('Issuing Mints of the Early Medieval period');
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->mints)): ?>
    <table class="table table-striped">
        <caption>A list of all Early Medieval mints listed on our database</caption>
        <thead>
        <tr>
            <th>Mint name</th>
            <th>Geo location</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/numismatics/medieval/medievalMints.phtml', $this->mints); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No mints have been listed.</p>
<?php endif; ?>