<?php 
$this->headMeta($this->curUrl(),'dc.identifier')
->headMeta('Early Medieval numismatics','dc.subject')
->headMeta('numismatics,early medieval,coins,categories,Vikings,invaders','keywords')
->headMeta('This page provides a list of mints that issued coins in the Early Medieval period','description')
->headMeta('Daniel Pett','dc.creator')
->headMeta('The Portable Antiquities Scheme','dc.publisher');
$this->headTitle('Issuing mints ');
?>
<h2>Issuing Mints of the Early Medieval period</h2>
<table class="table table-striped">
	<caption>A list of all Early Medieval mints listed on our database</caption>
	<thead>
	<tr>
	<th>Mint name</th>
	<th>Geo location</th>
	</tr>
	</thead>
	<tbody>
	<?php echo $this->partialLoop('partials/numismatics/medmints.phtml',$this->mints);?>
	</tbody>
</table>