<?php echo $this->partialLoop('partials/numismatics/medieval/medievalMintDetail.phtml', $this->mints); ?>
<h3 class="lead">
    Issuers
</h3>
<?php if (!empty($this->actives)): ?>
    <p>This mint was active under the following issuers:</p>

    <ul>
        <?php echo $this->partialLoop('partials/numismatics/medieval/medievalMintsToRulers.phtml', $this->actives); ?>
    </ul>
<?php else: ?>
    <p>No active mints listed.</p>
<?php endif; ?>

<?php echo $this->latestRecords()->setQuery('mint:' . $this->id); ?>
