<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$landuses  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$landuses->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->manufactures)));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$manufacturesElem = $dom->createElement('landuses');
$landuses->appendChild($manufacturesElem);
// set it's attribute
foreach($this->landuses as $r){
$manufactureElem = $dom->createElement('landuse');
foreach($r as $k => $v){
$manufactureElem->appendChild( $dom->createElement($k, $v));
}
foreach($this->landuses2 as $child){
	$childElem = $dom->createElement('childLanduse');
	foreach($child as $k => $v){
	$childElem->appendChild( $dom->createElement($k, $v));	
	}
$manufactureElem->appendChild($childElem);
}
$manufacturesElem->appendChild( $manufactureElem );
}

$dom->appendChild( $landuses );

$xmlData  = $dom->saveXML();
echo $xmlData;
