<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$objects  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$objects->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', $this->data['total']));
$meta->appendChild( $dom->createElement('page', $this->data['pageNumber']));
$meta->appendChild( $dom->createElement('totalPages', $this->data['totalPages']));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$objectsElem = $dom->createElement('objectTerms');
$objects->appendChild($objectsElem);
// set it's attribute
foreach($this->objectdata as $r){
$objectElem = $dom->createElement('objectTerm');
foreach($r as $k => $v){
$objectElem->appendChild( $dom->createElement($k, $v));
}
$objectsElem->appendChild( $objectElem );
}

$dom->appendChild( $objects );

$xmlData  = $dom->saveXML();
echo $xmlData;
