<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$reeces  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$reeces->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->reeces)));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$reecesElem = $dom->createElement('periods');
$reeces->appendChild($reecesElem);
// set it's attribute
foreach($this->reeces as $r){
$r = (object)$r;
$periodElem = $dom->createElement('period');
$periodElem->appendChild( $dom->createElement('name', $r->period_name));
$periodElem->appendChild( $dom->createElement('quantity', $r->description));

$reecesElem->appendChild( $periodElem );
}

$dom->appendChild( $reeces );

$xmlData  = $dom->saveXML();
echo $xmlData;
