<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 25/10/2015
 * Time: 07:46
 */
 ?>
<?php
// Add namespaces for the foaf file. These will only appear if used
\EasyRdf\RdfNamespace::set('geo', 'http://www.w3.org/2003/01/geo/wgs84_pos#');
\EasyRdf\RdfNamespace::set('admin', 'http://webns.net/mvcb');
\EasyRdf\RdfNamespace::set('rdfs', 'http://www.w3.org/2000/01/rdf-schema#');
\EasyRdf\RdfNamespace::set('xsd', 'http://www.w3.org/2001/XMLSchema#');
\EasyRdf\RdfNamespace::set('owl', 'http://www.w3.org/2002/07/owl#');
\EasyRdf\RdfNamespace::set('crm', 'http://erlangen-crm.org/current/');
\EasyRdf\RdfNamespace::set('crmeh', 'http://purl.org/crmeh#');
\EasyRdf\RdfNamespace::set('crmbm', 'http://collection.britishmuseum.org/id/crm/bm-extensions/');
\EasyRdf\RdfNamespace::set('claros', 'http://purl.org/NET/Claros/vocab#');
\EasyRdf\RdfNamespace::set('dc', 'http://purl.org/dc/elements/1.1/');
\EasyRdf\RdfNamespace::set('oac', 'http://www.openannotation.org/ns/');
\EasyRdf\RdfNamespace::set('dcterms', 'http://purl.org/dc/terms/');
\EasyRdf\RdfNamespace::set('skos', 'http://www.w3.org/2004/02/skos/core#');
\EasyRdf\RdfNamespace::set('google', 'http://rdf.data-vocabulary.org/#');
\EasyRdf\RdfNamespace::set('units', 'http://qudt.org/vocab/unit#');
\EasyRdf\RdfNamespace::set('og', 'http://ogp.me/ns#');
\EasyRdf\RdfNamespace::set('nm', 'http://nomisma.org/id/');
\EasyRdf\RdfNamespace::set('nmo', 'http://nomisma.org/ontology#');
\EasyRdf\RdfNamespace::set('foaf', 'http://xmlns.com/foaf/0.1/');
\EasyRdf\RdfNamespace::set('cc', 'http://creativecommons.org/ns#');
\EasyRdf\RdfNamespace::set('gn', 'http://www.geonames.org/ontology#');
\EasyRdf\RdfNamespace::set('osAdminGeo', 'http://data.ordnancesurvey.co.uk/ontology/admingeo/');
\EasyRdf\RdfNamespace::set('osSpatialRel', 'http://data.ordnancesurvey.co.uk/ontology/spatialrelations/');
\EasyRdf\RdfNamespace::set('lawd', 'http://lawd.info/ontology/1.0/');
\EasyRdf\RdfNamespace::set('db', 'http://dbpedia.org/id/');
\EasyRdf\RdfNamespace::set('bmt', 'http://collection.britishmuseum.org/id/thesauri/');
\EasyRdf\RdfNamespace::set('bmo', 'http://collection.britishmuseum.org/id/ontology/');
\EasyRdf\RdfNamespace::set('void', 'http://rdfs.org/ns/void#');
// Create the graph
$graph = new \EasyRdf\Graph();
$periods = $graph->resource(str_replace('/format/rdf','',$this->curUrl()), 'crm:E4_Period');
$periods->addType('skos:Concept');
$periods->addLiteral('skos:prefLabel', $this->periods[0]['period_name']);
echo $graph->serialise('rdfxml');