<?php echo $this->partialLoop('partials/numismatics/roman/reeceDetail.phtml', $this->periods); ?>
<?php if (!empty($this->reeces)): ?>
    <h3 class="lead">
        Issuers associated with this period
    </h3>

    <ul>
        <?php echo $this->partialLoop('partials/numismatics/roman/emperorList.phtml', $this->reeces); ?>
    </ul>
<?php endif; ?>

<?php if (!empty($this->reverses)) : ?>
    <h3 class="lead">
        Associated reverse types
    </h3>

    <ul>
        <?php echo $this->partialLoop('partials/numismatics/roman/reverseTypeListReece.phtml', $this->reverses); ?>
    </ul>
<?php endif; ?>

<?php echo $this->latestRecords()->setQuery('reeceID:' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>