<?php
$this->headTitle('Login to the system');
$this->headScript()->appendFile('//www.google.com/recaptcha/api.js');
?>
<h2 class="lead">Registered user login</h2>
<div id="capslock" style="display: none;">
    <div class="alert alert-danger">
        <h2>Your caps lock is on</h2>
        <p>This may affect your password.</p>
    </div>
</div>
<?php
echo $this->form;
?>

<h3 class="lead">Forgotten your details?</h3>
<p>You can retrieve your user account details using the links below:</p>
<ul>
    <li>
        <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'account', 'action' => 'forgotten'), NULL, TRUE); ?>"
           title="Retrieve your password">Forgotten password</a></li>
    <li>
        <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'account', 'action' => 'forgotusername'), NULL, TRUE); ?>"
           title="Retrieve your username">Forgotten username</a></li>
</ul>


<h3 class="lead">Register for an account</h3>

<p>
    <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'account', 'action' => 'register'), NULL, true); ?>"
       title="Register for a database account">Registering for an account</a> to use the Scheme's database is now
    very simple and has the following benefits:</p>
<ul>
    <li>You can record your own objects</li>
    <li>Your search history is saved</li>
    <li>You can get higher level access if you are an academic involved in archaeological research</li>
</ul>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/jquery.jccapsalert.js', $type='text/javascript'); ?>

<?php $this->jQuery()->onLoadCaptureStart(); ?>

jQuery("#current-password").CapsLockAlert();

<?php $this->jQuery()->onLoadCaptureEnd(); ?>
