<h4 class="lead">Audit data</h4>
<p>
    Recording Institution: <?php echo $this->institution;?>
    <br />
    Created: <span property="dc:created" datatype="xsd:datetime" content="<?php echo $this->created; ?>">
<?php echo $this->timeAgoInWords($this->created); ?></span>
    <?php if (!is_null($this->updated)): ?>
        <br/>
        <span property="dc:modified" datatype="xsd:datetime" content="<?php echo $this->updated; ?>">
Updated: <?php echo $this->timeAgoInWords($this->updated); ?></span> by <?php echo $this->fullnameUpdate;?>
    <?php endif; ?>
</p>
