<h2 class="lead">
    <?php echo $this->title(); ?>
</h2>

<!-- Three columns of text below the carousel -->
<div class="row-fluid">
    <div class="span4">

        <h2 class="lead">Micropasts</h2>

        <p>A community platform for conducting, designing and funding research into our human past. The Scheme's
            latest partnership project in conjunction with UCL and funded by the AHRC.</p>

    </div>
    <!-- /.span4 -->

    <div class="span4">

        <h2 class="lead">Search our database</h2>

        <p>A community platform for conducting, designing and funding research into our human past. The Scheme's
            latest partnership project in conjunction with UCL and funded by the AHRC.</p>

    </div>
    <!-- /.span4 -->

    <div class="span4">

        <h2 class="lead">Latest tweets</h2>

        <p>A community platform for conducting, designing and funding research into our human past. The Scheme's
            latest partnership project in conjunction with UCL and funded by the AHRC.</p>
    </div>
    <hr class="featurette-divider">
</div>
<div class="row-fluid">

    <div>
        <?php echo $this->form; ?>
    </div>

    <div>
        <?php echo $this->statisticsDatabase(); ?>
    </div>

</div>

<div class="row-fluid">
    <?php echo $this->partialLoop('partials/content/article.phtml', $this->contents); ?>
</div>


<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {
// focus on the first text input field in the first field on the page
$("input[type='text']:first", document.forms[0]).focus();
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
