<h2 class="lead">
    <?php echo $this->title(); ?>
</h2>


<div class="row-fluid">

    <div>
        <?php echo $this->form; ?>
    </div>

    <div>
        <?php echo $this->statisticsDatabase(); ?>
    </div>

</div>

<div class="row-fluid">
    <?php echo $this->partialLoop('partials/content/article.phtml', $this->contents); ?>
</div>


<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {
// focus on the first text input field in the first field on the page
$("input[type='text']:first", document.forms[0]).focus();
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
