<?php
$moduleName = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controllerName= Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$actionName = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

$url = $this->url(
    array(
        'module' => $moduleName,
        'controller' => $controllerName,
        'action' => $actionName,
        'datefrom' => $this->year . '-01-01',
        'dateto' => $this->year == date('Y') ? date('Y-m-d')  : $this->year . '-12-31'
    ),
    null,
    true
);
?>
<li>
    <a href="<?= $url ?>"
       title="View archived records for <?= $this->year; ?>"><?= $this->year; ?>
    </a>
</li>