<?php
$this->headTitle('Add jetton data');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<div class="btn-group">
    <a class="btn btn-success btn-small" href="<?php echo $this->url(array(
        'module' => 'database', 'controller' => 'coins', 'action' => 'add',
        'copy' => 'last'), null, false);?>" title="Autofill form fields from last
    record you created" id="populate" accesskey="c">Copy last record</a>
</div>
<hr/>
<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jQueryLinkedSelect.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/coinslinkedselect.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/tokensLinkedQuery.js', $type = 'text/javascript');
?>
