<h2 class="lead">
    Edit jetton data
</h2>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl()
    . '/js/JQuery/jQueryLinkedSelect.js', $type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
    . '/js/JQuery/coinslinkedselect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl()
    . '/js/JQuery/tokensLinkedQuery.js',$type='text/javascript');
echo $this->form;?>