<?php
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php
$this->editCheck()
    ->setInstitution($this->coin['institution'])
    ->setCreatedBy($this->coin['createdBy'])
    ->canThey();
?>

    <p><a class="btn btn-success btn-small"
          href="<?php echo $this->url(
              array(
                  'module' => 'database',
                  'controller' => 'artefacts',
                  'action' => 'record',
                  'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('returnID')
              ), null, true); ?>" title="return to the record">Return to record</a></p>
<?php echo $this->form; ?>

<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jQueryLinkedSelect.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/coinslinkedselect.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/tokensLinkedQuery.js', $type = 'text/javascript');
?>