<?php 
$this->headMeta('A list of all foreign issuing rulers of the Medieval period 
    with coins found in England and Wales','description');
$this->headMeta('kings,doges,foreign,low countries,venice,medieval,imitations,
    shortlongs','dc.keywords');
?>

<h2>Foreign issuing rulers of the Medieval period</h2>

<h3>Late medieval French coins</h3>
<p>This period had <?php echo count($this->french);?> issuers.</p>
<ul id="related">
<?php 
echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->french); ?>
</ul>

<h3>Coins of Scotland</h3>
<p>This period had <?php echo count($this->scots);?> issuers.</p>
<ul id="related">
<?php 
echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->scots); ?>
</ul>

<h3>The Doges of Venice</h3>
<p>This period had <?php echo count($this->doges);?> issuers.</p>
<ul id="related">
<?php 
echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->doges); ?>
</ul>

<h3>Coins of Portugal</h3>
<p>This period had <?php echo count($this->portugal);?> issuers.</p>
<ul id="related">
<?php 
echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->portugal); 
?>
</ul>

<h3>Coins of the Medieval Low Countries</h3>
<p>This period had <?php echo count($this->low);?> issuers.</p>
<ul id="related">
<?php 
echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->low); 
?>
</ul>

<h3>Edwardian imitations (Continental)</h3>
<p>This period had <?php echo count($this->imitate);?> issuers.</p>
<ul id="related">
<?php 
echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->imitate);
?>
</ul>

<h3>Short Long cross imitations (Continental)</h3>
<p>This period had <?php echo count($this->shortlongs);?> issuers.</p>
<ul id="related">
<?php 
echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->shortlongs);
?>
</ul>