<?php
$this->headTitle('Issuing rulers of the Medieval period');
$this->metaBase()->setDescription('A list of all issuing rulers for the Medieval period in England and Wales.')
    ->setSubject('Medieval Numismatics')
    ->setKeywords('medieval,numismatics,archaeology,coins,rulers,normans')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

    <!-- Norman rulers -->
<?php if (!empty($this->normans)): ?>
    <?php echo $this->partial('partials/numismatics/medieval/categoryTitle.phtml', $this->normans['0']); ?>
    <p>This period had <?php echo count($this->normans); ?> issuers.</p>
    <ul><?php echo $this->partialLoop('partials/numismatics/shared/rulers.phtml', $this->normans) ?></ul>
<?php endif; ?>

    <!-- Short long -->
<?php if (!empty($this->shortlong)): ?>
    <?php echo $this->partial('partials/numismatics/medieval/categoryTitle.phtml', $this->shortlong['0']); ?>
    <p>This period had <?php echo count($this->shortlong); ?> issuers.</p>
    <ul><?php echo $this->partialLoop('partials/numismatics/shared/rulers.phtml', $this->shortlong) ?></ul>
<?php endif; ?>


    <!-- Edwardian -->
<?php if (!empty($this->edwardian)): ?>
    <?php echo $this->partial('partials/numismatics/medieval/categoryTitle.phtml', $this->edwardian['0']); ?>
    <p>This period had <?php echo count($this->edwardian); ?> issuers.</p>
    <ul><?php echo $this->partialLoop('partials/numismatics/shared/rulers.phtml', $this->edwardian) ?></ul>
<?php endif; ?>

    <!-- Late medieval -->
<?php if (!empty($this->latemed)): ?>
    <?php echo $this->partial('partials/numismatics/medieval/categoryTitle.phtml', $this->latemed['0']); ?>
    <p>This period had <?php echo count($this->latemed); ?> issuers.</p>
    <ul><?php echo $this->partialLoop('partials/numismatics/shared/rulers.phtml', $this->latemed) ?></ul>
<?php endif; ?>