<?php 
$this->headTitle('Issuing rulers of the Medieval period');
$this->headMeta($this->curUrl(),'dc.identifier')
    ->headMeta('CC NC-SA-BY','dc.rights')
    ->headMeta('Daniel Pett','dc.creator')
    ->headMeta('The Portable Antiquities Scheme','dc.publisher')
    ->headMeta('A list of all issuing rulers for the Medieval period in England 
        and Wales.','description')
    ->headMeta('medieval,coins,numismatics,archaeology,medieval,england,wales','dc.keywords');

?>
<h2>Issuing rulers of the Medieval period</h2>

<?php echo $this->partial('partials/numismatics/categorytitle.phtml', $this->normans['0']) ; ?>
<p>This period had <?php echo count($this->normans);?> issuers.</p>

<ul id="related"><?php echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->normans) ?></ul>

<?php echo $this->partial('partials/numismatics/categorytitle.phtml', $this->shortlong['0']) ; ?>
<p>This period had <?php echo count($this->shortlong);?> issuers.</p>

<ul id="related"><?php echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->shortlong) ?></ul>

<?php echo $this->partial('partials/numismatics/categorytitle.phtml', $this->edwardian['0']) ; ?>
<p>This period had <?php echo count($this->edwardian);?> issuers.</p>
<ul id="related"><?php echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->edwardian) ?></ul>

<?php echo $this->partial('partials/numismatics/categorytitle.phtml', $this->latemed['0']) ; ?>
<p>This period had <?php echo count($this->latemed);?> issuers.</p>
<ul id="related"><?php echo $this->partialLoop('partials/numismatics/rulers.phtml', $this->latemed) ?></ul>