<?php 
$front = Zend_Controller_Front::getInstance()->getRequest();
$controller = $front->getControllerName();
?>
<div class="well sidebar-nav" >
<ul id="menu1" class="menu collapsible nav nav-pills nav-stacked">
<li><a href="<?php echo $this->url(array('module' => 'analytics'),'default', true);?>">Headline stats</a></li>
<li <?php if($controller == 'audience') { echo 'class="expandfirst"';};?>><a href="#">Audience <i class="icon-folder-open"></i></a>
	<ul class="nav nav-pills nav-stacked  menuindent">
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'audience', 'action' => 'overview'),'default', true);?>">Overview</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'audience','action' => 'map'),'default', true);?>">Visitors on a Google Map</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'audience','action' => 'continent'),'default', true);?>">Demography by continent</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'audience','action' => 'subcontinent'),'default', true);?>">Demography by subcontinent</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'audience','action' => 'country'),'default', true);?>">Demography by country</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'audience','action' => 'city'),'default', true);?>">Demography by city</a></li>
				<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'audience','action' => 'hourly'),'default', true);?>">Hourly profiles</a></li>
						
	</ul>
</li>
<li <?php if($controller == 'social') { echo 'class="expandfirst"';};?>><a href="#">Social media <i class="icon-folder-open"></i></a>
	<ul class="nav nav-pills nav-stacked  menuindent">
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'social', 'action' => 'interactions'),'default', true);?>">Interactions</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'social','action' => 'activities'),'default', true);?>">Activities</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'social','action' => 'networks'),'default', true);?>">Networks</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'social','action' => 'mobiles'),'default', true);?>">Mobile use</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'social','action' => 'tablets'),'default', true);?>">Tablet use</a></li>
	</ul>
</li>
<li <?php if($controller == 'technology') { echo 'class="expandfirst"';};?>><a href="#">Technology <i class="icon-folder-open"></i></a>
	<ul class="nav nav-pills nav-stacked  menuindent">
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'technology', 'action' => 'metrics'),'default', true);?>">Site speed metrics</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'technology', 'action' => 'tablets'),'default', true);?>">Tablets</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'technology', 'action' => 'mobiles'),'default', true);?>">Mobiles</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'technology', 'action' => 'browsers'),'default', true);?>">Browsers</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'technology', 'action' => 'desktopos'),'default', true);?>">Desktop O/S</a></li>
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'technology', 'action' => 'mobileos'),'default', true);?>">Mobile O/S</a></li>
	</ul>
</li>
<li <?php if($controller == 'content') { echo 'class="expandfirst"';};?>><a href="#">Content <i class="icon-folder-open"></i></a>
	<ul class="nav nav-pills nav-stacked  menuindent">
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'content', 'action' => 'overview'),'default', true);?>">Overview</a></li>
	</ul>
</li>
<li <?php if($controller == 'traffic') { echo 'class="expandfirst"';};?>><a href="#">Traffic <i class="icon-folder-open"></i></a>
	<ul class="nav nav-pills nav-stacked  menuindent">
		<li><a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'traffic', 'action' => 'overview'),'default', true);?>">Overview</a></li>
	</ul>
</li>
</ul>
</div>