<?php
if (!empty($this->announcements)): ?>

    <?php
    $this->jQuery()->addJavascriptFile(
        '/js/JQuery/jquery.cookie.js',
        $type = 'text/javascript'
    );
    ?>
    <?php
    $this->jQuery()->javascriptCaptureStart(); ?>
    initAnnouncement()
    <?php
    $this->jQuery()->javascriptCaptureEnd(); ?>
    <div class="alert alert-info" id="announcement">
        <?php
        foreach ($this->announcements as $announce): ?>
            <?php
            echo $announce['quote']; ?>
        <?php
        endforeach; ?>
        <span class="close">x</span>
    </div>
<?php
endif; ?>

<?php
if (in_array(
    $this->serverUrl(),
    array('https://beta.finds.org.uk', 'http://finds.dev')
)
): ?>
    <div class="alert alert-danger" id="announcement">
        <p>You are on a backup or testing server - there are no images here</p>
    </div>
<?php
elseif (in_array($this->serverUrl(), array('https://training.finds.org.uk')
)
): ?>
    <div class="alert alert-danger">
        <p>You are on the training database</p>
    </div>
<?php
endif; ?>
