<?php if (!empty($this->announcements)): ?>

    <?php
    $this->jQuery()->addJavascriptFile('/js/JQuery/jquery.cookie.js', $type = 'text/javascript');
    ?>
    <?php
    $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function(){
    if ($.cookie('noShowSurvey')) $('#announcement').hide();
    else {
    $("#close-welcome").click(function() {
    $("#announcement").fadeOut(1000);
    $.cookie('noShowSurvey', true);
    });
    }
    });
    <?php $this->jQuery()->javascriptCaptureEnd(); ?>
    <div class="alert alert-info" id="announcement">
        <?php foreach ($this->announcements as $announce): ?>
            <?php echo $announce['quote']; ?>
            <p><strong><a id="close-welcome" href="#">Dismiss this announcement</a></strong></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if ($this->serverUrl() == 'http://beta.finds.org.uk'): ?>
    <div class="alert alert-danger" id="announcement">
        <h2 class="lead">You are on the backup server - there are no images here</h2>
    </div>
<?php endif; ?>