<?php $gold = array(
'gold', 'dress-fasteners', 'gold-bracelets',
'penannular-rings', 'lock-rings','sleeve-fasteners',
'bullae', 'gorgets', 'collars',
'torcs', 'stud-caps-on-stone-wristguards', 'basket-shaped-ornaments',
'discs', 'lunulae', 'cups',
'capes', 'ribbon-torcs','bar-torcs',
'bar-bracelets', 'sheet-bracelets', 'composite-rings',
'bar-twisted-rings'
);
$slug = Zend_Controller_Front::getInstance()->getRequest()->getParam('slug');?>
<div class="well sidebar-nav" >
<ul id="menu1" class="menu  nav nav-stacked nav-pills">
<li><a href="<?php echo $this->url(array('module' => 'bronzeage'),'default',true);?>">Introduction</a></li>
<li <?php if(in_array($slug, $gold)) { echo ' class="expandfirst"';};?>><a href="#">Gold objects <i class="icon-folder-open"></i></a>
<ul class="nav nav-stacked nav-pills menuindent">
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'gold'),'bronzeage',true);?>">Introduction</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'dress-fasteners'),'bronzeage',true);?>">Dress fasteners</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'gold-bracelets'),'bronzeage',true);?>">Gold bracelets</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'penannular-rings'),'bronzeage',true);?>">Penannular rings</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'lock-rings'),'bronzeage',true);?>">Lock-Rings</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'sleeve-fasteners'),'bronzeage',true);?>">Sleeve-fasteners</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'bullae'),'bronzeage',true);?>">Bullae</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'gorgets'),'bronzeage',true);?>">Gorgets</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'collars'),'bronzeage',true);?>">Collars</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'torcs'),'bronzeage',true);?>">Torcs</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'stud-caps-on-stone-wristguards'),'bronzeage',true);?>">Stud caps on stone wristguards</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'basket-shaped-ornaments'),'bronzeage',true);?>">Basket-Shaped Ornaments</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'discs'),'bronzeage',true);?>">Discs</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'lunulae'),'bronzeage',true);?>">Lunulae</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'cylindrical-armlets'),'bronzeage',true);?>">Cylindrical armlets</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'cups'),'bronzeage',true);?>">Cups</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'capes'),'bronzeage',true);?>">Capes</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'ribbon-torcs'),'bronzeage',true);?>">Ribbon torcs</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'bar-torcs'),'bronzeage',true);?>">Bar torcs</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'bar-bracelets'),'bronzeage',true);?>">Bar bracelets</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'sheet-bracelets'),'bronzeage',true);?>">Sheet bracelets</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'composite-rings'),'bronzeage',true);?>">Composite rings</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'bar-twisted-rings'),'bronzeage',true);?>">Bar Twisted Rings</a></li>
</ul>
</li>
<?php 
$other = array(
'other','bracelets','knife',
'beads', 'awl', 'shield',
'ingots', 'metal-working-debris','arrowheads',
'wheeled-vehicle-equipment', 'horse-fittings', 'punches',
'rings', 'crotals', 'chapes',
'pins', 'flesh-hooks', 'fish-hooks',
'saw-blades', 'hammers', 'gouges',
'sickles', 'razors', 'bronze-torcs',
'vessels', 'axes', 'spearheads',
'halberd', 'rapiers-and-dirks', 'daggers'
);
$slug = Zend_Controller_Front::getInstance()->getRequest()->getParam('slug');?>
<li <?php if(in_array($slug, $other)) { echo ' class="expandfirst"';};?>><a href="#">Other metal objects <i class="icon-folder-open"></i></a>
<ul class="nav nav-stacked nav-pills menuindent">
<li ><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'other'),'bronzeage',true);?>">Introduction</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'bracelets'),'bronzeage',true);?>">Bracelets</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'knife'),'bronzeage',true);?>">Knives</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'beads'),'bronzeage',true);?>">Beads</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'awl'),'bronzeage',true);?>">Awls</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'shield'),'bronzeage',true);?>">Shields</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'ingots'),'bronzeage',true);?>">Ingots</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'metal-working-debris'),'bronzeage',true);?>">Metal working debris</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'arrowheads'),'bronzeage',true);?>">Arrowheads</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'wheeled-vehicle-equipment'),'bronzeage',true);?>">Wheeled vehicle equipment</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'horse-fittings'),'bronzeage',true);?>">Horse fittings</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'punches'),'bronzeage',true);?>">Punches</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'rings'),'bronzeage',true);?>">Rings</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'crotals'),'bronzeage',true);?>">Crotals</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'chapes'),'bronzeage',true);?>">Chapes</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'pins'),'bronzeage',true);?>">Pins</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'flesh-hooks'),'bronzeage',true);?>">Flesh-hooks</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'fish-hooks'),'bronzeage',true);?>">Fish-hooks</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'saw-blades'),'bronzeage',true);?>">Saw blades</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'anvils'),'bronzeage',true);?>">Anvils</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'hammers'),'bronzeage',true);?>">Hammers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'gouges'),'bronzeage',true);?>">Gouges</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'sickles'),'bronzeage',true);?>">Sickles</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'razors'),'bronzeage',true);?>">Razors</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'bronze-torcs'),'bronzeage',true);?>">Torcs</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'buttons-and-studs'),'bronzeage',true);?>">Buttons and studs</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'vessels'),'bronzeage',true);?>">Vessels</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'spearheads'),'bronzeage',true);?>">Spearheads</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'axes'),'bronzeage',true);?>">Axes</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'swords'),'bronzeage',true);?>">Swords</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'halberd'),'bronzeage',true);?>">Halberd</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'daggers'),'bronzeage',true);?>">Daggers</a></li>
<li><a href="<?php echo $this->url(array('module' => 'bronzeage','controller' => 'objects',
'action' => 'index','slug' => 'rapiers-and-dirks'),'bronzeage',true);?>">Rapiers and dirks</a></li>
</ul>
</li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'search',
'action' => 'results','broadperiod' => 'BRONZE AGE'),'default',true);?>">All Bronze Age objects <i class="icon-search"></i></a></li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'search',
'action' => 'map','broadperiod' => 'BRONZE AGE'),'default',true);?>">Map of Bronze Age artefacts</a></li>
</ul>
</div>

