<div class="well row-fluid" >
    <div class="span8"><h3>Britain's Secret Treasures</h3>
    <p>During July 2012, ITV ran a programme highlighting archaeological objects found by the British public. </p>
    <p>You can find out more about the series and the objects featured in our dedicated section for this ground <a href="<?php echo $this->url(array('module' => 'secrettreasures'),null,true);?>">breaking series</a> which has been produced in partnership with the Council for British Archaeology and ITN.</p></div>
    <div class="span4"><a href="<?php $this->url(array('module' => 'admin','controller' => 'contacts'),null,true);?>"><img  src="<?php echo $this->serverUrl();?>/images/logos/bst.png" alt="Britain's Secret Treasures logo" /></a></div>
</div>