<div class="sidebar-nav col-md-3" >
<ul id="menu1" class="menu nav nav-stacked nav-pills collapsible">
	<li <?php echo $this->currentPage()->active('byzantinecoins','index','index');?>><a href="<?php echo $this->url(array('module' => 'byzantinecoins'),NULL, true);?>" title="Read an introduction on Byzantine coins">Introduction </a></li>
	<li <?php echo $this->currentPage()->active('byzantinecoins','rulers','index');?>><a href="<?php echo $this->url(array('module' => 'byzantinecoins','controller' =>'rulers'),NULL, true);?>" title="Learn more about the issuers of the Byzantine period">Issuing rulers</a></li>
	<li <?php echo $this->currentPage()->active('byzantinecoins','mints','index');?>><a href="<?php echo $this->url(array('module' => 'byzantinecoins','controller'  => 'mints'),NULL,true);?>" title="Issuing mints of the Byzantine period">Issuing mints</a></li>
	<li <?php echo $this->currentPage()->active('byzantinecoins','denominations','index');?>><a href="<?php echo $this->url(array('module' => 'byzantinecoins', 'controller' =>  'denominations'),NULL,true);?>" title="Denominations of the Byzantine period">Denominations</a></li>
	<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'byzantinenumsimatics'),NULL,true);?>" title="Search for coins of the Byzantine period">Search</a></li>
	<li><a href="#"><i class="icon-folder-open"></i>Numismatics</a>
		<ul class="nav nav-pills nav-stacked  menuindent">
			<li><a href="<?php echo $this->url(array('module'=>'ironagecoins'),NULL, true);?>" title="Learn about Iron age coins">Iron age coins</a></li>
			<li><a href="<?php echo $this->url(array('module'=>'romancoins'),NULL, true);?>" title="Learn about Roman coins">Roman coins</a></li>
			<li><a href="<?php echo $this->url(array('module'=>'greekromancoins'),NULL, true);?>" title="Learn about Greek and Roman coins">Greek &amp; Roman coins</a></li>
			<li><a href="<?php echo $this->url(array('module'=>'byzantinecoins'),NULL, true);?>" title="Learn about Byzantine coins">Byzantine coins</a></li>
			<li><a href="<?php echo $this->url(array('module'=>'earlymedievalcoins'),NULL, true);?>" title="Learn about Early Medieval coins">Early Medieval coins</a></li>
			<li><a href="<?php echo $this->url(array('module'=>'medievalcoins'),NULL, true);?>" title="Learn about Medieval coins">Medieval coins</a></li>
			<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins'),NULL, true);?>" title="Learn about Post Medieval coins">Post Medieval  coins</a></li>
		</ul>
	</li>
</ul>
</div>
