<?php
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();

$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<div class="sidebar-nav col-md-3" >
    <ul  id="menu1" class="nav nav-stacked nav-pills collapsible">
    
        <?php echo $this->conservationmenu();?>

    </ul>
</div>