<div class="well sidebar-nav" >
<ul  id="menu1" class="menu collapsible nav nav-stacked nav-pills">
<li><a href="<?php echo $this->url(array('module'=>'contacts','controller' => 'staff'),null,true);?>" title="Find contact details for our staff">Contact list <i class="icon-user"></i></a></li>
<li><a href="<?php echo $this->url(array('module' => 'contacts','controller'=>'staff','action'=>'map'),null,true);?>" title="View our office locations">Contact map <i class="icon-map-marker"></i></a></li>
<li><a href="<?php echo $this->url(array('module' => 'contacts','controller' => 'alumni'),null,true);?>" title="View Scheme alumni statistics">Scheme Alumni <i class="icon-list"></i></a></li>
<li><a href="<?php echo $this->url(array('module'=>'contacts','controller'=>'coroners'),null,true);?>" title="View coroners' details">Coroners' details <i class="icon-list"></i></a></li>
<li><a href="<?php echo $this->url(array('module'=>'contacts','controller'=>'coroners','action' => 'map'),null,true);?>" title="View coroners' locations on map">Coroners mapped <i class="icon-map-marker"></i></a></li>
<li><a href="<?php echo $this->url(array('module'=>'contacts','controller'=>'accreditedmuseums'),null,true);?>" title="A list of accredited museums">Accredited museums <i class="icon-list"></i></a></li>
</ul>
</div>