<div class="row-fluid">
    <?php
    echo $this->contextsAvailable()->setContexts($this->contexts);
//    echo $this->analyticsLink();
    ?>
    <div class="btn-toolbar">
        <div class="btn-group">
            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-twitter"></i></a>
            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-facebook"></i></a>
            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-google-plus"></i></a>
            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-pinterest"></i></a>
            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-linkedin"></i></a>
            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-envelope"></i></a>
        </div>
    </div>
</div>