<div class="row-fluid">
    <?php
    echo $this->contextsAvailable()->setContexts($this->contexts);
//    echo $this->analyticsLink();
    $url = urlencode($this->curUrl());
    ?>
<!--    <div class="btn-toolbar">-->
<!--        <div class="btn-group">-->
<!--            <button class="btn btn-default btn-lg disabled">Share:</button>-->
<!--            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-twitter"></i></a>-->
<!--            <a title="Like On Facebook" href="http://www.facebook.com/sharer.php?u=--><?php //echo $url;?><!--" class="btn btn-inverse disabled"><i class="icon-white icon-facebook"></i></a>-->
<!--            <a title="+1 On Google" href="https://plusone.google.com/_/+1/confirm?hl=en&url=--><?php //echo $url;?><!--" class="btn btn-inverse disabled" target="_blank"><i  class="icon-white icon-google-plus"></i></a>-->
<!--            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-pinterest"></i></a>-->
<!--            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-linkedin"></i></a>-->
<!--            <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-envelope"></i></a>-->
<!--        </div>-->
<!--    </div>-->
</div>