<?php
$twitterConfig = Zend_Registry::get('config')->webservice->twitter->homepage;
?>

<?php if (!empty($twitterConfig->src) && !empty($twitterConfig->jsSrc)) : ?>

<div class="embed-container" style="--aspect-ratio:16/13">
    <div class="cookieconsent-optin-marketing cookie-placeholder cookie-placeholder--reload">
        If you can see this, please <a href="#" onclick="window.location.reload(true)">refresh</a>
        your <br>page to view these Tweets.
    </div>

    <div class="cookieconsent-optin-marketing">
        <a class="twitter-timeline" data-height="300"
           href="<?= $twitterConfig->src ?>">Tweets
            by findsorguk</a>
        <script async type="text/plain" data-cookieconsent="marketing"
                src="<?= $twitterConfig->jsSrc ?>"
                charset="utf-8"></script>
    </div>

    <div class="cookieconsent-optout-marketing cookie-placeholder dark">
        <div>
            Please <a href="javascript:Cookiebot.renew()"
                      style="color:white !important; text-decoration:underline;">accept
                marketing-cookies</a> to view these tweets
        </div>
    </div>
</div>

<?php endif;?>


