<div class="sidebar-nav col-md-3" >
    <ul  id="menu1" class="nav nav-stacked nav-pills collapsible">
        <li <?php echo $this->currentPage()->active('events','index','index');?>>
            <a href="<?php echo $this->url(array('module' => 'events','controller' => 'index'),'default',true);?>" title="Find out about our events programme">Our events</a></li>

        <li <?php echo $this->currentPage()->active('events','upcoming','index');?>>
            <a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'index'),'default',true);?>" title="Upcoming events at the Scheme">Upcoming events</a></li>
        
        <li <?php echo $this->currentPage()->active('events','upcoming','map');?>>
            <a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'map'),'default',true);?>" title="Map of upcoming events"><i class="icon-map-marker"></i>Events map</a></li>
        
        <li <?php echo $this->currentPage()->active('events','archives','index');?>>
            <a href="<?php echo $this->url(array('module' => 'events' , 'controller' => 'archives'),'default',true);?>" title="Our events archive">Events archive</a></li>
        
        <li <?php echo $this->currentPage()->active('events','foba','index');?>>
            <a href="<?php echo $this->url(array('module' => 'events' , 'controller' => 'foba'),'default',true);?>" title="Our events for the festival">FoBA 2011</a></li>
    </ul>
</div>