<div class="well sidebar-nav" >
<ul  id="menu1" class="menu collapsible nav nav-stacked nav-pills">
<li><a href="<?php echo $this->url(array('module' => 'events','controller' => 'index'),'default',true);?>" title="Find out about our events programme">Our events</a></li>
<li><a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'index'),'default',true);?>" title="Upcoming events at the Scheme">Upcoming events</a></li>
<li><a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'map'),'default',true);?>" title="Map of upcoming events">Events map <i class="icon-map-marker"></i></a></li>
<li><a href="<?php echo $this->url(array('module' => 'events' , 'controller' => 'archives'),'default',true);?>" title="Our events archive">Events archive</a></li>
<li><a href="<?php echo $this->url(array('module' => 'events' , 'controller' => 'foba'),'default',true);?>" title="Our events for the festival">FoBA 2011</a></li>
</ul>
</div>