<?php
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();

$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<div class="sidebar-nav col-md-3" >
    <ul  id="menu1" class="nav nav-stacked nav-pills collapsible">
        <li <?php if($module == 'events' && $controller == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'events','controller' => 'index'),'default',true);?>" title="Find out about our events programme">Our events</a></li>

        <li <?php if($module == 'events' && $controller == 'upcoming' && $action == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'index'),'default',true);?>" title="Upcoming events at the Scheme">Upcoming events</a></li>
        
        <li <?php if($module == 'events' && $controller == 'upcoming' && $action == 'map') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'map'),'default',true);?>" title="Map of upcoming events"><i class="icon-map-marker"></i>Events map</a></li>
        
        <li <?php if($module == 'events' && $controller == 'archives') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'events' , 'controller' => 'archives'),'default',true);?>" title="Our events archive">Events archive</a></li>
        
        <li <?php if($module == 'events' && $controller == 'foba') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'events' , 'controller' => 'foba'),'default',true);?>" title="Our events for the festival">FoBA 2011</a></li>
    </ul>
</div>