<div class="row-fluid ">
	<div class="span3">
	<a href="http://www.britishmuseum.org" title="The British Museum website">
	<img class="sponsors" src="<?php echo $this->baseUrl();?>/assets/logos/bm_logo.png"  width="150" height="60" alt="The British Museum logo"/></a>
	</div>
	<div class="span3">
            <h4 class="lead">About Us</h4>
            <ul>
                <li><a href="<?php echo $this->url(array('module' => 'about','controller' => 'index','action'=> 'index'),'default',true);?>" title="More information about the Portable Antiquities Scheme">About the Scheme</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'about','controller' => 'vacancies','action'=> 'index'),'default',true);?>" title="See all current job vacancies">Vacancies</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'about','controller' => 'logoandbranding','action' => 'index'),'default',true);?>" title="Scheme logo and branding guidelines">Logo and branding</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'about','controller' => 'contactus'),'default',true);?>" title="Contact the Scheme regarding our work" accesskey="9">Contact Us</a></li>

            </ul>
	</div>
	<div class="span3">
            <h4 class="lead">About our Site</h4>
            <ul>
                <li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'index','action' => 'index'),'default',true);?>" title="Information about this website">About our site</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action' => 'page','slug' => 'accessibility'),'information',true);?>" title="Information about our site's accessibility" accesskey="0">Accessibility</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action' => 'page','slug' => 'termsandconditions'),'information',true);?>" title="Read about our terms and conditions - nothing onerous" accesskey="8">Terms of Use</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action' => 'page','slug' => 'privacy'),'information',true);?>" title="Read about our privacy policy">Privacy &amp; Cookies</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'info','controller' => 'content','action'=> 'page','slug' => 'foi'),'information',true);?>" title="Freedom of information requests and how to submit one">Freedom of Information</a></li>
                <li><a href="<?php echo $this->url(array('module' => 'help','controller' => 'database','action'=> 'index'),'default',true);?>" title="Find helpful information about using our site" accesskey="6">Help</a></li>
            </ul>
	</div>

    <div class="span3 ">
        <h4 class="lead">Join the conversation</h4>
        <ul>
            <li><a href="http://www.twitter.com/#!/findsorguk" title="Our social media presence on Twitter" >Twitter</a></li>
            <li><a href="http://facebook.com/portableantiquitiesscheme" title="Our social media presence on Facebook" >Facebook</a></li>
            <li><a href="http://flickr.com/finds" title="Our social media presence on Flickr" >Flickr</a></li>
            <li><a href="http://www.youtube.com/user/portableantiquities" title="Our social media presence on Youtube" >YouTube</a></li>
            <li><a href="http://pinterest.com/findsorguk/" title="Our social media presence on Pinterst" >Pinterest</a></li>
        </ul>
    </div>

</div>

<div class="row-fluid ">

    <div class="span3">
<a href="http://www.culture.gov.uk" title="The Department of Culture, Media and Sport website"><img src="<?php echo $this->baseUrl();?>/assets/logos/dcms.png" width="80" height="70" alt="DCMS logo" class="sponsors" /></a>
    </div>

    <div class="span3">
        <h4 class="lead">Data Labs</h4>
        <ul>
            <li><a href="<?php echo $this->url(array('module' => 'datalabs','controller' => 'index','action' => 'index'),'default',true);?>">Linked open data policy</a></li>
            <li><a href="<?php echo $this->url(array('module' => 'datalabs','controller' => 'terminology','action' => 'objects'),'default',true);?>" title="Learn about object terms in use">Controlled vocabulary</a></li>
            <li><a href="<?php echo $this->url(array('module' => 'datalabs','controller' => 'oai'),'default',true);?>">OAI interface</a></li>
            <li><a href="<?php echo $this->url(array('module' => 'datalabs','controller' => 'rss','action' => 'index'),'default',true);?>">RSS feeds</a></li>
        </ul>
    </div>

    <div class="span3">
        <h4 class="lead">Tech</h4>
        <ul>
            <li><a href="https://github.com/findsorguk/findsorguk" title="The source code in github">Source code on Github</a></li>
            <li><a href="<?php echo $this->url(array('module' => 'tech'),'default',true);?>">Technology</a></li>
            <li><a href="<?php echo $this->url(array('module' => 'analytics'),'default',true);?>">Analytics</a></li>

        </ul>
    </div>
    
	<div class="span3">
		<div class="address">
		<strong>&copy; <?php echo $this->romannumerals()->setDate(2003);?> - <?php echo $this->romannumerals()->setDate(Zend_Date::now()->toString('yyyy'));?></strong> &raquo; <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">CC-BY</a> <br /><span class="vcard"><span class="adr"><span class="org fn">The British Museum</span>, <span class="street-address">Great Russell Street</span>, <span class="locality">London</span> <span class="postal-code">WC1B 3DG</span>.</span> T: <span class="tel"><span class="value">+44(0) 20 73238618</span></span> E: <a href="mailto:info@finds.org.uk" title="Email the Scheme" class="email">info@finds.org.uk</a></span></div>
		</div>
	</div>
