<div class="well sidebar-nav" >
<ul  id="menu1" class="menu collapsible nav nav-stacked nav-pills">
<li><a href="<?php echo $this->url(array('module' => 'help','controller' => 'database'),'default',true);?>" title="Help with using our database">Database help topics</a></li>
<li><a href="<?php echo $this->url(array('module' => 'help','controller' => 'site'),'default',true);?>" title="Upcoming events at the Scheme">Site help topics</a></li>
<li><a href="<?php echo $this->url(array('module' => 'help','controller' => 'database','action' => 'requesthelp'),'default',true);?>" title="Request help">Submit a help topic</a></li>
</ul>
</div>
