<?php
$front = Zend_Controller_Front::getInstance()->getRequest();

$module = $front->getModuleName();

$controller = $front->getControllerName();

$action = $front->getActionName();
?>

<div class="sidebar-nav col-md-3" >
    <ul  id="menu1" class="nav nav-stacked nav-pills collapsible">
    
        <li <?php if($module == 'getinvolved' && $controller == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'index'),'default',true);?>" title="How to get involved with the Scheme">How to get involved</a></li>
        
        <li <?php if($module == 'getinvolved' && $controller == 'vacancies' && $action == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'vacancies','action' => 'index'),'default',true);?>" title="Current vacancy listing">Current vacancies</a></li>
        
        <li <?php if($module == 'getinvolved' && $controller == 'vacancies' && $action == 'archives') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'vacancies','action' => 'archives'),'default',true);?>" title="Archived vacancy lists">Archived vacancies</a></li>
        
        <li <?php if($module == 'getinvolved' && $controller == 'volunteering') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'volunteering'),'default',true);?>" title="Volunteer opportunities with the Scheme">Volunteer opportunities</a></li>
        
        <li <?php if($module == 'getinvolved' && $controller == 'contactus') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'contactus'),'default',true);?>" title="Send us a message via our contact form">Contact us</a></li>
        
        <li <?php if($module == 'getinvolved' && $controller == 'faq') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'faq'),'default',true);?>" title="Read our frequently asked questions">FAQs &amp; Answers</a></li>
        
        <?php echo $this->involvedMenu();?>
        
        <li <?php if($module == 'getinvolved' && $controller == 'publications') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'publications'),'default',true);?>" title="Obtain our publications">Our publications</a></li>
        
        <li <?php if($module == 'getinvolved' && $controller == 'links') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'getinvolved','controller' => 'links'),'default',true);?>" title="Our bookmarks on delicious">Links</a></li>
        
    </ul>
</div>