<div class="well sidebar-nav" >
<ul id="menu1" class="menu collapsible expandfirst nav nav-stacked nav-pills">
<?php $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName(); ?>
<li><a href="#">Medieval coins</a>
<ul class="nav nav-stacked nav-pills menuindent">
<li><a href="<?php echo $this->url(array('module' => $module),NULL,true);?>" title="An introduction to Medieval coins">Introduction</a></li>

<li><a href="<?php echo $this->url(array('module' => $module,'controller'=>'rulers'),'default', true);?>" title="View listing of rulers of England and Wales">Issuing rulers of England</a></li>
<li><a href="<?php echo $this->url(array('module' => $module,'controller'=>'rulers','action' => 'foreign'),'default', true);?>">Foreign issuing rulers</a></li>
<li><a href="<?php echo $this->url(array('module' => $module,'controller'=> 'denominations'),'default', true);?>">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module' => $module,'controller'=>'mints'),'default', true);?>">Issuing mints</a></li>
<li><a href="<?php echo $this->url(array('module' => $module,'controller'=> 'categories'),'default', true);?>">Coin categories</a></li>
<li><a href="<?php echo $this->url(array('module' => $module,'controller'=> 'types'),'default', true);?>">Types</a></li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller'=> 'search','action' => 'mednumismatics'),'default', true);?>">Search</a></li>
<li><a href="<?php echo $this->url(array('module' => $module,'controller'=> 'articles','action' => 'index'),'default', true);?>">Articles</a></li>
</ul>
</li>
<li><a href="#">Other numismatic periods <i class="icon-folder-open"></i></a>
<ul class="nav nav-pills nav-stacked menuindent">
<li><a href="<?php echo $this->url(array('module'=>'byzantinecoins'),'default', true);?>">Byzantine coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'ironagecoins'),'default', true);?>">Iron Age coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'romancoins'),'default', true);?>">Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'greekromancoins'),'default', true);?>">Greek &amp; Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'earlymedievalcoins'),'default', true);?>">Early Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins'),'default', true);?>">Post Medieval  coins</a></li>

</ul></li>
</ul>
</div>