<?php 
if (in_array($this->serverUrl(), array('https://beta.finds.org.uk', 'http://finds.dev'))): ?>
    <div class="alert alert-danger" id="announcement">
        <h2>Server check!</h2>
        <p>You are on a backup or testing server - there are no images here</p>
    </div>
    <?php elseif(in_array($this->serverUrl(), array('https://training.finds.org.uk'))):?>
    <div class="alert alert-danger" >
        <h2>Server check!</h2>
            <p>You are on the training database</p>
    </div>
<?php endif; ?>

<?php if (!empty($this->messages[0])): ?>
    <?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function(){
    setTimeout(function(){
    $('#flashmessenger').fadeOut('slow'); }, 8000);
    });
    <?php $this->jQuery()->javascriptCaptureEnd(); ?>

    <div class="alert alert-info" id="flashmessenger">
        <a class="close" data-dismiss="alert"><i class="icon-eject"></i></a>
        <?php foreach ($this->messages as $message): ?>
            <?php echo $message; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
