<?php $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>

<div class="sidebar-nav col-md-3" >
    <ul id="menu1" class="menu nav nav-stacked nav-pills collapsible">
        <li <?php echo $this->currentPage()->active('news','index','index');?>>
            <a href="<?php echo $this->url(array('controller' => 'news','action' => 'index'),'default',true);?>" title="Latest news from the Scheme"><i class="icon-list-alt"></i>Scheme news</a></li>
        <li <?php if($controller == 'reports') { echo 'class="expandfirst active"';};?>><a href="#"><i class="icon-folder-open"></i>Scheme Annual reports</a>
            <ul class="nav nav-pills nav-stacked menuindent"> 
                <?php echo $this->menu('news','reports','index','reps');?></ul>
        </li>
        <li <?php if($controller == 'reports') { echo 'class="expandfirst"';};?> >
            <a href="#"><i class="icon-folder-open"></i>Treasure Reports</a>
                <ul class="nav nav-pills nav-stacked menuindent"><?php echo $this->TreasureReportsMenu();?></ul></li>
        <li <?php if($controller == 'reviews') { echo 'class="expandfirst"';};?>><a href="#"><i class="icon-folder-open"></i>Commissioned reviews</a>
            <ul class="nav nav-pills nav-stacked menuindent"><?php
            echo $this->menu('news','reviews','index','r');?></ul></li>
        <li <?php echo $this->currentPage()->active('news','map','index');?>>
            <a href="<?php echo $this->url(array('module' => 'news','controller' => 'map'),'default',true);?>" title="View most recent news stories on a map"><i class="icon-map-marker"></i>Geographic news map</a></li>
        <li <?php if($controller == 'theyworkforyou') { echo 'class="expandfirst"';};?>><a href="#" ><i class="icon-folder-open"></i>Data from theyworkforyou</a>
            <ul class="nav nav-pills nav-stacked menuindent">
        <li <?php echo $this->currentPage()->active('news','theyworkforyou','index');?>><a href="<?php echo $this->url(array('module' => 'news','controller' => 'theyworkforyou'),'default',true);?>" title="View latest mentions of related terms in Parliament">Parliamentary news</a></li>
        <li <?php echo $this->currentPage()->active('news','theyworkforyou','members');?>><a href="<?php echo $this->url(array('module' => 'news','controller' => 'theyworkforyou','action' => 'members'),'default',true);?>" title="Parliamentarian lookup by finds and record">Finds by Member of Parliament</a></li>
        <li <?php echo $this->currentPage()->active('news','theyworkforyou','constituencies');?>><a href="<?php echo $this->url(array('module' => 'news','controller' => 'theyworkforyou','action' => 'constituencies'),'default',true);?>" title="Parliamentary constituency find lookup">Finds by constituency</a></li>
        <li <?php echo $this->currentPage()->active('news','theyworkforyou','findmymp');?>><a href="<?php echo $this->url(array('module' => 'news','controller' => 'theyworkforyou','action' => 'findmymp'),'default',true);?>" title="Finds by constituency by postcode">Find by postcode to constituency</a></li></ul></li>
        <li <?php echo $this->currentPage()->active('news','guardian','index');?>>
            <a href="<?php echo $this->url(array('controller' => 'news','action' => 'guardian'),'default',true);?>" title="View articles on the Scheme from the Guardian"><i class="icon-list-alt"></i>Scheme in the Guardian</a></li>
    </ul>
    <?php if($controller == 'theyworkforyou'):?>
        <h4>Enhanced by</h4>
        <img src="/images/logos/logo-theyworkforyou.jpg" height="80" width="66" alt="Theyworkforyou.com powered"/>
        <img src="/images/logos/geoplanet.png" alt="Yahoo geoplanet logo" height="68" width="70"/>
    <?php endif;?>
    <?php if($controller == 'guardian'):?>
        <h4>Enhanced by</h4>
        <a href="http://www.guardian.co.uk/open-platform" title="The Guardian's openplatform"><img src="http://a1.twimg.com/profile_images/190112865/dataBlog_normal.png" alt="Guardian datastore powered"
        width="48" height="48" /></a>
    <?php endif;?>

</div>