<?php $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>

<div class="sidebar-nav col-md-3" >
    <ul id="menu1" class="menu nav nav-stacked nav-pills collapsible">
        <li <?php echo $this->currentPage()->active('news','index','index');?>>
        	<a href="<?php echo $this->url(array('controller' => 'news','action' => 'index'),'default',true);?>" title="Latest news from the Scheme"><i class="icon-list-alt"></i>Scheme news</a></li>
        <li <?php echo $this->currentPage()->active('news','map','index');?>>
        	<a href="<?php echo $this->url(array('module' => 'news','controller' => 'map'),'default',true);?>" title="View most recent news stories on a map"><i class="icon-map-marker"></i>Geographic news map</a></li>
        <li <?php echo $this->currentPage()->active('events','index','index');?>>
        	<a href="<?php echo $this->url(array('module' => 'events','controller' => 'index'),'default',true);?>" title="Find out about our events programme">Our events</a></li>
        <li <?php echo $this->currentPage()->active('events','upcoming','index');?>>
        	<a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'index'),'default',true);?>" title="Upcoming events at the Scheme">Upcoming events</a></li>
        <li <?php echo $this->currentPage()->active('events','upcoming','map');?>>
        	<a href="<?php echo $this->url(array('module' => 'events','controller' => 'upcoming','action' => 'map'),'default',true);?>" title="Map of upcoming events"><i class="icon-map-marker"></i>Events map</a></li>
        <li <?php echo $this->currentPage()->active('events','archives','index');?>>
        	<a href="<?php echo $this->url(array('module' => 'events' , 'controller' => 'archives'),'default',true);?>" title="Our events archive">Events archive</a></li>
    </ul>
</div>