<div class="well sidebar-nav" >
<ul id="menu1" class="menu collapsible expandfirst nav nav-stacked   nav-pills">
<li><a href="#">Post Medieval coins</a>
<ul class="nav nav-stacked nav-pills menuindent">
<li><a href="<?php echo $this->url(array('module' => 'postmedievalcoins'),NULL,true);?>" title="An introduction to Post Medieval coins">Introduction</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller'=>'rulers'),NULL, true);?>" title="View listing of rulers of England and Wales">Issuing rulers of England</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller'=>'rulers','action' => 'foreign'),NULL, true);?>" title="View a listing of foreign issued coins found in England">Foreign issuing rulers</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller'=>'denominations'),NULL, true);?>" title="Learn about post medieval denominations">Denominations</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller'=>'mints'),NULL, true);?>" title="Learn about issuing mints of the post medieval period">Issuing mints</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller'=>'categories'),NULL, true);?>" title="Learn about the categories of coin">Coin categories</a></li>
<li><a href="<?php echo $this->url(array('module'=>'postmedievalcoins','controller'=>'types'),NULL, true);?>" title="Learn about coin types">Types</a></li>
<li><a href="<?php echo $this->url(array('module' => 'database','controller' => 'search','action' => 'postmednumismatics'),NULL,true);?>" title="Search our database for post medieval coins">Search</a></li>
</ul>
</li>
<li><a href="#">Other numismatic periods <i class="icon-folder-open"></i></a>
<ul class="nav nav-stacked nav-pills menuindent">
<li><a href="<?php echo $this->url(array('module'=>'byzantinecoins'),NULL, true);?>" title="Learn about Byzantine coins">Byzantine coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'ironagecoins'),NULL, true);?>" title="Learn about Iron age coins">Iron Age coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'romancoins'),NULL, true);?>" title="Learn about Roman coins">Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'greekromancoins'),NULL, true);?>" title="Learn about Greek and Roman provincial coins">Greek &amp; Roman coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'earlymedievalcoins'),NULL, true);?>" title="Learn about Early Medieval coins">Early Medieval coins</a></li>
<li><a href="<?php echo $this->url(array('module'=>'medievalcoins'),NULL, true);?>" title="Learn about medieval coins">Medieval coins</a></li>

</ul></li>

</ul>
<div id="enhanced">
<h4>Data enhanced by:</h4>

<img src="/images/logos/calais.png" alt="The Open Calais logo" width="52" height="68"/><img src="/images/logos/geoplanet.png" alt="Yahoo geoplanet logo" height="68" width="70"/>
<img src="<?php echo $this->baseUrl();?>/images/logos/dbpedia.png" alt="Dbpedia's logo" height="43" width="70" />
</div>
</div>