<div id="paging">
<?php if ($this->pageCount): ?>
<p>
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
of <?php echo $this->totalItemCount; ?> records.
</p>

<?php $this->headTitle(' page' . $this->firstItemNumber . ' - ' . $this->lastItemNumber);?>

<?php
$queryString = ($_SERVER['QUERY_STRING'] != '') ? '?' . $_SERVER['QUERY_STRING'] : '';
?>

<ul id="pagination">
<!-- Previous page link -->
<li>
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->url(array('page' => $this->first)); ?>">First page</a> 
<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo; Previous</a> 
<?php else: ?>
<span class="previous-off">&laquo; Previous</span>
<?php endif; ?>
</li>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?>
<li>
<a href="<?php echo $this->url(array('page' => $page)). $queryString;  ?>" ><?php echo $page; ?></a>
</li>
<?php else: ?>
<li>
<a href="#" class="active"><?php echo $page; ?></a>
</li>
<?php endif; ?>
<?php endforeach; ?>

<li class="next">
<!-- Next page link -->
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->next)). $queryString;  ?>">Next &raquo;</a>
<?php else: ?>
<span class="next-off">Next &raquo;</span>
<?php endif; ?>
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->last)); ?>">Last page</a>
<?php else: ?>
<span class="disabled">Last</span>
<?php endif; ?>
</li>
</ul>
<?php endif; ?>
</div>