<?php
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();

$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<div class="sidebar-nav col-md-3" >
    <ul  id="menu1" class="nav nav-stacked nav-pills collapsible">
        <li <?php if($module == 'research' && $controller == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'research','controller' => 'index'),'default',true);?>" title="Research section home">Research</a>
        
        <li <?php if($module == 'research' && $controller == 'projects' && $action == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'research','controller' => 'projects'),'default',true);?>" title="View our research register">Research projects</a></li>
        
        <li <?php if($module == 'research' && $controller == 'projects' && $action == 'suggested') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'research','controller' => 'projects','action' => 'suggested'),'default',true);?>" title="Some topics we believe need investigating">Suggested research projects</a></li>
        
        <li <?php if($module == 'research' && $controller == 'datatransfer' && $action == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'research','controller' => 'datatransfer'),'default',true);?>" title="Data transfer to third parties">Data transfer</a></li>
        
        <li <?php if($module == 'research' && $controller == 'datatransfer' && $action == 'hers') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'research','controller' => 'datatransfer','action' => 'hers'),'default',true);?>" title="Which HERS have signed our agreement">HER signup</a></li>
        
        <li <?php if($module == 'research' && $controller == 'publications') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'research','controller' => 'publications'),'default',true);?>" title="Our research publication output">Research output</a></li>
    </ul>
</div>