<div class="well sidebar-nav" >
<ul id="menu1" class="menu collapsible nav nav-stacked nav-pills">
<li><a href="<?php echo $this->url(array('module' => 'secrettreasures'),'default',true);?>" title="An introduction to the series">About the series</a></li>
<?php ?>
<?php
$params = array('module' => 'secrettreasures','controller' => 'content', 'action' => 'index');
$current = Zend_Date::now();
$dateOne = '2012-07-16 20:00:00';
$difference = $current->isLater($dateOne);
$params['slug'] = 'episodeone';
if($difference):
?>
<li><a href="<?php echo $this->url($params,'secret', true);?>" title="Read about episode one's details">Episode one</a></li>
<?php endif;?>
<?php
$dateTwo = '2012-07-17 19:30:00';
$difference = $current->isLater($dateTwo);
$params['slug'] = 'episodetwo';
if($difference):
?>
<li><a href="<?php echo $this->url($params,'secret', true);?>" title="Read about episode two's details">Episode two</a></li>
<?php endif;?>
<?php
$dateThree = '2012-07-18 20:00:00';
$difference = $current->isLater($dateThree);
$params['slug'] = 'episodethree';
if($difference):
?>
<li><a href="<?php echo $this->url($params,'secret', true);?>" title="Read about episode three's details">Episode three</a></li>
<?php endif;?>
<?php
$dateFour = '2012-07-19 19:30:00';
$params['slug'] = 'episodefour';
$difference = $current->isLater($dateFour);
if($difference):
?>
<li><a href="<?php echo $this->url($params,'secret', true);?>" title="Read about episode four's details">Episode four</a></li>
<?php endif;?>
<?php
$dateFive = '2012-07-20 20:00:00';
$difference = $current->isLater($dateFive);
$params['slug'] = 'episodefive';
if($difference):
?>
<li><a href="<?php echo $this->url($params,'secret', true);?>" title="Read about episode five's details">Episode five</a></li>
<?php endif;?>
<?php
$dateSix = '2012-07-22 19:00:00';
$params['slug'] = 'episodesix';
$difference = $current->isLater($dateSix);
if($difference):
?>
<li><a href="<?php echo $this->url($params,'secret', true);?>" title="Read about episode six's details">Episode six</a></li>
<?php endif;?>
<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'content', 'action' => 'index', 'slug' => 'itv-sendin'),'secret',true);?>" title="Submit an object">Submit an object</a></li>
<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'content', 'action' => 'index', 'slug' => 'thepanel'),'secret',true);?>" title="The selection panel">The panel of experts</a></li>
<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'content', 'action' => 'index', 'slug' => 'treasure-meaning'),'secret',true);?>" title="The word Treasure">The word 'Treasure'</a></li>
<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'content', 'action' => 'index', 'slug' => 'festivalofarchaeology'),'secret',true);?>" title="The festival of British Archaeology">The festival of British Archaeology</a></li>
<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'photos', 'action' => 'inaset', 'id' => '72157630527845990'),'default',true);?>" />Behind the scenes images</a></li>

<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'photos', 'action' => 'inaset', 'id' => '72157630526828120'),'default',true);?>" />Featured object gallery</a></li>

<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'content', 'action' => 'index', 'slug' => 'trail-britishmuseum'),'default',true);?>" />British Museum object trail</a></li>
<li><a href="<?php echo $this->url(array('module' => 'secrettreasures', 'controller' => 'content', 'action' => 'index', 'slug' => 'codeofpractice'),'secret',true);?>" />Code of practice for responsible metal detecting</a></li>

</ul>

</div>