<div class="sidebar-nav col-md-3" >
    <ul  id="menu1" class="nav nav-stacked nav-pills collapsible">
        <li <?php echo $this->currentPage()->active('tech','index','index');?>><a href="<?php echo $this->url(array('module' => 'tech'),'default', true);?>">Technology</a></li>
        <li <?php echo $this->currentPage()->active('analytics','index','index');?>><a href="<?php echo $this->url(array('module' => 'analytics'),'default', true);?>">Analytics</a></li>
    </ul>
</div>