<div class="well sidebar-nav" >
<?php
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>
<ul id="menu1" class="menu collapsible nav nav-stacked nav-pills">
<li><a href="<?php echo $this->url(array('module' => 'treasure','controller' => 'index'),'default',true);?>"
title="An introduction to the Treasure Act">Introduction</a></li>
<?php echo $this->treasuremenu();?>
<li <?php if($controller == 'reports') { echo 'class="expandfirst"';};?>><a href="#">Treasure Reports <i class="icon-folder-open"></i>  </a>
<ul class="menuindent"><?php echo $this->TreasureReportsMenu();?></ul>
</li>
<li><a href="<?php echo $this->url(array('module' => 'treasure','controller' => 'cases'),'default',true);?>" title="Case history">Cases</a></li>
<li><a href="<?php echo $this->url(array('module' => 'treasure','controller' => 'minutes'),'default',true);?>" title="TVC minutes">TVC Minutes</a></li>
</ul>
</div>