<?php
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();

$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>

<div class="sidebar-nav col-md-3" >
    <ul  id="menu1" class="nav nav-stacked nav-pills collapsible">
        <li <?php if($module == 'treasure' && $controller == 'index') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'treasure','controller' => 'index'),'default',true);?>" title="An introduction to the Treasure Act">Introduction</a></li>
        
        <?php echo $this->treasuremenu();?>
        
        <li <?php if($controller == 'reports') { echo 'class="expandfirst active"';};?> >
            <a href="#"><i class="icon-folder-open"></i>Treasure Reports</a>
            <ul class="menuindent"><?php echo $this->TreasureReportsMenu();?></ul></li>
        
        <li <?php if($module == 'treasure' && $controller == 'cases') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'treasure','controller' => 'cases'),'default',true);?>" title="Case history">Cases</a></li>
        
        <li <?php if($module == 'treasure' && $controller == 'minutes') { echo 'class="active"';};?> >
            <a href="<?php echo $this->url(array('module' => 'treasure','controller' => 'minutes'),'default',true);?>" title="TVC minutes">TVC Minutes</a></li>
    </ul>
</div>