<?php 
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
?>

<?php if(!is_null($this->gridref) && is_null($this->knownas)) : ?>
<?php
$this->googleDynamicMap(null,null,true);
$this->inlineScript()->appendFile('http://maps.stamen.com/js/tile.stamen.js',$type = 'text/javascript');
?>
<?php $this->inlineScript()->captureStart();?>
$(document).ready(function() {
<?php
	$user = new Pas_User_Details();
	$person = $user->getPerson()->role;
	$allowed = array('admin', 'fa', 'flos', 'research', 'treasure');
	if(in_array($person, $allowed)) {
		$maxzoom = 18;
		$minzoom = 1;
	} else {
		$maxzoom = 11;
		$minzoom = 1;
	}
?>

	var max = <?php echo $maxzoom;?>;
	var min = <?php echo $minzoom;?>;
	var osmMapType = new google.maps.ImageMapType({
        getTileUrl: function (coord, zoom) {
            return "http://tile.openstreetmap.org/" +
                zoom + "/" + coord.x + "/" + coord.y + ".png";

        },
        tileSize: new google.maps.Size(256, 256),
        isPng: true,
        alt: "OpenStreetMap layer",
        name: "OSM",
        maxZoom: max
    });
    
    var nlsmap = new google.maps.ImageMapType({
	   getTileUrl: function(tile, zoom) { return NLSTileUrlOS(tile.x, tile.y, zoom); },
	   tileSize: new google.maps.Size(256, 256),
	   isPng: false,
	   maxZoom: max,
	   minZoom: min,
	   name: 'Historic',
	   alt: "NLS Historic Map"
	});
	<?php $geo = new Pas_Geo_Gridcalc($this->fourFigure);
	$results = $geo->convert();
	$lat = $results['decimalLatLon']['decimalLatitude'];
	$lon = $results['decimalLatLon']['decimalLongitude'];
	?>
	var myOptions = {
          center: new google.maps.LatLng(<?php echo $lat;?>, <?php echo $lon;?>),
          zoom: 12,
		  mapTypeControlOptions: {
          mapTypeIds: [
          google.maps.MapTypeId.ROADMAP, 
          google.maps.MapTypeId.HYBRID,
          google.maps.MapTypeId.TERRAIN,
          google.maps.MapTypeId.SATELLITE,
          'OSM',
          'historic',
          'Watercolor',
          'Toner'
          ]
    	  },
    	  mapTypeControl: true,
    	  style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
          scaleControl: true,
    	  zoomControl: true,
          mapTypeId: 'OSM',
          scrollwheel: false,
          maxZoom: max,
          minZoom: min
        };
        var map = new google.maps.Map(document.getElementById("map"),
            myOptions);
            map.mapTypes.set('OSM',osmMapType); 
        	map.mapTypes.set('historic',nlsmap);
			map.mapTypes.set("Watercolor", new google.maps.StamenMapType("watercolor"));
			map.mapTypes.set("Toner", new google.maps.StamenMapType("toner"));
            map.setTilt(45);
  		
  		var myTitle = document.createElement('h1');
		myTitle.style.color = '#444444';
		myTitle.style.font = "10px sans-serif";
		myTitle.innerHTML = 'Historical maps from <a href="http://geo.nls.uk/maps/api/">NLS Maps API<\/a> | OSM &copy; <a href="http://www.openstreetmap.org/">OpenStreetMap<\/a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA<\/a> | Google tiles &copy; Google';

		var myTextDiv = document.createElement('div');
		myTextDiv.appendChild(myTitle);

		map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(myTextDiv);
  		
  		var parish = new google.maps.KmlLayer('<?php echo $this->serverUrl();?>/kml/parishes/<?php echo strtoupper(str_replace(' ','',$this->parish));?>.kml',
                                                 {preserveViewport: true, suppressInfoWindows: false });
		parish.setMap(map);
		var county = new google.maps.KmlLayer('<?php echo $this->serverUrl();?>/kml/<?php echo strtoupper(str_replace(' ','',$this->county));?>.kml',
                                                 {preserveViewport: true, suppressInfoWindows: false });
		county.setMap(map);

<?php 
	$bbox = new Pas_Geo_BoundBox();
	$d = 5;  // distance
    $path_top_right = $bbox->createPoint($this->declat ,  $this->declong, 45, $d);
    $path_bottom_right = $bbox->createPoint($this->declat ,  $this->declong, 135, $d);
    $path_bottom_left = $bbox->createPoint($this->declat ,  $this->declong, 225, $d);
    $path_top_left = $bbox->createPoint($this->declat ,  $this->declong, 315, $d);
?>
  		
  		 var latLngBounds = new google.maps.LatLngBounds(
          new google.maps.LatLng(<?php echo $path_bottom_left;?>),
          new google.maps.LatLng(<?php echo $path_top_right;?>)
        );
    	map.fitBounds(latLngBounds);
});
<?php $this->inlineScript()->captureEnd();?>

<div id="map">
<noscript><img src="http://maps.google.com/maps/api/staticmap?center=<?php echo $this->declat;?>,<?php echo $this->declong;?>&amp;zoom=6&amp;size=640x300&amp;maptype=terrain&amp;markers=color:green|label:G|<?php echo $this->declat;?>,<?php echo $this->declong;?>&amp;sensor=false" alt="Findspot map generated via google static maps" /></noscript>
</div>


<?php endif;?>
<div class="row-fluid">

<div class="span4">
<h3>Spatial metadata</h3>
<p>
<?php if(!is_null($this->region)) :?>
Region: <?php echo $this->escape(ucwords(strtolower($this->region)));?><br />
<?php endif;?>
<?php if(!is_null($this->county)) :?>
County: <?php echo $this->escape(ucwords(strtolower($this->county)));?><br />
<?php endif;?>
<?php if(!is_null($this->district)) :?>
District: <?php echo $this->escape(ucwords(strtolower($this->district)));?><br />
<?php endif;?>
<?php if(!is_null($this->parish) && is_null($this->knownas))  :?>
Parish: <?php echo $this->escape(ucwords(strtolower($this->parish)));?>
<?php endif;?>
<?php if(!is_null($this->knownas)) :?>
<br /><span class="knownas">To be known as: <?php echo $this->escape($this->knownas);?></span>
<?php endif;?>
</p>
</div>

<div class="span4">
<?php if(!is_null($this->gridref)): ?>
<h3>Spatial coordinates</h3>
<p>
<?php if(!is_null($this->gridref) && is_null($this->knownas)):?>
<span class="fourfigure">4 Figure: <?php echo $this->fourFigure;?></span><br />
1:25K map: <?php echo $this->map25k;?><br />
1:10K map: <?php echo $this->map10k;?><br />
<?php endif;?>
Grid reference source: <?php echo $this->escape($this->source);?><br />
Grid reference accurate to a <?php echo $this->GetAccuracy($this->gridref);?> metre square.

</p>

</div>


<div class="span4">
<h3>Discovery metadata</h3>
<p>
<?php if(!is_null($this->method)) :?>
Method of discovery: <?php echo $this->escape($this->method);?>
 <span class="scope">[<a href="<?php echo $this->url(array(
     'module' => 'database',
     'controller'=>'terminology',
    'action'=>'method',
     'id' => $this->discmethod),null,true);?>"
 title="Read scope note for <?php echo $this->method;?>">scope notes</a>]</span><br />
<?php endif;?>

<?php if(!is_null($this->disccircum)) :?>
Discovery circumstances:  <?php echo $this->escape($this->disccircum);?> <br />
<?php endif;?>

<?php if(!is_null($this->curr_loc)) :?>
Current location: <?php echo $this->escape($this->curr_loc);?> <br />
<?php endif;?>

<?php if(!is_null($this->landvalue)) :?>
General landuse: <?php echo $this->landvalue;?>
<span class="scope">[<a href="<?php echo $this->url(array(
    'module' => 'database',
    'controller' => 'terminology',
    'action' => 'landuse',
    'id' => $this->landusevalue)
	,NULL, true);?>" title="View scope notes for <?php echo $this->landvalue;?>">scope notes</a>]
</span><br />
<?php endif;?>

<?php if(!is_null($this->landuse)) :?>
Specific landuse: <?php echo $this->escape($this->landuse);?>
<span class="scope">[<a href="<?php echo $this->url(array(
    'module' => 'database',
    'controller'=>'terminology',
    'action'=> 'landuse',
    'id' => $this->landusecode),null,true);?>"
    title="Read scope note for <?php echo $this->landuse;?>">scope notes</a>]
</span><br/>
<?php endif;?>
</p>
</div>
</div>
<?php endif; ?>

</div>



