<?php
$this->headTitle('Headline analytics data provided via Google Analytics');
?>
<h2><?php echo $this->title();?></h2>
<img src="<?php echo $this->serverUrl();?>/assets/google-analytics-logo.png" />
<h3 class="lead">Headline statistics</h3>
<div class="row fluid">

<div class="span3 well" >
<h3>This week</h3>
<?php 
$date = new Zend_Date();
$date->setYear($date->get(Zend_Date::YEAR))
     ->setWeek($date->get(Zend_Date::WEEK))
     ->setWeekDay(1);
$weekDates = array();

for ($day = 1; $day <= 7; $day++) {
    if ($day == 1) {
    	// we're already at day 1
    }
    else {
    	// get the next day in the week
    	$date->addDay(1);
    }

    $weekDates[] = date('Y-m-d', $date->getTimestamp());
}

echo $this->gaHeadlineStats($this->username, $this->password)->setProfile($this->profile)->setStart($weekDates[0])->setEnd($weekDates[6]);?>
</div>

<div class="span3 well" >
<h3>This month</h3>
<?php 
$date = new Zend_Date();
echo $this->gaHeadlineStats($this->username, $this->password)->setProfile($this->profile)->setStart($date->get(Zend_Date::YEAR . '-' .Zend_Date::MONTH . '-01'))->setEnd($date->get(Zend_Date::YEAR . '-' .Zend_Date::MONTH . '-' . Zend_Date::MONTH_DAYS));?>
</div>

<div class="span3 well" >
<h3>This year</h3>
<?php echo $this->gaHeadlineStats($this->username, $this->password)->setProfile($this->profile)->setStart($date->get(Zend_Date::YEAR) . '-01-01')->setEnd($date->get(Zend_Date::YEAR . '-' .Zend_Date::MONTH . '-' . Zend_Date::MONTH_DAYS));?>
</div>

</div>

<div class="row fluid">

<div class="span3 well" >
<h3>Last week</h3>
<?php 
$date = new Zend_Date();
$date->setYear($date->get(Zend_Date::YEAR))
     ->setWeek($date->get(Zend_Date::WEEK) - 1)
     ->setWeekDay(1);
$weekDates = array();

for ($day = 1; $day <= 7; $day++) {
    if ($day == 1) {
    	// we're already at day 1
    }
    else {
    	// get the next day in the week
    	$date->addDay(1);
    }

    $weekDates[] = date('Y-m-d', $date->getTimestamp());
}

echo $this->gaHeadlineStats($this->username, $this->password)->setProfile($this->profile)->setStart($weekDates[0])->setEnd($weekDates[6]);?>

</div>

<div class="span3 well" >
<h3>Last month</h3>
<?php 
$date = new Zend_Date();
$date->setYear($date->get(Zend_Date::YEAR))
     ->setMonth($date->get(Zend_Date::MONTH) - 1);
$monthYear = $date->toString('yyyy-MM');
$end = $date->get(Zend_Date::MONTH_DAYS);
echo $this->gaHeadlineStats($this->username, $this->password)->setProfile($this->profile)->setStart($monthYear . '-01')->setEnd($monthYear . '-' . $end);?>
</div>

<div class="span3 well" >
<h3>Last year</h3>
<?php 
echo $this->gaHeadlineStats($this->username, $this->password)->setProfile($this->profile)->setStart('2012-01-01')->setEnd('2012-12-31');?> 
</div>

</div>


