<?php
$this->headTitle('A guide to denominations issued by the rulers of Byzantium and its Empire');
$this->metaBase()->setKeywords('byzantium,coins,numismatics,denominations, nummi, assarion,tornese,trachy,constantinople')
    ->setSubject('numismatics of Byzantium')
    ->setDescription($this->title())
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->denominations)): ?>
    <p>The following coins were issued during the Byzantine period.</p>
    <ul>
        <?php echo $this->partialLoop('partials/numismatics/denominations.phtml', $this->denominations); ?>
    </ul>

    <?php echo $this->paginationControl($this->denominations, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>There are no denominations available to you.</p>
<?php endif; ?>