<?php 
$this->headTitle('Overall statistics for our events');
$this->headMeta('A breakdown of our events and attendance','description');?>
<h2>Statistical analysis of our events</h2>
<p>The Scheme's staff organise and attend a wide variety of events and lectures annually. We started collecting figures digitally in the Spring of 2010. The below gives a breakdown on an overall level.</p>

<table class="table table-striped" summary="A breakdown of the events that we have run or attended">
<thead>
<tr>
<th>Event type</th>
<th>Quantity</th>
<th>Adults attending</th>
<th>Children attending</th>
<th>Total attending</th>
<th>Average</th>
</tr>
</thead>
<tbody>
<?php foreach($this->stats as $s):?>
<tr>
<td><?php echo $s['type'];?></td>
<td><?php echo $s['number'];?></td>
<td><?php echo $s['adults'];?></td>
<td><?php echo $s['children'];?></td>
<td><?php echo $s['children'] + $s['adults'];?></td>
<td><?php echo number_format(($s['children']+$s['adults'])/$s['number'],0);?>
<?php endforeach;?>
</tbody>
</table>