<?php $this->mail->setSubject('Activate your account on finds.org.uk');
$activationLink = $this->serverUrl() . '/users/account/activate';
?>
<p>
    Dear <?php echo $this->escape($this->splitName()->setName($this->name)); ?>,
</p>

<p>
    Thank you for registering with the Scheme. By doing so, you will get access to
    enhanced features, and if required higher level access.
</p>

<p>
    To activate your account please go to the link <a
            href="<?php echo $this->serverUrl(); ?>/users/account/activate?activationKey=<?= $this->urlActivationKey ?? '' ?>">here</a>,
    complete the captcha, and click <strong>"Submit me"</strong>.
</p>

<p>
    Alternatively, visit the link <a href="<?= $activationLink ?>"><?= $activationLink ?></a> and enter
    your username, email address, and activation key (below).
</p>

<p>
    <strong><?= $this->activationKey ?></strong>
</p>

<p>
    Yours sincerely,
</p>

<p>
    The Portable Antiquities Scheme.
</p>
