<?php $this->mail->setSubject('Activate your account on finds.org.uk');
$activationLink = $this->serverUrl() . '/users/account/activate';
?>
<p>
    Dear <?php echo $this->escape($this->splitName()->setName($this->name)); ?>,
</p>

<p>
    Thank you for registering with the Scheme. By doing so you will get access to
    enhanced features and if required higher level access.
</p>

<p>
    To activate your account please go to this link:
</p>

<p>
    <a href="<?php echo $this->serverUrl(); ?>/users/account/activate?activationKey=<?= $this->urlActivationKey ?? '' ?>">
        Activate me
    </a>
</p>

<p>
    Alternatively, visit the link <a href="<?= $activationLink ?>"><?= $activationLink ?></a> and enter the below
    activation key,
    your username and email address
</p>

<p>
    <strong><?= $this->activationKey ?></strong>
</p>

<p>
    Yours sincerely,
</p>

<p>
    The Portable Antiquities Scheme.
</p>
