<?php $this->mail->setSubject('Your account is activated on finds.org.uk'); ?>
<p>Dear <?= $this->escape($this->fullname) ?>,</p>
<p>This e-mail is sent to inform you that your account (username: <b><?= $this->escape($this->username) ?></b>) has now been activated.</p>
<p>If you have any problems, please <a href="mailto:info@finds.org.uk">contact us</a> at the Central Unit.</p>
<p>Yours sincerely,</p>
<p>The Portable Antiquities Scheme</p>

