<?php $this->mail->setSubject('New password request for the PAS website');?>
<p>Dear <?php echo $this->escape($this->splitName($this->fullname));?>,</p>

<p>Thank you for requesting to reset your forgotten password.</p>
<p>For your security, we don't send passwords in cleartext, so instead enter the string below:</p>
<p><?php echo $this->activationKey;?></p>
<p>into the activation key box at the following page address:</p>

<p><a href="<?php echo $this->serverUrl() . $this->url(array('module' => 'users', 'controller' => 'account', 'action' => 'resetpassword'),'default', true); ?>"><?php echo $this->serverUrl() . $this->url(array('module' => 'users', 'controller' => 'account', 'action' => 'resetpassword'),'default', true); ?></a></p>

<p><?php echo $this->password;?></p>

<p>If you still have problems accessing your account, please do contact us.</p>

<p>Yours,</p>

<p>The Portable Antiquities Scheme</p>