<?php $this->mail->setSubject('Portable Antiquities Scheme find: ' . $this->old_findID . ' has progressed through the workflow system'); ?>

<p>Dear <?php echo $this->escape($this->splitName()->setName($this->name)); ?>,</p>
<strong>This is an automated email from the Portable Antiquities Scheme</strong>
<p>An object that you had recorded on finds.org.uk by a Finds Liaison Officer has progressed through our workflow.</p>
<p>Object number <?php echo $this->old_findID; ?>, is now at stage:
    <strong><?php echo $this->workflowStatus()->setWorkflow($this->workflow); ?></strong>.<br/>
    You can find out more about what that means at <a href="<?php echo $this->serverUrl();?><?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'workflows'), 'default', true); ?>"><?php echo $this->serverUrl();?><?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'workflows'), 'default', true); ?></a>.
    <?php if (in_array($this->workflow, array('3', '4'))): ?><br/>
        It can be found at:
        <a href="<?php echo $this->serverUrl();?><?php echo $this->url(array('module' => 'database', 'controller' => 'artefacts', 'action' => 'record', 'id' => $this->id), 'default', true)); ?>"><?php echo $this->serverUrl();?><?php echo $this->url(array('module' => 'database', 'controller' => 'artefacts', 'action' => 'record', 'id' => $this->id), 'default', true)); ?></a>
    <?php endif; ?>
</p>

<?php if ($this->content): ?>
    <p>You have also been sent this comment by the person sending this message:</p>
    <?php echo $this->content; ?>
<?php endif; ?>

<p>Yours sincerely,</p>

<p><?php echo $this->escape($this->splitName()->setName($this->from)); ?></p>

<?php echo $this->emailSignature(); ?>
