<?php $this->mail->setSubject('Portable Antiquities Scheme find: ' . $this->old_findID . ' has progressed through the workflow system');?>

<p>Dear <?php echo $this->escape($this->splitName($this->name));?>,</p>
<strong>This is an automated email from the Portable Antiquities Scheme</strong>
<p>An object that you had recorded on finds.org.uk by a Finds Liaison Officer has progressed through our workflow.</p>
<p>Object number <?php echo $this->old_findID;?>, is now at stage: <strong><?php echo $this->workflowStatus($this->workflow);?></strong>.<br />
You can find out more about what that means at <a href="http://finds.org.uk/database/terminology/workflows">http://finds.org.uk/database/terminology/workflows</a>. 
<?php if(in_array($this->workflow, array('3','4'))):?><br />
<?php $url = array('module' => 'database', 'controller' => 'artefacts', 'action' => 'record', 'id' => $this->id);?>
It can be found at: 
<a href="<?php echo $this->serverUrl($this->url($url, 'default', true));?>"><?php echo $this->serverUrl($this->url($url, 'default', true));?></a>
<?php endif;?>
</p>

<?php if($this->content):?>
<p>You have also been sent this comment by the person sending this message:</p>
<?php echo $this->content;?>
<?php endif;?>

<p>Yours sincerely,</p>

<p><?php echo $this->escape($this->splitName($this->from));?></p>

<?php echo $this->emailSignature();?>
	