<?php $this->mail->setSubject($this->fullname . ' sent you a search from finds.org.uk');?>

<p>Dear <?php echo $this->escape($this->splitName($this->fullname));?>,</p>

<p>RE: A search you might be interested in on finds.org.uk.</p>
<?php 
$actions = array('action' => 'results');
$url = array_merge($actions,$this->url); ?>

<p>Search string: <a href="<?php echo $this->serverUrl($this->url($url, 'default', false));?>"><?php echo $this->serverUrl($this->url($url, 'default', false));?></a></p>

<?php echo $this->purify($this->message);?>

<p>The search is located at this url:  <?php echo $this->serverUrl($this->url($url, 'default', false));?></p>

<p>Best wishes,</p>

<?php echo $this->emailSignature();?>
	