<?php $this->mail->setSubject('Reference request for Portable Antiquities Scheme Database Access'); ?>
<p>Dear <?php echo $this->escape($this->splitName()->setName($this->reference)); ?>,</p>

<p>We have had a request from <?php echo $this->name;?> for access to the Portable Antiquities Scheme Database, and they
have given your name as a referee. Can you vouch for the research outline that they provided and whether they should be allowed
access.</p>

<p>For reference, this is the abstract they submitted:</p>

<?php echo $this->purify()->setValue($this->researchOutline); ?>

<p>Yours sincerely,</p>

<p>The Portable Antiquities Scheme.</p>
