<?php $this->mail->setSubject('Your request for an upgrade has been rejected');?>
<p>Dear <?php echo $this->escape($this->splitName($this->fullname)); ?>,</p>

<p>RE: Account upgrade rejected</p>

<?php echo $this->purify($this->message); ?>

<p>With the research outline you provided us with as follows:</p>

<?php echo $this->purify($this->researchOutline);?>

<p>If you feel that this has been rejected unfairly, please	call 0207 323 8611 
and speak to Roger Bland, Keeper of Portable Antiquities and Treasure.</p>

<p>Yours,</p>

<p>The Scheme's Central Unit.</p>

<?php echo $this->emailSignature();?>