<p>Dear <?php echo $this->escape($this->splitName()->setName($this->reference)); ?>,</p>

<p>We have had a request from <?php echo $this->name;?> (copied in with our finds adviser team) for access to the Portable Antiquities Scheme Database, and they
have given your name as a referee. Can you vouch for the research outline that they provided and whether they should be allowed
access.</p>

<p>The request should be dealt with during a 15 day working week timescale and terms and conditions are attached.</p>

<p>For reference, this is the abstract they submitted:</p>

<?php echo $this->purify()->setValue($this->researchOutline); ?>

<p>Yours sincerely,</p>

<p>The Portable Antiquities Scheme.</p>
