<?php
$this->headTitle('Post Medieval coin categories');
$this->metaBase()->setSubject('Post medieval numismatics')
    ->setDescription('A list of post medieval categories')
    ->setKeywords('post,medieval,typology')
    ->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->categories)): ?>
    <ul>
        <?php echo $this->partialLoop('partials/numismatics/medieval/categories.phtml', $this->categories); ?>
    </ul>
<?php else: ?>
    <p>No categories available.</p>
<?php endif; ?>