<?php 
$this->headTitle('Portable Antiquities Upcoming Scheme Events');
$this->headMeta('An overview of our attendance of upcoming events','description')
->headMeta($this->curUrl(),'dc.identifier')
->headMeta('Daniel Pett','dc.creator')
->headMeta('The Portable Antiquities Scheme','dc.publisher')
->headMeta('CC NC-BY-SA','dc.rights');?>
<h2>Upcoming Scheme events</h2>

<?php if(count($this->events)):?>
<table class="table table-striped" summary="List of all archived scheme events">
<caption>List of upcoming Scheme events</caption>
<thead>
<tr>
<th>Date of event</th>
<th>Event title</th>
<th>Location</th>
<th>Type</th>
<th>Organised by</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/events/upcoming.phtml',$this->events);?>
</tbody>
</table>
<?php else:?>
<p>There are no upcoming events available to you on this date.</p>
<?php endif;?>

<div id="calendars">

<div id="current"><?php echo $this->curr;?></div>
<div id="next"><?php echo $this->next;?></div>
<div id="nextplusone"><?php echo $this->nextplusone;?></div>

</div>
