<?php if (!empty($this->regions)): ?>
    <?php
    $this->headTitle('Iron age regions issuing coins');
    $this->metaBase()->setSubject('Iron Age Numismatics')
        ->setKeywords('iron age,coins,geography,regions,numismatics')
        ->setDescription('A list of iron age regions issuing coins')
        ->generate();
    ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <ul>
        <?php echo $this->partialLoop('partials/numismatics/ironAge/ironAgeRegions.phtml', $this->regions) ?>
    </ul>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>No regions have been found</p>
<?php endif; ?>