<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$regions  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$regions->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$regionsElem = $dom->createElement('regions');
$regions->appendChild($regionsElem);
// set it's attribute
foreach($this->regions as $m){
$m = (object)$m;
$regionElem = $dom->createElement('region');
$regionElem->appendChild( $dom->createElement('id', $m->id));
$regionElem->appendChild( $dom->createElement('name', $m->region));
$regionElem->appendChild( $dom->createElement('area', $m->area));
$regionElem->appendChild( $dom->createElement('url',$site . $this->url(array('module' => $module,
'controller' => $controller,'action' => 'mints','id' => $m->id),NULL,true) ));
$regionsElem->appendChild( $regionElem );
}

$dom->appendChild( $regions );

$xmlData  = $dom->saveXML();
echo $xmlData;
