<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();
$dom = new DomDocument("1.0", "UTF-8");
$regions  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$regions->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$mintsElem = $dom->createElement('mints');

foreach($this->regions as $m){
$m = (object)$m;
$regionElem = $dom->createElement('region');
$regionElem->appendChild( $dom->createElement('id', $m->id));
$regionElem->appendChild( $dom->createElement('name', $m->region));
$regionElem->appendChild( $dom->createElement('area', $m->area));
$imageElem = $dom->createElement('recentRecords');	
$regionElem->appendChild($imageElem);
$denomElem = $dom->createElement('denominations');
$regionElem->appendChild($denomElem);
$rulersElem = $dom->createElement('rulers');
$regionElem->appendChild($rulersElem);

foreach($this->denominations as $d){
$d = (object)$d;
$denominationElem = $dom->createElement('denomination');
$denomElem->appendChild( $denominationElem);	
$denominationElem->appendChild( $dom->createElement('id', $d->id));
$denominationElem->appendChild( $dom->createElement('name', $d->denomination));
$denominationElem->appendChild( $dom->createElement('rarity', $d->rarity));
$denominationElem->appendChild( $dom->createElement('description', $d->description));
$denominationElem->appendChild( $dom->createElement('weight', $d->weight));
$denominationElem->appendChild( $dom->createElement('diameter', $d->diameter));
$denominationElem->appendChild( $dom->createElement('material', $d->old_material));
$denominationElem->appendChild( $dom->createElement('created', $d->created));
$denominationElem->appendChild( $dom->createElement('updated', $d->updated));
}

foreach($this->rulers as $r) {
$r = (object)$r;
$rulerElem = $dom->createElement('ruler');
$rulersElem->appendChild( $rulerElem);	

$rulerElem->appendChild( $dom->createElement('id', $r->id));
$rulerElem->appendChild( $dom->createElement('name', $r->issuer));
$rulerElem->appendChild( $dom->createElement('region', $r->region));
$rulerElem->appendChild( $dom->createElement('url',$site . $this->url(array('module' => $module,
'controller' => $controller,'action' => 'ruler','id' => $r->id),NULL,true) ));
$rulersElem->appendChild( $rulerElem );	
}

//foreach($this->images as $i){
//$i = (object)$i;
//$recordElem = $dom->createElement('record');
//$imageElem->appendChild( $recordElem);
//$recordElem->appendChild( $dom->createElement('findID', $i->old_findID));
//$recordElem->appendChild( $dom->createElement('objectType', $i->objecttype));
//$recordElem->appendChild( $dom->createElement('broadPeriod', $i->broadperiod));
//$recordElem->appendChild( $dom->createElement('url', $site . '/database/artefacts/record/id/' . $i->id));
//$recordElem->appendChild( $dom->createElement('thumbnail', $site . ' /images/' . $i->id . '.jpg'));
//}
$regions->appendChild( $regionElem );
}

$dom->appendChild( $regions );

$xmlData  = $dom->saveXML();
echo $xmlData;
