<?php
$this->headTitle('Edit quote/ announcement');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

<?php echo $this->form; ?>

<?php
$this->jQuery()->addJavascriptFile(
    $this->baseUrl() . '/js/bootstrap-datepicker-v1.9.0.js',
    $type = 'text/javascript'
);
$this->headLink()->appendStylesheet('/css/bootstrap-datepicker.css');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
    $(document).ready(function() {
    var datePickerSettings = {
        endDate: (new Date((new Date()).getFullYear() + 1, 12, 0)),
        format: 'yyyy-mm-dd',
    };
    $("#expire").datepicker(datePickerSettings);
    $('form').areYouSure();
    $("form").submit(function() {
        $(":submit", this).attr("disabled", "disabled");
    });
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>