<?php 
	$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-datepicker.js',$type='text/javascript');
	$this->headTitle('Edit quote/ announcement');?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {
$("#expire").datepicker({ maxDate: '+1y' });
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
<h2><?php echo $this->title();?></h2>
<?php echo $this->form;?>