<?php
$this->headTitle('Edit quote/ announcement');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

<?php echo $this->form; ?>

<?php $this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-datepicker.js', $type = 'text/javascript'); ?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
    $(document).ready(function() {
    $("#expire").datepicker({ maxDate: '+1y' });
    $('form').areYouSure();
    $("form").submit(function() {
    $(":submit", this).attr("disabled", "disabled");
    });
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>