<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$stories  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$stories->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('totalItems',$this->data['total']));
$meta->appendChild( $dom->createElement('currentPage',$this->data['pageNumber']));
$meta->appendChild( $dom->createElement('totalPages',ceil($this->data['total']/ $this->data['itemsReturned'])));

$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$storiesElem = $dom->createElement('guardianStories');
foreach($this->guardianStories["guardianStory"] as $story){
$tags = array_slice($story,12);
$story = array_slice($story,0,12);
$storyElem = $dom->createElement('story');
   foreach($story as $k => $v){
      
       $storyElem->appendChild( $dom->createElement($k, htmlspecialchars($v))); 
   }
//$tagsElem = $dom->createElement('tags');
//foreach($tags as $t){
//foreach($t as $a){
//		$tagElem = $dom->createElement('tag');
//		$tagElem->appendChild( $dom->createElement('term',htmlspecialchars($a['tag'])));
//		$tagElem->appendChild( $dom->createElement('url',htmlspecialchars($a['tagUrl'])));
//		$tagsElem->appendChild($tagElem);
//}
//	
//}
//$storyElem->appendChild($tagsElem);
$storiesElem->appendChild( $storyElem );
}
$stories->appendChild($storiesElem);
$dom->appendChild( $stories );

$xmlData  = $dom->saveXML();
echo $xmlData;
