<?php
Zend_Controller_Front::getInstance()->getResponse()->setHeader("Content-type", 'application/rss+xml');
$feed =  new Zend_Feed_Writer_Feed();
$feed->setTitle('News stories about the Scheme in the Guardian');
$feed->setDescription('All news stories that mention the Scheme within the Guardian API');
$feed->setLink($this->serverUrl());
$feed->setFeedLink($this->curUrl(), 'rss');
$feed->setLastBuildDate();
$feed->setDateModified();
 Zend_Date::setOptions(array(
    'format_type'   => 'iso'
));

foreach($this->guardianStories['guardianStory'] as $e){

$entry = $feed->createEntry();
$entry->setTitle($e['headline']);
$entry->setLink($e['url']);
//$entry->addAuthor(array(
//    'name'  => $e['byline'],
//));
$entry->setDateCreated(Zend_Date::now());
if(!is_null($e['standfirst'])){
$desc = $e['standfirst'];
} else {
$desc = $e['linkText'];
}
$updated = strtotime($e['pubDate']);
$len = strlen($e['content']);
if($len == 61){
	$content = 'Content only available on the Guardian site';

} else {
$content = strip_tags($this->ellipsisstring($e['content'],600));
}
$entry->setDescription(htmlspecialchars(strip_tags($desc)));
$entry->setContent($content);
$entry->setDateModified($updated);
$entry->setDateCreated(time());
$feed->addEntry($entry);

}
$out = $feed->export('rss');
echo $out;