<?php 
echo $this->partialLoop('partials/news/guardianNewsArticle.phtml',$this->story);
?>
<h3 class="lead">Related Content</h3>
<ul>
<?php foreach($this->related as $related): ?>
    <?php $params = array(
    'module' => 'news',
    'controller' => 'guardian',
    'action' => 'story',
    'id' => urlencode($related['id'])
        );
    ?>
<li><a href="<?php echo $this->url($params,null,true);?>"><?php echo $related['webTitle'];?></a></li>
<?php endforeach;?>
</ul>