<?php
$this->headTitle('A list of Arts Council England accredited museums');
$this->metaBase()
    ->setDescription('A list of accredited Arts Council England museums in the UK')
    ->setSubject('ACE museums')
    ->setKeywords('museums,accredited,treasure')
    ->generate();
?>
<h2 class="lead">
   A list of Arts Council England accredited museums
</h2>

<p>
   A list of Arts Council England accredited museums can be found <a href="https://www.artscouncil.org.uk/accreditation-scheme/about-accreditation#section-4">here</a>.
</p>

<p>
   Further information on the museum accreditation scheme can be found <a href="https://www.artscouncil.org.uk/supporting-arts-museums-and-libraries/museums-accreditation-scheme"/>here</a>.
</p>
