<div class="sidebar-nav col-md-3">
    <ul id="menu1" class="menu nav nav-stacked nav-pills collapsible">
        <li <?php echo $this->currentPage()->active('about', 'index', 'index'); ?>>
            <a href="<?php echo $this->url(array('module' => 'about', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"
               title="About the Scheme"><i class=" icon-question-sign"></i>About the Scheme</a>
        </li>
        <li <?php echo $this->currentPage()->active('about', 'vacancies', 'index'); ?>>
            <a href="<?php echo $this->url(array('module' => 'about', 'controller' => 'vacancies', 'action' => 'index'), 'default', true); ?>"
               title="Current vacancy listing"><i class="icon-user"></i>Vacancies</a>
        </li>
        <li <?php echo $this->currentPage()->active('about', 'vacancies', 'archives'); ?>>
            <a href="<?php echo $this->url(array('module' => 'about', 'controller' => 'vacancies', 'action' => 'archives'), 'default', true); ?>"
               title="Archived vacancy lists"><i class="icon-user"></i>Archived vacancies</a>
        </li>
        <li <?php echo $this->currentPage()->active('about', 'alumni', 'index'); ?>>
            <a href="<?php echo $this->url(array('module' => 'about', 'controller' => 'alumni'), null, true); ?>"
               title="View former staff details"><i class="icon-list"></i>Former staff</a>
        </li>
        <li <?php echo $this->currentPage()->active('about', 'logoandbranding', 'index'); ?>>
            <a href="<?php echo $this->url(array('module' => 'about', 'controller' => 'logoandbranding', 'action' => 'index'), 'default', true); ?>"
               title="The Scheme's logo and branding guidelines"><i class="icon-exclamation-sign"></i>Logo and branding</a>
        </li>
    </ul>
</div>