<div class="sidebar-nav col-md-3">
    <ul id="menu1" class="nav nav-stacked nav-pills collapsible menu">
        <li <?php echo $this->currentPage()->active('getinvolved', 'index', 'index'); ?>><a
                href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'index'), 'default', true); ?>"
                title="How to report your finds"><i class="icon-info-sign"></i>Report your finds</a></li>
        <li <?php echo $this->currentPage()->active('getinvolved', 'faq', 'index'); ?>><a
                href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'faq'), 'default', true); ?>"
                title="Frequently asked questions"><i class="icon-question-sign"></i> FAQs</a></li>
        <li <?php
        $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
        if ($controller == 'guides') {
            echo 'class="expandfirst"';
        }; ?>>
            <a href="#"><i class="icon-folder-open"></i>Guidance and briefings</a>
            <ul class="nav nav-pills nav-stacked menuindent">
		<li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'ngr'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'ngr'), 'guides', true); ?>"
                        title="How to Take a Grid">How to Take a Grid Reference</a></li>
                <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'gps'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'gps'), 'guides', true); ?>"
                        title="How to Use a GPS">How to Use a GPS</a>
                </li>
                <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'codeofpractice'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'codeofpractice'), 'guides', true); ?>"
                        title="Code of Practice">Code of Practice</a>
                </li>
                <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'rallycode'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'rallycode'), 'guides', true); ?>"
                        title="Rally Organiser's Code of Practice">Rally Code of Practice</a>
                </li>
                <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'guidancelandowners'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'guidancelandowners'), 'guides', true); ?>"
                        title="Guidance for Landowners">Guidance for Landowners</a>
                </li>
                 <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'recordingguidance'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'recordingguidance'), 'guides', true); ?>"
                        title="Recording Guidance">Recording Guidance</a>
                </li>
                <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'pressures'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'pressures'), 'guides', true); ?>"
                        title="Presures for FLOs">FLO Working Pressures</a>
                </li>
                <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'helpusrecordthepast'); ?>><a
                        href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'helpusrecordthepast'), 'guides', true); ?>"
                        title="Help Us Record the Past">Help Us Record the Past</a>
                </li>
                <li <?php echo $this->currentPage()->active('getinvolved', 'guides', 'index', 'Managing/Meeting Finder’s Expectations '); ?>><a
                            href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'guides', 'action' => 'index', 'slug' => 'expectations'), 'guides', true); ?>"
                            title="Help Us Record the Past">Managing/Meeting Finder’s Expectations</a>
                </li>
            </ul>
        </li>
        <li <?php echo $this->currentPage()->active('getinvolved', 'volunteering', 'index'); ?>><a
                href="<?php echo $this->url(array('module' => 'getinvolved', 'controller' => 'volunteering'), 'default', true); ?>"
                title="Volunteer opportunities with the Scheme"><i class="icon-user"></i> Volunteer opportunities</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'volunteerrecording'), 'default', true); ?>"
               title="Learn more about recording"><i class="icon-eye-open"></i>Volunteer recording guide</a></li>
    </ul>
</div>
