<div class="sidebar-nav col-md-3">
    <ul id="menu1" class="menu nav nav-stacked nav-pills collapsible">
        <li <?php echo $this->currentPage()->active('info', 'index', 'index'); ?>><a
                href="<?php echo $this->url(array('module' => 'info'), 'default', true); ?>"
                title="Information about our site"><i class="icon-info-sign"></i>About our site</a>
        </li>
        <li <?php echo $this->currentPage()->active('info', 'advice', 'index', 'accessibility'); ?>><a
                href="<?php echo $this->url(array('module' => 'info', 'controller' => 'advice', 'action' => 'index', 'slug' => 'accessibility'), 'information', true); ?>"
                title="Information about our site\'s accessibility"><i class="icon-cogs"></i>Accessibility</a>
        </li>
        <li <?php echo $this->currentPage()->active('info', 'advice', 'index', 'termsandconditions'); ?>><a
                href="<?php echo $this->url(array('module' => 'info', 'controller' => 'advice', 'action' => 'index', 'slug' => 'termsandconditions'), 'information', true); ?>"
                title="Read about our terms and conditions - nothing onerous"><i class="icon-warning-sign"></i>Terms of Use</a></li>
        <li <?php echo $this->currentPage()->active('info', 'advice', 'index', 'privacy'); ?>><a
                href="<?php echo $this->url(array('module' => 'info', 'controller' => 'advice', 'action' => 'index', 'slug' => 'privacy'), 'information', true); ?>"
                title="Read about our privacy policy"><i class="icon-warning-sign"></i>Privacy</a></li>
        <li><a href="https://www.britishmuseum.org/cookies" target="_blank"
               title="Information about our site's cookies"><i class="icon-warning-sign"></i>Cookie information </a></li>
        <li <?php echo $this->currentPage()->active('info', 'advice', 'index', 'foi'); ?>><a
                href="<?php echo $this->url(array('module' => 'info', 'controller' => 'advice', 'action' => 'index', 'slug' => 'foi'), 'information', true); ?>"
                title="Freedom of information requests and how to submit one"><i class="icon-warning-sign"></i>Freedom of Information</a></li>
        <li <?php echo $this->currentPage()->active('help', 'database', 'index'); ?>><a
                href="<?php echo $this->url(array('module' => 'help', 'controller' => 'database'), 'default', true); ?>"
                title="Help with using our site"><i class="icon-question-sign"></i>Help</a></li>
    </ul>
</div>
