<div class="sidebar-nav col-md-3" >
	<ul id="menu1" class="menu nav nav-stacked nav-pills collapsible">
		<li <?php echo $this->currentPage()->active('info','index','index');?>><a href="<?php echo $this->url(array('module' => 'info'),'default',true);?>" title="Information about our site">About our site</a></li>
		<li <?php echo $this->currentPage()->active('info','advice','index', 'accessibility');?>><a href="<?php echo $this->url(array('module' => 'info','controller' => 'advice','action' => 'index','slug' => 'accessibility'),'information',true);?>" title="Information about our site\'s accessibility">Accessibility</a></li>
		<li <?php echo $this->currentPage()->active('info','advice','index', 'termsandconditions');?>><a href="<?php echo $this->url(array('module' => 'info','controller' => 'advice','action' => 'index','slug' => 'termsandconditions'),'information',true);?>" title="Read about our terms and conditions - nothing onerous">Terms of Use</a></li>
		<li <?php echo $this->currentPage()->active('info','advice','index', 'privacy');?>><a href="<?php echo $this->url(array('module' => 'info','controller' => 'advice','action' => 'index','slug' => 'privacy'),'information',true);?>" title="Read about our privacy policy">Privacy &amp; Cookies</a></li>
		<li <?php echo $this->currentPage()->active('info','advice','index', 'foi');?>><a href="<?php echo $this->url(array('module' => 'info','controller' => 'advice','action'=> 'index','slug' => 'foi'),'information',true);?>" title="Freedom of information requests and how to submit one">Freedom of Information</a></li>
		<li <?php echo $this->currentPage()->active('help','database','index');?>><a href="<?php echo $this->url(array('module' => 'help','controller' => 'database'),'default',true);?>" title="Help with using our site">Help</a></li>
	</ul>
</div>
