<div class="sidebar-nav col-md-3" >
	<ul id="menu1" class="menu nav nav-stacked nav-pills collapsible">
		<li <?php echo $this->currentPage()->active('volunteerrecording','index','index');?>>
			<a href="<?php echo $this->url(array('module' => 'volunteerrecording'),'default',true);?>"
			title="Introduction to recording finds">Introduction</a></li>
                <li><a href="/documents/volunteers/0-sr-cover.pdf">Front cover</a></li>
                <li><a href="/documents/volunteers/1-sr-contents.pdf">Contents</a></li>
                <li><a href="/documents/volunteers/2-sr-introduction.pdf">Introduction</a></li>
                <li><a href="/documents/volunteers/3-sr-getting-started.pdf">Getting started on the database</a></li>
                <li><a href="/documents/volunteers/4-sr-using-db.pdf">Using the database to add information</a></li>
                <li><a href="/documents/volunteers/5-sr-object-id.pdf">Object identification and description</a></li>
                <li><a href="/documents/volunteers/6-sr-photographs.pdf">Taking and editing photographs</a></li>
                <li><a href="/documents/volunteers/7-sr-using-database.pdf">Using the database to get information</a></li>
                <li><a href="/documents/volunteers/8-sr-guidance.pdf">Guidebook guidance</a></li>
                <li><a href="/documents/volunteers/9-sr-back-cover.pdf">Back cover</a></li>
	</ul>
</div>
