<?php
$dom 	  = new DomDocument("1.0", "UTF-8");
$news  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$news->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->news)));

$activitiesElem = $dom->createElement('stories');
$news->appendChild($activitiesElem);
// set it's attribute
foreach($this->news as $r){
$activityElem = $dom->createElement('story');
foreach($r as $k => $v){
$v = strip_tags($v);
$activityElem->appendChild( $dom->createElement($k, $v));
}
$activitiesElem->appendChild( $activityElem );
}

$dom->appendChild( $news );

$xmlData  = $dom->saveXML();
echo $xmlData;