<?php
$feed = new Zend_Feed_Writer_Feed;
$feed->setTitle('News from the Portable Antiquities Scheme');
$feed->setDescription('An rss feed of news stories from the Scheme');
$feed->setLink($this->serverUrl());
$feed->setFeedLink($this->curUrl()->__toString(), 'rss');

$feed->setDateModified(time());
$feed->addHub('http://pubsubhubbub.appspot.com/');
foreach ($this->news as $result) {
	
$result = (object)$result;
$entry = $feed->createEntry();
$entry->setTitle($result->title);
$url = $this->url(array(
    'module' => 'news', 
    'controller' => 'story',
    'action' => 'index',
    'id' => $result->id),
        'newsstory', true);
$entry->setLink($this->serverUrl() . $url);
$entry->addAuthor(array(
    'name'  => $result->author,
    'email' => 'info@finds.org.uk',
    'uri'   => $this->serverUrl() . '/contacts' ,
));
if(!is_null($result->updated)){
    $entry->setDateModified(strtotime($result->updated));
}
$entry->setDateCreated(strtotime($result->created));
if(!is_null($result->summary)){
$entry->setDescription($result->summary);

$entry->setContent(strip_tags($result->contents));
}
$feed->addEntry($entry);
}
echo $feed->export('rss');