<?php
$feedArray = array(

			'title' => 'The lastest news from the Portable Antiquities Scheme',
			'link' => $this->CurUrl(),
			'charset' => 'utf-8',
			'description' => 'All the news from around the regions of the Scheme',
			'author' => 'The Portable Antiquities Scheme',
			'image' => Zend_Registry::get('siteurl').'/images/logos/pas.gif',
			'email' => 'info@finds.org.uk',
			'copyright' => 'Creative Commons Licenced',
			'generator' => 'The Scheme database powered by Zend Framework and Dan\'s magic',
			'language' => 'en',
			'entries' => array()
		);


		foreach ($this->news as $new) {
			$feedArray['entries'][] = array(
				'title' => $new['title'],
				'link' => Zend_Registry::get('siteurl').'/news/stories/article/id/'.$new['id'],
				'guid' => Zend_Registry::get('siteurl').'/news/stories/article/id/'.$new['id'],
				'description' => strip_tags($new['summary']),
				'lastUpdate' => strtotime($new['updated']),
				'content' => strip_tags($new['summary']),
				);
		}
		
  		 $feed = Zend_Feed::importArray($feedArray,'atom');
		 $feed->send();
		
				?>