<?php
$this->headTitle('List of Scheme alumni');
$this->metaBase()
    ->setDescription('A list of all people who used to work for the Portable Antiquities Scheme')
    ->setSubject('alumni')
    ->setKeywords('alumni,scheme,head office,archaeology')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if(!empty($this->alumni)):?>
    <ul>
        <?php echo $this->partialLoop('partials/about/alumniList.phtml', $this->alumni); ?>
    </ul>
<?php else:?>
<p>No contacts available just now.</p>
<?php endif;?>