<?php
$this->headTitle('Add a new vacancy');
$this->metaBase()->setDescription($this->title())->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users'), 'default', true); ?>"
       class="btn btn-small btn-success">Return to users list</a>
<?php echo $this->form;?>
<?php
$this->jQuery()->addJavascriptFile(
    $this->baseUrl() . '/js/bootstrap-datepicker.js',
    $type = 'text/javascript'
);

$this->headLink()->appendStylesheet('/css/bootstrap-datepicker.css');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
    $(document).ready(function() {
        var datePickerSettings = {
            endDate: (new Date((new Date()).getFullYear() + 6, 12, 0)),
            format: 'yyyy-mm-dd',
        };

        $("#live").datepicker(datePickerSettings);
        $("#expire").datepicker(datePickerSettings);
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>