<?php 
	$this->headTitle('Delete a vacancy');
if ($this->vac) :?>
<h2>Delete vacancy details for: <?php echo $this->escape($this->vac->title); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->vac->title); ?> ' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'vacancies','action' =>'delete'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->vac->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?><h2>An error has occured</h2>
<p>Cannot find the requested vacancy's details.</p>
<?php endif;?>