<?php
$this->headTitle('Edit a Vacancy\'s details');
$this->metaBase()->setDescription($this->title())->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'vacancies'), 'default', true); ?>"
       class="btn btn-small btn-success">Return to vacancies list</a>
<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-datepicker.js', $type = 'text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/autocomplete.css');
?>