<?php
$this->headTitle('Edit a Vacancy\'s details');
$this->metaBase()->setDescription($this->title())->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-datepicker.js', $type = 'text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/autocomplete.css');
?>