<?php
   $this->headTitle('Delete staff role');
   $this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!is_null($this->role)) : ?>
    <h2 class="lead">Delete a staff role</h2>
    <p>Are you sure that you want to delete <b><em><?= $this->escape($this->role->role) ?></em></b></p>
    <form action="<?= $this->url(array('module' => 'admin', 'controller' => 'roles', 'action' => 'delete'), null, true) ?>" method="post">
        <div class="btn-toolbar">
            <input type="hidden" name="id" value="<?= $this->role->id ?>"/>
            <input type="submit" class="btn btn-danger" name="confirmDelete" value="Yes"/>
            <input type="submit" class="btn btn-default" name="confirmDelete" value="No"/>
        </div>
    </form>
<?php else: ?>
    <p>Cannot find the item requested.</p>
<?php endif; ?>
