<?php
$this->headTitle('Staff roles in use on the database');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<a href="<?php echo $this->url(
    array(
        'module' => 'admin', 'controller' => 'roles', 'action' => 'add'
    ),'default',true);?>" class="btn btn-small btn-info">Add a role</a>
<?php if (!empty($this->roles)): ?>
    <table class="table table-striped" summary="A list of all roles available on the database">
        <thead>
        <tr>
            <th>Role name</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/staffRoles.phtml', $this->roles); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No roles available.</p>
<?php endif; ?>