<?php
$this->headTitle('Post Medieval coin types');
$this->metaBase()->setSubject('Post Medieval numismatics')
    ->setDescription('A list of post medieval coin types')
    ->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->types)): ?>
    <table class="table table-striped" summary="<?php echo $this->title();?>">
        <caption><?php echo $this->title(); ?></caption>
        <thead>
        <tr>
            <th>Coin type</th>
            <th>Issuing ruler</th>
            <th>Issue date</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/numismatics/medieval/medievalTypes.phtml', $this->types); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->types, 'Elastic', 'structure/pagination.phtml'); ?>

<?php else: ?>
    <p>There are no coin types available.</p>
<?php endif; ?>