<?php $url = array('module' => 'database', 'controller' => 'artefacts', 'action' => 'record', 'id' => $this->id);?>
<abbr title="The Portable Antiquities Scheme">PAS</abbr> record number: <?php echo $this->old_findID; ?><br/>
Object type: <?php echo ucfirst($this->objecttype); ?><br/>
Broadperiod: <?php echo ucwords($this->broadperiod); ?><br/>
County of discovery: <?php echo ucwords(strtolower($this->county)); ?><br/>
Stable url: <a href="<?php echo $this->serverUrl();?><?php echo $this->url($url, null, true); ?>" title="<?php echo $this->old_findID ;?>: a <?php echo $this->broadperiod;?> <?php echo $this->objecttype; ?>"><?php echo $this->serverUrl(); ?><?php echo $this->url($url, null, true); ?></a>