<?php
$this->headTitle('Scheme news stories mapped by location');
$this->MetaBase('A map showing all of our georeferenced news stories that the Scheme has filed','map of stories','archaeology,news,stories,map,georeferenced');
$this->googleDynamicMap();
$this->inlineScript()->captureStart();
?>
    function load() {
      var map = new google.maps.Map(document.getElementById("map"), {
        center: new google.maps.LatLng(54.70235509327093, -3.2080078125),
        zoom: 6,
		scrollwheel:false,
        mapTypeId: 'terrain'
      });
      var infoWindow = new google.maps.InfoWindow;

      // Change this depending on the name of your PHP file
      downloadUrl("<?php echo $this->url(array(
		'module' => 'news','controller' => 'ajax',
		'action' => 'newsdata'),null,true);?>", function(data) {
        var xml = parseXml(data);
        var markers = xml.documentElement.getElementsByTagName("marker");
        for (var i = 0; i < markers.length; i++) {
          var title = markers[i].getAttribute("title");
          var id = markers[i].getAttribute("id");
          var point = new google.maps.LatLng(
              parseFloat(markers[i].getAttribute("lat")),
              parseFloat(markers[i].getAttribute("lon")));
          var url = "<?php echo $this->serverUrl();?>/news/stories/article/id/" + id;
          var content = markers[i].getAttribute("content")
          var html = "<h3><a href='" + url + "'>"+ title + "</a></h3>" + content;
          var marker = new google.maps.Marker({
            map: map,
            position: point,
            icon: "http://labs.google.com/ridefinder/images/mm_20_blue.png",
        	shadow: "http://labs.google.com/ridefinder/images/mm_20_shadow.png"
          });
          bindInfoWindow(marker, map, infoWindow, html);
        }
      });
    }

    function bindInfoWindow(marker, map, infoWindow, html) {
      google.maps.event.addListener(marker, 'click', function() {
        infoWindow.setContent(html);
        infoWindow.open(map, marker);
      });
    }

    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;

      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };

      request.open('GET', url, true);
      request.send(null);
    }

    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }

    function doNothing() {}

	window.onload = load;

<?php 
$this->inlineScript()->captureEnd();?>
<h2>Map of where our news comes from</h2>
<div id="map"></div>