<?php
$this->headTitle($this->title . ' '.$this->staffregions);
$this->headMeta($this->ellipsisstring($this->specification,200),'description');
?>
<h2><?php echo $this->escape($this->title);?> <?php echo $this->escape($this->staffregions);?></h2>
<?php
if($this->ExpiredJob($this->expire) == -1)  {
 echo '<p class="valid-0 jobexpire">This job is no longer available, it expired
     on the ' . $this->niceshortdate($this->expire).'</p>';
}
?>

<p>Salary: &pound; <?php echo $this->escape($this->salary);?></p>
<?php echo $this->specification ;?>
<p>Advert went live on: <?php echo $this->escape($this->niceshortdate($this->live));?>
<?php
$today = new Zend_Date(null, 'YYYY-MM-DD');
$datecompare =  new Zend_Date($this->expire);
$difference = $today->compare($datecompare, Zend_Date::DAY);
if($difference == -1) {
?>
<br />
Advert archived on: <?php echo $this->escape($this->niceshortdate($this->expire));?>
<?php }?>
</p>
