<?php
$this->headTitle('Personifications present on Roman coins');
$this->metaBase()->setDescription('A list of Roman personifications on Roman coins - deities, gods, symbols')
    ->setSubject('Roman Numismatics')
    ->setKeywords('roman,numsimatics,deity,symbol,god,deities')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>

<p>The reverse often shows a Roman deity (such as <a href="/romancoins/personifications/named/as/Jupiter"
                                                     title="Read about the reverse depiction of Jupiter">Jupiter</a> or
    <a href="/romancoins/personifications/named/as/Venus" title="Read about the reverse depiction of Venus">Venus</a>);
    a personification of a virtue (such as <a href="/romancoins/personifications/named/as/Aequitas"
                                              title="Read about the reverse depiction of Aequitas">Aequitas</a> meaning
    'fair-dealing') or something symbolic (such as <a href="/romancoins/personifications/named/as/Military+standards"
                                                      title="Read about the reverse depiction of Military standards">military</a>
    or <a title="Read about the reverse depiction of religious symbols"
          href="/romancoins/personifications/named/as/Priestly+objects">religous symbols</a>). The reverse inscriptions
    either name these figures or list the emperor's titles. The following examples of the Personifications of <a
        href="/romancoins/articles/page/victoryreverse"
        title="Read about how to decipher Victory's reverse">Victoria</a> (Victory) and <a
        href="/romancoins/articles/page/reversepax" title="Read about how to decipher Pax's reverse">Pax</a> (Peace)
    demonstrate how to work out who is shown on the reverse: </p>

<h3 class="lead">Gods present on coins</h3>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/personifications.phtml', $this->gods);?>
</ul>

<h3 class="lead">Virtues present</h3>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/personifications.phtml', $this->virtues);?>
</ul>

<h3 class="lead">Symbols</h3>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/personifications.phtml', $this->symbols);?>
</ul>
