<?php
$this->headTitle('All available full data dumps');
?>
<h2>Daily data dumps of entire database</h2>
<p>The below lists all available database dumps in zipped CSV format. This contains grid references and the following fields:</p>
<blockquote>
<p>id, old_findID, objecttype, broadperiod, periodFromName, periodToName, fromdate, todate, description, notes, workflow, materialTerm, secondaryMaterialTerm, 
subsequentActionTerm, discoveryMethod, datefound1, datefound2, TID, rallyName, weight, height, diameter, thickness, diameter, length, quantity, 
finder, identifier, recorder, denominationName, rulerName, mintName, obverseDescription, obverseLegend, reverseDescription, reverseLegend, 
tribeName, reeceID, cciNumber, mintmark, abcType, categoryTerm, typeTerm, moneyerName, reverseType, regionName, county, district, parish, knownas, 
gridref, gridSource, fourFigure, easting, northing, latitude, longitude, fourFigureLat, fourFigureLon, geohash, created, updated</p>
</blockquote>
<p>As of the 11th December, grid reference source and four figure Lat/Lon have been added to the download.</p>
<p>These files are hosted securely at Amazon's server farm and cost a couple of cents to download. So be wise young Jedi.</p>
<ul><?php echo $this->amazonDataDump();?></ul>