<?php
$this->headTitle('Our favourite images from other users.');
$this->metaBase()
        ->setDescription('A list of our favourite images that we have found on flickr from the creative commons community')
        ->setSubject('photos')
        ->setKeywords('favourites,flickr,archaeology,creative commons,portable antiquities');
?>
<h2><?php echo $this->title();?></h2>
<?php if($this->photos):?>
<?php
$photos = array();
foreach($this->photos->photo as $photo){
	$photos[] = (array)$photo;
}
echo $this->partialLoop('partials/flickr/favourite.phtml',$photos);
?>
<div class="row span16">
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
</div>
<?php else:?>
    <p>
        There are no favourites available at the moment
    </p>
<?php endif;?>