<?php
echo $this->flickrSetInfo()
        ->setSetId($this->pictures->photoset->id)
         ->setApiKey($this->getInvokeArg('bootstrap')->config->webservice->flickr->apikey);
?>
<?php if(count($this->pictures)):?>
<?php
$photos = array();
foreach($this->pictures->photoset->photo as $photo){
	$photos[] = (array)$photo;
}
echo $this->partialLoop('partials/flickr/set.phtml',$photos);?>
<div class="row span16">
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>
</div>
<?php else:?>
<p>There are no photos available with that tag.</p>
<?php endif;?>
