<?php 
$this->headTitle('All pictures tagged with ' . $this->tagtitle);
$this->metaBase()
        ->setDescription('A list of photos retrieved from the flickr api using creative commons searches on the tag ' 
. $this->tagtitle)
        ->setSubject('photos')
        ->setKeywords('photos,flickr,api,tagged,' . $this->tagtitle)
        ->generate();
?>
<h2 class="lead">
    <?php echo $this->title();?>
</h2>

<?php if(count($this->pictures)):?>
<?php echo $this->partialLoop('partials/flickr/set.phtml',$this->pictures);?>
<div class="row span16">
<?php echo $this->paginationControl($this->$paginator, 'Sliding', 'structure/pagination.phtml'); ?>
</div>
<?php else:?>
<p>There are no photos available with that tag.</p>
<?php endif;?>
