<?php
$this->headTitle('Add archaeological context');
$this->metaBase()
    ->setDescription('A form for entering archaeological contextual data')
    ->setKeywords('context,archaeology,hoards')
    ->generate();
?>
    <h2 class="lead">
        <?php echo $this->title(); ?>
    </h2>
<?php $url = array(
    'module' => 'database',
    'controller' => 'hoards',
    'action' => 'record',
    'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('id'));
?>
    <a href="<?php echo $this->url($url, 'default', true); ?>" class="btn btn-small btn-default"
       title="Return to record">Return to record</a>
<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {
$('form').areYouSure();
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
