<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$news  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$news->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));

foreach($this->news as $d){
$d = (object)$d;
$dynElem = $dom->createElement('story');
$dynElem->appendChild( $dom->createElement('id', $d->id));
$dynElem->appendChild( $dom->createElement('title', $d->title));
$dynElem->appendChild( $dom->createElement('contents', $d->contents));
$dynElem->appendChild( $dom->createElement('webLink', $d->link));
$dynElem->appendChild( $dom->createElement('keywords', $d->keywords));
$dynElem->appendChild( $dom->createElement('author', $d->author));
$dynElem->appendChild( $dom->createElement('editorNotes', $d->editorNotes));
$dynElem->appendChild( $dom->createElement('contactTelephone', $d->contactTel));
$dynElem->appendChild( $dom->createElement('contactEmail', $d->contactEmail));
$dynElem->appendChild( $dom->createElement('contactName', $d->contactName));
$news->appendChild( $dynElem );
}

$dom->appendChild( $news );

$xmlData  = $dom->saveXML();
echo $xmlData;
