<?php

$dom 	  = new DomDocument("1.0", "UTF-8");
$dom->createElement('markers');

$documentNode = $dom->createElement('markers');
$dom->appendChild($documentNode);

foreach($this->mapping as $result){
	
	
    if(!is_null($result['lon'])){
		$description = $this->purify($this->ellipsisstring($result['contents'],200));

		$marker = $dom->createElement('marker');
		$marker->setAttribute('id',$result['id']);
		$marker->setAttribute('lat', $result['lat']);
        $marker->setAttribute('lon', $result['lon']);
        $marker->setAttribute('content', $description);
        $marker->setAttribute('title', $result['title']);
		$documentNode->appendChild( $marker );
    }
}
$xmlData  = $dom->saveXML();
echo $xmlData;
