<?php
$this->headTitle('All Van Arsdell types recorded on the database');?>
<h2>Van Arsdell types</h2>
<?php if($this->va):?>
<table summary="A list of all Van Arsdell types in use" class="table table-striped">
<caption>All Van Arsdell types</caption>
<thead>
<tr>
<th>Type name</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/numismatics/va.phtml',$this->va);?>
</tbody>
</table>
<?php echo $this->paginationControl($this->va, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>No Allen types available</p>
<?php endif;?>