<?php
$this->headTitle('Van Arsdell types');
$this->metaBase()->setSubject('Iron Age Numismatics')
    ->setDescription('A list of Van Arsdell types used for recording coins')
    ->setKeywords('iron age,numismatics,archaeology')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if ($this->va): ?>
    <ul><?php echo $this->partialLoop('partials/numismatics/vanArsdellTypes.phtml', $this->va); ?></ul>
    <?php echo $this->paginationControl($this->va, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>No Allen types available</p>
<?php endif; ?>