<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();
$dom = new DomDocument("1.0", "UTF-8");
$types  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$types->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$mintsElem = $dom->createElement('vanArsdellTypes');
$tribeElem = $dom->createElement('type');

foreach($this->type as $k => $v){
$tribeElem->appendChild( $dom->createElement($k, $v));
}
$types->appendChild($mintsElem);
$mintsElem->appendChild( $tribeElem );
$dom->appendChild( $types );

$xmlData  = $dom->saveXML();
echo $xmlData;