<?php
$this->headTitle('Delete a copyright');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!empty($this->copyright)) : ?>
    <h2 class="lead">Delete content</h2>
    <p>Are you sure that you want to delete <?php echo $this->copyright->copyright; ?></p>
    <form action="<?php echo $this->url(
        array(
            'module' => 'admin', 'controller' => 'copyrights', 'action' => 'delete'
        ), null, true); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->copyright->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
    <?php else: ?>
    <h2 class="lead">An error has occured</h2>
    <p>Cannot find the requested copyright details.</p>
<?php endif; ?>