<?php
$this->headTitle('Administer copyright');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!empty($this->copyrights)): ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p><a class="btn btn-small btn-success" href="<?php echo $this->url(
            array('module' => 'admin', 'controller' => 'copyrights', 'action' => 'add'
            ), null, true); ?>" title="">Add a new copyright</a></p>
    <table class="table table-striped" summary="All copyrights entered on the system">
        <caption>All copyrights entered</caption>
        <thead>
        <tr>
            <th>Copyright</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/copyrightTable.phtml', $this->copyrights); ?>
        </tbody>

    </table>
    <?php echo $this->paginationControl($this->copyrights, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else: ?>
    <p>No copyright content found.</p>
<?php endif; ?>
