<?php
$this->headMeta('noodp', 'robots');
$this->headMeta('BJ0IxlmtPbri25v9zbMgcOFDOBuZmNacd9-friMs1_E', 'google-site-verification');
$this->jQuery()->addJavascriptFile('js/bootstrap-carousel.js', $type = 'text/javascript');
$this->headMeta($this->serverUrl() . '/assets/logos/axe.jpg', 'twitter:image');
?>


    <!-- Carousel
        ================================================== -->
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">

            <div class="item active">
                <img src="assets/carousel/head.jpg" alt="The Roman head from Brackley">

                <div class="container">
                    <div class="carousel-caption">
                        <?php echo $this->partialLoop('partials/content/articleLead.phtml', $this->contents); ?>
                    </div>
                </div>
            </div>

            <div class="item">
                <img src="assets/carousel/coinsHerts.jpg" alt="The gold coin hoard from Hertfordshire">

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Amazing discoveries.</h1>

                        <p class="lead">New finds are uncovered and reported daily. It is easy to get involved with the
                            Scheme and report your discoveries.</p>
                        <a class="btn btn-small btn-primary" href="/getinvolved">Learn more</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="assets/carousel/lucyEllis.jpg" alt="Lucy Ellis with the Holy Island hoard">

                <div class="container">
                    <div class="carousel-caption">
                        <h1>See more about what we do...</h1>

                        <p class="lead">Our images on Flickr are liberally licensed. You might find something that you
                            can use or learn more about our mission.</p>
                        <a class="btn btn-small btn-primary" href="https://flickr.com/finds">Browse our flickrstream</a>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

    <div class="row">
        <div class="span12">
            <h2>Coronavirus: important advice on reporting public finds, including potential Treasure, during the coming period</h2>
            <p>Under the Treasure Act 1996, it is a legal obligation for the finder to report potential Treasure. For all new finds of potential Treasure, finders must notify their local Finds Liaison Officer and/or the British Museum treasure team (in England) by <a href="mailto:treasure@britishmuseum.org">email</a>, with photographs of the object and full details of the findspot, finders' and landowners' details, and await further instruction. The necessary precautions mean there may be delays in the Treasure process. We thank finders, landowners, occupiers and everyone involved in the process for their understanding, patience and cooperation during this time.
            <p>Portable Antiquities Scheme staff will no longer meet finders in person or undertake outreach work until further notice. Most Portable Antiquities Scheme staff, including Finds Liaison Officers, will remain contactable by email, so, therefore, can advise on the recording of finds (such as self-recording). We ask that you temporarily retain your non-Treasure finds for full recording at a later date. Please ensure that you keep detailed records of the findspot in accordance with the <a href="https://finds.org.uk/getinvolved/guides/codeofpractice">Code of Practice for Responsible Metal-Detecting in England and Wales</a> 
            <p>Finders in <a href="https://museum.wales/portable-antiquities-scheme-in-wales/">Wales</a> and <a href="https://www.nidirect.gov.uk/articles/archaeology-and-treasure#toc-0">Northern Ireland</a> should contact the relevant authorities for advice.
            <p>Following the latest government social distancing guidance, advising everyone to stay at home to save lives and protect the NHS, do not metal detect during the current situation. All metal-detecting rallies should be cancelled.
        </div>
    </div>
    <br>
    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="span4">
            <img class="img-circle" width=150px height=150px src="assets/logos/treasure20.png">

            <h2 class="lead">Treasure 20</h2>

            <p>We’re celebrating 20 years since the commencement of the Treasure Act. Visit here to see what’s on show at your local museum!</p>

            <p><a class="btn" href="<?php echo $this->url(array('module' => 'treasure', 'controller' => 'advice', 'action' => 'index', 'slug' => 'treasure20'), 'treasure', true); ?>">Read more &raquo;</a></p>
        </div>
        <!-- /.span4 -->

        <div class="span4">
            <img class="img" src="/assets/logos/pas.jpg" width="213" height="104">

            <h2 class="lead">Search our database</h2>
            <?php echo $this->form; ?>

        </div>
        <!-- /.span4 -->

        <div class="span4">
            <img class="img-circle" src="assets/logos/bird.jpg">

            <h2 class="lead">Latest tweets</h2>
            <?php //echo $this->LatestTweets(); ?>
        </div>
        <!-- /.span4 -->
    </div><!-- /.row -->


    <hr class="featurette-divider">

    <div class="container marketing">
        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="span4">
                <img class="img-circle" src="assets/logos/penny.jpg">

                <h2 class="lead">Learn about coins</h2>

                <p>
                    <a href="<?php echo $this->url(array('module' => 'ironagecoins'), 'default', true); ?>"
                       title="Learn about Iron age coins">Iron Age</a><br/>
                    <a href="<?php echo $this->url(array('module' => 'romancoins'), 'default', true); ?>"
                       title="Learn about Roman coins">Roman</a><br/>
                    <a href="<?php echo $this->url(array('module' => 'byzantinecoins'), 'default', true); ?>"
                       title="Learn about Byzantine coins">Byzantine</a><br/>
                    <a href="<?php echo $this->url(array('module' => 'greekromancoins'), 'default', true); ?>"
                       title="Learn about Greek and roman provincial coins">Greek &amp; Roman Provincial</a><br/>
                    <a href="<?php echo $this->url(array('module' => 'earlymedievalcoins'), 'default', true); ?>"
                       title="Learn about Early Medieval coins">Early Medieval</a><br/>
                    <a href="<?php echo $this->url(array('module' => 'medievalcoins'), 'default', true); ?>"
                       title="Learn about Medieval coins">Medieval</a><br/>
                    <a href="<?php echo $this->url(array('module' => 'postmedievalcoins'), 'default', true); ?>"
                       title="Learn about Post medieval coins">Post Medieval</a><br/>
                </p>
            </div>
            <!-- /.span4 -->
            <div class="span4">
                <img class="img-circle" src="assets/logos/hoard.jpg">
                <?php echo $this->partial('partials/content/staffs.phtml', null); ?>

            </div>
            <!-- /.span4 -->
            <div class="span4">
                <img class="img-circle" src="assets/logos/axe.jpg">
                <?php echo $this->partial('partials/content/bronzeAgeWidget.phtml', null); ?>
            </div>
            <!-- /.span4 -->
        </div>
        <!-- /.row -->
        <hr class="featurette-divider">
        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="span4">
                <img class="img-circle" src="assets/logos/doa.jpg">

                <h2 class="lead">Day of Archaeology</h2>

                <p>The Day of Archaeology project, documents what 1000s of archaeologists do as a career. Find out more.</p>

                <p><a class="btn" href="http://dayofarchaeology.com">Read more &raquo;</a></p>
            </div>
            <!-- /.span4 -->

            <div class="span4">
		<img class="img-circle" width="185px" src="https://farm2.staticflickr.com/1087/1072822674_225a538fe8.jpg ">

                <h2 class="lead">PASt Explorers</h2>

                <p>Get involved with the Scheme as part of the PASt Explorers project.</p>

                <p><a class="btn" href="/getinvolved">Read more &raquo;</a></p>
            </div>
            <!-- /.span4 -->

            <div class="span4">
                <img class="img-circle" src="assets/logos/research.jpg">

                <h2 class="lead">Research in progress</h2>

                <p>The Scheme's database provides the basis of hundreds of research projects and has enabled the Scheme to
                    gain funding for several large grants - Leverhulme and AHRC funding for instance.</p>

                <p><a class="btn" href="<?php echo $this->url(array('module' => 'research'), 'default', true); ?>">Read
                        more &raquo;</a></p>
            </div>
            <!-- /.span4 -->
        </div>
        <!-- /.row -->


        <!-- START THE FEATURETTES -->

        <!--  <hr class="featurette-divider"> -->
        <?php
        //        echo $this->partialLoop('partials/index/news.phtml',$this->news);
        ?>
        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->
    </div>

<?php $this->jQuery()->javascriptCaptureStart() ?>
    $('.myCarousel').carousel({
    interval: 2000
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<?php $this->placeholder('searchForm')->captureStart(); ?>
<?php echo $this->form; ?>
<?php $this->placeholder('searchForm')->captureEnd();
