<div class="row-fluid">
<?php echo $this->partialLoop('partials/content/article.phtml',$this->contents);?>
</div>
<div class="row-fluid">
<section id="carousel">
        <div class="span10">

          <div id="myCarousel" class="carousel slide">
            <div class="carousel-inner">
              <div class="item active">
                <img src="http://farm2.staticflickr.com/1411/971953847_012aab06ac_o.jpg" alt="">
                <div class="carousel-caption">
                  <h4>The Viking hordes fight on the BM lawns</h4>
                  <p>Viking re-enactors battle for their lives at a Museum event</p>
                </div>
              </div>
              <div class="item">
                <img src="http://farm2.staticflickr.com/1149/971947585_d4de864f95_b.jpg" alt="">
                <div class="carousel-caption">
                  <h4>Drawing finds</h4>
                  <p>Surrey Finds Liaison Officer David Williams drawing objects</p>
                </div>
              </div>
              <div class="item">
                <img src="http://farm5.staticflickr.com/4131/5200670881_373ed82088_b.jpg" alt="">
                <div class="carousel-caption">
                  <h4>The magnificent Frome hoard</h4>
                  <p>150 kg of Roman coins were found by detectorist Dave Crisp.</p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
          </div>

        </div>
      </div>
    </section>
    </div>
 <?php $this->jQuery()->javascriptCaptureStart()?>
    $('.myCarousel').carousel({
  interval: 2000
});
<?php $this->jQuery()->javascriptCaptureEnd()?>


