<?php
/** A view for listing upcoming events
 *
 * @author Daniel Pett <dpett at britishmuseum.org>
 * @version 1
 * @copyright (c) 2014, Daniel Pett
 */
?>
<?php
$this->headTitle('Upcoming Scheme Events');
$this->metaBase()->setDescription('An overview of our attendance of upcoming events')
    ->setSubject('Events')
    ->setKeywords('events,listings,archaeology')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>

<?php if (!empty($this->events)): ?>

    <table class="table table-striped" summary="List of all upcoming scheme events">
        <caption>List of upcoming Scheme events</caption>
        <thead>
        <tr>
            <th>Date of event</th>
            <th>Event title</th>
            <th>Location</th>
            <th>Type</th>
            <th>Organised by</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/news/upcoming.phtml', $this->events); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>There are no upcoming events available to you on this date.</p>
<?php endif; ?>