<?php echo $this->partialLoop('partials/numismatics/romanDenom.phtml', $this->denoms) ;?>
<?php if(count($this->emps)):?>
<h3>Issued by</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/empDenom.phtml', $this->emps);?>
</ul>
<?php endif;?>
<?php echo $this->latestRecords()->setQuery('denomination:' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>
<?php echo $this->coinStatsSolr()->setDenomination(Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>