<?php
$this->headTitle('Denominations issued during the Roman Empire');
$this->headMeta('Daniel Pett','dc.creator')
->headMeta('The Portable Antiquities Scheme','dc.publisher')
->headMeta('The Roman Empire issued a variety of denominations through different mints and issuers. This page
outlines the available denominations catalogued on our database','description')
->headMeta('roman,coins,denominations,empire,in use,portable antiquities,numismatics','dc.keywords')
->headMeta($this->curUrl(),'dc.identifier')
->headMeta('CC NC-BY-SA','dc.rights');
?>
<h2>Roman denominations</h2>
<p>The following coins were issued during the Roman Empire.</p>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/denominations.phtml',$this->denominations);?>
</ul>

