<?php
$this->headTitle('Denominations issued during the Roman Empire');
$this->metaBase()->setDescription('The Roman Empire issued a variety of denominations through different mints and issuers. This page
outlines the available denominations catalogued on our database')
    ->setKeywords('roman,coins,denominations,empire,in use,portable antiquities,numismatics')
    ->setSubject('Roman Numismatics')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<p>The following coins were issued during the Roman Empire.</p>
<ul>
    <?php echo $this->partialLoop('partials/numismatics/denominations.phtml', $this->denominations); ?>
</ul>

