<?php $this->headTitle('All users on our system');?>
<h2>Users on our database</h2>
<?php if($this->users):?>
<div class="row-fluid">
<ul class="thumbnails">
<?php echo $this->partialLoop('partials/users/usersList.phtml',$this->users);?>
</ul>
</div>
<?php echo $this->paginationControl($this->users, 'Elastic', 'structure/pagination.phtml'); ?>
<?php else:?>
<p>No users are available to your profile</p>
<?php endif;?>