<li id="record-<?php echo $this->linkid; ?>" class="record">
    <a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'artefacts', 'action' => 'record', 'id' => $this->findID), null, true); ?>"
       title="View record details"><?php echo $this->old_findID; ?></a> <?php echo $this->objecttype; ?> <?php echo $this->broadperiod; ?>
    : created by <?php echo $this->fullname; ?>
</li>