<tr>
    <td>
        <a href="<?php echo $this->url(array('module' => 'database','controller' => 'organisations','action' => 'organisation','id' => $this->escape($this->id)),null,true);?>" title="View <?php echo $this->escape($this->name);?> details"><?php echo $this->escape($this->name);?></a>
    </td> 
    <td>
        <?php if (!is_null($this->county)): ?>
            <?php echo $this->county; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
    <td>
        <?php if (!is_null($this->fullname)): ?>
            <a href="<?php echo $this->url(array('module'=> 'database', 'controller' => 'people', 'action' => 'person', 'id' => $this->peopleID),'default', true);?>"><?php echo $this->fullname; ?></a>
        <?php else: ?>
            -
        <?php endif; ?>
    </td> 
    <td>
        <div class="btn-group">
        <a class="btn btn-mini" href="<?php echo $this->url(array(
            'module' => 'database',
            'controller' => 'organisations',
            'action' => 'edit',
            'id' => $this->id)
                ,null,true);?>" title="Edit <?php echo $this->name;?>'s details">Edit</a>
        <a class="btn btn-mini" href="<?php echo $this->url(array(
            'module' => 'database',
            'controller' => 'organisations',
            'action' => 'delete',
            'id' => $this->id),null,true);?>" title="Delete <?php echo $this->name;?>">Delete</a>
        </div>
    </td>
</tr>