<tr>
    <td><a href="<?php echo $this->url(array(
            'module' => 'database',
            'controller' => 'people',
            'action' => 'person',
            'id' => $this->id),
            null, true); ?>" title="View <?php echo ucfirst($this->forename); ?>
        <?php echo ucfirst($this->surname); ?>'s details"><?php echo
            ucfirst($this->forename); ?> <?php echo ucfirst($this->surname); ?></a>
    </td>
    <td>
        <?php if (!is_null($this->county)): ?>
            <?php echo $this->county; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
    <td>
        <?php if (!is_null($this->organisation)): ?>
            <?php echo $this->organisation; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
    <td>
        <?php if (!is_null($this->activity)): ?>
            <?php echo $this->activity; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
    <td>
        <div class="btn-group">
            <a class="btn-mini btn btn-info" href="<?php echo $this->url(array(
                'module' => 'database',
                'controller' => 'people',
                'action' => 'edit',
                'id' => $this->id), null, true); ?>" title="Edit <?php echo $this->forename; ?>
    <?php echo $this->surname; ?>">Edit</a> <a class="btn-mini btn btn-danger" href="<?php echo
            $this->url(array(
                'module' => 'database',
                'controller' => 'people',
                'action' => 'delete',
                'id' => $this->id), null, true); ?>" title="Delete <?php echo $this->forename; ?>
    <?php echo $this->surname; ?>">Delete</a>
        </div>
    </td>
</tr>