<?php
$this->headTitle('Report an error relating to ' . $this->old_findID);
$this->metaBase()->setDescription('Using the form on this page, an error report can be submitted
    for the record : ' . $this->old_findID)
    ->setKeywords('report,error,portable,antiquities,' . $this->old_findID)
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<p>Thank you for taking the time to report an error about this find. The error
    report will be sent to:
</p>
<h3 class="lead">Finds Adviser(s) responsible</h3>
<?php echo $this->relevantAdviser()->setObjectType($this->objecttype)->setBroadperiod($this->broadperiod); ?>
<h3 class="lead">Finds Liaison Officer(s) responsible</h3>
<?php echo $this->relevantFlo()->setFindID($this->id); ?>
