<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 02/02/15
 * Time: 23:08
 */
?>
<?php $dates = array($this->numdate1, $this->numdate2); ?>
<?php if (array_filter($dates)): ?>
    <?php
    $this->headLink()->appendStylesheet('https://s3.amazonaws.com/cdn.knightlab.com/libs/timeline/latest/css/timeline.css');
    $this->jQuery()->addJavascriptFile('https://s3.amazonaws.com/cdn.knightlab.com/libs/timeline/latest/js/timeline-min.js');
    $this->jQuery()->addJavascriptFile('https://s3.amazonaws.com/cdn.knightlab.com/libs/timeline/latest/js/storyjs-embed.js');
    ?>
    <h4 class="lead">Timeline of associated dates</h4>
    <div id="objectTimeline"></div>
    <?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function() {
    createStoryJS({
    type:       'timeline',
    width:      '100%',
    height:     '400',
    source:     '/database/ajax/timeline/id/<?php echo $this->id; ?>/format/json',
    embed_id:   'objectTimeline',
    hash_bookmark: true,
    debug: true
    });
    });
    <?php $this->jQuery()->javascriptCaptureEnd(); ?>
<?php endif; ?>
