<?php
$dom = new DomDocument("1.0", "UTF-8");
$dom->createElement('markers');
$documentNode = $dom->createElement('markers');
$dom->appendChild($documentNode);

//echo "<br> tHIS IS TEST FOR THE  app/modules/default/views/scripts/ajax/staffdata.phtml. <br>";
foreach ($this->contacts as $contact) {
    $url = $this->serverUrl() . '/contacts/staff/profile/id/';
    if (!is_null($contact['longitude'])) {
        $title = $contact['firstname'] . ' ' . $contact['lastname'];
        $content = '<a href="' . $url . $contact['id'] . '"><h3 class="lead">' . $title . '</h3></a>';
        //$content .= '<p>' $contact['address_2'] . '</p>';
	$content .= '<p>' .  $contact['address_1'] . '</br>' . $contact['address_2'] . '</br>';
	$content .= $contact['county'] . '</br>' .  $contact['postcode'] . '</p>';
        $marker = $dom->createElement('marker');
        $marker->setAttribute('lat', $contact['latitude']);
        $marker->setAttribute('lng', $contact['longitude']);
        $marker->setAttribute('title', $title);
        $marker->setAttribute('id', $contact['id']);
        $marker->setAttribute('content', $content);
        $documentNode->appendChild($marker);
    }
}
$xmlData = $dom->saveXML();
echo $xmlData;
