<?php
$this->headTitle('Edit an organisation\'s details');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinitpeople1.js',$type='text/javascript'); 
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title();?></h2>
<?php $url = array(
    'module' => 'database',
    'controller' => 'organisations',
    'action' => 'organisation',
    'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('id'));
?>
    <a href="<?php echo $this->url($url, 'default', true); ?>" class="btn btn-small btn-success"
       title="Return to record">Return to record</a>
<?php echo $this->form ;?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function() {
    $('form').areYouSure();
    });
<?php $this->jQuery()->javascriptCaptureEnd(); ?>