<?php 
$module =  Zend_Controller_Front::getInstance()->getRequest()->getModuleName();

$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$ctrllr = strtolower($controller);
?>
<li><a href="<?php echo $this->url(array('module' => $module,'controller' => $ctrllr, 'action' => 'year','date' => $this->year),null,true);?>" title="View archived records for <?php echo $this->year;?>"><?php echo $this->year;?></a></li>