<h3><?php echo $this->name;?></h3>
<p><?php echo $this->niceshortdate($this->eventStartDate);?></p>
<?php echo $this->purify($this->ParagraphRemove($this->eventDescription));?>
<?php 
$params = array(  
        'markers'=>array(array($this->lat,$this->lng)),  
        'size'=>array(100,100),  
        'zoom'=>12,
		'alt' => 'Static map for event',
		'title' => ''
    );
echo $this->GoogleStaticMap( $params );?>
<?php $url =  $this->url(array('module' => 'events',
							   'controller' => 'info',
							   'action' => 'index',
							   'id' => $this->id),
							   'default',
							   true);?>
<p><a href="<?php echo $url?>" title="get further details">Further details &raquo;</a></p>
