<?php
 
//echo "ATTENDEE;ROLE=CHAIR;CN=Dan:MAILTO:info@finds.org.uk\n";
//echo "ORGANIZER;CN=The Portable Antiquities Scheme:MAILTO:info@finds.org.uk\n";
echo "DTSTART:".strftime("%Y%m%d", strtotime($this->eventStartDate))."T".$this->eventStartTime."Z\n";
echo "DTEND:".strftime("%Y%m%d", strtotime($this->eventStartDate))."T".$this->eventEndTime."Z\n";
//echo "RRULE:FREQ=WEEKLY;COUNT=10;INTERVAL=2;BYDAY=TU,WE;WKST=SU\n";
//echo "LOCATION;LANGUAGE=de;ENCODING=QUOTED-PRINTABLE:Vienna\n";
echo "TRANSP:OPAQUE\n";
echo "SEQUENCE:0\n";
if(isset($this->eventDescription) && $this->eventDescription != '')
  {
echo "DESCRIPTION:";
$description = str_replace(chr(13).chr(10),"  ", $this->eventDescription);
echo strip_tags($description)."\n";
   }
echo 'LOCATION:'.$this->eventLocation."\n";
echo 'UID:'.$this->id."\n";
echo "DTSTAMP:".date('Ymd').'T'.date('His')."\n";
echo 'SUMMARY:'.$this->eventTitle;
	
