<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 23/02/15
 * Time: 11:54
 */
?>
<a class="btn-mini btn btn-success"
   href="<?php echo $this->url(array('module' => 'database', 'controller' => 'images', 'action' => 'edit', 'id' => $this->id, 'recordtype' => $this->recordtype), null, true); ?>">Edit</a>
<a class="delete btn btn-mini btn-danger"
   href="<?php echo $this->url(array('module' => 'database', 'controller' => 'images', 'action' => 'delete', 'id' => $this->id, 'recordtype' => $this->recordtype), null, true); ?>">Delete</a>
