<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 23/02/15
 * Time: 11:54
 */
?>
<div class="btn-group">
    <a class="btn-mini btn btn-success"
       href="<?php echo $this->url(array('module' => 'database', 'controller' => 'images', 'action' => 'edit', 'id' => $this->id), null, true); ?>">Edit</a>
    <a class="delete btn btn-mini btn-danger"
       href="<?php echo $this->url(array('module' => 'database', 'controller' => 'images', 'action' => 'delete', 'id' => $this->id), null, true); ?>">Delete</a>
</div>