<?php $path = implode('/',array(IMAGE_PATH,$this->username, 'medium', $this->filename));?>
<?php if(file_exists($path)):?>
<h2 class="lead">Large image view and metadata</h2>

<div id="image">

        <?php list($w, $h, $type, $attr) = getimagesize($path); ?>
        <?php $src = array($this->serverUrl(),'images', $this->username, 'medium', $this->filename);?>
        <img src="<?php echo implode('/', $src); ?>"  height="<?php echo $h; ?>" width="<?php echo $w; ?>"
             alt="A resized image of <?php echo $this->label; ?>"/>
    <div class="btn-group">
        <a class="btn"
           href="<?php echo $this->url(array('module' => 'database', 'controller' => 'ajax', 'action' => 'download', 'id' => $this->id), null, true); ?>"
           title="Download image">Download original</a>
        <?php echo $this->imageToolBox()->setID($this->id)->setCreatedBy($this->createdBy)->setInstitution($this->institution); ?>
    </div>
</div>


<div class="row-fluid">
    <!--  Navigation for tabs  -->
    <ul id="tab" class="nav nav-tabs">
        <li><a class="active" href="#meta" data-toggle="tab">Metadata</a></li>
        <li><a href="#exif" data-toggle="tab">Exif data</a></li>
    </ul>
    <!--  End of Tabs navigation -->

    <!-- Start of tabbed content div -->
    <div id="myTabContent" class="tab-content">

        <div class="tab-pane fade in active" id="meta">
            <h3 class="lead">Image meta data</h3>
            <ul>
                <li>Label: <?php echo $this->label; ?></li>
                <li>Broadperiod: <?php echo $this->broadperiod; ?></li>
                <li>County: <?php echo $this->county; ?></li>
                <li>Filesize: <?php echo $this->humanReadableFileSize()->setSize($this->filesize); ?></li>
                <li>Copyright: <?php echo $this->imagerights; ?></li>
                <li>License: <?php echo $this->license; ?></li>
            </ul>
        </div>


        <div class="tab-pane fade" id="exif">
            <h3 class="lead">Extracted data</h3>
            <ul>
                <?php $location = implode('/',array(IMAGE_PATH,$this->username, $this->filename));?>
                <?php $img = getimagesize($location); ?>

                <li>Width: <?php echo $img['0']; ?> pixels</li>

                <li>Height: <?php echo $img['1']; ?> pixels</li>

                <?php if (array_key_exists('channels', $img)): ?>
                    <li>Channels: <?php echo $img['channels']; ?></li>
                <?php endif; ?>

                <?php if (array_key_exists('bits', $img)): ?>
                    <li>Bits: <?php echo $img['bits']; ?></li>
                <?php endif; ?>

                <li>Mime type: <?php echo $img['mime']; ?></li>

                <?php if (array_key_exists('APP13', $img)): ?>
                    <?php $iptc = iptcparse($img["APP13"]); ?>
                <?php endif; ?>


            </ul>
        </div>


    </div>
    <!--  End of tabbed content div -->

</div>
<?php else:?>
    <p>No file found</p>
<?php endif;?>