<?php
//assign value to API key for google map
$config = Zend_Registry::get('config');
$apiKey = $config->webservice->googlemaps->apikey;

$this->headTitle('Coroner\'s Profile for ' . $this->escape($this->firstname) . ' ' . $this->escape($this->lastname));
$this->headLink()->appendAlternate(
    $this->url(array(
        'module' => 'contacts',
        'controller' => 'coroners',
        'action' => 'profile',
        'id' => $this->id, 'format' => 'foaf'), NULL, true)
    , 'application/rdf+xml', 'FOAF');
$this->metaBase()
    ->setDescription('A description of the coroner for ' . $this->region_name)
    ->setSubject('coroner profile')
    ->setKeywords('coroner,' . $this->region_name)
    ->generate();
?>

<div id="person" class="hresume" typeof="google:Person foaf:Person dc:Agent"
     property="dc:title"
     content="FOAF data about the real person called <?= $this->escape($this->firstname) ?> <?= $this->escape($this->lastname) ?>">
    <div class="contact vcard">
        <h2 class="fn n" property="foaf:name">
            <span class="given-name"><?= $this->escape($this->firstname) ?></span>
            <span class="family-name"><?= $this->escape($this->lastname) ?></span>
        </h2>


        <p class="adr work">
            Address: <span property="con:address_1"><?= $this->escape($this->address_1) ?></span>
            <br/>
            <span class="org organization-name"></span>
            <span class="street-address" property="con:address_2"><?= $this->escape($this->address_2) ?></span>
            <span property="con:city google:locality" class="locality"><?= $this->escape($this->town) ?></span>
            <span class="region"><?= $this->escape($this->county) ?></span>
            <span class="postal-code" property="con:postalCode"><?= $this->escape($this->postcode) ?></span>
        </p>
<span rel="foaf:based_near" class="forRDFOnly">
<span typeof="geo:Point">
lat:
<span property="geo:lat"><?= $this->latitude ?></span>
, long:
<span property="geo:long"><?= $this->longitude ?></span>
</span>
</span>
        <div class="tel">
            <p>Phone (<span class="type">work</span>): <span class="value" rel="foaf:phone"
                                                             resource="tel:<?= $this->escape($this->telephone) ?>"><?= $this->escape($this->telephone) ?></span><br/>
                Phone (<span class="type">fax</span>): <span class="value" rel="foaf:fax"
                                                             resource="tel:<?= $this->escape($this->fax) ?>"><?= $this->escape($this->fax) ?></span>
            </p>
        </div>
        <?php if (!is_null($this->email_one)): ?>
            <p>Email address: <a rel="foaf:mbox" href="mailto:<?= $this->escape($this->email_one) ?>"
                                 class="email"><?= $this->escape($this->email_one) ?></a></p>
        <?php endif; ?>
    </div>
</div>
<h3 class="lead">Location map</h3>
<img
    src="https://maps.google.com/maps/api/staticmap?center=<?= $this->latitude ?>,<?= $this->longitude ?>&zoom=14&size=300x300&maptype=terrain&markers=color:green|label:G|
<?= $this->latitude ?>,<?= $this->longitude ?>&key=<?= $apiKey ?>" />
