<?php
$graph = new EasyRdf_Graph();
EasyRdf_Namespace::set('con', 'http://www.w3.org/2000/10/swap/pim/contact#');
$me = $graph->resource($this->serverUrl() . '/coroners/profile/id/' . $this->number, 'foaf:Person');
$me->set('foaf:name', $this->firstname . ' ' . $this->lastname);
$me->set('foaf:givenName', $this->firstname);
$me->set('foaf:familyName', $this->lastname);
$email = $graph->resource("mailto:" . $this->email_one);
$me->add('foaf:mbox', $email);
$me->add('foaf:mbox_sha1sum', sha1($this->email_one))   ;
$phone = $graph->resource($this->telephone);
$me->add('foaf:phone', $phone);
echo $graph->serialise('rdfxml');