<?php
$this->metaBase()->setDescription('This page allows you to change your password', 'description')
    ->setSubject('Password change')
    ->setKeywords('users,password,change')
    ->generate();
$this->headTitle('Change your password');
$this->headScript()->appendFile('//www.google.com/recaptcha/api.js');
?>
    <h2 class="lead"><?php
        echo $this->title(); ?></h2>
<?php
echo $this->form; ?>