<?php 
$this->headTitle('Retrieve your password');
$this->headMeta('Recover your password for the Scheme\'s website','description');
?>

<h2>Reset my password</h2>
<p>If you have registered for an account with the Scheme's website, but have 
    forgotten it, you can get it reset here. Once you complete the form 
    correctly, you will receive an email with your new password. If this does 
    not arrive, please contact us and we can reset the password for you.</p>
<?php echo $this->form;?>