<?php
$this->headTitle('Reset your password');
$this->metaBase()->setDescription('Recover your password for the Scheme\'s website')
    ->setKeywords('password,recovery,reset')
    ->generate();
$this->headTitle('Reset your password');
$this->headScript()->appendFile('//www.google.com/recaptcha/api.js');
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>If you have registered for an account with the Scheme's website, but have
        forgotten it, you can get it reset here. Once you complete the form
        correctly, you will receive an email with your new password. If this does
        not arrive, please contact us and we can reset the password for you.</p>
<?php echo $this->form; ?>