<?php
$this->headTitle("Register for a user account");
?>


<h2>Register for an account with the Scheme</h2>

<?php echo $this->form;?>

<div>
<h3>Terms and conditions for higher level access</h3>

<p>By applying for a user account for the Portable Antiquities Database, you must agree to abide by the following conditions.</p>
<ol>
<li>You will not reveal your password to any one else.</li>
<li>You will not allow anyone other than yourself to use your account (for example, do not log on for another person to use the database.)</li>
<li>You are bound by the Data Protection Act, not to distribute any of the personal data held within the database.</li>
<li>You must not contact any of the finders named on the database, without firstly liaising with the regional Finds Liaison Officer for that area. Namely, if you want to speak to Mr X. based in Suffolk, you must contact the Suffolk Finds Liaison Officer in the first instance.</li>
<li>It is a priority that find spot information should be as accurate as possible and therefore you should not record material where there is doubt about it's provenance unless there are strong reasons for doing so.</li>
<li>The Portable Antiquities Scheme reserves the right to revoke your license to use the database at anytime.  This can be reinstated, on appeal to the Central Unit, if investigation reveals that there are grounds for this.</li>
<li>If you wish to use the data recorded on the system for publication purposes, you must, in the first instance contact the Central Unit for permission to do so. This will be granted on a case by case basis. Therefore, you must ask for permission for each instance that you will be using the data. </li>
<li>Images recorded on the system, remain the copyright of the named person, held within the meta - data. Ergo, if you wish to make use of these images for publication or profit, you must contact the Central Unit, outlining your purpose (s).</li>
<li>If you want an account for research purposes, then the scheme will need documentation proving your accreditation. A letter from your supervisor or institution will usually suffice. If you are an independent researcher, then a letter outlining your research methodology will be accepted instead, along with a reference from either your publisher or an academic institution that is prepared to guarantee your good character.</li>
<li>Any data downloads provided by the scheme are not transferable to a third party. </li>
</ol>
<p>I agree to abide by the conditions outlined above.</p>

</div>