<?php $this->headTitle('Request an account upgrade');
$this->metaBase()->setDescription('This page allows you to request an account upgrade')->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>If your account falls into the member category, you can request an upgrade in status to research level by using
        the form below. We require evidence in written form from your supervisor or an archaeological referee to do
        this.</p>
<?php echo $this->form; ?>