<?php
$this->headTitle('Volunteering with the Portable Antiquities Scheme');
$this->metaBase()->setDescription('A list of volunteering opportunities currently available with the
Portable Antiquities Scheme')
    ->setKeywords('portable,antiquities,scheme,volunteer,volunteering')
    ->generate();
?>
<h2 class="lead"><?= $this->title() ?></h2>


<?php
if (count($this->vols)): ?>
    <table class="table table-striped" summary="A list of all volunteering opportunities with the Scheme">
        <caption>Volunteer opportunities</caption>
        <thead>
        <tr>
            <th>Opportunity</th>
            <th>Suitability</th>
            <th>Managed by</th>
            <th>Suggested length</th>
            <th>Location</th>
        </tr>
        </thead>
        <tbody>
        <?= $this->partialLoop('partials/getinvolved/volunteerList.phtml', $this->vols) ?>
        </tbody>
    </table>
    <?= $this->paginationControl($this->vols, 'Sliding', 'structure/pagination.phtml') ?>

<?php else: ?>
    <p>
	The Portable Antiquities Scheme supports a network of volunteers across the country. Volunteering for the Scheme is a great way to get involved with your local heritage. Our volunteer roles are varied and flexible, and include finds identification and recording, finds photography, and public engagement and outreach.
    </p>

    <p>
	Volunteering usually takes place alongside your local Finds Liaison Officer. If you are interested in volunteering for the Scheme, please email us at <a href="mailto:info@finds.org.uk">info@finds.org.uk</a> and let us know where you are based so that we can contact the relevant Finds Liaison Officer.
    </p>
<?php endif; ?>
