<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getActionContexts( $action );

$dom 	  = new DomDocument("1.0", "UTF-8");
$vols  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$vols->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', $this->data['total']));
$meta->appendChild( $dom->createElement('currentPage',$this->data['pageNumber']));
$meta->appendChild( $dom->createElement('totalPages',$this->data['totalPages']));
$meta->appendChild( $dom->createElement('itemsReturned',$this->data['itemsReturned']));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$volsElem = $dom->createElement('volunteering');
$vols->appendChild($volsElem);

foreach($this->vols as $f){
$volElem = $dom->createElement('role');
foreach($f as $k => $v){
	$volElem->appendChild( $dom->createElement($k, htmlspecialchars($v))); 
}
$volsElem->appendChild( $volElem );
}

$dom->appendChild( $vols );

$xmlData  = $dom->saveXML();
echo $xmlData;
