<?php
$this->headTitle('Primary Activities');
$this->metaBase()
    ->setDescription('This page outlines the majority of activities in which finders engage when
discovering artefacts')
    ->setSubject('discovery')
    ->setKeywords('metal detecting,fieldwalking,methods,discovery,personal')
    ->generate();
?>
<h2 class="lead">
    <?php echo $this->title(); ?>
</h2>
<ul>
    <?php echo $this->partialLoop('partials/datalabs/activityList.phtml', $this->activities); ?>
</ul>