<?php
$this->headTitle('Scope notes for completeness type of ' . $this->comps['0']['term']);
$this->metaBase()->setDescription('Scope notes for completeness type of ' . $this->comps['0']['term']
    . ' and thumnbnails of latest records attributed')
->setKeywords('completeness,terms')
->setSubject('terminology')
->generate();
$this->headMeta('completeness,' . $this->comps['0']['term'] . ',type,portable antiquities,terminology', 'dc.keywords');?>
    <h2 class="lead">Details for <?php echo $this->title(); ?></h2>
<?php echo $this->comps['0']['description']; ?>
<?php echo $this->latestRecords()->setQuery('completeness:' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>