<?php
$this->headTitle('Early Medieval ascribed cultures');
$this->metaBase()
        ->setDescription('A list of ascribed cultures, primarily used for the '
                . 'Early medieval period.')
        ->setSubject('terminology')
        ->setKeywords('cultures,early,medieval,saxon,viking')
        ->generate();
?>
<h2>
    <?php echo $this->title();?>
</h2>
<p>The Scheme has broken the Early Medieval period down into the following ascribed cultures to make it easier to search the database.</p>
<ul>
    <?php echo $this->partialLoop('partials/database/culture.phtml',$this->cultures);?>
</ul>
