<?php
$this->headTitle('Decoration styles');
$this->metaBase()->setDescription($this->title())
    ->setSubject('terminology')
    ->setKeywords('terminology,archaeology,decorative,decoration')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->decs)): ?>
    <ul>
        <?php echo $this->partialLoop('partials/datalabs/decStylesList.phtml', $this->decs); ?>
    </ul>
<?php else: ?>
    <p>No styles available.</p>
<?php endif; ?>