<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$denominations  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$denominations->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', $this->data['total']));
$meta->appendChild( $dom->createElement('page', $this->data['pageNumber']));
$meta->appendChild( $dom->createElement('totalPages', $this->data['totalPages']));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$denominationsElem = $dom->createElement('dieAxes');
$denominations->appendChild($denominationsElem);
// set it's attribute
foreach($this->dieaxes as $r){
$denominationElem = $dom->createElement('dieaxis');
foreach($r as $k => $v){
$denominationElem->appendChild( $dom->createElement($k, $v));
}
$denominationsElem->appendChild( $denominationElem );
}

$dom->appendChild( $denominations );

$xmlData  = $dom->saveXML();
echo $xmlData;
