<?php
$this->headTitle('Die Axes in use on the database');
$this->metaBase()->setDescription($this->title())
    ->setSubject('terminology')
    ->setKeywords('numismatics,archaeology')
    ->generate();
?>
<?php if (!empty($this->dieaxes)): ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <ul>
        <?php echo $this->partialLoop('partials/datalabs/dies.phtml', $this->dieaxes); ?>
    </ul>
<?php else: ?>
    <p>No die axes available.</p>
<?php endif; ?>