<?php $this->headTitle('Learn about our various controlled terminologies');
$this->headMeta('archaeology,thesauri,terminology,preferred terms','dc.keywords');
$this->headMeta('This page gives you access to our range of vocabularies 
    employed by the Scheme on the database','description');
?>
<h2>Controlled terminologies</h2>
<ul>
<?php foreach($this->vocabularies as $k):?>
<li><a href="<?php echo $k['html']?>" title="learn more about the <?php echo $k['type'];?> vocab"><?php echo ucfirst($k['type']);?></a></li>
<?php endforeach;?>
</ul>