<?php $this->headTitle('Land use characterisations employed'); ?>
<?php $this->metaBase()->setDescription($this->title())
    ->setKeywords('terminology,landuse,thesaurus')
    ->setSubject('terminology')
    ->generate(); ?>
<?php if (!empty($this->landuses)): ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <table class="table table-striped" summary="List of land uses that the Scheme employes">
        <thead>
        <tr>
            <th>Landuse type</th>
            <th>Landuse code</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/datalabs/landuseListTable.phtml', $this->landuses); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No land use codes available.</p>
<?php endif; ?>