<?php $this->headTitle('Object types that the Scheme uses - MDA');?>

<h2>Object terms in use on the Scheme's database.</h2>
<p>These terms are from the BM/MDA thesaurus of archaeological object terms.</p>
<?php if (count($this->paginator)): ?>
<table class="table table-striped" summary="All object terms in use on the Scheme's database">
<thead>
<tr>
<th>Term</th>
<th>Scope note</th>
<th>Term type</th>
</tr>
</thead>

<tbody>

<?php echo $this->partialLoop('partials/database/objectLister.phtml',$this->paginator);?>
</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>No object terms available.</p>
<?php endif; ?>