<?php
$this->headTitle('Object types that the Scheme uses');
$this->metaBase()->setDescription('This set of pages details the object type list we employ.')
    ->setSubject('terminology')
    ->setKeywords('terminology, british,museum, thesaurus')
    ->generate();
?>

    <h2 class="lead"><?php $this->title(); ?></h2>

    <p>These terms are from the British Museum /MDA thesaurus of archaeological object terms.</p>

<?php if (!empty($this->paginator)): ?>
    <table class="table table-striped" summary="All object terms in use on the Scheme's database">
        <thead>
        <tr>
            <th>Term</th>
            <th>Scope note</th>
            <th>Term type</th>
            <th>SENESCHAL URI</th>
            <th>British Museum URI</th>
        </tr>
        </thead>

        <tbody>

        <?php echo $this->partialLoop('partials/datalabs/objectLister.phtml', $this->paginator); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', 'structure/pagination.phtml'); ?>

<?php else: ?>
    <p>No object terms available.</p>
<?php endif; ?>