<?php
$this->headTitle('Rulers or issuers available for use on the database');
$this->metaBase()->setSubject('terminology')
    ->setKeywords('terminology,archaeology,numismatics')
    ->setDescription($this->title())
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>

<?php if (!empty($this->rulers)): ?>
    <table class="table table-striped" summary="List of all active rulers on the Scheme's database">
        <caption>Active rulers on the Scheme database</caption>
        <thead>
        <tr>
            <th>Issuer name</th>
            <th>Period</th>
            <th>Date reigned</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/datalabs/rulerListsCTerms.phtml', $this->rulers); ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->rulers, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>It is you lucky day Odysseus, Nemo has been and gone and left you with nothing to do.</p>
<?php endif; ?>



