<?php
$this->headTitle('Numismatic wear types in use');
$this->metaBase()->setDescription('A list of wear types for numismatics used on the database')
    ->setKeywords('wear,types,numismatics')

    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->wear)): ?>
    <ul>
        <?php foreach ($this->wear as $wear): ?>
            <li><?php echo $wear['term']; ?></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>No numismatic wear types available.</p>
<?php endif; ?>