<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$workflows  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$workflows->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->workflows)));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$workflowsElem = $dom->createElement('workflowStages');
$workflows->appendChild($workflowsElem);
// set it's attribute
foreach($this->workflows as $r){
$workflowElem = $dom->createElement('workflowStage');
foreach($r as $k => $v){
$workflowElem->appendChild( $dom->createElement($k, $v));
}
$workflowsElem->appendChild( $workflowElem );
}

$dom->appendChild( $workflows );

$xmlData  = $dom->saveXML();
echo $xmlData;
