<div class="page-header"><h2><?php echo date('d-m-Y', strtotime($this->starts));?>: <?php echo $this->title;?></h2></div>
<?php if($this->content != ''):?>
<blockquote><?php echo $this->paragraphRemove($this->purify($this->content));?></blockquote>
<?php endif;?>
<p>Location: <?php echo $this->where;?><br />
Start: <?php echo date('g:ia', strtotime($this->starts));?> <?php echo $this->niceshortdate(date('d-m-Y', strtotime($this->ends)));?><br />
End: <?php echo date('g:ia', strtotime($this->ends));?> <?php echo $this->niceshortdate(date('d-m-Y', strtotime($this->ends)));?><br />
<?php 
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
if($action != 'event'):
?>
<a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'calendar', 'action' => 'event', 'id' => urlencode($this->id)), null, true);?>" >Further details &rarr;</a><br />
<?php 
endif;
?>

<?php
if($action == 'event'): 
$geocoder = new Pas_Service_Geo_Coder(Zend_registry::get('config')->webservice->google->apikey);
?>
<?php 
$coords = $geocoder->getCoordinates((string)$this->where);
if($coords['lat'] && $coords['lon']):
$this->inlineScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false',$type='text/javascript');
?>
<?php 

$this->inlineScript()->captureStart();?>

$(document).ready(function() {
	var myLatlng = new google.maps.LatLng(<?php echo $coords['lat'];?>,<?php echo $coords['lon'];?>);
    var myOptions = {
      zoom: 14,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
	  scrollwheel:false
    }
    var map = new google.maps.Map(document.getElementById("eventmap"), myOptions);
    
    var marker = new google.maps.Marker({
        position: myLatlng, 
        map: map,
        title:"Event location"
    });   
});

<?php $this->inlineScript()->captureEnd();?>

<div id="eventmap">
<noscript>
<img src="http://maps.google.com/maps/api/staticmap?center=<?php echo $this->latitude;?>,<?php echo $this->longitude;?>&zoom=14&size=640x300&maptype=terrain&markers=color:green|label:X|<?php echo $this->latitude;?>,<?php echo $this->longitude;?>&sensor=false" />
</noscript>
</div>

<?php 
endif;
?>
<?php 
endif;
?>
<span class="label label-important"><?php echo str_replace('=',': ',$this->type);?></span><br />
Created by: <?php echo str_replace('creator=', '',$this->creator);?>


<br/>
<?php 
$person = new Pas_User_Details();
$user = $person->getPerson();
if(str_replace('creator=', '',$this->creator) === $user->fullname):
?>
<a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'calendar', 'action' => 'edit', 'id' => $this->id),null,true);?>" class="btn btn-info btn-small">Edit</a>
<a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'calendar', 'action' => 'delete', 'id' => $this->id),null,true);?>" class="btn btn-warning btn-small">Delete</a>
<?php endif;?>
</p>

