<?php
$this->headTitle('Add a research project');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.autocomplete.pack.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/autocompleteinitPeople.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile(
    $this->baseUrl() . '/js/bootstrap-datepicker.js',
    $type = 'text/javascript'
);
$this->headLink()->appendStylesheet('/css/bootstrap-datepicker.css');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/autocomplete.css');
?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
$(document).ready(function() {
    var datePickerSettings = {
        endDate: (new Date((new Date()).getFullYear() + 6, 12, 0)),
        format: 'yyyy-mm-dd',
    };
    $("#startDate").datepicker(datePickerSettings);
    $("#endDate").datepicker(datePickerSettings);
    $('form').areYouSure();
    $("form").submit(function() {
        $(":submit", this).attr("disabled", "disabled");
    });
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>
