<?php 
	$this->headTitle('Delete suggested research project');
if ($this->suggest) :?>
<h2>Delete <?php echo $this->escape($this->suggest->title);?></h2>
<p>Are you sure that you want to delete this project</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'research','action'=>'deletesuggested'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->suggest->id; ?>" />

<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>