<?php
$this->headTitle('Delete suggested research project');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!empty($this->suggest)) : ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>Are you sure that you want to delete <?php echo $this->suggest->title; ?></p>
    <form
        action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'research', 'action' => 'deletesuggested'), null, true); ?>"
        method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->suggest->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <p>Cannot find the item requested.</p>
<?php endif; ?>