<?php
$this->headTitle('Research projects conducted on Scheme data');
$this->metaBase()->setDescription($this->title())->generate();
?>


<h2 class="lead"><?= $this->title() ?></h2>
<p>
    <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'research', 'action' => 'add'), null, true) ?>"
       class="btn btn-small btn-default" title="Add a new research project to the register">Add a new project</a></p>
<?php if (!empty($this->research)): ?>

    <table class="table table-striped" summary="A table of all research projects conducted on Scheme research">
        <caption>Research projects</caption>
        <thead>
        <tr>
            <th>Project title</th>
            <th>Primary investigator</th>
            <th>Level of research</th>
            <th>Start</th>
            <th>Finish</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?= $this->partialLoop('partials/admin/researchList.phtml', $this->research) ?>
        </tbody>
    </table>
    <?= $this->paginationControl($this->research, 'Sliding', 'structure/pagination.phtml') ?>

    <?php else:?>
    <p>No research to administer.</p>
<?php endif; ?>
