<?php
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jQueryLinkedSelect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/coinslinkedselect.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/linkedinit.js',$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/jquery.autocomplete.pack.js',
$type='text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl().'/js/JQuery/autocompleteinit.js',
$type='text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/autocomplete.css');
$this->headTitle('List of all antiquities in the OS 1:50k Gazetteer');
$this->headMeta('These pages catalogue all sites in the Ordnance Survey 1:50K dataset that can be obtained from the opendata download.','description')
->headMeta('Daniel Pett','dc.creator')
->headMeta('The Portable Antiquities Scheme','dc.publisher')
->headMeta($this->curUrl(),'dc.identifier');
?>

<h2>Ordnance Survey 1:50 K records</h2>
<p>These records are obtained from the 1:50K data download from the Ordnance Survey Opendata project.</p>
<?php echo $this->form;?>
<?php if($this->results):?>
<div class="row-fluid">
<div class="span9">
<table class="table table-striped" summary="A list of all ordnance survey listed monuments">
<thead>
<tr>
<th>Monument name</th>
<th>County</th>
<th>Feature type</th>
</tr>
</thead>
<tr><?php
//echo $this->form;
?></tr>
<tbody>
<?php echo $this->partialLoop('partials/database/osdata.phtml',$this->results);?>
</tbody>
</table>
</div>
<div class="span3">
<p><a class="btn btn-small" href="<?php echo $this->url(array('module' => 'database','controller' => 'osdata','action' => 'map'),'default',false);?>">Map these sites</a></p>
<?php echo $this->facetCreator($this->facets);?>
</div>
</div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<p>No OS records are available to you right now.</p>
<?php endif;?>

<?php
$this->inlineScript()->appendFile('/js/bootstrap-modal.js', $type='text/javascript');
$this->inlineScript()->captureStart();
?>
$(document).ready(function() {
	$('#print').click(function() {
	window.print();
	return false;
	});

    $('.overlay').click(function(e) {
    e.preventDefault();
    var href = $(e.target).attr('href');
    if (href.indexOf('#') == 0) {
        $(href).modal('open');
    } else {
        $.get(href, function(data) {
            $('<div class="modal fade" >' + data + '</div>').modal();
        });
    }
});

	});
<?php $this->inlineScript()->captureEnd();?>