<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 24/11/14
 * Time: 16:35
 */
?>
<?php
$this->headTitle('Upload images');
$this->metaBase()->setDescription($this->title())->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>

    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" action="<?php echo $this->serverUrl();?>/database/ajax/upload" method="POST" enctype="multipart/form-data">
        <noscript><p>Your browser cannot support this uploader due to JavaScript problems.</p></noscript>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row-fluid fileupload-buttonbar">
            <div class="btn-group">

                <!-- The fileinput-button span is used to style the file input field as button -->
                <input type="file" name="files[]" multiple>
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-white icon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="icon-white icon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <a class="btn btn-success btn-small"
           href="<?php echo $this->url(array('module' => 'database', 'controller' => 'artefacts', 'action' => 'record', 'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('id')), null, true); ?>"
           title="return to the record">Return to record</a>
<!--                <button type="button" class="btn btn-danger delete">-->
<!--                    <i class="icon-white icon-trash"></i>-->
<!--                    <span>Delete</span>-->
<!--                </button><br/>-->
<!--                Toggle delete button: <input type="checkbox" class="toggle">-->
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>
            </div>
            <!-- The global progress state -->
            <div class="span12 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="bar" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
            <div class="span6">
                <?php $url = array('module' => 'database', 'controller' => 'images', 'action' => 'metadata', 'id' => $this->findID); ?>
                <a href="<?php echo $this->url($url);?>" class="btn btn-success">Finished uploads? Add metadata to images</a>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped">
            <tbody class="files"></tbody>
        </table>
    </form>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title lead">Uploading notes</h3>
        </div>
        <div class="panel-body">
            <p>
                You are adding images for a single record.
            </p>
            <ul>
                <li>The maximum file size for uploads is <strong>20 MB</strong>.</li>
                <li>Only high quality image files (<strong>JPG or TIFF</strong>) are allowed.</li>
                <li>You can <strong>drag &amp; drop</strong> files from your desktop on this web page (see <a
                        href="https://github.com/blueimp/jQuery-File-Upload/wiki/Browser-support">Browser support</a>).
                </li>
            </ul>
        </div>
    </div>
    </div>
    <!-- The template to display files available for upload -->
    <script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            <div class="btn-group">
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="icon-white icon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="icon-white icon-trash"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
            </div>
        </td>
    </tr>
{% } %}

    </script>
    <!-- The template to display files available for download -->
    <script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><h4 class="lead">An error has occurred with that upload</h4>
                <ul>
                    {% if(file.error = 'fileNotExistsDoesExist') { %}
                    <li>That file already exists</li>
                    {% } %}
                </ul>
                </div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>

    </tr>
{% } %}

    </script>

<?php
$this->headLink()->appendStylesheet('/thirdParty/css/jquery.fileupload-ui.css');
$this->jQuery()->addJavascriptFile('/thirdParty/js/tmpl.min.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/load-image.all.min.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/canvas-to-blob.min.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.iframe-transport.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.fileupload.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.fileupload-process.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.fileupload-image.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.fileupload-audio.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.fileupload-video.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.fileupload-validate.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/jquery.fileupload-ui.js');
$this->jQuery()->addJavascriptFile('/thirdParty/js/bootstrap.file-input.js', $type = 'text/javascript');

?>

<?php $this->jQuery()->javascriptCaptureStart(); ?>
    $('input[type=file]').bootstrapFileInput();
    $('.file-inputs').bootstrapFileInput();

    $(document).ready(function() {
        'use strict';
        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
            url: '<?php echo $this->serverUrl();?>/database/ajax/upload/',
            disableImageResize: /Android(?!.*Chrome)|Opera/
            .test(window.navigator.userAgent),
            maxFileSize: 200000000,
            acceptFileTypes: /(\.|\/)(tif|jpe?g)$/i

        }).bind('fileuploadsubmit', function (e, data) {
        data.formData = {
        'findID': "<?php echo $this->findID;?>"
        };
        });
    });

<?php $this->jQuery()->javascriptCaptureEnd(); ?>