<?php
$this->headTitle('Add an image');
$this->metaBase()->setDescription($this->title())->generate();
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.validate.min.js', $type = 'javascript');
$id = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <div class="btn-group">
        <a class="btn btn-success btn-small" href="<?php echo $this->url(
            array(
                'module' => 'database',
                'controller' => 'artefacts',
                'action' => 'record',
                'id' => $id
            ), null, true);?>" title="return to the record">Return to record</a>
    </div>

<?php echo $this->form; ?>

    <div><?php echo $this->partial('partials/content/article.phtml', $this->contents); ?></div>

<?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function() {
    $("#imagetofind").validate();
    });
<?php $this->jQuery()->javascriptCaptureEnd(); ?>