<?php 
	$this->headTitle('Delete an image');
if ($this->slide) :?>
<h2>Delete <?php echo $this->escape($this->slide->label); ?></h2>
<p>Are you sure that you want to delete this image and all variants. It cannot be undone.
</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'images','action'=>'delete'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->slide->imageID; ?>" />
<input type="hidden" name="findID" value="<?php echo $this->find->old_findID; ?>" />

<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>