<?php
$this->headTitle('Delete an image');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!is_null($this->slide)) : ?>
    <h2 class="lead">Delete <?php echo $this->escape($this->slide->label); ?></h2>
    <p>Are you sure that you want to delete this image and all variants. It cannot be undone.
    </p>
    <form
        action="<?php echo $this->url(
            array(
                'module' => 'database', 'controller' => 'images', 'action' => 'delete'
            ), null, true); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->slide->imageID; ?>"/>
            <input type="hidden" name="recordtype" value="<?php echo $this->recordtype; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>Cannot find the item requested.</p>
<?php endif; ?>