<?php
if (!empty($this->images)): ?>
    <?php
    $this->headTitle('Image and metadata for ' . $this->images['0']['label']);
    $this->metaBase()->setDescription($this->title())->generate();
    ?>
    <?php echo $this->partial('partials/database/images/image.phtml', $this->images['0']); ?>
    <div id="linked">
        <h2 class="lead">Linked finds for this image</h2>
        <?php if (!is_null($this->finds['0']['old_findID'])): ?>
            <ul>
                <?php echo $this->partialLoop('partials/database/structural/linkedFinds.phtml', $this->finds); ?>
            </ul>
        <?php endif; ?>
    </div>
<?php else: ?>
    <h2 class="lead">An error has occurred.</h2>
    <p>No image data available</p>
<?php endif; ?>