<?php
$this->headTitle('All images on the database');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead">All images on the database</h2>
<?php echo $this->form; ?>

<?php if (!empty($this->results)): ?>
    <div class="row-fluid ">
        <div class="span9">
            <ul class="thumbnails">
                <?php echo $this->partialLoop('partials/database/myImagesList.phtml', $this->results);?>
            </ul>
        </div>
        <div class="span3">
            <?php echo $this->resultsQuantityChooser()->setResults($this->paginator); ?>
            <?php echo $this->thumbnailToggler(); ?>
            <?php echo $this->resultsSorter()->setResults($this->paginator); ?>
            <?php echo $this->imagesFacetCreator($this->facets); ?>
        </div>
    </div>


    <?php echo $this->paginationControl($this->paginator, 'Elastic', 'structure/pagination.phtml'); ?>

<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>You have added no images to our database.</p>
<?php endif; ?>

<?php $this->jQuery()->javascriptCaptureStart() ?>
    $(function() {
<?php
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $user = $auth->getIdentity();
    {
        if (in_array($user->role, array('flos', 'treasure', 'fa', 'admin'))) {
            ?>
            $('div.image-controls').css('visibility','hidden');
            $('div.thumbnail').each(function() {
            var controls = $(this).children('div.image-controls');
            $(this).hover(
            function() {
            $(controls).css('visibility','visible')
            },
            function() {
            $(controls).css('visibility','hidden')
            });
            });
        <?php
        }
    }
}
?>
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>

<?php
$this->inlineScript()->appendFile($this->baseUrl() . '/js/bootstrap-modal.js', $type = 'text/javascript');
$this->inlineScript()->captureStart();
?>
    $(document).ready(function() {
    $('#print').click(function() {
    window.print();
    return false;
    });

    $('.overlay').click(function(e) {
    e.preventDefault();
    var href = $(e.target).attr('href');
    if (href.indexOf('#') == 0) {
    $(href).modal('open');
    } else {
    $.get(href, function(data) {
    $('<div class="modal fade">' + data + '</div>').modal();});
    }
    });

    });
<?php $this->inlineScript()->captureEnd(); ?>