<?php
$this->headTitle('Delete image association');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <?php if (!is_null($this->slide)) :
    ?>
    <h2 class="lead">Delete image link for <?php echo $this->escape($this->slide->label); ?></h2>
    <p>Are you sure that you want to delete this link for this image. It cannot be undone.
    </p>
    <form
        action="<?php echo $this->url(
            array(
                'module' => 'database', 'controller' => 'images', 'action' => 'unlink',
                'returnID' => $this->returnID
            ), null, true); ?>"
        method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->slide->imageID; ?>"/>
            <input type="hidden" name="findID" value="<?php echo $this->findID; ?>"/>
            <input type="hidden" name="imageID" value="<?php echo $this->slide->secuid; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>Cannot find the item requested.</p>
<?php endif; ?>