<?php
$this->headTitle('Zooming image of ' . $this->escape($this->data[0]['label']));
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!empty($this->data)): ?>
    <h2 class="lead">High resolution image view of <?php echo $this->escape($this->data['0']['label']); ?> </h2>

    <div class="btn-group">
        <a class="btn btn-success btn-small" href="<?php echo $this->url(
            array(
                'module' => 'database',
                'controller' => Zend_Controller_Front::getInstance()->getRequest()->getParam('recordtype'),
                'action' => 'record',
                'id' => $this->data[0]['id'],
                'recordtype' => Zend_Controller_Front::getInstance()->getRequest()->getParam('recordtype')
            ), NULL, true); ?>"
           title="Return to the object's full details">Return to object</a>
        <a class="btn btn-small btn-success" href="<?php echo $this->url(
            array(
                'module' => 'database',
                'controller' => 'images',
                'action' => 'image',
                'id' => $this->data[0]['imageID'],
                'recordtype' => Zend_Controller_Front::getInstance()->getRequest()->getParam('recordtype')

            ), NULL, true); ?>"
           title="Go back to all the details for this image">Return to full image details</a>
    </div>

    <div class="row-fluid span12">
        <?php echo $this->zoomify()->setData($this->data[0]);?>
    </div>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>That zooming image cannot be rendered.</p>
<?php endif; ?>