<?php
    $editUrl = array(
        'module' => 'database',
        'controller' => 'archaeology',
        'action' => 'edit',
        'id' => $this->id,
        'hoardID' => $this->hoardID
    );
    $deleteUrl = array(
        'module' => 'database',
        'controller' => 'archaeology',
        'action' => 'delete',
        'id' => $this->id,
        'hoardID' => $this->hoardID
    );
?>
<td>
    <div class="btn-group">
        <a href="<?php echo $this->url($editUrl, 'default', true);?>" class="btn btn-mini btn-primary">Edit</a>
        <a href="<?php echo $this->url($deleteUrl, 'default', true);?>" class="btn btn-mini btn-danger">Delete</a>
    </div>
</td>