<?php if (!empty($this->coinSummary)) : ?>
    <?php
    $broadperiodarray = array();
    foreach ($this->coinSummary as $row) {
        $broadperiodarray[] = $row['broadperiod'];
    }
    ?>
    <h4 class="lead">Coin summary</h4>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Period</th>

            <?php if (in_array('ROMAN', $broadperiodarray)) : ?>
                <th>Ruler</th>
            <?php endif; ?>

            <th>Denomination</th>

            <?php if (in_array('ROMAN', $broadperiodarray)) : ?>
                <th>Mint</th>
            <?php endif; ?>
            <?php if (in_array('IRON AGE', $broadperiodarray)) : ?>
                <th>Geog. area</th>
            <?php endif; ?>

            <th>From</th>
            <th>To</th>
            <th>Quantity</th>
            <th></th>
        </tr>
        </thead>

        <tbody>

        <?php foreach ($this->coinSummary as $coinrow) : ?>
            <tr>
                <td>
                    <?php echo $coinrow['broadperiod']; ?>
                </td>

                <?php if (in_array('ROMAN', $broadperiodarray)) : ?>
                    <td>
                        <?php if (!is_null($coinrow['ruler'])) : ?>
                            <?php echo $coinrow['ruler']; ?>
                        <?php else: ?>
                            -
                        <?php endif; ?>
                    </td>
                <?php endif; ?>

                <td>
                    <?php echo $coinrow['denomination']; ?>
                </td>

                <?php if (in_array('ROMAN', $broadperiodarray)) : ?>
                    <td>
                        <?php if (!is_null($coinrow['mint'])) : ?>
                            <?php echo $coinrow['mint']; ?>
                        <?php else: ?>
                            -
                        <?php endif; ?>
                    </td>
                <?php endif; ?>

                <?php if (in_array('IRON AGE', $broadperiodarray)) : ?>
                    <td>
                        <?php if (!is_null($coinrow['geographicarea'])) : ?>
                            <?php echo $coinrow['geographicarea']; ?>
                        <?php else: ?>
                            -
                        <?php endif; ?>

                    </td>
                <?php endif; ?>

                <td>
                    <?php if (!is_null($coinrow['numdate1'])): ?>
                        <?php echo $this->adBc()->setDate($coinrow['numdate1']); ?>
                    <?php else: ?>
                        -
                    <?php endif; ?>
                </td>
                <td>
                    <?php if (!is_null($coinrow['numdate2'])): ?>
                        <?php echo $this->adBc()->setDate($coinrow['numdate2']); ?>
                    <?php else: ?>
                        -
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $coinrow['quantity']; ?>
                </td>
                <td>
                <?php
                echo $this->editDeleteSummary()
                    ->setID($coinrow['summaryID'])
                    ->setHoardID($coinrow['id'])
                    ->setCreatedBy($coinrow['createdBy'])
                    ->setInstitution($coinrow['institution']);
                ?>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>

    </table>
    <?php
    echo $this->addCoinSummary()
        ->setSecUID($this->hoards['uniqueID'])
        ->setID($this->hoards['id'])
        ->setCreatedBy($this->hoards['createdBy'])
        ->setInstitution($this->hoards['institution']);
    ?>
<?php else: ?>
    <?php
    echo $this->addCoinSummary()
        ->setSecUID($this->hoards['uniqueID'])
        ->setID($this->hoards['id'])
        ->setCreatedBy($this->hoards['createdBy'])
        ->setInstitution($this->hoards['institution']);
    ?>
<?php endif; ?>