<h4 class="lead">Description</h4>
<div property="pas:description">
    <?php
    echo $this->description;
    ?>
</div>
<?php if (!empty($this->notes)) : ?>
    <h4 class="lead">Notes</h4>
    <span property="pas:notes"><?php echo $this->notes; ?></span>
<?php endif; ?>

<?php if ($this->findofnote == 1): ?>
    <h4 class="lead">Find of note status</h4>
    <?php if (($this->findofnote == 1) && (!is_null($this->reason))): ?>
        <p>This is a find of note and has been designated: <?php echo $this->reason; ?></p>
    <?php elseif (($this->findofnote == 1) && (is_null($this->reason))): ?>
        <p>This has been noted as an interesting find by the recorder.</p>
    <?php endif; ?>
<?php endif; ?>