<h4>Coins linked to this hoard</h4>
<?php foreach($this->linkedCoins as $coin) : ?>

    <p>Record ID:
    <a href="
    <?php echo $this->url(array(
        'module'=>'database',
        'controller' => 'artefacts',
        'action'=>'record',
        'id' =>  $coin['id']),null,true);?>" title="View this record">
        <?php echo $this->escape($coin['old_findID']); ?></a>
        <br />Object type:
        <?php echo $this->escape($coin['objecttype']); ?>
        <?php if(!is_null($coin['treasureID'])) :?>
            <br />Treasure number:
            <?php echo $this->escape($coin['treasureID']); ?>
        <?php endif;?>
    </p>

<?php endforeach; ?>