<?php if (!empty($this->linkedArtefacts)) : ?>
    <h4>Artefacts linked to this hoard</h4>
    <?php foreach ($this->linkedArtefacts as $artefact) : ?>

        <p>Record ID:
            <a href="
    <?php echo $this->url(array(
                'module' => 'database',
                'controller' => 'artefacts',
                'action' => 'record',
                'id' => $artefact['id']), null, true);?>" title="View this record">
                <?php echo $this->escape($artefact['old_findID']); ?></a>
            <br/>Object type:
            <?php echo $this->escape($artefact['objecttype']); ?>
            <?php if (!is_null($artefact['treasureID'])) : ?>
                <br/>Treasure number:
                <?php echo $this->escape($artefact['treasureID']); ?>
            <?php endif; ?>
        </p>

    <?php endforeach; ?>
<?php endif; ?>