<?php
$ids = array(
    $this->legacyID, $this->smrrefno, $this->other_ref,
    $this->treasureID, $this->musaccno
);
?>
<?php if (array_filter($ids)): ?>
    <h4 class="lead">Other reference numbers</h4>
    <p>
        <?php if (isset($this->legacyID)): ?>
            Legacy hoard number: <?php echo $this->escape($this->legacyID); ?><br/>
        <?php endif; ?>
        <?php if (isset($this->smrrefno) || ($this->smrrefno != '')): ?>
            SMR reference number: <?php echo $this->escape($this->smrrefno); ?><br/>
        <?php endif; ?>
        <?php if (isset($this->other_ref)): ?>
            Other reference: <?php echo $this->escape($this->other_ref); ?><br/>
        <?php endif; ?>
        <?php if (isset($this->treasureID)): ?>
            Treasure case number: <?php echo $this->escape($this->treasureID); ?><br/>
        <?php endif; ?>
        <?php if (isset($this->musaccno)): ?>
            Museum accession number: <?php echo $this->escape($this->musaccno); ?>
        <?php endif; ?>
    </p>
<?php endif; ?>