<?php
$quantities = array($this->quantityCoins, $this->quantityArtefacts, $this->quantityContainers);
?>
<?php if (array_filter($quantities)): ?>
    <h4 class="lead">Quantity summary</h4>
    <ul>
        <?php if ($this->quantityCoins > 0): ?>
            <li>Coins in hoard: <?php echo $this->quantityCoins; ?></li>
        <?php endif; ?>
        <?php if ($this->quantityArtefacts > 0): ?>
            <li>Artefacts in hoard: <?php echo $this->quantityArtefacts; ?></li>
        <?php endif; ?>
        <?php if ($this->quantityContainers > 0): ?>
            <li>Containers for the hoard: <?php echo $this->quantityContainers; ?></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
