<?php
$this->headTitle('Submit an error report on ' . $this->hoardID);
$this->metaBase()->setDescription('Add an error report on one of the hoards we have recorded.')
    ->setKeywords('error,reports,hoards, data checking')
    ->generate();
?>
<h2 class="lead">
    <?php echo $this->title(); ?>
</h2>
<p>
    Thank you for taking the time to report an error about this find. The error report will be sent to the hoarding
    project team.
</p>
