<?php if(!empty($this->curr_loc) || !empty($this->subsequentActionTerm)):?>
    <h4>Subsequent actions</h4>
    <p>
        <?php if(!empty($this->curr_loc) ):?>
            Current location of find: <?php echo $this->curr_loc;?><br />
        <?php endif;?>
        <?php if(!empty($this->subsequentActionTerm)):?>
            Subsequent action after recording: <?php echo $this->subsequentActionTerm;?>
        <?php endif;?>
    </p>
<?php endif;?>