<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 29/10/14
 * Time: 13:46
 */
?>
<tr>
    <?php $url = array('module' => 'database', 'controller' => 'hoards', 'action' => 'record', 'id' => $this->hoardID); ?>
    <td><a href="<?php echo $this->url($url, 'default', true); ?>"><?php echo $this->hoard; ?></a></td>
    <td><?php echo $this->broadperiod; ?></td>
    <td><?php echo $this->quantity; ?></td>
    <td><?php echo $this->denomination; ?></td>
    <td><?php if (!is_null($this->ruler)): ?>
            <?php echo $this->ruler; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
    <td><?php if (!is_null($this->mint)): ?>
            <?php echo $this->mint; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
    <td><?php if (!is_null($this->geography)): ?>
            <?php echo $this->geography; ?>
        <?php else: ?>
            -
        <?php endif; ?>
    </td>
</tr>