<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$rulers  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$rulers->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$rulersElem = $dom->createElement('emperors');
foreach($this->emps as $r){
$rulerElem = $dom->createElement('emperor');
   foreach($r as $k => $a){

       $rulerElem->appendChild( $dom->createElement($k, htmlspecialchars($a)));
   }

$rulersElem->appendChild( $rulerElem );

$rulers->appendChild( $rulerElem );
}

$dom->appendChild( $rulers );

$xmlData  = $dom->saveXML();
echo $xmlData;
