<?php
$this->headTitle('The Roman Emperors and their wives');
$this->headMeta('A list of the Roman Emperors and their wives who issued coins during the Empire','description');
$this->headMeta('roman,emperors,empire,coins,numismatics','dc.keywords');
?>

<h2 class="lead">Emperors of the Roman Empire</h2>
<p>View on an interactive <a href="<?php echo $this->url(array('module' => 'romancoins','controller'=>'emperors','action' => 'timeline'),'default',true);?>">Timeline</a>.</p>
<h3 class="lead">The Julio Claudian Dynasty</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->julioclaudian);?>
</ul>

<h3 class="lead">Civil War Emperors</h3>
<ul> 
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->civilwar);?>
</ul>

<h3 class="lead">The Flavians</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->flavian);?>
</ul>

<h3 class="lead">The Adoptive Emperors</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->adoptive);?>
</ul>

<h3 class="lead">The Antonines</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->antonine);?>
</ul>

<h3 class="lead">The Emperors of 193 AD</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->waremperors);?>
</ul>

<h3 class="lead">The Severans</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->severan);?>
</ul>

<h3 class="lead">Third Century Emperors</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->thirdcentury);?>
</ul>

<h3 class="lead">The Gallic Empire</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->british);?>
</ul>

<h3 class="lead">Brittanic Empire</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->theodosius);?>
</ul>

<h3 class="lead">The Tetrarchy</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->gallic);?>
</ul>

<h3 class="lead">The House of Constantine</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->tetrarchy);?>
</ul>

<h3 class="lead">House of Valentinian (AD 364 - AD 378)</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->constantine);?>
</ul>

<h3 class="lead">House of Theodosius (AD 378 - AD 402)</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->valentinian);?>
</ul>



<h3 class="lead">4th Century Emperors</h3>
<ul>
<?php echo $this->partialLoop('partials/numismatics/dynasticList.phtml',$this->fourthcentury);?>
</ul>