<?php
$this->headTitle('The Roman Emperors and their wives');
$this->headMeta('A list of the Roman Emperors and their wives who issued coins during the Empire','description');
$this->headMeta('roman,emperors,empire,coins,numismatics','dc.keywords');
?>

<h2>Emperors of the Roman Empire</h2>
<p>View on an interactive <a href="<?php echo $this->url(array('module' => 'romancoins','controller'=>'emperors','action' => 'timeline'),'default',true);?>">Timeline</a>.</p>
<h3>The Julio Claudian Dynasty</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->julioclaudian);?>
</ul>

<h3>Civil War Emperors</h3>
<ul id="related"> 
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->civilwar);?>
</ul>

<h3>The Flavians</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->flavian);?>
</ul>

<h3>The Adoptive Emperors</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->adoptive);?>
</ul>

<h3>The Antonines</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->antonine);?>
</ul>

<h3>The Emperors of 193 AD</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->waremperors);?>
</ul>

<h3>The Severans</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->severan);?>
</ul>

<h3>Third Century Emperors</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->thirdcentury);?>
</ul>

<h3>The Gallic Empire</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->british);?>
</ul>

<h3>Brittanic Empire</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->theodosius);?>
</ul>

<h3>The Tetrarchy</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->gallic);?>
</ul>

<h3>The House of Constantine</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->tetrarchy);?>
</ul>

<h3>House of Valentinian (AD 364 - AD 378)</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->constantine);?>
</ul>

<h3>House of Theodosius (AD 378 - AD 402)</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->valentinian);?>
</ul>



<h3>4th Century Emperors</h3>
<ul id="related">
<?php echo $this->partialLoop('partials/numismatics/dynasticlist.phtml',$this->fourthcentury);?>
</ul>