<?php
$this->headTitle('A timeline of Roman issuers');
$this->metaBase()
        ->setDescription('A timeline of Roman issuers')
        ->setKeywords('roman,issuers,timeline,emperor')
        ->generate();
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/compiled/js/storyjs-embed.js',$type = 'text/javascript');
?>
<h2 class="lead">
    <?php echo $this->title();?>
</h2>
<div id="timeline"></div>
<?php $this->jQuery()->javascriptCaptureStart() ?>

$(document).ready(function() {
    createStoryJS({
        type: 'timeline',
        width: '100%',
        height: '600',
        source:	'<?php echo $this->serverUrl();?>/romancoins/emperors/data/format/json',
        embed_id; 'timeline',
        hash_bookmark:  true,                           
    });
});
<?php $this->jQuery()->javascriptCaptureEnd() ?>