<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 19/12/14
 * Time: 10:51
 */
$this->headTitle('Edit a SketchFab 3D model attached to a record');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title();?></h2>
<?php
$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
?>

    <a class="btn btn-success"
       href="<?php echo $this->url(array(
           'module' => 'database',
           'controller' => 'artefacts',
           'action' => 'record', 'id' => $params['returnID']), null, true); ?>"
       title="return to the record">Return to record</a>
<?php echo $this->form;?>