<h4 class="lead">Coin data (numismatics)</h4>
<?php echo $this->coinEditDeleteLink()
    ->setFindID($this->id)
    ->setRecordID($this->coinID)
    ->setBroadperiod($this->broadperiod)
    ->setSecuID($this->secuid)
    ->setInstitution($this->institution)
    ->setCreatedBy($this->createdBy);
?>
<p>
    <?php if (!is_null($this->cciNumber)): ?>
        <strong>Celtic Coin Index Number:</strong> <span property="owl:sameAs"
                                                         resource="http://http://www.celticcoins.ca/record.php?coin_id=<?php echo str_replace('.', '', $this->cciNumber); ?>"><?php echo $this->cciNumber; ?></span>
    <?php endif; ?>

    <?php if (!is_null($this->denomination)) : ?>
        <br />
        Denomination: <?php echo $this->denomination; ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'denominations', 'action' => 'denomination', 'id' => $this->denominationID), null, true); ?>"
                title="Read scope note for <?php echo $this->denomination; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'denomination' => $this->denominationID), null, true); ?>"
                title="view all records assigned to denomination: <?php echo $this->denomination; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->ruler1)) : ?>
        <br />
        Ruler/issuer: <?php echo $this->escape($this->primaryRuler); ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'rulers', 'action' => 'ruler', 'id' => $this->ruler1), null, true); ?>"
                title="Read scope note for <?php echo $this->primaryRuler; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'ruler' => $this->ruler1), null, true); ?>"
                title="view all records assigned to <?php echo $this->primaryRuler; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->ruler2)) : ?>
        <br />
        Secondary ruler/issuer: <?php echo $this->escape($this->secondaryRuler); ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'rulers', 'action' => 'ruler', 'id' => $this->ruler2), null, true); ?>"
                title="Read scope note for <?php echo $this->secondaryRuler; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'ruler' => $this->ruler2), null, true); ?>"
                title="view all records assigned to <?php echo $this->ruler2; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->tribe)) : ?>
        <br />
        Tribe: <?php echo $this->escape($this->tribe); ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'tribes', 'action' => 'tribe', 'id' => $this->tribeID), null, true); ?>"
                title="Read scope note for <?php echo $this->tribe; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'tribe' => $this->tribeID), null, true); ?>"
                title="view all records assigned to <?php echo $this->tribe; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->ironAgeRegion)): ?>
        <br />
        Geographic provenance: <?php echo $this->ironAgeArea; ?> <?php echo $this->ironAgeRegion; ?>
    <?php endif; ?>

    <?php if (!is_null($this->bmcType)): ?>
        <br />
        British Museum Catalogue type: <?php echo $this->escape($this->bmcType); ?>x
    <?php endif; ?>

    <?php if (!is_null($this->allenType)): ?>
        <br />
        Allen Type: <?php echo $this->escape($this->allenType); ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'allentypes', 'action' => 'type', 'id' => $this->allenType), null, true); ?>"
                title="Read scope note for <?php echo $this->allenType; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'allen' => $this->allenType), null, true); ?>"
                title="view all records assigned to <?php echo $this->allenType; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->mack)): ?>
        <br />
        Mack Type: <?php echo $this->escape($this->mack); ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'macktypes', 'action' => 'type', 'id' => $this->mack), null, true); ?>"
                title="Read scope note for <?php echo $this->mack; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'mack' => $this->mack), null, true); ?>"
                title="view all records assigned to <?php echo $this->allebn_type; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->vaType)): ?>
        <br />
        Van Arsdell Type (VA): <?php echo $this->vaType; ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'vanarsdelltypes', 'action' => 'type', 'id' => $this->vaType), null, true); ?>"
                title="Read scope note for <?php echo $this->vaType; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'vaType' => $this->vaType), null, true); ?>"
                title="view all records assigned to <?php echo $this->vaType; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->abcType)): ?>
        <br />
        Ancient British Coins (ABC): <?php echo $this->escape($this->abcType); ?>
    <?php endif; ?>

    <?php if (!is_null($this->mintName)) : ?>
        <br />
        Mint or issue place: <?php echo $this->escape($this->mintName); ?> <a
                href="<?php echo $this->url(array('module' => 'ironagecoins', 'controller' => 'mints', 'action' => 'mint', 'id' => $this->mintID), null, true); ?>"
                title="Read scope note for <?php echo $this->mintName; ?>"><i class="icon-info-sign"></i></a> | <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'mint' => $this->mintID), null, true); ?>"
                title="view all records assigned to <?php echo $this->mintName; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->obverseDescription)) : ?>
        <br />
        Obverse description: <?php echo $this->escape($this->obverseDescription); ?>
    <?php endif; ?>

    <?php if (!is_null($this->obverseInscription)) : ?>
        <br />
        Obverse inscription: <?php echo $this->escape($this->obverseInscription); ?>
    <?php endif; ?>

    <?php if (!is_null($this->reverseDescription)) : ?>
        <br />
        Reverse description: <?php echo $this->escape($this->reverseDescription); ?>
    <?php endif; ?>

    <?php if (!is_null($this->reverseInscription)) : ?>
        <br />
        Reverse inscription: <?php echo $this->escape($this->reverseInscription); ?>
    <?php endif; ?>

    <?php if (!is_null($this->dieAxisName)) : ?>
        <br />
        Die axis measurement: <?php echo $this->escape($this->dieAxisName); ?> <a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'dieaxis', 'id' => $this->dieAxis), null, true); ?>"
                title="Read scope note for <?php echo $this->dieAxisName; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'axis' => $this->dieAxis), null, true); ?>"
                title="view all records assigned to <?php echo $this->dieAxisName; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>

    <?php if (!is_null($this->wear)) : ?>
        <br />
        Degree of wear: <?php echo $this->escape($this->wear); ?> <a
                href="<?php echo $this->url(array('module' => 'datalabs', 'controller' => 'terminology', 'action' => 'weartype', 'id' => $this->wearID), null, true); ?>"
                title="Read scope note for <?php echo $this->wear; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'wear' => $this->wearID), null, true); ?>"
                title="view all records assigned to <?php echo $this->wear; ?>"><i class="icon-search"></i></a>
    <?php endif; ?>
    <?php if (!is_null($this->status)): ?>
        <br/>
        Status: <span property="pas:status"><?php echo $this->status; ?></span><br/>
        <?php if (!is_null($this->rulerQualifier)): ?>
            Status qualifier: <?php echo $this->certainty()->setCertainty($this->statusQualifier); ?>
        <?php endif; ?>
    <?php endif; ?>

</p>
