<h4 class="lead">Jetton / token data</h4>
<?php
echo $this->jettonEditDeleteLink()
    ->setFindID($this->id)
    ->setRecordID($this->coinID)
    ->setBroadperiod($this->broadperiod)
    ->setSecuID($this->secuid)
    ->setInstitution($this->institution)
    ->setCreatedBy($this->createdBy);
?>
<p>

    <?php if (!is_null($this->primaryRuler)) : ?>
        Issuer: <?php echo $this->escape($this->primaryRuler); ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->jettonClass)): ?>
        Class: <?php echo $this->jettonClass; ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->jettonGroup)): ?>
        Group: <?php echo $this->jettonGroup; ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->jettonType)): ?>
        Type: <?php echo $this->jettonType; ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->denomination)) : ?>
        Denomination: <?php echo $this->escape($this->denomination); ?> <a
                href="<?php echo $this->url(array('module' => 'medievalcoins', 'controller' => 'denominations', 'action' => 'denomination', 'id' => $this->denominationID), null, true); ?>"
                title="Read scope note for <?php echo $this->denomination; ?>"><i class="icon-info-sign"></i></a> <a
                href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'results', 'denomination' => $this->denominationID), null, true); ?>"
                title="view all records assigned to denomination: <?php echo $this->denomination; ?>"><i class="icon-search"></i></a><br/>
    <?php endif; ?>

    <?php if (!is_null($this->mint_name)): ?>
        Mint or issue place: <?php echo $this->escape($this->mint_name); ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->obverseDescription)): ?>
        Obverse description: <?php echo $this->escape($this->escape($this->obverseDescription)); ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->obverseInscription)): ?>
        Obverse inscription: <?php echo $this->escape($this->obverseInscription); ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->reverseDescription)): ?>
        Reverse description: <?php echo $this->escape($this->reverseDescription); ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->reverseInscription)): ?>
        Reverse inscription: <?php echo $this->escape($this->reverseInscription); ?><br/>
    <?php endif; ?>


    <?php if (!is_null($this->dieAxisName)): ?>
        Die axis measurement: <?php echo $this->dieAxisName; ?><br/>
    <?php endif; ?>

    <?php if (!is_null($this->wear)): ?>
        Degree of wear: <?php echo $this->wear; ?>
    <?php endif; ?>
</p>

