<?php 	$this->headTitle('System actions');?>
<h2>Administer system settings</h2>
<h3>Site mechanics</h3>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'configuration'),null,true);?>">System config</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'acronyms'),null,true);?>" title="Manage acronyms">Acronyms</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'system','action' => 'serverconfig'),null,true);?>" title="Manage acronyms">System environment</a></li>
</ul>
<h3>Roles</h3>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'system','action' => 'roles'),null,true);?>" title="View system roles">System roles</a></li>
</ul>

<h3>Cache operations</h3>
<ul id="related">
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'system','action' => 'cleancache'),null,true);?>" title="Clean out the entire cache">Clean entire cache</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'system','action' => 'cleanoldcache'),null,true);?>" title="Clean out the old cache">Clean old cache</a></li>
</ul>

<h3>System backup to Amazon</h3>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'system','action' => 's3'),null,true);?>">List S3 backups</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'system','action' => 's3backup'),null,true);?>">Manual backup</a></li>
</ul>

<h3>Oauth tokens</h3>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'oauth'),null,true);?>">View current tokens</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'oauth','action' => 'twitter'),null,true);?>">Create Twitter token</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'oauth','action' => 'yahoo'),null,true);?>">Create yahoo token</a></li>
<li><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'oauth','action' => 'flickr'),null,true);?>">Create flickr token</a></li>
</ul>