<?php $this->headTitle('Available backups on Amazon S3');
?>
<h2>All backups available on Amazon S3</h2>
<?php if($this->data):?>
<ul>
<?php foreach($this->data as $data):?>
<li><a href="http://s3.amazonaws.com/<?php echo $data['name'];?>" title="Download <?php echo $data['name'];?>"><?php echo $data['name']?></a>: Backup date: <?php echo date('d-m-Y H:i:s',$data['mtime']);?> - Backup size: <?php echo $this->humanfilesize($data['size']);?></li>
<?php endforeach;?>
</ul>
<?php endif;?>