<?php $this->headTitle('Issuing Mints of the Post Medieval period'); ?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<table class="table table-striped" summary="A list of all Medieval mints in use">
    <caption>A list of all Medieval mints in England and Wales</caption>
    <thead>
    <tr>
        <th>Mint name</th>
        <th>Geo location</th>
    </tr>
    </thead>
    <tbody>
        <?php echo $this->partialLoop('partials/numismatics/medievalMints.phtml', $this->mints); ?>
    </tbody>
</table>