<?php
$this->headTitle($this->os . ' operating system version ' . $this->timeSpanParameter());
?>
<h2><?php echo $this->title();?></h2>
<?php echo $this->timeSpansGa();?>
<a href="<?php echo $this->url(array('module' => 'analytics', 'controller' => 'technology', 'action' => 'mobileos'),'default', true);?>" class="btn btn-small">Return to operating system lists</a>

<?php 
$this->inlineScript()->appendFile('https://www.google.com/jsapi',$type = 'text/javascript');
$this->inlineScript()->captureStart();?>
google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Operating system version', 'Visitors'],
          <?php foreach($this->results as $row):?>
          ['<?php echo $this->os;?>: <?php echo $this->os . ': ' .$row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_OPERATING_SYSTEM_VERSION)->value;?>' , <?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value;?>	],
          <?php endforeach;?>
        ]);

        var options = {
          title: '<?php echo $this->title();?>',
          legend: { position: 'right'},
          height: '500',
          
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart'));
        chart.draw(data, options);
      }
<?php $this->inlineScript()->captureEnd();?>   
<div id="chart" style="width: 900px; height: 500px;"></div>

<table class="table table-striped">
	<caption><?php echo $this->title();?> </caption>
		<thead>
		<tr>
			<th>Operating system Version</th>
			<th>Visitors</th>
			<th>Visits</th>
			<th>Bounces</th>
			<th>Time on site</th>
		</tr>
		</thead>
		<tbody>
			<?php foreach ($this->results as $row): ?>
			<tr>
				<td><?php echo $this->os;?>: <?php echo $row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_OPERATING_SYSTEM_VERSION)->value;?></td>
				<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value;?></td>
				<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITS)->value;?></td>
				<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_BOUNCES)->value;?></td>
				<td><?php echo $this->secondsToMinutes()->setSeconds($row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_AVG_TIME_ON_SITE)->value);?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
</table>