<?php
$this->headTitle('Activities available for use on the database');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <a class="btn btn-small btn-success"
       href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'terminology', 'action' => 'addactivity'), null, true); ?>">Add
        a new activity</a>
    <hr/>
<?php if (!empty($this->activities)): ?>
    <table class="table table-striped" summary="List of primary activities on database">
        <thead>
        <tr>
            <th>Activity type</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/activityList.phtml', $this->activities); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No activities available.</p>
<?php endif; ?>