<?php 	$this->headTitle('Early Medieval ascribed cultures');?>
<h2>Ascribed cultures</h2>
<p>The Scheme has broken the Early Medieval period down into the following ascribed cultures to make it easier to search the database.</p>
<p><a class="btn btn-large btn-success" href="<?php echo $this->url(array('module' => 'admin','controller'=>'terminology','action'=>'addculture'),null,true);?>">Add a new ascribed culture</a></p>
<table class="table table-striped" summary="Ascribed cultures in use on the database">
<caption>All available ascribed Early Medieval culture</caption>
<thead>
<tr>
<th>Culture</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Validity</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/cultureTable.phtml',$this->cultures);?>
</tbody>
</table>
