<?php
$this->headTitle('Methods of decoration');
$this->metaBase()
        ->setDescription(' A list of all methods of decoration in use in our terminologies')
        ->generate();
?>
<h2><?php echo $this->title();?></h2>
<p>
    <a class="btn btn-large btn-success" href="<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'terminology',
        'action' => 'adddecorationmethod'
        ),null,true);?>" title="Add a new decorative method">Add new decorative method</a></p>
<table class="table table-striped" summary="<?php echo $this->title();?>">
    <caption><?php echo $this->title();?></caption>
    <thead>
        <tr>
            <th>Denomination</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php echo $this->partialLoop('partials/admin/decmethodsTable.phtml',$this->decs);?>
    </tbody>
</table>
