<?php 
	$this->headTitle('Delete an activity');
if ($this->activity) :?>
<h2>Delete a primary activity</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->activity->term); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action'=>'deleteactivity')); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->activity->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>