<?php
$this->headTitle("Delete a preservation state");
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!is_null($this->preserve)) : ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>Are you sure that you want to delete <?php echo $this->preserve->term; ?></p>
    <form
        action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'terminology', 'action' => 'deletepreservation'), null, true); ?>"
        method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->preserve->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">There has been an error</h2>
    <p>Cannot find the person that you requested.</p>
<?php endif; ?>