<?php 
	$this->headTitle('Delete a Workflow stage from the system');
if ($this->workflow) :?>
<h2>Delete a Workflow stage</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->workflow->workflowstage); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action'=>'deleteworkflow'),null.true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->workflow->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<h2>An error has occurred.</h2>
<p>Cannot find the item requested.</p>
<?php endif;?>