<?php 
	$this->headTitle('Delete a surface treatment from the system');
if ($this->surface) :?>
<h2>Delete <?php echo $this->escape($this->surface->term); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->surface->term); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action'=>'deletesurface'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->note->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>