<?php 
	$this->headTitle('Delete a period');
if ($this->period) :?>
<h2>Delete <?php echo $this->escape($this->period->term); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->period->term); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action'=>'deleteperiod'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->period->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>