<?php
$this->headTitle('Delete a material');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!is_null($this->material)) : ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>Are you sure that you want to delete <?php echo $this->material->term; ?></p>
    <form action="<?php echo $this->url(
        array(
            'module' => 'admin', 'controller' => 'terminology', 'action' => 'deletematerial'
        ), null, true); ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->material->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>Cannot find the item requested.</p>
<?php endif; ?>