<?php 
	$this->headTitle("Delete a Landuse from the system");
if ($this->landuse) :?>
<h2>Delete <?php echo $this->escape($this->landuse->term); ?></h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->landuse->term); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action'=>'deletelanduse')); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->landuse->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<h2>An error has occurred.</h2>
<p>Cannot find the item requested.</p>
<?php endif;?>