<?php 	$this->headTitle('Methods of manufacture');?>
<h2>Methods of manufacture</h2>
<p><a class="btn btn-large btn-success" href="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action' => 'addmanufacture'),null,true);?>" title="Add a new manufacturing method">Add a new manufacture method</a></p>
<table class="table table-striped" summary="List of materials available">
<thead>
<tr>
<th>Manufacture</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/manufactureTable.phtml',$this->manufactures);?>
</tbody>
</table>
