<?php
$this->headTitle('Methods of manufacture');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead">Methods of manufacture</h2>
    <a class="btn btn-large btn-success"
       href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'terminology', 'action' => 'addmanufacture'), null, true); ?>"
       title="Add a new manufacturing method">Add a new manufacture method</a>
    <hr/>

<?php if (!empty($this->manufactures)): ?>
    <table class="table table-striped" summary="<?php echo $this->title(); ?>">
        <thead>
        <tr>
            <th>Manufacture</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/manufactureTable.phtml', $this->manufactures); ?>
        </tbody>
    </table>
<?php else: ?>

<?php endif; ?>