<?php 	$this->headTitle('List of map origins for findspots');?>
<h2>Terms for the origin of grid references</h2>
<p><a class="btn btn-large btn-success" href="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action' => 'addmaporigin'),null,true);?>" title="Add a new term">Add a new term</a></p>

<table class="table table-striped" summary="A list of all available map origin terms">
    <caption>All originating grid reference types</caption>
    <thead>
        <tr>
            <th>Term</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Valid</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php echo $this->partialLoop('partials/admin/originsList.phtml',$this->origins);?>
    </tbody>
</table>