<?php
$this->headTitle('Materials available for use on the database');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<a clsss="btn btn-large btn-success"
   href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'terminology', 'action' => 'addmaterial'), null, true); ?>"
   title="Add a new material">Add a new material</a>

<hr/>

<?php if (!empty($this->materials)): ?>
    <table class="table table-striped" summary="List of materials available">
        <thead>
        <tr>
            <th>Material</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/materialsTable.phtml', $this->materials); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>You have either entered an incorrect url parameter, or there are no recorded coin types available.</p>
<?php endif; ?>

<?php echo $this->paginationControl($this->materials, 'Sliding', 'structure/pagination.phtml'); ?>
