<?php
$this->headTitle('Materials available for use on the database');?>
<h2>Materials</h2>
<p><a clsss="btn btn-large btn-success" href="<?php echo $this->url(array('module' => 'admin','controller' => 'terminology','action' => 'addmaterial'),null,true);?>" title="Add a new material">Add a new material</a></p>
<?php if (count($this->materials)): ?>
<table class="table table-striped" summary="List of materials available">
<thead>
<tr>
<th>Material</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/materialsTable.phtml',$this->materials);?>
</tbody>
</table>
<?php else:?>
<p>You have either entered an incorrect url parameter, or there are no recorded coin types available.</p>
<?php endif; ?>

<?echo $this->paginationControl($this->materials, 'Sliding', 'structure/pagination.phtml'); ?>
