<h2>Periods used on the database</h2>
<?php
$this->headTitle('All periods in use on the database');

echo $this->Href(array(
    'module' => 'admin',
    'controller' => 'terminology',
    'action' => 'addperiod',
    'checkAcl' => true,
    'acl'=>'Zend_Acl',
    'attribs' => array('title' => 'Edit a period', 'class' => 'btn btn-large btn-success'),
    'params' => array('id'=>$this->id),
    'content'=> 'Add a new period',
        'wrapper' => array('tag' => 'p'))
    );

?>
<table class="table table-striped" summary="All periods in use on the database">
    <caption>All periods in use</caption>
<thead>
<tr>
<th>Period name</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Validity</th>
<th>Actions</th>
</tr>
</thead>
<?php echo $this->partialLoop('partials/admin/periodsTableList.phtml',$this->periods);?>
</table>

