<?php 	$this->headTitle('Preservation states');?>
<h2>States of preservation</h2>
<p><a class="btn btn-success btn-large"href="<?php echo $this->url(array('module' => 'admin','controller'=>'terminology','action'=>'addpreservation'),null,true);?>">Add a new preservation state</a></p>
<table class="table table-striped" summary="List of preservation states available">
<thead>
<tr>
<th>State</th>
<th>Created</th>
<th>Created by</th>
<th>Updated</th>
<th>Updated by</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/admin/preservationTable.phtml',$this->preserves);?>
</tbody>
</table>