<?php
$this->headTitle('Surface treatments');
$this->metaBase()->setDescription($this->title())->generate();
?>
    <h2 class="lead">Surface treatments</h2>
    <a class="btn btn-large btn-success"
       href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'terminology', 'action' => 'addsurface'), null, true); ?>"
       title="Add a new surface treatment term">Add a new surface treatment term</a>
    <hr/>
<?php if (!empty($this->surfaces)): ?>
    <table class="table table-striped" summary="List of surface treatments that the Scheme uses">
        <caption>Surface treatments</caption>
        <thead>
        <tr>
            <th>Treatment term</th>
            <th>Created</th>
            <th>Created by</th>
            <th>Updated</th>
            <th>Updated by</th>
            <th>Validity</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->partialLoop('partials/admin/surfacesTable.phtml', $this->surfaces); ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No surface treatments available.</p>
<?php endif; ?>