<h2>Searches performed</h2>
<?php 
	$this->headTitle('All searches on the database');
if(count($this->searches)):?>
<ol id="timeline" class="statuses">

<?php echo $this->partialLoop('partials/users/searchList.phtml', $this->searches) ?>
</ol>
<?echo $this->paginationControl($this->searches, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else:?>
<p>No search history available to you at present.</p>
<?php endif;?> 