<?php
$this->headTitle("Issuing rulers of the Greek and Roman Provincial period");
$this->metaBase()->setDescription($this->title())
    ->setSubject('Greek numismatics')
    ->generate();
?>

<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->greeks)): ?>
    <ul><?php echo $this->partialLoop('partials/numismatics/shared/rulers.phtml', $this->greeks); ?></ul>
    <?php echo $this->paginationControl($this->greeks, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>No records available.</p>
<?php endif; ?>


