<?php
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom = new DomDocument("1.0", "UTF-8");
$rulers  = $dom->createElement('response');

$meta = $dom->createElement('meta');
$rulers->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
$rulersElem = $dom->createElement('rulers');

foreach($this->greek as $r){
$rulerElem = $dom->createElement('ruler');
   foreach($r as $k => $a){
      
       $rulerElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
	
$rulersElem->appendChild( $rulerElem );
$imageElem = $dom->createElement('recentRecords');	
$rulerElem->appendChild($imageElem);

foreach($this->images as $i){
$i = (object)$i;
$recordElem = $dom->createElement('record');
$imageElem->appendChild( $recordElem);
$recordElem->appendChild( $dom->createElement('findID', $i->old_findID));
$recordElem->appendChild( $dom->createElement('label', $i->label));
$recordElem->appendChild( $dom->createElement('objectType', $i->objecttype));
$recordElem->appendChild( $dom->createElement('broadPeriod', $i->broadperiod));
$recordElem->appendChild( $dom->createElement('url', $site . '/database/artefacts/record/id/' . $i->id));
$recordElem->appendChild( $dom->createElement('thumbnail', $site . ' /images/' . $i->id . '.jpg'));
}
$rulers->appendChild( $rulerElem );
}

$dom->appendChild( $rulers );

$xmlData  = $dom->saveXML();
echo $xmlData;
