<?php 
$this->headTitle('Expired advertisements for vacancies at the Scheme');
$this->metaBase()
        ->setDescription('A list of expired vacancies that the Scheme has advertised')
        ->setSubject('Expired vacancies')
        ->setKeywords('vacancies,archive')
        ->generate();
?>
<h2>
    <?php echo $this->title();?>
</h2>
<?php if(count($this->archives)):?>
<ul>
<?php echo $this->partialLoop('partials/about/vacancyList.phtml',$this->archives); ?>
</ul>
<?php echo $this->paginationControl($this->archives, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else:?>
<p>There are no archived jobs available to you.</p>
<?php endif;?>
