<?php
$this->headTitle('Current vacancies at the Portable Antiquities Scheme');
$this->metaBase()
    ->setDescription('The Scheme regularly announces vacancies when they arise via this page and other job sites.')
    ->setSubject('Vacancies')
    ->setKeywords('vacancies,jobs,archaeology,portable antiquities')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (count($this->vacs)) : ?>

    <ul>
        <?php echo $this->partialLoop('partials/about/vacancyList.phtml', $this->vacs); ?>
    </ul>
    <?php echo $this->paginationControl($this->vacs, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else: ?>
    <p>There are currently no vacancies at the Scheme.</p>
<?php endif; ?>
