<?php
$this->headTitle('Current vacancies at the Portable Antiquities Scheme');
$this->metaBase(
'The Scheme regularly announces vacancies when they arise via this page and other job sites.',
'Vacancies',
'vacancies,jobs,archaeology,portable antiquities',
'keywords');
?>
<?php if (count($this->vacs) > 0) : ?>
<h2>Current vacancies</h2>

<ul id="related">
<?php echo $this->partialLoop('partials/getinvolved/vacancyList.phtml',$this->vacs);
?>
</ul>
<?php echo $this->paginationControl($this->vacs, 'Sliding', 'structure/pagination.phtml'); ?>

<?php else:?>
<h2>Current vacancies</h2>
<p>There are currently no vacancies at the Scheme. However, you can try the following sites for vacancies in the Museum and Heritage/ Archaeology sector:</p>
<?php
$delicious = new Zend_Service_Delicious($this->delicious->id, $this->delicious->pwd);
$posts = $delicious->getAllPosts();
?>
<ul>
<?php
foreach ($posts->withTags(array('jobs')) as $post){
?>
<li><a href="<?php echo $post->getUrl();?>" title="<?php echo $post->getTitle();?>"><?php echo $post->getNotes();?></a>
<?php } ?>
</ul>
<?php endif;?>
