<?php
$this->headTitle('Add a new object');
$this->metaBase()->setDescription($this->title())->generate();
$this->addCheck()->canThey();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p><a class="btn btn-success btn-small" href="<?php echo $this->url(array(
                'module' => 'database',
                'controller' => 'artefacts',
                'action' => 'add',
                'copy' => 'last'),
            null, true);?>"
          title="Autofill form fields from last record you created" id="populate" accesskey="c">Copy last record</a></p>

<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile(
    $this->baseUrl() . '/js/bootstrap-datepicker-v1.9.0.js',
    $type = 'text/javascript'
);
$this->headLink()->appendStylesheet('/css/bootstrap-datepicker.css');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-typeahead.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/objectType.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/finder.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/secondaryfinder.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/primaryID.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/secondaryID.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/recorder.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');

if (!is_null(Zend_Controller_Front::getInstance()->getRequest()->getParam('copy'))) {
    $this->headTitle(' copied from last record');
}
?>

<?php $this->jQuery()->javascriptCaptureStart() ?>
    $(document).ready(function() {
        $datePickerSettings = {
            endDate: '0d',
            format: 'yyyy-mm-dd',
        };

        $("#datefound1").datepicker($datePickerSettings);
        $("#datefound2").datepicker($datePickerSettings);
        $("input[type='select']:first", document.forms[0]).focus();
        $('form').areYouSure();
        $("form").submit(function() {
            $(":submit", this).attr("disabled", "disabled");
        });
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>