<?php
$this->headTitle('Delete find');
?>
<?php if (!is_null($this->find)) : ?>
    <?php
    $this->editCheck()
        ->setInstitution($this->find->institution)
        ->setCreatedBy($this->find->createdBy)
        ->canThey();
    ?>
    <h2 class="lead">
        Delete <?= $this->escape($this->find->old_findID) . ' - ' . $this->escape($this->find->objecttype) ?></h2>
    <p>Are you sure that you want to delete
        <strong><?=  $this->escape($this->find->objecttype) ?></strong>
    </p>
    <form action="<?= $this->url(array('module' => 'database', 'controller' => 'artefacts', 'action' => 'delete'), null, true) ?>" method="post">
        <div class="btn-toolbar">
            <input type="hidden" name="id" value="<?= $this->find->id ?>"/>
            <input type="hidden" name="findID" value="<?= $this->find->secuid ?>"/>
            <input type="hidden" name="objectType" value="<?= $this->find->objecttype ?>"/>

            <input type="submit" class="btn btn-danger" name="confirmDelete" value="Yes"/>
            <input type="submit" class="btn btn-default" name="confirmDelete" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occurred.</h2>
    <p>Cannot find the item requested.</p>
<?php endif; ?>
