<?php
$this->headTitle('Edit find details');
$this->metaBase()->setDescription($this->title())->setSubject('Database editing')->generate();
?>
<?php
$this->editCheck()
    ->setInstitution($this->find['institution'])
    ->setCreatedBy($this->find['createdBy'])
    ->canThey();
?>
<?php echo $this->partial('partials/database/structural/editFindH2.phtml', $this->find); ?>

<?php echo $this->form; ?>

<?php
$this->jQuery()->addJavascriptFile(
    $this->baseUrl() . '/js/bootstrap-datepicker-v1.9.0.js',
    $type = 'text/javascript'
);
$this->headLink()->appendStylesheet('/css/bootstrap-datepicker.css');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-typeahead.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/objectType.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/finder.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/secondaryfinder.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/primaryID.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/secondaryID.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/recorder.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/jquery.are-you-sure.js', $type = 'text/javascript');

?>
<?php $this->jQuery()->javascriptCaptureStart() ?>
    $(document).ready(function() {
        $datePickerSettings = {
            endDate: '0d',
            format: 'yyyy-mm-dd',
        };

        $("#datefound1").datepicker($datePickerSettings);
        $("#datefound2").datepicker($datePickerSettings);
        $("input[type='text']:first", document.forms[0]).focus();
        $('form').areYouSure();
        $("form").submit(function() {
            $(":submit", this).attr("disabled", "disabled");
        });
    });
<?php $this->jQuery()->javascriptCaptureEnd() ?>