<?php 
$results = array();

foreach($this->record as $result){
	
	if(array_key_exists('description',$result)){
	$description = trim(preg_replace( '/\s+/', ' ',$result['description']));
	$result['description'] = $description;
	} else {
	$result['description'] = 'No description available';	
	}
	if(!array_key_exists('thumbnail',$result)){
	unset($result['imagedir']);
	unset($result['thumbnail']);
	unset($result['filename']);	
	} else {
		$result['thumbnail'] = $this->serverUrl() . '/images/thumbnails/' . $result['thumbnail'] . '.jpg';
	}
	$result['url'] = $this->serverUrl() . '/database/artefacts/record/id/' . $result['id'];
	if(isset($result['knownas'])){
		unset($result['parish']);
		unset($result['fourFigure']);
		unset($result['fourFigureLat']);
		unset($result['fourFigureLon']);
	} 
	if(isset($result['fourFigure'])){
		$geoJson = array(
		'type' => 'Point',
		'coordinates' => array(
		$result['fourFigureLon'],
		$result['fourFigureLat'],
		)
		);
	} else {
		$geoJson = array(
		'type' => 'Point',
		'coordinates' => array(
		NULL,
		NULL
		)
		);
	}
	
	
	
	
	$results[] = array('type' => 'Feature','geometry' => $geoJson, 'properties' => $result, 'id' => $result['id']);
	
}
echo Zend_Json::prettyPrint(Zend_Json::encode(( 
	array(
	'type' => 'FeatureCollection',
	'features' =>  $results,
	)))
	);
