<?php $results = array(); ?>
<?php
$fieldsRemove = array(
    'finderID', 'finder', 'gridref',
    'latitude', 'longitude', 'usernameUpdate',
    'fullnameUpdate', 'geohash', 'elevation',
    'landOwnerName', 'address', 'postcode',
    'easting', 'northing', 'findspotDescription',
    'comments', 'disccircum', 'coordinates'

);
$knownasRemove = array(
    'parish', 'parishID', 'centreLat',
    'centreLon', 'fourFigureLat', 'fourFigureLon',
    'fourFigure', 'map25k', 'map10k', 'woeid',
    'geonamesID'
);
?>

<?php if ($this->finds): ?>
    <?php foreach ($this->finds as $result) {
        foreach ($result as $k => $v) {
            if (in_array($k, $fieldsRemove)) {
                unset($result[$k]);
            }
        }
        if(array_key_exists('knownas', $result) && !is_null($result['knownas'])){
            foreach ($result as $k => $v) {
                if (in_array($k, $knownasRemove)) {
                    unset($result[$k]);
                }
            }
        }
        if (array_key_exists('description', $result)) {
            $description = trim(preg_replace('/\s+/', ' ', $result['description']));
            $result['description'] = $description;
        } else {
            $result['description'] = 'No description available';
        }
        if (!array_key_exists('thumbnail', $result)) {
            unset($result['imagedir']);
            unset($result['thumbnail']);
            unset($result['filename']);
        } else {
            $result['thumbnail'] = $this->serverUrl() . '/images/thumbnails/' . $result['thumbnail'] . '.jpg';
        }
        $result['url'] = $this->serverUrl() . '/database/artefacts/record/id/' . $result['id'];
        if (isset($result['knownas'])) {
            unset($result['parish']);
            unset($result['parishID']);
            unset($result['fourFigure']);
            unset($result['fourFigureLat']);
            unset($result['fourFigureLon']);
        }
        if (isset($result['fourFigure'])) {
            $geoJson = array(
                'type' => 'Point',
                'coordinates' => array(
                    $result['fourFigureLon'],
                    $result['fourFigureLat'],
                )
            );
        } else {
            $geoJson = array(
                'type' => 'Point',
                'coordinates' => array(
                    NULL,
                    NULL
                )
            );
        }


        $results[] = array('type' => 'Feature', 'geometry' => $geoJson, 'properties' => $result, 'id' => $result['id']);

    }
    echo Zend_Json::prettyPrint(Zend_Json::encode((array('type' => 'FeatureCollection', 'features' => $results))));
    ?>
<?php else: ?>
    <?php echo Zend_Json::prettyPrint(Zend_Json::encode((array('type' => 'FeatureCollection', 'features' => null)))); ?>
<?php endif; ?>