<?php
$this->headTitle('Mack Types classifications');
$this->metaBase()->setSubject('Iron Age Numismatics')
    ->setDescription('A list of Mack types in use on the Scheme database')
    ->setKeywords('iron age, numismatics,archaeology')
    ->generate();
?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php if (!empty($this->macks)): ?>
    <ul>
        <?php echo $this->partialLoop('partials/numismatics/ironAge/mackTypes.phtml', $this->macks); ?>
    </ul>
    <?php echo $this->paginationControl($this->macks, 'Sliding', 'structure/pagination.phtml'); ?>
<?php else: ?>
    <p>No Mack types available</p>
<?php endif; ?>