<?php if ($this->type->type): ?>
    <?php
    $this->headTitle('Details for Mack Type: ' . $this->type->type);
    $this->metaBase()->setDescription($this->title())->generate();
    ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <?php echo $this->searchLink()->setField('mackType')->setId($this->type->type); ?>
    <?php echo $this->latestRecords()->setQuery('mackType:"' . $this->type->type . '"'); ?>
<?php else: ?>
    <h2 class="lead">An error has occurred</h2>
    <p>No Mack Type has been found with that ID.</p>
<?php endif; ?>