<?php $this->headTitle('Most popular content for ' . $this->timeSpanParameter());?>
<h2><?php echo $this->title();?></h2>
<?php echo $this->timeSpansGa();?>
<?php echo $this->modulesGa();?>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Page</th>
			<th>Visitors</th>
			<th>Page views</th>
			<th>Unique page views</th>
			<th>Time on page</th>
			<th>Entrances</th>
			<th>Exits</th>
			<th>Bounces</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->results as $row):?>
		<tr>
			<td><a href="<?php echo $this->serverUrl();?><?php echo $row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_PAGE_PATH)->value;?>"><?php echo $row->getDimension(Zend_Gdata_Analytics_DataQuery::DIMENSION_PAGE_TITLE)->value;?></a></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_VISITORS)->value;?></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_PAGEVIEWS)->value;?></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_UNIQUE_PAGEVIEWS)->value;?></td>
			<td><?php echo $this->secondsToMinutes()->setSeconds($row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_AVG_TIME_ON_PAGE)->value);?></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_ENTRANCES)->value;?></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_EXITS)->value;?></td>
			<td><?php echo $row->getMetric(Zend_Gdata_Analytics_DataQuery::METRIC_BOUNCES)->value;?></td>
		</tr>
		<?php endforeach;?>	
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'structure/pagination.phtml'); ?>