<?php
/** Controller for displaying information about tags used and generated by opencalais
 * 
 * @author Daniel Pett <dpett at britishmuseum.org>
 * @copyright (c) 2014 Daniel Pett
 * @category   Pas
 * @package    Controller_Action
 * @subpackage Admin
 * @license http://www.gnu.org/licenses/agpl-3.0.txt GNU Affero GPL v3.0
 * @version 1
 * @uses OpenCalaisModel
 * @uses Pas_Exception_Param
 * 
*/
class Database_TagsController extends Pas_Controller_Action_Admin {
	
    /** The opencalais model
     * @access protected
     * @var \OpenCalaisModel
     */
    protected $_opencalais;

    /** Get the opencalais model
     * @access public
     * @return \OpenCalais
     */
    public function getOpenCalais()
    {
        $this->_opencalais = new OpenCalais();
        return $this->_opencalais;
    }
    
    /** Setup the contexts by action and the ACL.
     * @access public
     * @return void
    */	
    public function init() {
        $this->_helper->_acl->allow(null);
        $this->view->addScriptPath('/app/modules/database/views/scripts/');

    }
    /** Display index page
     * @access public
     * @return void
     */	
    public function indexAction() {
        $this->getFlash()->addMessage('The page requested has permanently gone from our server');
        $this->getResponse()->setHttpResponseCode(410)->setRawHeader('HTTP/1.1 410 Gone');
        $this->renderScript('pageGone.phtml');
    }
    /** Tags created by opencalais
     * @access public
     * @return void
    */	
    public function opencalaisAction() {
        $this->getFlash()->addMessage('The page requested has permanently gone from our server');
        $this->getResponse()->setHttpResponseCode(410)->setRawHeader('HTTP/1.1 410 Gone');
        $this->renderScript('pageGone.phtml');
    }
    /** Tags created by yahoo
     * @access public
     * @return void
     */	
    public function geotagAction() {
        $this->getFlash()->addMessage('The page requested has permanently gone from our server');
        $this->getResponse()->setHttpResponseCode(410)->setRawHeader('HTTP/1.1 410 Gone');
        $this->renderScript('pageGone.phtml');
    }
}