<?php
/** Controller for displaying information about tags used and generated by opencalais
* 
* @category   Pas
* @package    Pas_Controller
* @subpackage ActionAdmin
* @copyright  Copyright (c) 2011 DEJ Pett dpett @ britishmuseum . org
* @license    GNU General Public License
*/
class Database_TagsController extends Pas_Controller_Action_Admin {
	
	protected $_opencalais;
	/** Setup the contexts by action and the ACL.
	*/	
	public function init() {
	$this->_helper->_acl->allow(null);
	$this->_flashMessenger = $this->_helper->getHelper('FlashMessenger');
	$this->_opencalais = new OpenCalaisModel();
	}
	/** Display index page
	*/	
	public function indexAction() {
	}
	/** Tags created by opencalais
	*/	
	public function opencalaisAction() {
	if($this->_getParam('tag',false)) {
	} else {
		throw new Pas_Exception_Param($this->_missingParameter);
	}
	}
	/** Tags created by yahoo
	*/	
	public function geotagAction() {
	if($this->_getParam('tag',false)) {
	} else {
		throw new Pas_Exception_Param($this->_missingParameter);
	}
	}
}