<?php 
	$this->headTitle('Delete a hoard');
if ($this->hoard) :?>
<h2>Delete a hoard</h2>

<p>Are you sure that you want to delete
'<?php echo $this->escape($this->hoard->term); ?>' 
</p>
<form action="<?php echo $this->url(array('module' => 'database','controller' => 'hoards','action'=>'delete'),null,true); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->hoard->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<p>Deleting the hoard's details will remove this listing from all associated records.</p>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>