<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$cats  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$cats->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('totalItems',$this->hoards->getTotalItemCount()));
$meta->appendChild( $dom->createElement('currentPage',$this->hoards->getCurrentPageNumber()));
$meta->appendChild( $dom->createElement('itemsPerpage', $this->hoards->getItemCountPerPage()));
$meta->appendChild( $dom->createElement('totalPages',ceil($this->hoards->getTotalItemCount()/$this->hoards->getItemCountPerPage())));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$mintsElem = $dom->createElement('hoards');
$cats->appendChild($mintsElem);
// set it's attribute
foreach($this->hoards as $r => $v) {
     $typeElem = $dom->createElement('hoard');
   foreach($v as $k => $a){
      
       $typeElem->appendChild( $dom->createElement($k, htmlspecialchars($a))); 
   }
   $mintsElem->appendChild($typeElem);
}
$dom->appendChild( $cats );

$xmlData  = $dom->saveXML();
echo $xmlData;
