<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 20/01/15
 * Time: 12:57
 */
$this->headTitle('Iron Age and Roman Coin Hoards');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>

<?php echo $this->form;?>

<a class="btn btn-success" href="<?php echo $this->url(array(
    'module' => 'database',
    'controller' => 'search',
    'action' => 'hoards'
),'default',true);?>">Advanced Hoard search</a>

<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {
// focus on the first text input field in the first field on the page
$("input[type='text']:first", document.forms[0]).focus();
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>