<?php 	
$this->headTitle('Hoards listed on the database');
$this->headMeta('A descriptive list of all hoards on our database');
?>
<h2>Hoards listed on the database</h2>
<?php
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity())
{
$user = $auth->getIdentity();
{
$allowedAccess = array('flos','fa','admin');
if(in_array($user->role,$allowedAccess))
{
?>
<p><a href="<?php echo $this->url(array('module' => 'database','controller'=>'hoards','action'=>'add'),null,true);?>">Add a new hoard</a></p>
<?php
}
}
}
?>

<?php if (count($this->hoards)): ?>

<table class="table table-striped" summary="A list of all hoards on the database">
<thead>
<tr>
<th>Hoard details</th>
<?php
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity())
{
$user = $auth->getIdentity();
{
$allowedAccess = array('flos','fa','admin');
if(in_array($user->role,$allowedAccess))
{
?>
<th>Actions</th>
<?php
}
}
}
?>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/database/hoardList.phtml',$this->hoards);?>

</tbody>
</table><?php endif; ?>
<?php echo $this->paginationControl($this->hoards, 'Sliding', 'structure/pagination.phtml'); ?>