<?php
/**
 * Created by PhpStorm.
 * User: danielpett
 * Date: 20/01/15
 * Time: 12:57
 */
$this->headTitle('Iron Age and Roman Coin Hoards');
$this->metaBase()->setDescription($this->title())->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>

<?php echo $this->form;?>

<p><a href="<?php echo $this->url(array('module' => 'database', 'controller' => 'search', 'action' => 'hoards'),'default',true);?>">Advanced Hoard search</a></p>