<!--  Start previous next row -->
<div class="row-fluid" id="prior-next">
    <ul class="pager">

        <!-- The previous find widget -->
        <?php //echo $this->previousFind()->setFindID($this->finds['0']['id']);?>
        <!-- End of previous find widget -->

        <!-- The next find widget -->
        <?php //echo $this->nextFind()->setFindID($this->finds['0']['id']);?>
        <!-- End of next find widget -->

    </ul>
</div>
<!--  End the previous next row -->


<div typeof="crm:E22_Man-Made_Object"
     about="<?php echo $this->serverUrl();?>/database/hoards/record/id/<?php echo $this->hoards['id'];?>"
     class="record">
<!--  Start of main body of record -->

<div class="row-fluid">

    <?php echo $this->partialLoop('partials/hoards/recordheadtitle.phtml',array('hoards' => $this->hoards));?>
    <?php //echo $this->partialLoop('partials/hoards/zoterorecord.phtml',$this->hoards);?>


    <div id="workflowstatus">
        <!-- Empty div that updates with the workflow message -->
    </div>

    <!--  Start of descriptive data -->
    <div class="row-fluid">

        <div class="span8">
            <!-- Header of section displaying unique ID and workflow  -->
            <?php echo $this->partial('partials/hoards/hoardsh2section.phtml',$this->hoards); ?>
            <!-- Notification message if public record -->
            <?php //echo $this->notifyFloPublic($this->finds['0']['institution'],$this->finds['0']['id'],$this->finds['0']['secwfstage']);?>
            <!-- Names the hoard is known as  -->
            <?php echo $this->partial('partials/hoards/knownas.phtml',  $this->multipleKnownAs); ?>
            <!-- Temporal details of the hoard -->
            <?php echo $this->partial('partials/hoards/temporal.phtml', $this->temporals);?>
            <!-- Terminal dates of any coins -->
            <?php echo $this->partial('partials/hoards/coinchronology.phtml', $this->coinChronology);?>
            <!-- Coin data quality rating -->
            <?php echo $this->partial('partials/hoards/coindataquality.phtml', $this->coinDataQuality);?>
            <!-- The description of the object -->
            <?php echo $this->partial('partials/hoards/hoardsdescriptive.phtml',$this->hoardDescription);?>
            <!-- Treasure find info -->
            <?php echo $this->partial('partials/hoards/treasurefinddetails.phtml', $this->treasureDetails);?>
            <!-- Linked coins -->
            <?php echo $this->partial('partials/hoards/linkedcoins.phtml', array('linkedCoins' => $this->linkedCoins));?>
            <!-- Linked arefacts -->
            <?php echo $this->partial('partials/hoards/linkedartefacts.phtml', array('linkedArtefacts' => $this->linkedArtefacts));?>
            <!-- Linked containers -->
            <?php echo $this->partial('partials/hoards/linkedcontainers.phtml', array('linkedContainers' => $this->linkedContainers));?>
            <!-- Dimensional data -->
            <?php
            if (count($this->findsdata) > 0) {
                //echo $this->partial('partials/database/hoards/dimensions.phtml', $this->findsdata['0']);
            }
            ?>
            <!-- Date found -->
            <?php echo $this->partial('partials/hoards/datefound.phtml',$this->discoverySummary);?>
            <!-- Rally data -->
            <?php
            if (count($this->rallyfind)){
                //echo $this->partial('partials/database/hoards/rallyfind.phtml', $this->rallyfind['0']);
            }
            ?>
            <!-- Personal data -->
            <?php if (count($this->recordersIdentifiers) > 0): ?>
                <h4>Personal details</h4>
                <?php echo $this->partial('partials/hoards/finders.phtml', array('finders' => $this->finders)); ?>
                <?php echo $this->partial('partials/hoards/personal.phtml', $this->recordersIdentifiers);?>
            <?php endif;?>
            <!-- Other references -->
            <?php
            if ($this->referenceNumbers){
                echo $this->partial('partials/hoards/otherrefs.phtml', $this->referenceNumbers);
            }
            ?>
            <!-- Finds materials -->
            <?php
            if (count($this->findsmaterial)){
                echo $this->partial('partials/materials.phtml', $this->findsmaterial);
            }
            ?>



        </div>
        <!-- Start of image pane -->
        <div class="span3 well" id="imagepane">

            <?php
            if (count($this->thumbs) > 0){
                echo $this->partialLoop('partials/database/thumbs.phtml',
                    array_slice($this->thumbs,0,1));
                if(sizeof($this->thumbs) > 1):

                    ?>
                    <!-- Start small thumbnails -->
                    <ul class="thumbnails">
                        <?php
                        foreach(array_slice($this->thumbs,1) as $thumb){
                            echo $this->partialLoop('partials/database/smallThumbnails.phtml', $thumb);
                        }
                        ?>
                    </ul>
                    <!-- End small thumbnails -->
                <?php endif;?>

                <h4>Image use policy</h4>
                <p>Our images can be used under a
                    <a href="https://creativecommons.org/licenses/by-sa/2.0/" >CC
                        BY-SA licence</a> (unless stated otherwise).</p>
            <?php
            } else {?>
                <p>There are currently no images available.<br />
                    If you own this object please send us a picture of it.</p>
            <?php
            }
            ?>
            <?php
            echo $this->imageLink()
                ->setFindID($this->finds['0']['id'])
                ->setSecuID($this->finds['0']['secuid'])
                ->setCreatedBy($this->finds['0']['createdBy'])
                ->setInstitution($this->finds['0']['institution']);
            ?>
        </div>
        <!-- End of the image pane -->

    </div>
    <!--  End of descriptive data -->




    <!--  Start of the references section -->
    <div class="row-fluid" id="references">
        <h4>References cited</h4>
        <?php
        if (count($this->refs) > 0) : ?>
            <p>
                <?php
                echo $this->addRefLink()
                    ->setFindID($this->hoards['0']['id'])
                    ->setSecuID($this->hoards['0']['uniqueID'])
                    ->setCreatedBy($this->hoards['0']['createdBy'])
                    ->setInstitution($this->hoards['0']['institution']);
                ?>
            </p>

            <ul>
                <?php echo $this->partialLoop('partials/database/harvardbook.phtml',
                    $this->refs);?>
            </ul>
        <?php else:?>
            <p class="norefs">
                No references cited so far.
            </p>

            <?php
            echo $this->addRefLink()
                ->setFindID($this->hoards['0']['id'])
                ->setSecuID($this->hoards['0']['uniqueID'])
                ->setCreatedBy($this->hoards['0']['createdBy'])
                ->setInstitution($this->hoards['0']['institution']);
            ?>
        <?php endif;?>
    </div>
    <!--  End of references section -->
</div>

</div>
<!--  End of main body of record -->





</div>
</div>


<!-- Start of the Audit section -->
<div class="row-fluid" id="audit">
    <?php echo $this->partial('partials/database/recordaudit.phtml',$this->finds['0']); ?>
    <?php echo $this->auditLogs()->setId($this->finds['0']['id']); ?>
</div>
<!-- end of audit section -->