<?php
echo $this->dataEditDeleteCheck()->setInstitution($this->hoards['institution'])
    ->setCreatedBy($this->hoards['createdBy'])
    ->setFindID($this->hoards['id'])
    ->setWorkflow($this->finds[0]['workflow'])
    ->sesame();
?>

<div typeof="crm:E22_Man-Made_Object"
     about="<?php echo $this->serverUrl(); ?>/database/hoards/record/id/<?php echo $this->hoards['id']; ?>"
     class="record">
    <!--  Start of main body of record -->

    <div class="row-fluid">

        <!-- The descriptive bit for the record, generates meta data -->
        <?php echo $this->partialLoop('partials/hoards/recordHeadTitle.phtml', array('hoards' => $this->hoards)); ?>

        <!-- The zotero data -->
        <?php echo $this->partialLoop('partials/hoards/zoteroRecord.phtml', array('hoards' => $this->hoards)); ?>

        <!-- Empty div that updates with the workflow message -->
        <div id="workflowstatus">

        </div>

        <!--  Start of descriptive data -->
        <div class="row-fluid">

            <div class="span8">
                <!-- Header of section displaying unique ID and workflow  -->
                <?php echo $this->partial('partials/hoards/hoardsh2section.phtml', $this->hoards); ?>
                <!-- Notification message if public record -->
                <?php //echo $this->notifyFloPublic($this->finds['0']['institution'],$this->finds['0']['id'],$this->finds['0']['secwfstage']);?>
                <!-- Names the hoard is known as  -->
                <?php echo $this->partial('partials/hoards/knownAs.phtml', $this->multipleKnownAs); ?>
                <!-- Hoard quantities -->
                <?php echo $this->partial('partials/hoards/quantities.phtml', $this->quantities); ?>
                <!-- Temporal details of the hoard -->
                <?php echo $this->partial('partials/hoards/temporal.phtml', $this->temporals); ?>
                <!-- Terminal dates of any coins -->
                <?php echo $this->partial('partials/hoards/coinChronology.phtml', $this->coinChronology); ?>


            </div>
            <!-- Start of image pane -->
            <div class="span3 well" id="imagepane">

                <?php if (!is_null($this->thumbs)) : ?>
                    <?php echo $this->partialLoop('partials/database/images/thumbs.phtml', array_slice($this->thumbs, 0, 1)); ?>
                    <?php if (sizeof($this->thumbs) > 1): ?>
                        <!-- Start small thumbnails -->
                        <ul class="thumbnails">
                            <?php echo $this->partialLoop('partials/database/images/smallThumbnails.phtml', array_slice($this->thumbs, 1)); ?>
                        </ul>
                        <!-- End small thumbnails -->
                    <?php endif; ?>

                    <h4 class="lead">
                        Image use policy
                    </h4>
                    <p>
                        Our images can be used under a <a href="https://creativecommons.org/licenses/by/3.0/">CC BY
                            licence</a> (unless stated otherwise).
                    </p>
                <?php else: ?>
                    <p>There are currently no images available.<br/>
                        If you own this object please send us a picture of it.</p>
                <?php endif; ?>
                <?php
                echo $this->imageLink()
                    ->setFindID($this->finds['0']['id'])
                    ->setSecuID($this->finds['0']['secuid'])
                    ->setCreatedBy($this->finds['0']['createdBy'])
                    ->setInstitution($this->finds['0']['institution']);
                ?>
            </div>
            <!-- End of the image pane -->


        </div>

        <div class="row-fluid">

            <!-- Summary details of the coins in the hoard -->
            <?php echo $this->partial('partials/hoards/coinsummary.phtml', array('coinSummary' => $this->coinSummary, 'hoards' => $this->hoards)); ?>

            <!-- Coin data quality rating -->
            <?php echo $this->partial('partials/hoards/coindataquality.phtml', $this->coinDataQuality); ?>

            <!-- The description of the object -->
            <?php echo $this->partial('partials/hoards/hoardsDescriptive.phtml', $this->hoardDescription); ?>

            <!-- Subsequent action after recording hoard -->
            <?php echo $this->partial('partials/hoards/subsequentAction.phtml', $this->subsequentActions); ?>

            <!-- Treasure find info -->
            <?php echo $this->partial('partials/hoards/treasureFindDetails.phtml', $this->treasureDetails); ?>

            <!-- Finds materials -->
            <?php if (!empty($this->hoardMaterials)): ?>
                <?php echo $this->hoardMaterials()->setMaterials($this->hoardMaterials); ?>
            <?php endif; ?>

            <!-- Linked coins -->
            <?php echo $this->partial('partials/hoards/linkedCoins.phtml', array('linkedCoins' => $this->linkedCoins, 'hoards' => $this->hoards)); ?>

            <!-- Linked aretfacts -->
            <?php echo $this->partial('partials/hoards/linkedArtefacts.phtml', array(
                'linkedArtefacts' => $this->linkedArtefacts,
                'hoards' => $this->hoards
            )); ?>
            <!-- Linked containers -->
            <?php echo $this->partial('partials/hoards/linkedContainers.phtml', array(
                'linkedContainers' => $this->linkedContainers,
                'hoards' => $this->hoards
            )); ?>
            <!-- Render a button for linking coins, artefacts and containers to the hoard -->
            <?php echo $this->linkCoinArtefactContainer()->setHoardID($this->hoards['uniqueID'])->setID($this->hoards['id']); ?>
            <!-- Dimensional data -->
            <!-- Date found -->
            <?php echo $this->partial('partials/hoards/dateFound.phtml', $this->discoverySummary); ?>
            <!-- Rally data -->
            <?php if (!empty($this->rallyfind)): ?>
                <?php echo $this->partial('partials/database/rallies/rallyFind.phtml', $this->rallyfind['0']); ?>
            <?php endif; ?>

            <!-- Personal data -->
            <?php if (!empty($this->recordersIdentifiers)): ?>
                <?php echo $this->partial('partials/hoards/finders.phtml', array('finders' => $this->finders)); ?>
                <?php echo $this->partial('partials/hoards/personal.phtml', $this->recordersIdentifiers); ?>
            <?php endif; ?>

            <!-- Other references -->
            <?php echo $this->partial('partials/hoards/otherReferences.phtml', $this->referenceNumbers); ?>


        </div>
        <!--  End of descriptive data -->

        <!-- Start of the spatial data -->
        <div class="row-fluid">
            <!-- Render the map and findspot data -->

            <?php if (!empty($this->findspots)) : ?>

                <!-- Check for findspot data and if exists render -->

                <?php echo $this->findspot()->setData($this->findspots[0])->setCreatedBy($this->findspots[0]['createdBy']); ?>

            <?php else: ?>
                <!-- Render a link for adding find spot -->
                <div id="findspotdata">
                    <h4 class="lead">
                        Spatial data
                    </h4>

                    <p>
                        No spatial data available.
                    </p>
                    <!-- Work out whether user can add data -->
                    <?php
                    echo $this->findSpotLink()
                        ->setFindID($this->hoards['id'])
                        ->setSecuID($this->hoards['uniqueID'])
                        ->setCreatedBy($this->hoards['createdBy'])
                        ->setInstitution($this->hoards['institution']);
                    ?>
                    <!-- End of user test -->
                </div>
            <?php endif; ?>
            <!-- Render the map  and find spot ends -->
        </div>
        <!--  End of spatial data -->

            <!-- Start of the archaeological context data -->
            <div class="row-fluid">

                <?php if (!empty($this->archaeologicalContext)) : ?>
                    <!-- Check for archaeological context data and if there is render it -->
                    <?php echo $this->partial('partials/hoards/archaeology.phtml', $this->archaeologicalContext); ?>
                <?php else: ?>
                    <!-- Render a link for adding archaeological context -->
                    <div id="archaeologicalcontextdata">
                        <h4 class="lead">Archaeological context</h4>

                        <p>
                            No archaeological context available.
                        </p>
                        <?php echo $this->addArchaeology()->setHoardID($this->hoards['uniqueID'])->setID($this->hoards['id']); ?>
                    </div>
                <?php endif; ?>

            </div>
            <!--  End of archaeological context data -->

        <!--  Start of the references section -->
        <div class="row-fluid" id="references">
            <h4 class="lead">References cited</h4>
            <?php if (!empty($this->refs)) : ?>
                <p>
                    <?php
                    echo $this->addRefLink()->setFindID($this->hoards['id'])
                        ->setSecuID($this->hoards['uniqueID'])
                        ->setCreatedBy($this->hoards['createdBy'])
                        ->setInstitution($this->hoards['institution']);
                    ?>
                </p>

                <ul>
                    <?php echo $this->harvard()->setRefs($this->refs); ?>
                </ul>
            <?php else: ?>
                <p class="norefs">
                    No references cited so far.
                </p>

                <?php
                echo $this->addRefLink()
                    ->setFindID($this->hoards['id'])
                    ->setSecuID($this->hoards['uniqueID'])
                    ->setCreatedBy($this->hoards['createdBy'])
                    ->setInstitution($this->hoards['institution']);
                ?>
            <?php endif; ?>
        </div>
        <!--  End of references section -->
    </div>

</div>
<!--  End of main body of record -->

<!--  Start of commentary section -->
<div class="row-fluid" id="commentary">

    <p>
        <a class="btn btn-small btn-warning" href="<?php echo $this->url(array(
            'module' => 'database',
            'controller' => 'hoards',
            'action' => 'error',
            'id' => $this->hoards['id']
        )); ?>"
           title="Send message to the allotted National Finds Adviser"><i class="icon-warning-sign"></i> Report a
            mistake</a>
    </p>
</div>


</div>
</div>


<!-- Start of the Audit section -->
<?php if (!empty($this->hoards)): ?>
    <div class="row-fluid" id="audit">
        <?php echo $this->partial('partials/database/auditing/recordAudit.phtml', $this->hoards); ?>
        <?php echo $this->auditLogs()->setId($this->hoards['id']); ?>
    </div>
<?php endif; ?>
<!-- end of audit section -->