<?php
	$this->headTitle('Delete link to coin, artefact or container');
    if ($this->find) :
?>

        <h2 class="lead">Delete link to <?php echo $this->escape($this->find->old_findID); ?></h2>
        <p>Are you sure that you want to delete the link to this coin, artefact or container? It cannot be undone.</p>

        <form action="<?php echo $this->url(array('module' => 'database','controller' => 'hoards',
            'action'=>'unlink','hoardID' => $this->hoardID),null,true
        ); ?>"
              method="post">
<div>
    <input type="hidden" name="findID" value="<?php echo $this->find->id; ?>" />
    <input type="hidden" name="findSecuid" value="<?php echo $this->find->secuid; ?>" />
    <input type="hidden" name="hoardID" value="<?php echo $this->hoardID; ?>" />
    <input type="hidden" name="hoardSecuid" value="<?php echo $this->hoardSecuid; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>

        </form>

<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>
