<?php
/**
 * Open archives initiative interface at the PAS website home page 
 *
 * This view pulls content from a db call to explain methods available and 
 * verbs to use to pull data from the PAS database and return OAI XML.
 * @category	Pas
 * @package 	Zend_View
 * @author 		Daniel Pett
 * @copyright 	DEJ PETT 2011
 * @version		1
 * @since		September 23 2011
 * @license 	http://www.gnu.org/licenses/gpl-3.0.txt
 */
echo $this->partial('partials/content/article.phtml',$this->content['0']);

