<?php
$this->headTitle('Delete a vacancy');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if (!is_null($this->vac)) : ?>
    <h2 class="lead">Delete volunteer details for: <?php echo $this->escape($this->opp->title); ?></h2>
    <p>Are you sure that you want to delete
        '<?php echo $this->escape($this->vac->title); ?> '
    </p>
    <form action="<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'volunteers',
        'action' => 'delete'), null, true); ?>"
          method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->opp->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?><h2 class="lead">An error has occured</h2>
    <p>Cannot find the requested volunteering role's details.</p>
<?php endif; ?>