<?php
$this->headTitle('Scheme research publications');
$this->metaBase()
    ->setDescription('A list of our research publications')
    ->setImage('http://farm6.staticflickr.com/5296/5555344805_9e2f5d0c6f.jpg')
    ->setImageWidth(500)
    ->setImageHeight(375)
    ->setSubject('Archaeological research')
    ->setKeywords('research,reports,publications,pdfs')
    ->generate();
?>

<?php
    // Return a sorted list of files in a given directory
    // Note how .htaccess is ignored - this appears in some of the pdf folders
    function RetrieveFiles($path) {
        foreach (new DirectoryIterator($path) as $fileInfo):
            $filename = $fileInfo->getFilename();
            if ($fileInfo->isDot() or $filename == '.htaccess') continue;
                list($root, $ext) = explode('.', $filename);
                if (!$root) {
                    $root = $filename;
                }
                $filesFound[] = array(
                    "filename" => $filename,
                    "root" => $root
                );
        endforeach;
        asort($filesFound);
        return $filesFound;
    }
?>

<h2 class="lead">
    <?php echo $this->title(); ?>
</h2>

<p>
    The Portable Antiquities Scheme produces period round-ups for the majority
    of the major research journals.
</p>

</ul>

<?php $allFiles = RetrieveFiles(ROOT_PATH . '/public_html/documents/britannia/');
    if (count($allFiles) > 0) { ?>
        <h3 class="lead">
            Britannia
        </h3>
        <ul>
        <?php foreach( $allFiles as $file ): ?>
            <li>
                <a href="/documents/britannia/<?php echo $file["filename"] ?>"><?php echo $file["root"]; ?></a>
            </li>
        <?php endforeach; ?>
        </ul>
<?php } ?>

<?php $allFiles = RetrieveFiles(ROOT_PATH . '/public_html/documents/medieval/');
    if (count($allFiles) > 0) { ?>
        <h3 class="lead">
            Medieval Archaeology
        </h3>
        <ul>
        <?php foreach( $allFiles as $file ): ?>
            <li>
                <a href="/documents/medieval/<?php echo $file["filename"] ?>"><?php echo $file["root"]; ?></a>
            </li>
        <?php endforeach; ?>
        </ul>
<?php } ?>

<?php $allFiles = RetrieveFiles(ROOT_PATH . '/public_html/documents/postmedieval/'); 
    if (count($allFiles) > 0) { ?>
        <h3 class="lead">
            Post Medieval Archaeology
        </h3>
        <ul>
        <?php foreach( $allFiles as $file ): ?>
            <li>
                <a href="/documents/postmedieval/<?php echo $file["filename"] ?>"><?php echo $file["root"]; ?></a>
            </li>
        <?php endforeach; ?>
        </ul>
<?php } ?>

