<?php 
$this->headTitle("Delete a news story");
if ($this->new) :?>
<h2>Delete content</h2>
<p>Are you sure that you want to delete
'<?php echo $this->escape($this->new->title); ?>'
</p>
<form action="<?php echo $this->url(array(
'module' => 'admin', 'controller' => 'news', 'action'=>'delete')); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->new->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find the item requested.</p>
<?php endif;?>
