<?php 
$this->headTitle('List of Scheme alumni');
$this->metaBase()
        ->setDescription('A list of all people who used to work for the Portable Antiquities Scheme')
        ->setSubject('alumni')
        ->setKeywords('alumni,scheme,head office,archaeology')
        ->generate();

?>
<h2>
    <?php echo $this->title();?>
</h2>

<div id="contacts">
    <ul>
        <?php echo $this->partialLoop('partials/contacts/alumniList.phtml',$this->alumni);?>
    </ul>
</div>