<?php
$this->headTitle("Reverse types of the Fourth Century AD");
$this->metaBase()->setDescription('A list of common and uncommon reverse types for fourth century Roman
    coins issued throughout the Empire')
    ->setKeywords('roman,coins,numismatics,reverses,empire')
    ->setSubject('Roman Numismatics')
    ->generate();
?>
<h2 class="lead">Most common reverse types</h2>
<table class="table table-striped" summary="The most common reverse types">
    <caption>The most common reverse types</caption>
    <thead>
    <tr>
        <th>Type</th>
        <th>Description</th>
        <th>Date issued</th>
        <th>Reece period</th>
    </tr>
    </thead>
    <tbody>
    <?php echo $this->partialLoop('partials/numismatics/reverseTypeList2.phtml', $this->reverses); ?>
    </tbody>
</table>
<h2 class="lead">Less frequently found reverses</h2>
<table class="table table-striped" summary="The most common reverse types">
    <caption>The most common reverse types</caption>
    <thead>
    <tr>
        <th>Type</th>
        <th>Description</th>
        <th>Date issued</th>
        <th>Reece period</th>
    </tr>
    </thead>
    <tbody>
    <?php echo $this->partialLoop('partials/numismatics/reverseTypeList2.phtml', $this->uncommonreverses); ?>
    </tbody>
</table>
