<?php 
$site = $this->serverUrl();
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();	
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$contextSwitch = Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch');	
$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$contexts = $contextSwitch->getContexts();

$dom 	  = new DomDocument("1.0", "UTF-8");
$reverses  = $dom->createElement('response');
$meta = $dom->createElement('meta');
$reverses->appendChild($meta);
$meta->appendChild( $dom->createElement('generated', date(DATE_W3C,time())));
$meta->appendChild( $dom->createElement('count', count($this->reverses)));
$formats = $dom->createElement('formats');
$meta->appendChild($formats);	
foreach ($contexts as $k => $v){
$formats->appendChild( $dom->createElement($k, $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param,'format' => $k),NULL,true)  ));
}
$formats->appendChild( $dom->createElement('html', $site . $this->url(array('module' => $module,
'controller' => $controller,'action' => $action,'id' => $param),NULL,true)  ));
//1st item
$reversesElem = $dom->createElement('commonReverseTypes');
$reverses->appendChild($reversesElem);
// set it's attribute
foreach($this->reverses as $r){
$r = (object)$r;
$typeElem = $dom->createElement('reverseType');
$typeElem->appendChild( $dom->createElement('id', $r->id));
$typeElem->appendChild( $dom->createElement('type', $r->type));
$typeElem->appendChild( $dom->createElement('translation', $r->translation));
$typeElem->appendChild( $dom->createElement('description', $r->description));
$typeElem->appendChild( $dom->createElement('dates', $r->gendate));
$typeElem->appendChild( $dom->createElement('reecePeriod', $r->i));
$typeElem->appendChild( $dom->createElement('reecePeriodName', $r->period_name));
$typeElem->appendChild( $dom->createElement('created', $r->created));
$typeElem->appendChild( $dom->createElement('updated', $r->updated));

$reversesElem->appendChild( $typeElem );
}

$reverses2Elem = $dom->createElement('uncommonReverseTypes');
$reverses->appendChild($reverses2Elem);
// set it's attribute
foreach($this->uncommonreverses as $r){
$r = (object)$r;
$type2Elem = $dom->createElement('reverseType');
$type2Elem->appendChild( $dom->createElement('id', $r->id));
$type2Elem->appendChild( $dom->createElement('type', $r->type));
$type2Elem->appendChild( $dom->createElement('translation', $r->translation));
$type2Elem->appendChild( $dom->createElement('description', $r->description));
$type2Elem->appendChild( $dom->createElement('dates', $r->gendate));
$type2Elem->appendChild( $dom->createElement('reecePeriod', $r->i));
$type2Elem->appendChild( $dom->createElement('reecePeriodName', $r->period_name));
$type2Elem->appendChild( $dom->createElement('created', $r->created));
$type2Elem->appendChild( $dom->createElement('updated', $r->updated));

$reverses2Elem->appendChild( $type2Elem );
}

$dom->appendChild( $reverses );

$xmlData  = $dom->saveXML();
echo $xmlData;
