<?php
$this->headTitle('Minutes of the Treasure Valuation Committee');
$this->metaBase()
    ->setDescription('The minutes of the Treasure valuation committee are published retrospectively here')
    ->setSubject('Minutes')
    ->setKeywords('treasure,valuation,committee,minutes,recommendations')
    ->generate();
?>
<h2 class="lead">
    <?php echo $this->title(); ?>
</h2>

<p>
    The minutes of the meetings of the Treasure Valuation Committee are made public at regular intervals, 
    once valuations have been determined for all of the cases discussed therein. Personal information and 
    other sensitive information is appropriately redacted. Dates of past meetings with available minutes are 
    listed below. Minutes of meetings prior to 2007 are not available in electronic form. 
</p>

<ul>
    <?php
    $minutes = array();
    foreach (new DirectoryIterator(ROOT_PATH . '/public_html/documents/treasureMinutes/') as $fileInfo) {
        if ($fileInfo->isDot()) {
            continue;
        }
        list($root, $ext) = explode('.', $fileInfo->getFilename());
        $minutes[$fileInfo->getFilename()] = $root;
    }
    $minutes = array_flip($minutes);
    ksort($minutes);
    ?>

    <?php foreach ($minutes as $k => $v): ?>

    <?php $provisionalMeeting = "";
    if (strlen($k) > 10) {
        $provisionalMeeting = substr($k, 10);
        $k = substr($k, 1, 10);
    }
    ?>
        <li>
            <a href="<?php echo $this->serverUrl(); ?>/documents/treasureMinutes/<?php
            echo $v;
            ?>"><?php echo $this->niceShortDate()->setDate($k) . $provisionalMeeting; ?></a></li>
    <?php endforeach; ?>
</ul>
