<?php
$this->headTitle('Minutes of the Treasure Valuation Committee');
$this->metaBase()
    ->setDescription('The minutes of the Treasure valuation committee are published retrospectively here')
    ->setSubject('Minutes')
    ->setKeywords('treasure,valuation,committee,minutes,recommendations')
    ->generate();
?>
<h2 class="lead">
    <?= $this->title() ?>
</h2>

<p>
    The minutes of the meetings of the Treasure Valuation Committee are made public at regular intervals, 
    once valuations have been determined for all of the cases discussed therein. Personal information and 
    other sensitive information is appropriately redacted. Dates of past meetings with available minutes are 
    listed below. Minutes of meetings prior to 2007 are not available in electronic form. 
</p>

<ul>
    <?php
    $minutes = array();
    foreach (new DirectoryIterator(ROOT_PATH . '/public_html/documents/treasureMinutes/') as $fileInfo) {
        // Skip any special folders - we won't be showing them
        if ($fileInfo->isDot()) {
            continue;
        }
        $numberOfPeriods = substr_count($fileInfo->getFilename(), ".");
        // Bad (unexpected) format - skip
        if (0 === $numberOfPeriods) {
            continue ;
        }
        // Expected file. Split on period.
        elseif (1 === $numberOfPeriods) {
            list($root, $ext) = explode('.', $fileInfo->getFilename());
            $minutes[$root] = $fileInfo->getFilename();
        }
        // More than one period - take last one
        else {
            $components = explode('.', $fileInfo->getFilename());
            $ext = array_pop($components);
            $joinedRoot = join('.', $components); 
            $minutes[$joinedRoot] = $fileInfo->getFilename();
        }
    }
    krsort($minutes);

    foreach ($minutes as $pathWithNoExtension => $fullPath):
        $provisionalMeeting = "";
        $datePortionOfPath = substr($pathWithNoExtension, 1, 10);

        // If filename is more than just 2018-10-12, then:
        if (strlen($pathWithNoExtension) > 10) {
            $provisionalMeeting = substr($pathWithNoExtension, 10);
        }
    ?>
        <li>
            <a href="<?= $this->serverUrl() ?>/documents/treasureMinutes/<?= $fullPath ?>"><?= $this->niceShortDate()->setDate($datePortionOfPath) . $provisionalMeeting ?></a>
        </li>
    <?php endforeach; ?>
</ul>
