<?php
$this->headTitle('Delete coin summary record');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if ($this->summary) : ?>
    <h2 class="lead">
        Delete <?php echo $this->summary->hoardID; ?>
    </h2>

    <?php $url = array(
        'module' => 'database',
        'controller' => 'hoards',
        'action' => 'record',
        'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('hoardID'));
    ?>
    <a href="<?php echo $this->url($url, 'default', true); ?>" class="btn btn-small btn-success"
       title="Return to record">Return to record</a>

    <p>
        Are you sure that you want to delete <?php echo $this->summary->hoardID; ?>
    </p>
    <?php $url = array('module' => 'database', 'controller' => 'summary', 'action' => 'delete'); ?>
    <form action="<?php echo $this->url($url, 'default', true); ?>"
          method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->summary->id; ?>"/>
            <input type="hidden" name="hoardID" value="<?php echo $this->hoardID; ?>"/>

            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>
<?php else: ?>
    <p>
        Cannot find the item requested.
    </p>
<?php endif; ?>