<?php
$this->headTitle('Edit coin summary details');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/hoardPeriodLinkedSelect.js', $type = 'text/javascript');
$this->metaBase()
    ->setDescription()
    ->setKeywords()
    ->generate();
?>
    <h2 class="lead">
        <?php echo $this->title(); ?>
    </h2>
<?php $url = array(
    'module' => 'database',
    'controller' => 'hoards',
    'action' => 'record',
    'id' => Zend_Controller_Front::getInstance()->getRequest()->getParam('hoardID'));
?>
    <a href="<?php echo $this->url($url, 'default', true); ?>" class="btn btn-small btn-default"
       title="Return to record">Return to record</a>
<?php echo $this->form; ?>

<?php $this->jQuery()->javascriptCaptureStart(); ?>
    $(document).ready(function() {

    $('#broadperiod').linkedSelect('/ajax/lastruler','#ruler_id',{firstOption: 'Please select a ruler'});
    $('#broadperiod').linkedSelect('/ajax/getdenominations','#denomination',{firstOption: 'Please select a denomination'});
    $('#broadperiod').linkedSelect('/ajax/getmints','#mint_id',{firstOption: 'Please select a ruler'});

    var rulerPeriods = ['IRON AGE', 'EARLY MEDIEVAL', 'MEDIEVAL', 'POST MEDIEVAL', 'BYZANTINE',
    'GREEK AND ROMAN PROVINCIAL'];

    var IA = ['IRON AGE'];

    $('#geographyID').attr('disabled','disabled');
    $('#denomination').attr('disabled','disabled');
    $('#ruler_id').attr('disabled','disabled');
    $('#mint_id').attr('disabled','disabled');

    $('select[name="broadperiod"]').on('change',function(){
    $('#ruler_id').select2('val', 'All');
    $('#mint_id').select2('val', 'All');
    $('#denomination').select2('val', 'All');
    $('#geographyID').select2('val', 'All');

    var period = $(this).val();
    if(jQuery.inArray(period, rulerPeriods) !== -1) {
    console.log('In ruler array');

    }
    if (jQuery.inArray(period, IA) !== -1) {
    $('#ruler_id').linkedSelect('/ajax/iageography','#geographyID',{firstOption: 'Please select a ruler'});
    console.log('In IA array');
    }
    });
    });

<?php $this->jQuery()->javascriptCaptureEnd(); ?>