<?php
$this->headTitle('Edit account details');
$this->metaBase()->setDescription($this->title())->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'users'), 'default', true); ?>"
       class="btn btn-small btn-success">Return to users list</a>
<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-typeahead.js', $type = 'text/javascript');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/JQuery/typeaheads/userAccount.js', $type = 'text/javascript');
?>
<?php $this->jQuery()->javascriptCaptureStart(); ?>
$(document).ready(function() {
$('form').areYouSure();
$("form").submit(function() {
$(":submit", this).attr("disabled", "disabled");
});
});
<?php $this->jQuery()->javascriptCaptureEnd(); ?>
