<?php
$this->headTitle('Approve an account');
$this->metaBase()->setDescription('Approve an account for higher level access')->generate();
?>

    <h2 class="lead"><?php echo $this->title(); ?></h2>
<?php echo $this->form; ?>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/bootstrap-datepicker.js', $type = 'text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/autocomplete.css');
?>