<?php 
$this->headTitle('Archived scheme events');
$this->headMeta('A list of all our events that have expired','description');?>
<h2>Archived Scheme events</h2>

<?php if(count($this->events)):?><p>View events on calendar:</p>
<ul id="yearrange">
<?php echo $this->partialLoop('partials/events/archiveYears.phtml',$this->years);?>
</ul><table class="table table-striped" summary="List of all archived scheme events">
<caption>List of past Scheme events</caption>
<thead>
<tr>
<th>Date of event</th>
<th>Event title</th>
<th>Attendance</th>
<th>Organised by</th>
</tr>
</thead>
<tbody>
<?php echo $this->partialLoop('partials/events/archived.phtml',$this->events);?>
</tbody>
</table>
<?php else:?>
<p>There are no archived events available to you.</p>
<?php endif;?>
<?php echo  $this->paginationControl($this->events, 'Sliding', 'structure/pagination.phtml'); ?>
