<?php 
$this->headTitle('Event archives for ' . $this->date);
$this->headMeta('This page presents a calendar view of archived events for '
        . $this->date,'description')
->headMeta('events,portable antiquities,scheme,archaeology,outreach,' . $this->date,'dc.keywords')
->headMeta('CC NC-BY_SA','dc.rights')
->headMeta($this->curUrl(),'dc.identifier')
->headMeta('Daniel Pett','dc.creator')
->headMeta('The Portable Antiquities Scheme','dc.publisher');
?>

<h2>Archived events by year</h2>
<ul id="yearrange">
<?php echo $this->partialLoop('partials/events/archiveYears.phtml',$this->years);?>
</ul>