<?php echo "<br> This is in test <br>";
$this->headTitle('Location map showing Scheme staff');
$this->metaBase()
    ->setDescription('A map of the locations of our staff who work for the Portable Antiquities Scheme')
    ->setSubject('Contacts map')
    ->setKeywords('map,google,contacts,scheme,head office,archaeology')
    ->generate();
$this->googleDynamicMap();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<div id="map">
    <div id="loading"></div>
</div>

<?php $this->inlineScript()->captureStart() ?>
$(document).ready(function() {
var center = new google.maps.LatLng(54.70235509327093, -3.2080078125);
var myOptions = {
zoom: 6,
center: center,
mapTypeId: google.maps.MapTypeId.SATELLITE
}

var map = new google.maps.Map(document.getElementById("map"), myOptions);

var markers = new Array();

var infowindow = new google.maps.InfoWindow();
jQuery.get("<?php echo $this->serverUrl() . $this->url(array(
        'module' => 'default',
        'controller' => 'ajax',
        'action' => 'staffdata'), 'default', true);?>", {}, function(data) {

jQuery(data).find("marker").each(function() {
var markerXML = jQuery(this);
var latlng = new google.maps.LatLng(
parseFloat(markerXML.attr("lat")),
parseFloat(markerXML.attr("lng"))
);
var title = markerXML.attr("title");
// console.log(title);
//alert(title);

var marker = new google.maps.Marker({
position: latlng,
map: map,
title: title,
icon: "<?php echo $this->serverUrl() . $this->baseUrl(); ?>/assets/mapIcons/museumArcheological.png" });

// now that the marker is placed, assign event listener on the marker
// and create/assign infowindow to the event trigger.
markerInfoWindow(marker, markerXML.attr("content"));
markers.push(marker);
});
});

function markerInfoWindow(marker, information){
google.maps.event.addListener(marker, 'click',
function() {
infowindow.close();
infowindow.setContent(information);
infowindow.setPosition(marker.getPosition());
infowindow.open(map, marker);
});
}
var center;

function calculateCenter() {
center = map.getCenter();
}
google.maps.event.addDomListener(map, 'idle', function() {
calculateCenter();
});
google.maps.event.addDomListener(window, 'resize', function() {
map.setCenter(center);
});

});
<?php $this->inlineScript()->captureEnd() ?>
