<?php
$vc = new Pas_VCard();
$data = array();
foreach ($this->persons as $person) {
    $data['display_name'] = $person['firstname'] . ' ' . $person['lastname'];
    $data['first_name'] = $person['firstname'];
    $data['last_name'] = $person['lastname'];
    $data['company'] = "The Portable Antiquities Scheme";
    $data['title'] = $person['staffroles'];
    $data['work_address'] = $person['address_1'] . ' ' . $person['address_2'];
    $data['work_city'] = $person['town'];
    $data['work_state'] = $person['county'];
    $data['work_postal_code'] = $person['postcode'];
    $data['office_tel'] = $person['telephone'];
    $data['fax_tel'] = $person['fax'];
    $data['email1'] = $person['email_one'];
    $data['url'] = $this->serverUrl();
    if (!is_null($person['image'])) {
        $data['photo'] = $this->serverUrl() . '/assets/staffphotos/thumbnails/' . rawurlencode($person['image']);
    }
    $data['timezone'] = "00:00";
}
$vc->setData($data);
$vc->setClass('PUBLIC');;
echo $vc->createCard();