<?php
$this->headTitle('Mints active under the Roman Empire');
$this->metaBase()->setDescription('A list of all active mints under the Roman Empire')
    ->setSubject('Roman Numismatics')
    ->setKeywords('roman,mints,issuing,empire,republic')
    ->generate();
?>

<h2 class="lead"><?php echo $this->title(); ?></h2>
<table class="table table-striped" summary="List of locations">
    <caption>List of mint locations</caption>
    <thead>
    <tr>
        <th>Mint name</th>
        <th>Geo location</th>
    </tr>
    </thead>
    <tbody>
    <?php echo $this->partialLoop('partials/numismatics/roman/mintsTableList.phtml', $this->rommints); ?>
    </tbody>
</table>