<?php 
echo $this->partialLoop('partials/numismatics/shared/mintDetail.phtml',$this->rommints);
?>
<h3 class="lead">Issuers</h3>
<p>This mint was active under the following issuers:</p>
<ul>
<?php echo $this->partialLoop('partials/numismatics/roman/issuersRomanMints.phtml', $this->actives);?>
</ul>
<?php echo $this->latestRecords()->setQuery('mint:'. Zend_Controller_Front::getInstance()->getRequest()->getParam('id'));