<?php
$this->headTitle('Delete a content item');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if ($this->content) : ?>
    <h2 class="lead"><?php echo $this->title(); ?></h2>
    <p>Are you sure that you want to delete <?php echo $this->content->title; ?></p>
    <form action="<?php echo $this->url(
        array(
            'module' => 'admin',
            'controller' => 'content',
            'action' => 'delete'
        ), null, true); ?>"
          method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo $this->content->id; ?>"/>
            <input type="submit" name="del" value="Yes"/>
            <input type="submit" name="del" value="No"/>
        </div>
    </form>

<?php else: ?>
    <h2 class="lead">An error has occured</h2>
    <p>Cannot find the requested content details.</p>
<?php endif; ?>