<?php
$this->headTitle('Delete a content item');
$this->metaBase()->setDescription($this->title())->generate();
?>
<?php if ($this->content) : ?>
    <h2 class="lead"><?= $this->title() ?></h2>
    <p>Are you sure that you want to delete <b><em><?= $this->content->title ?></em></b></p>
    <form action="<?= $this->url(array('module' => 'admin', 'controller' => 'content', 'action' => 'delete'), null, true) ?>" method="post">
        <div class="btn-toolbar">
            <input type="hidden" name="id" value="<?= $this->content->id ?>"/>
            <input type="submit" class="btn btn-danger" name="confirmDelete" value="Yes"/>
            <input type="submit" class="btn btn-default" name="confirmDelete" value="No"/>
        </div>
    </form>
<?php else: ?>
    <h2 class="lead">An error has occured</h2>
    <p>Cannot find the requested content details.</p>
<?php endif; ?>
