<?php
$this->headTitle('Bookmarked links from our Delicious account');
$this->metaBase()->setSubject('Links')
    ->setDescription($this->title())
    ->generate();
$this->headLink()->appendAlternate('http://feeds.delicious.com/v2/rss/portableantiquities?count=10',
    'application/rss+xml', 'Scheme bookmarks at Delicious');
?>
    <h2 class="lead">Bookmarked links</h2>
    <p>
        You can subscribe to our <a href="http://feeds.delicious.com/v2/rss/portableantiquities?count=10"
                                    title="Our bookmarks stored on Delicious">bookmark list at Delicious</a> if you use rss.</p>
<?php
$config = Zend_Registry::get('config');
$delicious = new Zend_Service_Delicious($config->webservice->delicious->id, $config->webservice->delicious->pwd);
$posts = $delicious->getAllPosts();
$links = array();
foreach ($posts as $post) {
    $links[] = array(
        'title' => $post->getTitle(),
        'url' => $post->getUrl());
}
$paginator = new Zend_Paginator(new Zend_Paginator_Adapter_Array($links));
if (isset($this->page) && ($this->page != "")) {
    $paginator->setCurrentPageNumber((int)$this->page);
}
$paginator->setItemCountPerPage(20)->setPageRange(10);
?>
    <ul>
        <?php echo $this->partialLoop('partials/getinvolved/links2.phtml', $paginator); ?>
    </ul>
<?php echo $this->paginationControl($paginator, 'Sliding', 'structure/pagination.phtml'); ?>