<?php
$this->headTitle('Our bookmarks tagged ' . $this->tag);
$this->metaBase()->setDescription($this->title())
    ->setSubject('Links')
    ->generate();
?>
<h2 class="lead"><?php echo $this->title(); ?></h2>
<?php
$config = Zend_Registry::get('config');
$delicious = new Zend_Service_Delicious($config->webservice->delicious->id, $config->webservice->delicious->pwd);
$posts = $delicious->getAllPosts();
?>
<ul>
    <?php foreach ($posts->withTags(array($this->tag)) as $post): ?>
        <li><a href="<?php echo $post->getUrl(); ?>"
               title="<?php echo $post->getTitle(); ?>"><?php echo $post->getTitle(); ?></a></li>
    <?php endforeach; ?>
</ul>