<?php $this->headTitle('Our bookmarks tagged '.$this->tag);?>
<h2>Bookmarks tagged with <?php echo $this->tag;?></h2>
<?php 
	$config = Zend_Registry::get('config');
	$cachemain = Zend_Registry::get('formcache');
	$userid = $config->webservice->delicious->id;
	$pwd = $config->webservice->delicious->pwd;
	$delicious = new Zend_Service_Delicious($userid, $pwd);
	$posts = $delicious->getAllPosts();

echo '<ul id="related">';
foreach ($posts->withTags(array($this->tag)) as $post){
echo '<li><a href="'.$post->getUrl().'" title="'.$post->getTitle().'">'.$post->getTitle().'</a>';
}
echo '</ul>';
?>